### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by garfield185** [floatinghotpot/cordova-admob-pro#103]
Everything fine with Android devices, but I can't make it work on iOS. Anybody had this issue? I am using Intel XDK, latest build, and testing with an iPhone 5

**Comment by floatinghotpot** [comment]
What do you mean by not working, any screenshot or error message or log?

And, paste your code snippet please?

**Comment by garfield185** [comment]
Hi, I am just using your code from the example, nothing more. Copy and pasted, the app works but no banner or intersticial appears. In android it is perfect, so I understand everything is correct. Is there any specific configuration to be done in iOS devices? I used your other admob plugin and it was working correctly in iPhone, I don't understand what's missing with this new plugin. 

Code snippet that I am using (with my own admob codes). 

    var admobid = {};
    if( /(android)/i.test(navigator.userAgent) ) { // for android
        admobid = {
            banner: 'ca-app-pub-xxx/xxx', // or DFP format "/6253334/dfp_example_ad"
            interstitial: 'ca-app-pub-xxx/yyy'
        };
    } else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) { // for ios
        admobid = {
            banner: 'ca-app-pub-xxx/zzz', // or DFP format "/6253334/dfp_example_ad"
            interstitial: 'ca-app-pub-xxx/kkk'
        };
    } else { // for windows phone
        admobid = {
            banner: 'ca-app-pub-xxx/zzz', // or DFP format "/6253334/dfp_example_ad"
            interstitial: 'ca-app-pub-xxx/kkk'
        };
    }


if(AdMob) AdMob.createBanner( {
    adId: admobid.banner, 
    position: AdMob.AD_POSITION.TOP_CENTER, 
    autoShow: true } );


if(AdMob) AdMob.prepareInterstitial( {adId:admobid.interstitial, autoShow:false} );

if(AdMob) AdMob.showInterstitial();


Is there any complete test project I can download and try on my iPhone? Thank you

**Comment by floatinghotpot** [comment]
Try run the following commands to run the test project:

```bash
# create a demo project
    cordova create test1 com.rjfun.test1 Test1
    cd test1
    cordova platform add android
    cordova platform add ios

    # now add the plugin, cordova CLI will handle dependency automatically
    cordova plugin add com.google.cordova.admob

    # now remove the default www content, copy the demo html file to www
    rm -r www/*;
    cp plugins/com.google.cordova.admob/test/* www/;

    # now build and run the demo in your device or emulator
    cordova prepare; 
    cordova run android; 
    cordova run ios;
    # or import into Xcode / eclipse
```
