### ISSUE TITLE
Admob and Tabris.js

### ISSUE THREAD

**Issue by calebeaires** [floatinghotpot/cordova-admob-pro#104]
Tabris.js has cordova as its engine. (https://tabrisjs.com/) I have tried to install this plugin, but it doesnt do his job.

**Comment by floatinghotpot** [comment]
Only "not working "is not a good bug report... Tell me more details. How did you use it? Any error message or logs?

**Comment by calebeaires** [comment]
Tabris.js use cordova plus its own virtual box UI. It don`t make use of webview. Read this: https://github.com/eclipsesource/tabris-js/issues/353

**Comment by floatinghotpot** [comment]
if Tabris.js does not have a webview, then it will be a problem, as the plugin is written for Cordova, and it will resize webview when ad banner is on/off.

**Comment by calebeaires** [comment]
Tabris seems to be promissor and use cordova as its engine. Maybe you could make and plugin that works on it!

Thanks for your help!

**Comment by floatinghotpot** [comment]
I personally think webview is good enough, as Google and Apple have both improved the performance. 

Tabris.js seems not a popular project, as it only get 33 stars, but with 140+ open issues. It seems not wise to spend time porting the plugin especially for Tabris.js. I will consider your suggest when they get 500+ stars. :P

**Comment by dougmolineux** [comment]
357 and counting :)
