### ISSUE TITLE
Issues on Windows Phone 8 build

### ISSUE THREAD

**Issue by Udinra** [floatinghotpot/cordova-admob-pro#105]
I am using this plugin to display Admob ads in my app.It is working for Android but not for Windows Phone 8.I am outlining the code and details for your reference.

            //********************
            // Start of Admob code
            //********************
                        var admobid = {};
                        if( /(android)/i.test(navigator.userAgent) ) { 
                            admobid = { // Android Admob ad code
                                banner: 'my android admob code pasted here'
                            };
                            } else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
                             //   admobid = { // for iOS I do not want iOS app
                                //    banner: 'ca-app-pub-6869992474017983/4806197152'
                           // };
                            } else {
                                admobid = { // my windows phone admob code
                                banner: 'my windows phone admob code pasted here'
                            };
                        }

                        function initApp() {
                            if (AdMob) {
                                AdMob.createBanner({
                                adId : admobid.banner,
                                position : AdMob.AD_POSITION.BOTTOM_CENTER,
                                autoShow : true
                                });
                            }
                        } 
I am calling initApp function from ondeviceready.The App code remain same for Android as well as Windows Phone. But on WIndows Phone the ads are not getting displayed. If I comment the initApp call from ondeviceready my app is working fine for Windows.So there is something which halts the flow of app.

Note I am using Intel XDK for my development and have used 2.7.4 version of your plugin with Cordova CLI 4.1.2.And I am doing Legacy Windows Phone 8 build

Do let me know in case more information is required from my side

**Comment by floatinghotpot** [comment]
please discuss in issue #47 instead of creating a new issue tracker, as it's same issue.
