### ISSUE TITLE
2% Ad Revenue Share

### ISSUE THREAD

**Issue by JesusJoseph** [floatinghotpot/cordova-admob-pro#106]
hi,
Can you please tell me whether the 2% revenue share is pro version of the code.
If it is there can you please tell me how to remove this 2% ad revenue code.

Did I need to pay for ir or give donations please let me know.
Planing to use it for some personal android apps

Thanks for your help.
Joseph

**Comment by floatinghotpot** [comment]
I notice you are using a derived version:
https://github.com/JesusJoseph/admob-google-cordova
https://github.com/appfeel/admob-google-cordova

It is derived from my open source code, you can fork and change the code as your wish, as many other do.

As to pro version, it's totally re-designed and re-written from scratch, simple, elegant and powerful. You can use it for free if for personal purpose only, but strongly recommend to get a license if use for commercial purpose. Having a license will get high-priority support.

**Comment by iffifan** [comment]
How to get licence and what is the cost?

**Comment by floatinghotpot** [comment]
http://rjfun.github.io/
