### ISSUE TITLE
Playservices r19 is needed, but i already have v.22

### ISSUE THREAD

**Issue by aledelgo** [floatinghotpot/cordova-admob-pro#107]
Hi,
i can't compile the app with your plugin as i'm using GoogleAnalytics plugin that require
com.google.play.services (v22)

on the contrary your plugin require
com.google.playservices r19 (note missing dot)

both dependencies conflicts in name and version.

how to fix?

**Comment by aledelgo** [comment]
Found the solution.
as your plugin is perfectly working with Playservices 22 too, i would remove the "com.google.playservices" dependency and add it as a requirement in the readme so that each user can use the version it eventually already have.
Actually i've found that "com.google.play.services" (note the additive dot) is updated more frequently than com.google.playservices (missing dot) and infact actually it bind the most recent version of PlayServices (v.22).

I'll request a pull.

**Comment by floatinghotpot** [comment]
Buddy, maintenance is not that easy ...

I know this plugin is compatible with google playservices r22, but keep it dependent on r19 intentionally, until r22 is supported by all the build tools, especially intel xdk and phonegap build, because sometimes they are not always keeping updated to the latest version of android sdk.

Before merge your patch, it has to be tested sufficiently with all the build tools and make sure it works.

**Comment by aledelgo** [comment]
My friend i completely agree with you about testing and cross-compatibilty enviroinment handling but in this moment you are limiting anyone is using a greater version of Playservices and furthermore you are  limiting anyone is using a Playservices r20+ dependant plugin.
Here the major problem is in the plugin definition  is set a specific package name for the PlayServices package...

In this (probably wrong) cordova enviroinment where 2 or more non-official Playservices binding package may exist ("com.google.playservices" and "com.google.play.services" ) instead of one single and official/canonical, i think you should leave developers free to choose Playservices plugin to install.
In this moment, apart of having forked this repo cloned, the only solution to mantain an app that use your plugin and the one for GAnalystics is to note a complex order of commands to remove and readd plugins so that the last Playservices leaved is the r22.

My patch in my pull-request isn't adding anythign to the code. i simply removed completely the PlayServices dependency in the plugin definition file and added detailed instruction in the main Readme file on how to add it underlining it is a requirement... I wasn't aware of the specific r19 strong dependency for other platform like XDK so i haven't wrote about this, but we could add it in the readme...

What do you think about?

**Comment by floatinghotpot** [comment]
See: http://plugins.cordova.io/#/package/com.google.playservices

it's the most popular plugin to add google play services jar, and it's maintained by google chrome app team.

what I am using is compatible with it, if you wish to use newer version, try this one. but please avoid other id like "com.google.play.services", it will conflict with other plugins.
