### ISSUE TITLE
WP8.1 - suddenly image-banners are very small...

### ISSUE THREAD

**Issue by dMOTION** [floatinghotpot/cordova-admob-pro#109]
Out of the blue, the "image" banners are very small on Windows Phone (see attachments).

Banners with text are rendered correctly, but "pure" image banners are barely visible.

It happened some days ago, and I didn't change anything of the code / neither did I update the app - it worked well before (they were stretched tot the width of the screen, with the right dimensions).

Same app on Android is doing fine (with exact the same source-code).

![wp_ss_20150405_0003](https://cloud.githubusercontent.com/assets/2298150/7003373/b4067306-dc59-11e4-9118-877044489e2e.jpg)
![wp_ss_20150405_0002](https://cloud.githubusercontent.com/assets/2298150/7003374/b435528e-dc59-11e4-8552-3cee283dec2e.jpg)

**Comment by softexe** [comment]
Seems it is viewport / -ms-viewport issue

**Comment by arpita-sharda** [comment]
Hello,
I too having this issue, ads banner suddenly getting very small, with the same size as it is in in screeenshots provided by @dMOTION.
@softexe, I don't understand what do you mean by  -ms-viewport, I mean what to do with it, I applied meta tag like this:
<meta name="viewport" content="width=device-width, initial-scale=1">
in my index.html, but it does nothing.
Please help me, if you already had solution for this issue.

Thanks

**Comment by softexe** [comment]
My header for WP build with correct banner size:
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, minimal-ui">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="msapplication-tap-highlight" content="no" />
        <script src="js/w81shim.js"></script>
        <script>
            (function() {
                if ("-ms-user-select" in document.documentElement.style &&
                        (navigator.userAgent.match(/IEMobile/) ||
                        navigator.userAgent.match(/ZuneWP7/) ||
                        navigator.userAgent.match(/WPDesktop/))) {
                    var msViewportStyle = document.createElement("style");
                    msViewportStyle.appendChild(
                            document.createTextNode("@-ms-viewport{width:auto!important}")
                    );
                    document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
                }
            })();
        </script>


    </head>

**Comment by floatinghotpot** [comment]
@softexe thanks, I also see some similar solution to fix the wp8 viewport issue in follow articles:
https://coderwall.com/p/zk_2la/responsive-design-in-ie-10-on-windows-phone-8
http://stackoverflow.com/questions/24007577/windows-phone-8-viewport-issue

Someone says this error only happen to IEMobile 10.0, and suggest "This code specifically targets version IE Mobile 10.0 (I've also added an extra condition to ensure it only happens in IE), so future, fixed versions will be untouched."

```javascript
(function() {
    if ("-ms-user-select" in document.documentElement.style && navigator.userAgent.match(/IEMobile\/10\.0/)) {
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
            document.createTextNode("@-ms-viewport{width:auto!important}")
        );
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }
})();
```

As this is not plugin issue but IEMobile issue, I will close this tracker.
