### ISSUE TITLE
I can't make admob work in the phonegap build

### ISSUE THREAD

**Issue by landore** [floatinghotpot/cordova-admob-pro#110]
Well, here is the deal. I'm starting to learn how to create android apps using Phonegap. I'm using the "build" with GitHub to create apps, wich is the easiest way for a beginner.
I tried to create apps using html templates and it worked fine.
Now I'm starting to test admob in the templates but I can't get it to work.

Here is the link of my test project in GitHub where you can see the full codes. It is very basic, just for test.

https://github.com/landore/first.git

To put admob in my little project I'm using this plugin:

https://github.com/floatinghotpot/cor...

I created everything in the admob website and inserted this code in the index.html:

< script type="text/javascript" >
// select the right Ad Id according to platform
var admobid = {};
if( /(android)/i.test(navigator.userAgent) ) { // for android
admobid = {
banner: 'ca-app-pub-6955772823021597/3084622919', // or DFP format "/6253334/dfp_example_ad"
interstitial: 'ca-app-pub-6955772823021597/4561356112'
};
}
// it will display smart banner at top center, using the default options
if(AdMob) AdMob.createBanner( {
adId: admobid.banner,
position: AdMob.AD_POSITION.TOP_CENTER,
autoShow: true } );
// preppare and load ad resource in background, e.g. at begining of game level
if(AdMob) AdMob.prepareInterstitial( {adId:admobid.interstitial, autoShow:false} );
// show the interstitial later, e.g. at end of game level
if(AdMob) AdMob.showInterstitial();
< /script >

The beggining and the end of the code " < script type="text/javascript" > and < /script >" I copied from some tutorials in the internet, because when I didn't insert this the text of the code would appear on the page (or app)., but I have no idea if this is right.

And thi is the code I inerted in the config.xml:

< gap:plugin name="com.google.cordova.admob" source="plugins.cordova.io"/ >

I probably did something wrong, or place some code in the wrong place but I can't figure it out.

Can somebody hep me?

Thanks a lot!!

**Comment by floatinghotpot** [comment]
You can start with using this file to run the demo:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/test/index.html

It's a working demo.
