### ISSUE TITLE
IOS Rejection because of problem with Admob ads

### ISSUE THREAD

**Issue by didyseptiyono** [floatinghotpot/cordova-admob-pro#111]
Hello

I have some problem that my app rejected by apple because the ads from admob in my apps are display Google Play banners. Below are the email from apple.
============
From Apple
3.1 - Apps or metadata that mentions the name of any other mobile platform will be rejected
3.1 Details

We noticed that your app or its metadata contains irrelevant platform information in the advertisements. Providing other platform references is not appropriate for the App Store.

Please see the attached screenshot(s) for additional information.

Next Steps

Please remove any instances of this information from your app and its marketing materials, including the Application Description, What's New info, Previews and screenshots.

Since your iTunes Connect Application State is Rejected, a new binary will be required. Make the desired metadata changes when you upload the new binary.

NOTE: Please be sure to make any metadata changes to all App Localizations by selecting each specific localization and making appropriate changes.
==================
I have search around google and many people get same trouble like this link
http://forum.unity3d.com/threads/ios-rejection-because-of-problem-with-unityads.306488/

And this is the screenshoot attached by apple
http://prntscr.com/6rxpjd

Did you have idea how to fix this problem? maybe display test ads while on apple review process or can we manage the ads shown in apps?

**Comment by floatinghotpot** [comment]
Unfortunately I can do nothing about this, as the Ad is delivered by AdMob. You may turn to AdMob for help to review and filter such "bad" Ad.
