### ISSUE TITLE
not run for wp8.1 with visual studio community edition

### ISSUE THREAD

**Issue by mycolaos** [floatinghotpot/cordova-admob-pro#112]
Hi!
I've installed VS Community 2013 along with cordova tools. I've tried both your plugins — admob & admob pro — but neither works. I've tried to run blank app with only your plugin and full example code, but it's still does not work, even with test ads.
I have run it on real device.

Really don't know what to do.

**Comment by mycolaos** [comment]
I've tried another code:

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />

    <title>Hello World</title>

    <style type="text/css">
        div {padding: 50px;}
        #testBtn {visibility: hidden;}
    </style>

    <script>
    function onLoad() {
        document.getElementById("console").textContent = "is loaded...";
        document.addEventListener("deviceready", showBtn(), false);
    }

    function showBtn() {
        document.getElementById("console").textContent = "device is ready!";
        document.getElementById("testBtn").style.visibility = "visible";
    }

    function goOn() {
        try {
            var admobid = {};
            if (/(android)/i.test(navigator.userAgent)) { // for android
                admobid = {
                    banner: 'ca-app-pub-xxx/xxx', // or DFP format "/6253334/dfp_example_ad"
                    interstitial: 'ca-app-pub-xxx/yyy'
                };
            } else if (/(ipod|iphone|ipad)/i.test(navigator.userAgent)) { // for ios
                admobid = {
                    banner: 'ca-app-pub-xxx/zzz', // or DFP format "/6253334/dfp_example_ad"
                    interstitial: 'ca-app-pub-xxx/kkk'
                };
            } else { // for windows phone
                admobid = {
                    banner: 'ca-app-pub-xxx/zzz', // or DFP format "/6253334/dfp_example_ad"
                    interstitial: 'ca-app-pub-xxx/kkk'
                };
            }

            if (AdMob) AdMob.createBanner({
                adId: admobid.banner,
                position: AdMob.AD_POSITION.BOTTOM_CENTER,
                autoShow: true,
                isTesting: true
            });
        } catch (e) {
            document.getElementById("console").textContent = e.stack;
        }
    }
    </script>

</head>
<body onload="onLoad()">
    <div>
        <p>Banner example</p>
        <button id="testBtn" onclick="goOn()">Go on</button>
    </div>
    <div>
        <p id="console"></p>
    </div>
    
</body>
</html>


Result: ReferenceError: 'AdMob' is undefined

**Comment by mycolaos** [comment]
I've created another sample blank app.
Added your plugin.
Added script with 'deviceready'.
Added sample code:
  function showAd() {
        try {
            var admobid = {};
    if( /(android)/i.test(navigator.userAgent) ) { // for android
        admobid = {
            banner: 'ca-app-pub-xxx/xxx', // or DFP format "/6253334/dfp_example_ad"
            interstitial: 'ca-app-pub-xxx/yyy'
        };
    } else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) { // for ios
        admobid = {
            banner: 'ca-app-pub-xxx/zzz', // or DFP format "/6253334/dfp_example_ad"
            interstitial: 'ca-app-pub-xxx/kkk'
        };
    } else { // for windows phone
        admobid = {
            banner: 'ca-app-pub-xxx/zzz', // or DFP format "/6253334/dfp_example_ad"
            interstitial: 'ca-app-pub-xxx/kkk'
        };
    }

    if(AdMob) AdMob.createBanner( {
    adId: admobid.banner, 
    position: AdMob.AD_POSITION.TOP_CENTER, 
    autoShow: true,
 isTesting: true } );

    document.getElementById("console").textContent = AdMob;
    } catch(e) {
        document.getElementById("console").textContent = e.stack;
    }
}

**Comment by mycolaos** [comment]
Missing Command Error

**Comment by barans** [comment]
I already have that problem, console.log(AdMob) is not null, but when i call the function prepareInterstitial it fails, and says "Missing Command Error". I also tried it on nokia windows phone 8.1 nothing appears.

**Comment by softexe** [comment]
this plugin doesn't support wp8.1 (windows store/Windows Desktop) cordova platform. Try build your project with Window Phone target selected in the Visual Studio.

**Comment by floatinghotpot** [comment]
I've verified the plugin with Cordova CLI, like this:
```bash
cordova create test1 com.rjfun.test1 Test1
cd test1
cordova plugin add cordova-plugin-admobpro
cordova platform add wp8

# use the demo file to replace the default content
rmdir /S www/*
Xcopy /E /I .\plugins\cordova-plugin-admobpro\test .\www

cordova build wp8

# connect a windows phone
cordova run wp8
```
