### ISSUE TITLE
Questions about the PluginPro license.

### ISSUE THREAD

**Issue by rahmadid** [floatinghotpot/cordova-admob-pro#113]
Hi raymond,
I am still not clear about the license, so please allow me to ask a few questions:

1. If I use one of your PluginPro plugin, is it mandatory to buy a license? I ask this because some plugin has MIT license (which is free), yet at the bottom of the page there written ".. please buy a license ..".

2. What type of license is it, Usage license or Support license?

Thank you.

**Comment by floatinghotpot** [comment]
In a word, time is money. 

It's not mandatory to buy a license if you don't need any support and can fix everything by yourself.

If you need consume my extra time, you need pay. Or else your question or support request may be put to low priority.
