### ISSUE TITLE
Ads doesn't show up

### ISSUE THREAD

**Issue by januaroliver** [floatinghotpot/cordova-admob-pro#115]
i've followed all steps of instalation, but when it's running, the ads doesn't show up? do i miss something?

**Comment by floatinghotpot** [comment]
As a bug report or issue report, it should include more details. Or else no one knows what you did and what you didn't. What tool do you use, which platform, version, etc. And, can you paste any log or screenshot?

**Comment by januaroliver** [comment]
iam sorry for the inconvenience, here's the details of the bug :

screenshot when using Intel XDK (adding admob plugins) :

![pluginintelxdk](https://cloud.githubusercontent.com/assets/11997011/7215362/7c1386a6-e5fe-11e4-9f73-299a2a9fff69.jpg)

screenshot when using intel xdk (when app's running) :

![emulateintelxdk](https://cloud.githubusercontent.com/assets/11997011/7215364/b0f8f658-e5fe-11e4-94e0-df8655ce7e73.jpg)

when the app's emulated, there was no ads showed...

**Comment by floatinghotpot** [comment]
When you see the emulated app, it's not running in device emulator but web app emulator, so it's running the web code only, no plugin running yet. 

To see the full features, you have to configure the plugins and build the app either iOS or android, then download and install the package to device or device emulator.

**Comment by januaroliver** [comment]
the ads also doesn't show when using CLI, here's the details :

Screenshot using CLI (app launched success)

![usingcli](https://cloud.githubusercontent.com/assets/11997011/7215673/f66261d0-e60c-11e4-96b0-8abe879661b3.jpg)

screenshot Using CLI (app launched on device)

![devicerunning](https://cloud.githubusercontent.com/assets/11997011/7215683/2958d4ca-e60d-11e4-9ac6-44809c18f99b.png)

the ads still doesn't show up

**Comment by januaroliver** [comment]
here's provide details from logcat when running from eclipse :


![logcat](https://cloud.githubusercontent.com/assets/11997011/7215732/aa760eaa-e60e-11e4-817e-9548369e1e3e.jpg)

it has an exception (highlighted) related to AdMob

**Comment by floatinghotpot** [comment]
are you sure you have the plugin installed successfully? show me the plugin list...

**Comment by januaroliver** [comment]
yes it does, here's the plugin list..

![plugin](https://cloud.githubusercontent.com/assets/11997011/7218423/7b6bbb52-e698-11e4-9dca-ba4aaeeed9c0.jpg)

i had repeat those step few times, but the problem still exist...

**Comment by floatinghotpot** [comment]
The plugin was not installed properly, valid installation should also show a plugin named com.google.playservices to be installed via git from github repo.

Please install git, then install the plugins again.

**Comment by januaroliver** [comment]
i already add google play service...

![plugin2](https://cloud.githubusercontent.com/assets/11997011/7218723/d18ec20e-e6a7-11e4-9c8c-734ce755a80d.jpg)

but still doesn't show up..

![devicerunning](https://cloud.githubusercontent.com/assets/11997011/7218725/ed72afa8-e6a7-11e4-9a38-6524a42dc4f1.png)

**Comment by floatinghotpot** [comment]
Clean and rebuild, and any eclipse logcat logs?

**Comment by januaroliver** [comment]
logcat from eclipse

![logcat2](https://cloud.githubusercontent.com/assets/11997011/7218812/3c1766a0-e6ab-11e4-882f-91e3e9c1a58e.jpg)

**Comment by floatinghotpot** [comment]
AdMob is not defined, means that the plugin is not installed properly. 

I guess it's due to previous errors. 

Try keeping the plugins no change, but remove and re-add android platform by running following commands:
```bash
cordova platform remove android
cordova platform add android
```
Then rebuild the app.

**Comment by januaroliver** [comment]
finally the ads show up :)

![success](https://cloud.githubusercontent.com/assets/11997011/7226076/39e1b2cc-e76f-11e4-92f1-d6b2f0c2ebc3.png)

previously, i used "rm" command to remove platform or plugin and it doesn't working.

whether using different command has different result??

**Comment by floatinghotpot** [comment]
congratulations, finally you made it ! :+1:

**Comment by januaroliver** [comment]
Thank u for ur assist, this tutorial provides ease way to add Admob Plugin :+1:

**Comment by saothienhat** [comment]
Hi floatinghotpot,

i've followed all steps of installation, but when it's running, the Admob is undefined. I tried all steps in others same issues but the issue still happen. Do I miss anything ?

Below is my plugin list:

cordova-plugin-admobpro 2.10.0 "AdMob Plugin Pro"
cordova-plugin-extension 1.2.3 "Cordova Plugin Extension"
cordova-plugin-whitelist 1.1.1-dev "Whitelist"
ionic-plugin-keyboard 1.0.6 "Keyboard"

**Comment by floatinghotpot** [comment]
Some Ionic developers just view their index.html in IonicViewer and found AdMob undefined.

In fact, as the AdMob plugin has native code, the cordova project has to be built into app package and install to simulator or device.

What's the detailed steps to re-produce your issue? What tool do you use to build the app? Do you run your app in IonicViewer, local simulator, or your android / ios device?

**Comment by saothienhat** [comment]
Hi floatinghotpot,

Actually, I used Cordova + Ionic to build app. The "admob-service.js" will be called once device ready. So, I faced that issue in case I use command "ionic serve" or "cordova build android". The issue of "Admob is undefined" appear on Brower or Device.

**Comment by floatinghotpot** [comment]
Ionic serve won't work, as the plugin won't be loaded in browser. You need use "cordova run android" to build the app and install app to device to run.

**Comment by saothienhat** [comment]
Yes, I tested on Browser and Device. I also used "Cordova build android" command to build an APK file and installed it into my real Device. But that issue happen also.

**Comment by saothienhat** [comment]
Hi, 

I fixed this issue by following this topic: http://www.tagwith.com/question_571864_window-plugins-admob-always-undefined-in-ionic-app

Summary:

Instead of using window.plugins.AdMob, please directly use AdMob, or window.AdMob.

It's defined in the plugin.xml:

<js-module src="www/AdMob.js" name="AdMob">
    <clobbers target="window.AdMob" />
</js-module>
