### ISSUE TITLE
Smart Banner appearing in the middle of screen on Ionic with Crosswalk

### ISSUE THREAD

**Issue by franciswagner** [floatinghotpot/cordova-admob-pro#118]
Hi, I used this plugin with Ionic Framework and everything was fine, but when I installed Crosswalk the smart banner with position bottom_center appears in the middle of the screen. I don't know what is wrong  as prior to Crosswalk installation it was working.

**Comment by cvrajeesh** [comment]
One work around is to set `overlap:true` inside the `createBanner` options. That may be the best option for all scenarios

**Comment by floatinghotpot** [comment]
already fixed, see #119
