### ISSUE TITLE
Ads Display in Middle of Screen in Cordova Android 4.0.0

### ISSUE THREAD

**Issue by RangerRick** [floatinghotpot/cordova-admob-pro#119]
I recently updated my project to the latest Cordova and associated platforms and plugins. In Android (4.2, also reported on 4.1, probably others), the ad banner now shows in the middle of the screen instead of the bottom:

![image](https://cloud.githubusercontent.com/assets/89252/7430207/6305da54-efdd-11e4-9f31-4acabf46066b.png)

If I downgrade to Cordova Android 3.7.1 and leave all of my code alone, it works:

![image](https://cloud.githubusercontent.com/assets/89252/7430208/6a084954-efdd-11e4-963a-c7f1ca5d6e4c.png)

**Comment by floatinghotpot** [comment]
Could you paste the code snippet of calling plugin to create banner?

**Comment by RangerRick** [comment]
```javascript
						if ($window.AdMob) {
							var admobid;
							if (ionic.Platform.isIOS()) {
								admobid = iosBannerId;
							} else if (ionic.Platform.isAndroid()) {
								admobid = androidBannerId;
							} else if (ionic.Platform.isWindowsPhone()) {
								admobid = wpBannerId;
							}

							if (admobid) {
								console.log('Ads.show: Creating AdMob banner with ID: ' + admobid);
								$window.AdMob.createBanner({
									'adId': admobid,
									'position': AdMob.AD_POSITION.BOTTOM_CENTER,
									'autoShow': true
								});
							} else {
								console.log('Ads.show: WARNING: Unable to determine platform.');
							}
```

I saw another discussion of this from an old issue and you suggested overlap:true but in my case it makes the ad sit on top of the tab bar at the bottom of the app.  I need it to push the rest of the view up instead like the default on older Cordova.

**Comment by kacinskas** [comment]
I have exactly the same issue.
Additionaly - if ads position is set to TOP_CENTER then it is not visible at all, but I can see that it is created only its out of view and not pushing rest of the view down

If I set  overlap:true it is displayed as expected over the rest of the view

**Comment by eithe** [comment]
Can confirm the same thing here.

**Comment by neighborhoodhacker** [comment]
RangerRick how did you downgrade properly to 3.7.1 I tried cordova platform add android@3.7.1 and it throws a bunch of errors.

**Comment by manfromshadow** [comment]
For me works to set  overlap:true in create banner method:
AdMob.createBanner({
                  adId : admobid.banner,
                  position : AdMob.AD_POSITION.BOTTOM_CENTER,
                  adSize: 'SMART_BANNER',
                  isTesting: false,
                  autoShow : true,
                  overlap:true
              });

**Comment by eithe** [comment]
@manfromshadow Yeah, as mentioned above, overlapping works, but is not what we are looking for.

**Comment by RangerRick** [comment]
Right, overlap:true means that elements at the bottom of the screen are covered 100% of the time, and I'd really rather not have to rearrange all my content to have space at the bottom.

@neighborhoodhacker I'm using ionic, but that *should* work I think, it's basically what ionic is doing.  You did a 'cordova platform rm android' first?

**Comment by neighborhoodhacker** [comment]
Actually it was just giving issues with cordova-plugin-whitelist. I removed that plugin and good to go sorry for bothering you and thanks for the tip!

**Comment by ibewugb** [comment]
same issue here

**Comment by mikealo** [comment]
have the same issue with normal webview and crosswalk webview, i didn't test what neighborhoodhacker said about white-list plugin but it's a very bad idea removing it for security reason in most of the projects so if it doesn't work with it..this plugin is not usable at all.. i will keep testing and if i find a solution i will post it here

**Comment by neighborhoodhacker** [comment]
@mikealo whitelist is built in before Cordova android 4.0 it requires a plugin after. No security risk. Downgrade to Cordova android 3.7.1 solved til Dev updates code

**Comment by floatinghotpot** [comment]
hi guys, it's a bug in this plugin that triggered in cordova-android v4.0.0. 

Now it's fixed, please update to plugin v2.7.7.

NOTICE: if you are using cordova CLI, remember to clear the cache in ~/.plugman/cache before removing/adding plugin, to avoid old version causing trouble.

**Comment by floatinghotpot** [comment]
BTW, this bug is NOT related with whitelist plugin. it's about layout only.

**Comment by eithe** [comment]
@floatinghotpot I don't understand this, as I'm running 2.7.7 already according to cordova plugin list. Also, the commit you mentioned doesn't really change anything?

**Comment by floatinghotpot** [comment]
is it fixed or not?

**Comment by zunger** [comment]
Definitely still not fixed, banner is still appearing in the middle of the screen.

**Comment by mikealo** [comment]
just tested on crosswalk overlap false is ignored and the bottom bar overlap the bottom of the page like overlap true setting

**Comment by floatinghotpot** [comment]
@mikealo your feedback is very accurate. 

in cordova-android v4.0, the webview has no linearlayout as parent viewgroup any more, so it's quite hard to avoid overlap unless some hacks.

trying some hacks, stay tuned.

**Comment by kacinskas** [comment]
Yes its because cordova in v4.0 is using FrameLayout,

because Im using ads on top,
so as temp solution I have added padding to the top of CordovaView (Im using XWalk)
in onCreate of main activity and set 'overlap:true' in plugin:
```
        LinearLayout main = (LinearLayout) findViewById(100).getParent().getParent();
        XWalkCordovaView content = (XWalkCordovaView) findViewById(100);

        FrameLayout.LayoutParams flp = (FrameLayout.LayoutParams) content.getLayoutParams();
        flp.gravity = android.view.Gravity.TOP;
        content.setPadding(0,70,0,0);
        content.setLayoutParams(flp);
```
but its not very good as ads height can be different...

**Comment by neighborhoodhacker** [comment]
Lol I had to remove the plugin to downgrade Cordova android is all. Never claimed the whitelist to be a bug and never said not to use whitelist. Glad you are on your way to figuring it out

**Comment by zunger** [comment]
Thanks for all the hard work on the plugin and checking into this issue. Any sort of ETA on a fix?

**Comment by floatinghotpot** [comment]
Based on cordova-android 4.x changes, some refactoring is done to resolve the layout issue. 

I've tested to verify it works now.

Please remove and re-add the plugin, and double check the version to make sure you see: 
```
com.google.cordova.admob 2.7.7 "AdMob Plugin Pro"
com.rjfun.cordova.extension 1.1.0 "Cordova Plugin Extension"
```

NOTICE: if you are using cordova CLI, remember to clear the cache in ~/.plugman/cache before removing/adding plugin, to avoid old version causing trouble.

**Comment by zunger** [comment]
Working great, thank you!

**Comment by kacinskas** [comment]
Works, thank you!

**Comment by mikealo** [comment]
it works, thank you for the fix!

**Comment by do-web** [comment]
Still not working on lollipop
