### ISSUE TITLE
Play store violation

### ISSUE THREAD

**Issue by krish-dev** [floatinghotpot/cordova-admob-pro#120]
Hello @floatinghotpot  

I am using cordova-admob-pro plugin in my application from past 6 month ago. 26th April I got this email from adMob team. my application is simply base holiday vacation app. I don't understand what happen. please help me out.

"This email is to alert you that one of your applications is not currently in compliance with our AdMob program policies and as a result, ad serving has been disabled to your application

Violation explanation:
--------------------------------------
GOOGLE PLAY REMOVAL: AdMob publishers are not permitted to abuse or promote the abuse of any Google product, such as Google Play, YouTube, or Blogger. This includes circumventing, or providing the means to circumvent, the policies or terms of these or other Google products, such as by allowing users to download YouTube videos ".

**Comment by floatinghotpot** [comment]
This alert tells that your app violated Google play store rules first, then AdMob team just follow the decision. It's not caused by AdMob itself.

You may need check your app or contact Google play team for the root cause.
