### ISSUE TITLE
iOS simulator displays only "Test Interstitial"

### ISSUE THREAD

**Issue by keenkiran** [floatinghotpot/cordova-admob-pro#122]
Hi,
I am using cordova-admob-pro for my app and whenever I run the app on iphone 6 simulator (with ios 8) even with "isTesting=false", I am getting a Test Interstitial. Here is the code snippet I am using
```javascript
if (window.AdMob){
              window.AdMob.prepareInterstitial( {
                  isTesting: false, // receiving test to
                  adId:ad_units.ios.interstitial,
                  autoShow:false
                }
              );
          }
```
Is it a problem with latest Google SDK for iOS 8 ?

**Comment by floatinghotpot** [comment]
Did you test it on a real device?

**Comment by keenkiran** [comment]
Yes. I have tested on a real device too. Is there any special configuration required for this ?

**Comment by aledelgo** [comment]
Same here but I can't test on real device...
Il 05/mag/2015 11:21, "keenkiran" <notifications@github.com> ha scritto:

**Comment by floatinghotpot** [comment]
I think you need set your adId when calling prepareInterstitial().
