### ISSUE TITLE
Plugin file size is too big

### ISSUE THREAD

**Issue by calebeaires** [floatinghotpot/cordova-admob-pro#124]
On iOS, the file GoogleAdmobAds is 14mb. The app size goes too big

**Comment by floatinghotpot** [comment]
We cannot do nothing about this, as the library is provided by Google. After linking, the package is not that big.

If you do want a very small app, try using the plugin for Apple iAd, no extra library required.
https://github.com/floatinghotpot/cordova-iad-pro.git
