### ISSUE TITLE
Ads always overlap content

### ISSUE THREAD

**Issue by calebeaires** [floatinghotpot/cordova-admob-pro#126]
After the last update, ads cover the content. 

Cordova Version: 5.0
Ionic: 1.0
Android: 5.02

```
    if (AdMob) AdMob.createBanner({
        license: "xxxxx",
        adId: "xxxx",
        position: AdMob.AD_POSITION.BOTTOM_CENTER,
        autoShow: true
    });

```

![screenshot_2015-05-12-16-56-06](https://cloud.githubusercontent.com/assets/794195/7597184/1c9bee70-f8c8-11e4-8328-77cd47315378.png)

**Comment by floatinghotpot** [comment]
It's caused by cordova-android 4.0 code changes. Now it just fixed. 

See: #119

**Comment by calebeaires** [comment]
It works now!
