### ISSUE TITLE
Mopub plugin if I show mopub ad via admob?

### ISSUE THREAD

**Issue by nullday000** [floatinghotpot/cordova-admob-pro#127]
Hello.

Is it necessary to install https://github.com/floatinghotpot/cordova-plugin-mopub if I added mopub in my AdMob account and I think that mopub ad would be shown via admob?

Or maybe it's impossible at all? And I need to do it by myself in code: call randomly either admob or mopub code?

**Comment by floatinghotpot** [comment]
adapter for admob mediation to mopub is not supported yet, as mopub and mobfox are using some code conflicting with each other.

you can use both admob and mopub plugin in one app, but you may need switch the ad by yourself.

**Comment by nullday000** [comment]
Oh, that's bad news for me.

But how can I switch it by myself? Just do random() and choose one of them randomly? What about filling rate, is it possible to check do they have something to show to me before I will show it to my user?

**Comment by floatinghotpot** [comment]
though you can use 2 or more ad plugins in your hybrid apps, it's not good to display all of them at the same screen. you may consider creating one of them by a random choosing.
