### ISSUE TITLE
Cannot build android with cca using the chrome.identity plugin

### ISSUE THREAD

**Issue by Knorcedger** [floatinghotpot/cordova-admob-pro#128]
Im a using google cca to build a cordova app, but after adding the chrome.identity Plugin and Cordova admob pro, I cant build the app anymore. The terminal error says: *UNEXPECTED TOP-LEVEL EXCEPTION: com.android.dex.DexException: Multiple dex files define Lcom/google/andr
oid/gms/actions/ReserveIntents;* (Full error log below)

**System Details**  
Windows
cca v0.7.0
If you need anything else please let me know.

**Replication Steps**
1. Install cca
2. In a terminal: `cca create app`
3. `cd app`
4. `cca platform add android`
5. Open app/www/manifest.json and in the permissions array add: identity e.g. `"permissions": ["<all_urls>", "identity"]`
6. `cca build android` Builds fine.
7. `cca plugin add com.google.cordova.admob`
8. `cca build android` Fails

**Full error log from terminal**

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexArmv7Debug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        C:\Users\TsoumiAc\AppData\Local\Android\android-sdk\build-tools\22.0.1\d
x.bat --dex --no-optimize --output C:\Users\TsoumiAc\Desktop\app\platforms\andro
id\build\intermediates\dex\armv7\debug --input-list=C:\Users\TsoumiAc\Desktop\ap
p\platforms\android\build\intermediates\tmp\dex\armv7\debug\inputList.txt
Error Code:
        2
Output:

        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Lcom/google/andr
oid/gms/actions/ReserveIntents;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.ja
va:596)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:
554)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:
535)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)

                at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main
.java:454)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
                at com.android.dx.command.dexer.Main.run(Main.java:246)
                at com.android.dx.command.dexer.Main.main(Main.java:215)
                at com.android.dx.command.Main.main(Main.java:106)



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 24.141 secs

C:\Users\TsoumiAc\Desktop\app\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\Users\TsoumiAc\Desktop\app\pl
atforms\android\gradlew cdvBuildDebug -b C:\Users\TsoumiAc\Desktop\app\platforms
\android\build.gradle -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: C:\Users\TsoumiAc\Desktop\app\platfo
rms\android\cordova\build.bat: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: C:\Users\TsoumiAc\Desktop\app\platforms\android\cordova\build.bat: Comman
d failed with exit code 1
    at ChildProcess.whenDone (C:\Users\TsoumiAc\AppData\Roaming\npm\node_modules
\cca\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:131
:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
```

**Comment by floatinghotpot** [comment]
Hi, i run the above cca commands under Mac, it builds the apk successfully.

Here are the plugins in my build:
```
UnicMac:testcca liming$ cca plugin -s
cca v0.7.0
cordova-plugin-admobpro 2.8.0 "AdMob Plugin Pro"
cordova-plugin-background-app 2.0.2 "Background App"
cordova-plugin-blob-constructor-polyfill 1.0.2 "Blob constructor shim"
cordova-plugin-chrome-apps-bootstrap 2.0.7 "Chrome Apps Core"
cordova-plugin-chrome-apps-common 1.0.7 "Chrome Apps Common Utils"
cordova-plugin-chrome-apps-i18n 2.0.1 "Chrome Apps I18n API"
cordova-plugin-chrome-apps-navigation 1.0.3 "Chrome Apps Navigation"
cordova-plugin-chrome-apps-runtime 1.1.1 "Chrome App Runtime"
cordova-plugin-chrome-apps-storage 1.0.4 "Chrome Apps Storage API"
cordova-plugin-crosswalk-webview 1.2.0 "Crosswalk WebView Engine"
cordova-plugin-customevent-polyfill 1.0.5-dev "CustomEvent constuctor shim"
cordova-plugin-extension 1.1.4 "Cordova Plugin Extension"
cordova-plugin-file 2.0.0 "File"
cordova-plugin-googleplayservices 19.0.1 "Google Play Services for Android"
cordova-plugin-inappbrowser 1.0.0 "InAppBrowser"
cordova-plugin-network-information 1.0.0 "Network Information"
cordova-plugin-statusbar 1.0.0 "StatusBar"
cordova-plugin-whitelist 1.0.0 "Whitelist"
cordova-plugin-xhr-blob-polyfill 1.0.3 "XHR Blob Response Type Polyfill"
org.chromium.cca-hooks 0.0.0 "undefined"
```

From your logs, it seems that there are some duplicated symbol for google play services.

Did you add another other plugins or google-play-services.jar?

**Comment by Knorcedger** [comment]
Hello, thank you for your reply.

As shown from the commands above, im creating a new project, and the problem still exists. The only plugin I add is the [cordova-plugin-chrome-apps-identity](https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-identity) by adding it in the permissions. The conflict must be that your plugin and identity both require google play services or something. I created the same issue in the identity plugin as well ([issue link](https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-identity/issues/3)) but im still trying to figure out his suggestion and make this work. But I suppose a fix by you will fix the problem once for all.

**Plugin list**
C:\Users\TsoumiAc\Desktop\app>cca plugin -s
cca v0.7.0
com.google.cordova.admob 2.7.7 "AdMob Plugin Pro"
com.google.playservices 19.0.0 "Google Play Services for Android"
com.rjfun.cordova.extension 1.1.4 "Cordova Plugin Extension"
cordova-plugin-background-app 2.0.2 "Background App"
cordova-plugin-blob-constructor-polyfill 1.0.2 "Blob constructor shim"
cordova-plugin-chrome-apps-bootstrap 2.0.7 "Chrome Apps Core"
cordova-plugin-chrome-apps-common 1.0.7 "Chrome Apps Common Utils"
cordova-plugin-chrome-apps-i18n 2.0.1 "Chrome Apps I18n API"
cordova-plugin-chrome-apps-identity 1.4.4 "Chrome Apps Identity API"
cordova-plugin-chrome-apps-navigation 1.0.3 "Chrome Apps Navigation"
cordova-plugin-chrome-apps-runtime 1.1.1 "Chrome App Runtime"
cordova-plugin-chrome-apps-storage 1.0.4 "Chrome Apps Storage API"
cordova-plugin-crosswalk-webview 1.2.0 "Crosswalk WebView Engine"
cordova-plugin-customevent-polyfill 1.0.5-dev "CustomEvent constuctor shim"
cordova-plugin-file 2.0.0 "File"
cordova-plugin-google-open-source-ios 1.7.1 "Google Open Source iOS Framework Pl
ugin"
cordova-plugin-google-plus-ios 1.7.2 "Google Plus iOS Framework Plugin"
cordova-plugin-inappbrowser 1.0.0 "InAppBrowser"
cordova-plugin-network-information 1.0.0 "Network Information"
cordova-plugin-statusbar 1.0.0 "StatusBar"
cordova-plugin-whitelist 1.0.0 "Whitelist"
cordova-plugin-xhr-blob-polyfill 1.0.3 "XHR Blob Response Type Polyfill"
org.chromium.cca-hooks 0.0.0 "undefined"

**Comment by floatinghotpot** [comment]
@Knorcedger thanks for your feedback. it's now fixed, instead of ```com.google.cordova.admob```, please use ```cordova-plugin-admobpro```, which is in npm repo and follows the cordova v5.0 rules.

**Comment by Knorcedger** [comment]
@floatinghotpot Thank you, it looks fine now. Thank you for the awesome plugin!
