### ISSUE TITLE
The iAd adapter doesn't support cordova 5.0? Or is it a mistake?

### ISSUE THREAD

**Issue by earslap** [floatinghotpot/cordova-admob-pro#129]
I used to do

    cordova plugin add com.google.cordova.admob
    cordova plugin add com.google.cordova.admob-iad

with cordova 4.x

now when I do the first one, cordova says it's been renamed to cordova-plugin-admobpro so I install that instead. Then I do:

    cordova plugins add cordova-plugin-admob-iad

following the renaming convention (got the name from npm registry) but while intalling cordova says:

    Failed to install 'cordova-plugin-admob-iad':CordovaError: Plugin doesn't support this project's cordova version. cordova: 3.8.0, failed version requirement: >=5.0

if I install com.google.cordova.admob-iad as I did in the past, it installs just fine but not the latest version (1.0.1 instead of 1.0.2)

Is this expected behaviour?

**Comment by floatinghotpot** [comment]
thanks for the feedback. it's a bug after migrate to cordova CLI v5.0. 

the version requirement for >= 5.0 is not correct, now it's changed back to v3.5, and cordova-ios v3.8 should work now. 

please remove cordova-plugin-admob-iad and add back.
