### ISSUE TITLE
Android Interstitial ->  Blackscreen

### ISSUE THREAD

**Issue by christoph-schindler** [floatinghotpot/cordova-admob-pro#130]
Since last update of the plugin our app starts with a black screen on android phones... you cannot use the app anymore. There is an "no fill"-error for the interstital-ad (sometimes we have no advertising). Before the update nothing happened in such a case (which I think is the correct behavior).. To crash the app with a black screen should not be an intention.
Can you confirm this issue and can you please tell me when to expect a fix?

**Comment by floatinghotpot** [comment]
Could you please show me the version info of cordova and the plugins? If you are using cordova CLI, you can get it by typing: cordova platform ls, cordova plugin ls

**Comment by bheijns** [comment]
We currently have this issue with a smart banner (bottom screen). The banner itself loads as usual and shows up but then the rest of the screen is just black and the user can't do anything anymore.

We are using:

Phonegap Build 3.7.0
with
 <gap:plugin name="com.google.cordova.admob" source="plugins.cordova.io" version="2.7.4" />

Till a few days ago this was working fine!

**Comment by jmelvin** [comment]
Running Cordova 4.1.2 with the very latest standard plugins caused the blackscreen for me.  After the splashscreen was displayed and dismissed, the screen was all black on Android forevermore.  IOS was fine.  I did not pin down which standard plugin install caused the incompatibility.  Upgrading to Cordova 5.0.0 resolved it.  

NOTE: I noticed some unrelated issues with upgrading to 5.0.0.  The default build is debug instead of release, the Content Security Policy appears to be more enforced, and build/intermediates are not removed after the build.

NOTE2: the blackscreen problem is not related to the earlier issue with the admob-pro plugin showing ads in the middle of the screen.  I saw the blackscreen problem before upgrading to the latest admob-pro code that included the fix.

Hope this helps!

**Comment by christoph-schindler** [comment]
We use phonegap builder with the latest phonegap version 3.7.0 and these plugins:
  <gap:plugin name="org.apache.cordova.device" />
  <gap:plugin name="org.apache.cordova.dialogs" />
  <gap:plugin name="org.apache.cordova.inappbrowser" />
  <gap:plugin name="org.apache.cordova.statusbar" />
  <gap:plugin name="com.pushwoosh.plugins.pushwoosh" version="3.4.2"/>
  <gap:plugin name="nl.x-services.plugins.socialsharing" version="4.3.8" />
  <gap:plugin name="net.yoik.cordova.plugins.screenorientation" />
  <gap:plugin name="com.google.cordova.admob" source="plugins.cordova.io" />
There was no change in this configuration, but suddenly the builds have the black screen error. However, I must admit that I have suspected the wrong adType ... bheijns is right: it's the banner that's causing the black screen (not the empty interstitial). We request both at start and only the removal of the banner prevented the error.
As far as I can tell, it is not caused by an incompatibility with other plugins. Even if all plug-ins are disabled except AdMobPro, the screen remains black.
Reminder: it's only Android... not iOS.

I have to agree with bheijns again: Till a few days ago this was working fine!

**Comment by bheijns** [comment]
Do you use a framework for your app Christoph? 

For our app we make use of Onsen UI.

**Comment by floatinghotpot** [comment]
Thanks for the detailed info.

I guess it's caused by a recent update to resolve incompatibility with new cordova-android 4.0.0 but bring new trouble to old cordova version which is still running in phonegap build service. 

Will look into the issue and find solution soon.

**Comment by brianseeders** [comment]
We are suddenly seeing this in our project as well. Building on cordova 4.2.0.

Tried installing the plugin with com.google.cordova.admob@2.7.0, but it's still happening. Continuing to do research. Anyone have any luck fixing it?

**Comment by bheijns** [comment]
Nope. Still same issue also @ 2.7.0

**Comment by brianseeders** [comment]
Okay. The issue seems to be with a dependency and the culprit is this commit: https://github.com/floatinghotpot/cordova-extension/commit/887793a855bc12c393525367f413a013b93ab8df

I have forked the plugin and edited the plugin.xml to use an old version of that dependency, so that we are able to build apps again.

https://github.com/brianseeders/cordova-admob-pro
https://github.com/brianseeders/cordova-admob-pro/commit/c67fb4cd38f9b6dce2569a3bac11bea02a145f6c

I don't plan on keeping that up-to-date, and will switch back to the official distribution in our project later, so be careful if you directly reference my fork.

**Comment by floatinghotpot** [comment]
it's a defect that newly introduced, when resolving compatibility issue for cordova-android 4.x (cordova CLI v5.0), it breaks compatibility with cordova-android 3.x (cordova CLI v4.x)

now it's fixed, and already tested it to verify the plugins works for both cordova-android 3.x and 4.x

Please remove and re-add the plugin, and double check the version to make sure you see:

com.google.cordova.admob 2.7.7 "AdMob Plugin Pro"
com.rjfun.cordova.extension 1.1.3 "Cordova Plugin Extension"

NOTICE: if you are using cordova CLI, remember to clear the cache in ~/.plugman/cache before removing/adding plugin, to avoid old version causing trouble.

**Comment by kirmandi** [comment]
last version of extension seems to fix it, had the exact same problem and already looked into anything until i found that the admob plugin was responsible ...

**Comment by christoph-schindler** [comment]
Thank you very much for the quick help. The black screen is actually gone ... but with him the banner?! 
Were there any other changes in the new version (may be "autoShow" no longer supported)? 
Even if "isTesting" is activated, you can see no advertising. The event "onAdLoaded" is called but the banner doesn't appear.

**Comment by bheijns** [comment]
Great work guys!! Thanks! Our app works like before and since we planned to release our new version tomorrow this arrived just in time :+1: 

@christoph-schindler We also use bottom center banners. It works seems a bit slower then before. Do you want a snippet of our code?

**Comment by christoph-schindler** [comment]
@bheijns That would be great ... our ads are now unfortunately neither centered nor do they have a transparent background like before. The "overlap" doesn't work, too. And they do not appear at the initial launch of the app. Hopefully your snippet can help.

**Comment by bheijns** [comment]
Hi @christoph-schindler ! We set up this code for our app:

function createBanner(){
    document.body.style.marginBottom = "50px";
    if(typeof AdMob !== 'undefined'){
		if(AdMob){ 
			AdMob.removeBanner();
			AdMob.createBanner({
				adId:admobid.banner, 
				position:AdMob.AD_POSITION.BOTTOM_CENTER, 
				autoShow:true,
	            overlap: true
			});
		}
	}
}

function removeBanner(){
	document.body.style.marginBottom = "0px";
	if(typeof AdMob !== 'undefined'){
		if(AdMob){ 
			AdMob.removeBanner();
		}
	}
}

function initAd(){

	logger("initAdd function");
	var defaultOptions = {
		// bannerId: admobid.banner,
		// interstitialId: admobid.interstitial,
		 adSize: 'SMART_BANNER',
		// width: integer, // valid when set adSize 'CUSTOM'
		// height: integer, // valid when set adSize 'CUSTOM'
		position: AdMob.AD_POSITION.BOTTOM_CENTER,
		// offsetTopBar: false, // avoid overlapped by status bar, for iOS7+
		bgColor: 'black', // color name, or '#RRGGBB'
		// x: integer,		// valid when set position to 0 / POS_XY
		// y: integer,		// valid when set position to 0 / POS_XY
		
		// TESTMODUS -----------------------------------------------------------------
		// isTesting: true // set to true, to receiving test ad for testing purpose
		// TESTMODUS -----------------------------------------------------------------
		
		// autoShow: true // auto show interstitial ad when loaded, set to false if prepare/show
	};
	AdMob.setOptions( defaultOptions );
//	registerAdEvents();
	logger("AdMob setOptions done");

/*	AdMob.createBanner( {
		adId:admobid.banner, 
		overlap:1, 
		offsetTopBar:offsetTopBar, 
		adSize: getSelectedAdSize(), 
		position:getSelectedPosition()
	} );
*/
	if(AdMob){
		logger("Admob created");
	}
}

**Comment by floatinghotpot** [comment]
@christoph-schindler Will look into your issue.

**Comment by floatinghotpot** [comment]
The code has been optimized a little bit, please try again.

The snippet by bheijins is using overlap mode and set a margin for web content. I did not try this method but hope it works.

You can also use split mode by setting overlap:false, plugin will auto arrange the layout when banner ready to show.

**Comment by christoph-schindler** [comment]
Neither the optimization nor the kindly provided code helped. The app starts, the banner loads, the "onAdLoaded"-event is called, but the advertising is invisible. 

BUT: if you wait until the screen turns off and then hit a key to resume: the banner appears.

Perhaps the banner is there from the beginning, but off screen, or hidden, or a level too low?!

This issue is android only. On iOS devices the banner loads without any problems.

**Comment by christoph-schindler** [comment]
Like bheijns mentioned: it takes a little longer, but the banner work again!
