### ISSUE TITLE
Android banner middle screen

### ISSUE THREAD

**Issue by braianj** [floatinghotpot/cordova-admob-pro#131]
Y just saw that 5 days ago you fixed the problem, but i'm still having this issue.
```
AdMob.createBanner( {
			    adId: admobid.banner, 
			    position: AdMob.AD_POSITION.BOTTOM_LEFT,
			    autoShow: true 
			});
```

how can we solve this?

**Comment by floatinghotpot** [comment]
No logs no screenshots no version info, is it a good bug report?

**Comment by floatinghotpot** [comment]
Don't create new issue for same problem, please discuss in #119
