### ISSUE TITLE
AdMob.isInterstitialReady is not a function

### ISSUE THREAD

**Issue by butlimous** [floatinghotpot/cordova-admob-pro#132]
I have successfully installed the plugin and showed ads. I want to make sure that an is fully loaded before showing to avoid it from just popping randomly inside the game. I'm getting in my console log that "AdMob.isInterstitialReady is not a function". Have you removed it or something?

Thanks
Regards
Michael

**Comment by floatinghotpot** [comment]
You can use option autoShow:false, and listen to onAdLoaded event.

**Comment by butlimous** [comment]
I'm already using the autoShow: false. Has the above function been deprecated?

**Comment by floatinghotpot** [comment]
Yes. It's deprecated months ago, as it often caused confusion. Do you think it's still useful?

**Comment by butlimous** [comment]
It's useful in my case but not mandatory :) I want to show an ad after a user finishes a game level. So I tried to use this function to check if the interstitial is ready, then show it. If It's not ready, just don't show it.
The AdLoaded event won't fit well here as It will fire when the ad is loaded while the user is still in the current level. The deprecated one just fits well as I can just check at the time I want to show an ad whether it's ready or not.

Anyway, I can just give a variable a value when the AdLoaded event is fired and then check if this variable has that variable when I want to show an ad :)

Thanks
Regards
Michael

**Comment by JoeSchr** [comment]
hello, if it's really deprecated please also change the documentation: https://github.com/floatinghotpot/cordova-admob-pro/wiki/1.4-Methods-for-Interstitial

thx!
