### ISSUE TITLE
Ads are not showing up on mobile data, however it is working fine in wifi. Blank black space is displayed on mobile data.

### ISSUE THREAD

**Issue by sidbanya** [floatinghotpot/cordova-admob-pro#133]
Ads are not showing up on mobile data, however it is working fine in wifi. Blank black space is displayed on mobile data.

**Comment by floatinghotpot** [comment]
android, or ios?

**Comment by sidbanya** [comment]
Android .
Ios haven;t tried yet .

On Mon, May 18, 2015 at 5:01 PM, Raymond Xie <notifications@github.com>
wrote:

> android, or ios?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/floatinghotpot/cordova-admob-pro/issues/133#issuecomment-103025146>
> .
>



-- 
--
Thanks,

Sidharth Banyal
+91- 8447194719
Skype: sidharth.banyal

**Comment by sidbanya** [comment]
It is working now.
