### ISSUE TITLE
AdMob is not defined

### ISSUE THREAD

**Issue by hotgeart** [floatinghotpot/cordova-admob-pro#135]
Hi,

I've an issue with this plugin. The ads doesn't show and I've this error in my js console : *AdMob is not defined*.

Command I writed in my console : 

![cmd](http://image.noelshack.com/fichiers/2015/21/1432211404-sans-tidddddddddddtre-1.png)

My code (it's only an Android APP) :

```html
<script type="text/javascript">
    $(document).ready(function() {

        var admobid = {
            banner: 'ca-app-pub-.......................................................'
        };

        if(AdMob) AdMob.createBanner({
            adId: admobid.banner, 
            position: AdMob.AD_POSITION.TOP_CENTER, 
            autoShow: true
        });

    // other JS stuff
```

Any idea ?

Thank for your time.

**Comment by floatinghotpot** [comment]
The plugin is not added or not added correctly.

If you are using Cordova CLI, try remove and re-add android platform.

cordova plugin add ...

cordova platform remove android
cordova platform add android

It will often fix this issue.

**Comment by hotgeart** [comment]
No, I removed android and add again twice. I create an other project, nothing works.

Except when I follow this tutoriel https://github.com/floatinghotpot/cordova-admob-pro/wiki/01.-How-to-Use-with-Cordova-CLI . So I imagine someting is wrong with my JS

**Comment by hotgeart** [comment]
Ok it's work now, I had a number in my id. Exaple : com.7example.app .

I got no error when I build and now yes same as him :http://stackoverflow.com/questions/19554965/error-building-android-app-with-cordova-3-1-cli

I change my id to com.sevenexample.app and now it's work WTF :open_mouth: 

thx I close
