### ISSUE TITLE
Keyboard opened before banner show up

### ISSUE THREAD

**Issue by calebeaires** [floatinghotpot/cordova-admob-pro#136]
When user uses the keyboard before the banner "autoShow", this banner move up with the keyboard. I am trying to find an solution that watch this user action to prevent ads to move up when keyboard opens before ads autoshow.

Do you have a clue?

**Comment by floatinghotpot** [comment]
It's a know issue but not fixed yet, same as #23.

**Comment by floatinghotpot** [comment]
Good news, it's fixed. When banner at either bottom or top, it works perfectly with soft keyboard.  Please update to cordova-plugin-admobpro v2.11.0, enjoy. :-)
