### ISSUE TITLE
Crash on Lollipop with Crosswalk

### ISSUE THREAD

**Issue by do-web** [floatinghotpot/cordova-admob-pro#137]
My app plays html 5 audio data, if admob is enabled the app crashed some time if i play audio.

                var defaultOptions = {
                    bannerId: 'xxx',
                    interstitialId: 'xxx',
                    adSize: 'SMART_BANNER',
                    position: AdMob.AD_POSITION.BOTTOM_CENTER,
                    bgColor: '#30619D', // color name, or '#RRGGBB'
                    isTesting: true, 
                    autoShow: true
                };
                AdMob.setOptions( defaultOptions );
                AdMob.createBanner( {adId:defaultOptions.bannerId, overlap:false, adSize: defaultOptions.adSize, position:defaultOptions.position} );

**Comment by do-web** [comment]
If i use overlap:true the app don't crash.

**Comment by floatinghotpot** [comment]
No logs, no clues. Can you build and run it with Eclipse, and paste me the crash log in LogCat window?

**Comment by Netpolice** [comment]
Want to have the log, but there is no error logs. However, if comment out the AdMob.createBanner, then alright, so make sure that AdMob.createBanner to crash the app.

**Comment by floatinghotpot** [comment]
May be caused by crosswalk changed the cordova view hierarchy and cause problem.

Maybe you can try adding one options to createBanner(), overlap:true

**Comment by TheodoreLogan** [comment]
I'm also having a similar crash (audio is also involved). I can't get a stracktrace; my logcat is just throwing a memory violation and a tombstone the moment I try to show a banner after the app has been "paused" and "resumed" on android.

If anyone can point me in the direction of better logs that would be great! I'd also be grateful if anyone can elaborate on @do-web comment:
>i solved this bug by calling clear gc before a new ad is loaded 

````
W/google-breakpad(22169): ### ### ### ### ### ### ### ### ### ### ### ### ###
W/google-breakpad(22169): Chrome build fingerprint:
W/google-breakpad(22169): 1.1.1
W/google-breakpad(22169): 101010
W/google-breakpad(22169): 873fd9bc-5759-4679-9dc5-2d671bd0c1b7
W/google-breakpad(22169): ### ### ### ### ### ### ### ### ### ### ### ### ###
E/chromium(22169): ### WebView Version 44.0.2403.90 (code 240309000)
F/libc    (22169): Fatal signal 4 (SIGILL), code 1, fault addr 0xa499dedc in tid 22338 (Audio Decoder)
I/DEBUG   (  243): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
````

**Comment by floatinghotpot** [comment]
I re-tested it with cordova-plugin-crosswalk-webview, it not crash. 

I just guess crosstalk team has fixed it when replacing the default system webview with crosswalk webview.
