### ISSUE TITLE
Keyboard open an banner appears - view wrong size

### ISSUE THREAD

**Issue by do-web** [floatinghotpot/cordova-admob-pro#138]
If the keyboard is open and than the banner appears, the cordova view keeps the wrong size.

**Comment by floatinghotpot** [comment]
please paste a screenshot and your code calling the plugin api, thanks.

**Comment by floatinghotpot** [comment]
almost same as #23, let's follow it up in that issue tracker.

**Comment by floatinghotpot** [comment]
Good news, it's fixed. When banner at either bottom or top, it works perfectly with soft keyboard.  Please update to cordova-plugin-admobpro v2.11.0, enjoy. :-)
