### ISSUE TITLE
Removing banner doesn't resize screen

### ISSUE THREAD

**Issue by slikk66** [floatinghotpot/cordova-admob-pro#139]
Hi..

I've been using this plugin for a while..  This used to work with the same code.  Now, when my user logs out, I call AdMob.removeBanner() to remove the banner and reclaim the screen space.  My banner is bottom center in the footer.

Now, when I remove it, the banner goes away, but a black box remains and the screen doesn't go back to full size.

I tried to run hideBanner() also, but that didn't work!

Any tips?

**Comment by floatinghotpot** [comment]
ios or android? which version? 

is overlap set to true or false?

**Comment by slikk66** [comment]
Android, and I just removed and reinstalled the plugin, says it's version 2.7.7

Overlap?  I haven't touched this setting.. however I didn't before when this wasn't a problem.  Is this a new change/feature in later version?

```dbi-osx:app slikk66$ ionic plugin list
Updated the hooks directory to have execute permissions
android.support.v4 21.0.1 "Android Support v4"
com.google.cordova.admob 2.7.7 "AdMob Plugin Pro"
...
```

**Comment by floatinghotpot** [comment]
Need more input before figuring out the root cause.

Your cordova-android version please? You can get it by typing "cordova platform ls".

And let me have a look at your code calling the plugin. Thanks.

**Comment by slikk66** [comment]
Version Info:

dbi-osx:app slikk66$ cordova platform ls
Installed platforms: android 4.0.0
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, ios

Code:

This runs on app login:

--------

                    AdMob.createBanner( 
                        {
                            adId: CONFIG.admobid.banner, 
                            position: AdMob.AD_POSITION.BOTTOM_CENTER, 
                            autoShow: true
                        }
                    );

                    AdMob.prepareInterstitial( {adId:CONFIG.admobid.interstitial} );

--------

This runs on each load where we trigger the interstitial:

            if ( $scope.interstitialReady == 1 ) {
            
                AdMob.showInterstitial();

                $scope.interstitialReady = 0;
            
                AdMob.prepareInterstitial( {adId:CONFIG.admobid.interstitial, autoShow: false} );
            
            }

--------

This fires the angular event that sets the scope flag above for ad being ready:

    document.addEventListener('onAdLoaded',function(data){
        if ( data.adType == 'interstitial' ) {
            $rootScope.$broadcast('interstitial-ready');
        }
    });

--------

This runs on logout:

                if ( typeof AdMob != 'undefined' ) {
                    AdMob.removeBanner();
                }

---------

Couple of questions.. 

1 - What happens if you run a prepareInterstitial() while one is already loading or one has loaded but not been fired yet?  Will it only load one at a time or is that something to avoid?  I could probably work this better in my app

2 - When you run removeBanner() does that remove all banners?  I mainly want to remove the lower/bottom banner, which it does.. it's just that the black area where it was remains.

Thanks!

**Comment by floatinghotpot** [comment]
Thanks for the detailed info, I will look into it. 

Here I answer your question first:

1. There is only one interstitial Ad and one banner Ad at the same time. And Google does not allow us to present too many Ad on the same screen, as it will cause poor user experience.

2. No need to consider this, as you should display only one banner, either at top or at bottom.

**Comment by petarov** [comment]
I've got a similar issue on Android, but in a different context. Plugin version is plugin `2.7.7`.

In my case the app starts in `Landscape` mode. Then, when I rotate the device in `Portrait`mode I call `removeBanner()` and then `createBanner()` again, otherwise the banner does not get shown! The banner gets created but the app view gets cut in half somehow. Perhaps the Android layout is not reset/re-aligned or something. I believe it might be connected to this issue.

```javascript
       options = {
          'adSize': AdMob.AD_SIZE.SMART_BANNER,
          'position': AdMob.AD_POSITION.BOTTOM_CENTER,
          'overlap': false,
          'autoShow': false,
        };
```

**Comment by floatinghotpot** [comment]
Fixed.
