### ISSUE TITLE
Not work.

### ISSUE THREAD

**Issue by alissonlinneker** [floatinghotpot/cordova-admob-pro#140]
The Interstitial banner is working. But normal is not working.

See:

if(AdMob) AdMob.prepareInterstitial( {adId:admobid.interstitial, autoShow:true} );
				AdMob.isInterstitialReady(function(isready){
					if(isready) AdMob.showInterstitial();
				});
				if(AdMob) AdMob.createBanner( { adId:admobid.banner, position:AdMob.AD_POSITION.BOTTOM_CENTER, autoShow:true} );

**Comment by floatinghotpot** [comment]
What do you mean by "not working"? Any info about platform, version, logs, screenshots?

Some comments:
* isInterstitialReady() has been deprecated. It may cause error if call a non-existing API.
* as you already call prepareInterstitial() with autoShow:true, no need to call showInterstitial().

**Comment by alissonlinneker** [comment]
The Interstitial is working.
What is not working:

if(AdMob) AdMob.createBanner( { adId:admobid.banner, position:AdMob.AD_POSITION.BOTTOM_CENTER, autoShow:true} );

I use last version of PG/Cordova.
Only the banner in the footer does not want to work.

**Comment by floatinghotpot** [comment]
iOS or android?

**Comment by alissonlinneker** [comment]
both

**Comment by floatinghotpot** [comment]
You can try removing this code 
```javascript
AdMob.isInterstitialReady(function(isready){
if(isready) AdMob.showInterstitial();
});
```
then try again, as the error may interrupt your code execution.

**Comment by alissonlinneker** [comment]
Not work. : /

See my code:

<script type="text/javascript">
            
			function onDeviceReady() {
				var admobid = {};
				if( /(android)/i.test(navigator.userAgent) ) { // for android
					admobid = {
						banner: 'ca-app-pub-7075634274678445/4110341817 ', // or DFP format "/6253334/dfp_example_ad"
						interstitial: 'ca-app-pub-7075634274678445/5587075014'
					};
					} else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) { // for ios
					admobid = {
						banner: 'ca-app-pub-7075634274678445/7203409015', // or DFP format "/6253334/dfp_example_ad"
						interstitial: 'ca-app-pub-7075634274678445/8680142214'
					};
					} else { // for windows phone
					admobid = {
						banner: 'ca-app-pub-7075634274678445/1017274610', // or DFP format "/6253334/dfp_example_ad"
						interstitial: 'ca-app-pub-7075634274678445/2494007812'
					};
				}
				if(AdMob) AdMob.createBanner( { adId:admobid.banner, position:AdMob.AD_POSITION.BOTTOM_CENTER, autoShow:true} );
			};
		</script>
<body onload="onDeviceReady()">
.... content ...
</body>

**Comment by floatinghotpot** [comment]
Please directly use the sample file for a test:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/test/index.html
