### ISSUE TITLE
Ads not displaying with Phonegap + Phaser JS 2.02

### ISSUE THREAD

**Issue by rubberbird** [floatinghotpot/cordova-admob-pro#141]
Using the below code I get no adds, nothing on screen at all
- phonegap plugin add cordova-plugin-admobpro
- Phonegap - 5.0.0-0.27.1
- Phaser JS 2.02

Xcode Console:
2015-06-06 16:44:08.884 Marty[13908:2057002] [CDVTimer][admob] 0.124991ms
2015-06-06 16:44:08.884 Marty[13908:2057002] [CDVTimer][TotalPluginStartup] 0.286996ms

onDeviceReady: function() {
      // it will display smart banner at top center, using the default options
      if(AdMob) AdMob.createBanner( {
          adId: "ca-app-pub-XXXXXXXXXXXXXXXXXXXXX",
          position: AdMob.AD_POSITION.TOP_CENTER,
          autoShow: true,
          overlap:true, // overlap the game, so it won't steal space to canvas
          isTesting: true // show a demo ad
        });
              app.receivedEvent('deviceready');
    },

**Comment by floatinghotpot** [comment]
Try the plugin with its sample index.html first, with following commands:
```bash
[sudo] npm install plugin-verifiy -g
plugin-verify cordova-plugin-admobpro ios
```

If you can see the admob demo in simulator, then double check your code.

**Comment by rubberbird** [comment]
The simulator is working, But still no luck in my project. I have tried various different code solutions. With one I am getting ReferenceError: AdMob is not defined.

What would be causing this?

**Comment by floatinghotpot** [comment]
As I know, phaser requires a web server and load all game resources from the server, while the Cordova loads html5 from local path, this may be the root cause.

You can try the Cordova local server mode, or try Cordova-httpd which adds an embedded web server in Cordova.

**Comment by floatinghotpot** [comment]
@rubberbird sorry my previous answer is not correct. Phaser can work quite well in Cordova framework.

Here I just write a demo for phaser with admob:
https://github.com/floatinghotpot/admob-demo-game-phaser

You can copy all the files in demo folder to your www/ for a testing.
https://github.com/floatinghotpot/admob-demo-game-phaser/tree/master/demo

**Comment by rubberbird** [comment]
@floatinghotpot  Hey, thanks so much for taking the time to provide an working example. I will take a look at it and hopefully I can get mine to work also. Great stuff. Thanks again.

**Comment by PeterKoKo** [comment]
Tell me if you still have problem seeing admob apps in phonegap/cordova app. It might be something wrong with "ondeviceReady" event you. You need to wait this event first before you insert your game code.

Something like this:
(Create it as a seperate js file and give it a name and just reference to it in your index.html file with <script></script> tag.) This code waits "ondeviceReady" event I mentioned above. Also don't forget to reference "cordova.js" file in your index.html file.

**Comment by PeterKoKo** [comment]
Tell me if you still have problem seeing admob apps in phonegap/cordova app. It might be something wrong with "ondeviceReady" event you. You need to wait this event first before you insert your game code.

Something like this:
''''''''javascript
var app = {
    // Some scoped variables

    onDeviceReady : function () {
		
		// Adding Game after device ready
		
		game = new Phaser.Game(window.innerWidth, window.innerHeight, Phaser.AUTO,'mygame');
   
   //Add all states
				game.state.add("Boot", Boot);
				game.state.add("Preload", Preload);
				game.state.add("GameTitle", GameTitle);
				game.state.add("Main", Main);
				game.state.add("GameOver", GameOver);

				//Start the first state
				game.state.start("Boot");

        // alert("device ready.");
        console.log("device ready.");
        if (device.platform === "iOS") {
            // deals with post-iOS-7 change that covers the status bar
            // http://coenraets.org/blog/2013/09/phonegap-and-cordova-with-ios-7/
            document.body.style.marginTop = "20px";
        } else if (device.platform == 'Android') {
            // Get rid of 300ms delay 
            document.addEventListener('DOMContentLoaded', function() { FastClick.attach(document.body); }, false);
        } else if (device.platform == 'browser') {
            console.log("You are using a brower.");
        }

    }
};

// Wait for PhoneGap to load
document.addEventListener("deviceready", app.onDeviceReady, false);

// This JS object is create to support `app.onDeviceReady()`, and the timeout below.
// When `deviceready` fires, this variable is overwritten.
// The hope is that "Cordova/Phonegap" have completed before the timeout.
var device = {platform:'browser'};

// This timeout check to see if `cordova.js` has loaded the `device` plugin.
setTimeout(function() {
        console.log("timeout fired.");
        if (! ('cordova' in device) ) {
            app.onDeviceReady();
        }
    },
    2000);

// Note: this is created last with the hope that the entire DOM has loaded.
// If needed, we could wrap this with a function.
// The best time to load this binding is after the `deviceready` event has fired.
// 


'''''''

(Create it as a seperate js file and give it a name and just reference to it in your index.html file with <script></script> tag.) This code waits "ondeviceReady" event I mentioned above. Also don't forget to reference "cordova.js" file in your index.html file.
