### ISSUE TITLE
whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by victorhguillen** [floatinghotpot/cordova-admob-pro#142]
I receive this warning when try to put the ad before to play a video from stream.

Warning: Attempt to present ```Warning: Attempt to present <GADInterstitialViewController: 0x1994ce80> on <MainViewController: 0x155b1f60> whose view is not in the window hierarchy! ```

**Comment by floatinghotpot** [comment]
your cordova-ios and plugin version please?

**Comment by victorhguillen** [comment]
@floatinghotpot 
cordova -v 5.0.0

cordova-plugin-admobpro 2.8.0 "AdMob Plugin Pro"

Regards.

**Comment by floatinghotpot** [comment]
I re-tested it on ios, and cannot reproduce your problem.

can you tell me the steps to re-produce the issue?

**Comment by victorhguillen** [comment]
```
    $scope.playVideo = function(videoUrl){

        var options = {
            successCallback: function() {

            },
            errorCallback: function(obj) {
                $cordovaDialogs.alert('No se puede reproducir el canal en estos momentos', 'Canal fuera del aire', 'Ok');
            }
        };
        window.plugins.streamingMedia.playVideo(videoUrl, options);
        $timeout( function(){ $cordovaGoogleAds.prepareInterstitial( {adId:AdMob.admobid.interstitial, autoShow:true} ); }, 30000);

    };
```

**Comment by floatinghotpot** [comment]
I think it's probably caused by the streamingMedia plugin, which changed the Cordova view hierarchy.
