### ISSUE TITLE
Admob stopped building in Intel XDK

### ISSUE THREAD

**Issue by tysjiang** [floatinghotpot/cordova-admob-pro#143]
When trying to build with the latest version of Admob Pro and Intel XDK v1995 Cordova Android or iOS, it fails with the message: Error: Plugin "admob" failed to install.

To reproduce:
Add Admob as a third party plugin using
Name: Admob
Plugin ID: cordova-plugin-admobpro
Repo URL: https://github.com/floatinghotpot/cordova-admob-pro.git
Note: Same issue happens when using the option Apache Cordova Plugins Registry

This just started happening, the last time I built successfully was a month or so ago with the same unchanged info (and has been using Admob for a good year or so now) so something probably got messed up in the past month.

**Comment by floatinghotpot** [comment]
I guess Intel XDK has not upgraded cordova to v5.0 and not support npm repo yet.

Please try the old Id: com.google.cordova.admob

**Comment by tysjiang** [comment]
hm.. just tried using the old id (tried with git repo and cordova registry) but the error persisted
not sure where to go from here...
(note: Intel XDK is using Cordova 4.1.3)

**Comment by floatinghotpot** [comment]
Please do not use github repo URL in Intel XDK, instead, use id "com.google.cordova.admob", and check the checkbox of "plugin in cordova registry".

**Comment by tysjiang** [comment]
Thank you, using the id: "com.google.cordova.admob" and pulling it from the registry worked and all builds are building successfully now.
