### ISSUE TITLE
DFP Banner Ad always at BOTTOM_LEFT

### ISSUE THREAD

**Issue by jade81** [floatinghotpot/cordova-admob-pro#146]
Hello,

I have added your plugin to my Cordova project to show dfp banner.
This is my code:

if(AdMob) AdMob.createBanner( {
			adId: "XXXXX", 
			position: AdMob.AD_POSITION.BOTTOM_CENTER, 
			autoShow: true } );

Up to about 1 month ago it works properly showing banner at BOTTOM_CENTER, but now it is always shown at BOTTOM_LEFT.
I have tried to add overlap property: if I set it to true, the banner is correctly shown at BOTTOM_CENTER, if I remove overlap property or set it to false banner is shown at BOTTOM_LEFT.
I need overlap set to false.
Thanks

**Comment by floatinghotpot** [comment]
Android or iOS?

**Comment by jade81** [comment]
android 5.0.
if you need it, the dfp code is  "/1017836/320x50_Radio_Leaderboard" (it's
a banner)

thanks

2015-06-10 11:21 GMT+02:00 Raymond Xie <notifications@github.com>:

**Comment by floatinghotpot** [comment]
If you are using DFP banner with a fixed size like 320x50, try use adSize BANNER instead of SMART_BANNER.

**Comment by jellomaster** [comment]
I have the same issue in Android 6.0.  adSize: BANNER. Overlap:false.  If you choose position:8, it will align bottom left.  If you choose position 2, it will align top left.  If you put Overlap: true.  The positioning is in center for both situations.
