### ISSUE TITLE
Ad Mediation

### ISSUE THREAD

**Issue by Chuckv01** [floatinghotpot/cordova-admob-pro#147]
Can this plugin be used with your Flurry plugin (https://github.com/floatinghotpot/cordova-plugin-flurry) for ad mediation via AdMob? I would like to use AdMob to serve Flurry ads in my ionic app.

Thank you for your great work on these plugins. Truly wonderful.

**Comment by floatinghotpot** [comment]
Yes, you can install the mediation adapter:
```cordova plugin add cordova-plugin-admob-flurry```

It depends on two plugins and will install them automatically:
* cordova-plugin-admobpro
* cordova-plugin-flurry

And, you need configure in your admob portal, link your flurry account to your admob ad unit id.

**Comment by Chuckv01** [comment]
This issue could very well be specific to my project, but when I ran:

<code>cordova plugin add cordova-plugin-admob-flurry</code>

I received some errors when building on android:

![screen shot 2015-06-11 at 8 12 32 am](https://cloud.githubusercontent.com/assets/1181306/8110527/b0fb906a-1011-11e5-949c-c22db42849db.png)


Removing the flurry mediation plugin seemed to fix the issue and allow me to build successfully. Does my project have a conflict of some sort with the flurry mediation plugin, or is this issue on the plugin's end?

Thanks!

**Comment by Chuckv01** [comment]
I also faced the same build error on android with the cordova-plugin-admob-mmedia plugin. Here is meta project information:

Cordova CLI: 5.0.0
Ionic Version: 1.0.0-rc.1
Ionic CLI Version: 1.5.0
Ionic App Lib Version: 0.1.0
ios-deploy version: 1.5.0 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 6.3.2 Build version 6D2105

**Comment by floatinghotpot** [comment]
I verified the plugin, no problem.

The admob / flurry plugin use the default one in your Android SDK, see plugin.xml:
```xml
<framework src="com.google.android.gms:play-services-ads:+" />
```

From the error, it's caused by duplicate google-play-services.jar, please check if another plugin reference to it or contains such a jar.
