### ISSUE TITLE
DFP No Banners on Android Tablets or Landscape

### ISSUE THREAD

**Issue by chrisschaub** [floatinghotpot/cordova-admob-pro#149]
So, we are getting DFP banners on iphone and android phone. But on tablets, we don't see any banners. We are using sponsor banners, 100% fill. Is there some special setting for DFP? I've used this code with AdMob and it works great, but DFP seems to be a little different?

**Comment by floatinghotpot** [comment]
I just guess, it may be the size of banner, they are different on iphone and ipad/tablet. On iPhone it's 320x50, on iPad, the height of banner is 90. 

Can you check whether you can configure in DFP, or may need design a different size?

**Comment by chrisschaub** [comment]
So, we have some 90 height banners. Also, on iPhone, when we turn landscape, the banners disappear. Is it possible there is something different with DSP and how the code is invoked? I'm calling createBanner like this:
```
 AdMob.createBanner({
            adId:'/#######/footer-ad',
            overlap:true,
            position:AdMob.AD_POSITION.BOTTOM_CENTER,
            autoShow:true,
            license: 'mylicensekeyishere,
            isTesting: false,
...
```
It just seems odd that this code works for AdMob, but for DSP it has quirks. DSP says this regarding sizes:
![screen shot 2015-06-11 at 5 34 27 pm](https://cloud.githubusercontent.com/assets/3321008/8128486/27636cb0-10c5-11e5-96e6-116ca5bcf8ad.png)
just wondering if DSP ads are working for you, esp on tablets and landscape on phones?

**Comment by floatinghotpot** [comment]
When iPhone landscape the banner height is 32, not 50.

See: 
https://developers.google.com/admob/ios/banner

**Comment by floatinghotpot** [comment]
As we are discussing in another issue tracker, I'd like to close this one.
