### ISSUE TITLE
Build error with Telerik Build service?

### ISSUE THREAD

**Issue by chrisschaub** [floatinghotpot/cordova-admob-pro#151]
I am using the telerik build service. I need to know how to do a manual install for cordova 3.8 for android and ios. Are there special lines in AndroidManifest.xml and config.xml? I found the dependant plugin, any other steps?

**Comment by chrisschaub** [comment]
The build error I'm getting is
Project "someproject.tmp.proj" (default targets):^M
        android Build Tooling revision 2015.6.7.1r^M
        Warning: BUILD FAILED
/home/builder/android-sdk-linux/tools/ant/build.xml:577: ../../../../home/builder/android-sdk-linux/com.google.android.gms:play-services-ads:+ resolve to a path with no project.properties file for project /tmp/builds/Q8R4r0T1NTEsgsnJtM/app

**Comment by chrisschaub** [comment]
Feels like something is missing from AndroidManifest.xml ?

**Comment by floatinghotpot** [comment]
It seems that the build service did not handle the android SDK framework tag correctly. 

Please try the old plugin id: com.google.cordova.admob

**Comment by chrisschaub** [comment]
Will that work for pro version?

On Fri, Jun 12, 2015 at 12:40 PM, Raymond Xie <notifications@github.com>
wrote:

> It seems that the build service did not handle the android SDK framework
> tag correctly.
>
> Please try the old plugin id: com.google.cordova.admob
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/floatinghotpot/cordova-admob-pro/issues/151#issuecomment-111570512>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by chrisschaub** [comment]
So, I should re-install the non-pro version? I have a license key.

On Fri, Jun 12, 2015 at 1:12 PM, Christopher Schaub <chris@schaub.com>
wrote:

> Will that work for pro version?
>
> On Fri, Jun 12, 2015 at 12:40 PM, Raymond Xie <notifications@github.com>
> wrote:
>
>> It seems that the build service did not handle the android SDK framework
>> tag correctly.
>>
>> Please try the old plugin id: com.google.cordova.admob
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/floatinghotpot/cordova-admob-pro/issues/151#issuecomment-111570512>
>> .
>>
>
>
>
> --
> Christopher Schaub
> http://chris.schaub.com
>
>


-- 
Christopher Schaub
http://chris.schaub.com

**Comment by floatinghotpot** [comment]
com.google.cordova.admob is pro version published in Cordova plugin registry. 

After Cordova team announced the registry to be migrated to npm, this plugin is published to npm and follow the npm name rule, the plugin id is changed to cordova-plugin-admobpro.

Your JavaScript code can be same if use either of the above plugin id.

**Comment by chrisschaub** [comment]
Ok, I'm updating the plugin.xml file and changing the id to

com.google.cordova.admob

is that the only place?

On Fri, Jun 12, 2015 at 12:40 PM, Raymond Xie <notifications@github.com>
wrote:

> It seems that the build service did not handle the android SDK framework
> tag correctly.
>
> Please try the old plugin id: com.google.cordova.admob
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/floatinghotpot/cordova-admob-pro/issues/151#issuecomment-111570512>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by chrisschaub** [comment]
I still can't get it to build. Do you mean to install with a different id or github path? Or edit files and change the id within? You said ...

"com.google.cordova.admob is pro version published in Cordova plugin registry. "

I don't undestand what you're suggesting I do, where can I pull a version from that will build. Thanks for your help.

**Comment by floatinghotpot** [comment]
Ok, I'd like to explain a little bit.

Here is the github repo, the project home of this plugin to maintain the versions and history. 

Besides, the plugin is also published to two online repo:
* Cordova plugin registry, http://plugins.cordova.io/#/package/com.google.cordova.admob
* npm, https://www.npmjs.com/package/cordova-plugin-admobpro

If you use Cordova CLI older than v5.0, it can download the plugin from cordova plugin registry, with id: ```com.google.cordova.admob```. 

Since cordova CLI v5.0, cordova team announced npm is also supported and plan to deprecate cordova plugin registry in 6 months, and suggest plugins to be migrated to npm repo, and follow the new name rule, so it's new package id is renamed to: ```cordova-plugin-admobpro```. 

And, to simplify dependency, adding support to use the google-play-services.jar in your default android SDK with tag framework. But some build service is still using old version of cordova CLI and did not support it welll yet, so using the old package ```com.google.cordova.admob``` is a workaround.

You can also use cordova CLI or other tools to add the plugin from local path. Just download the zipped plugin from github specific branch, and unzip to your local folder, then add it from local path. 

Considering your situation, I suggest you to download the zipped plugin for the latest one ```com.google.cordova.admob``` published to Cordova plugin registry:
https://github.com/floatinghotpot/cordova-admob-pro/archive/regio.zip

**Comment by chrisschaub** [comment]
Ok, thanks for the info. So, it looks like I should be targeting Android SDK 19, not 22?

**Comment by floatinghotpot** [comment]
Should be no problem if targting v22

**Comment by chrisschaub** [comment]
Ok, that worked, builds again. Now to figure out why DFP ads are not working on landscape or tablets. Hopefully this upgrade helps.

**Comment by chrisschaub** [comment]
Ok, still no ads landscape or on tablets. In other apps, switching to landscape didn't mean I had to re-invoke the adshow call. I'm using ionic here and wonder, do I have to re-invoke the add call on orientation change? Seems like I should not, but ...

**Comment by floatinghotpot** [comment]
Please check the DFP banner size. 

Can one ad unit id bind to height of 32, 50 and 90 ?

If cannot, you may need detect the screen orientation and tablets, then create banner with different ad unit id.

**Comment by chrisschaub** [comment]
Ok, found the issue. We have our ad unit in DFP setup as "SMART_BANNER" and was letting the client side invocation default to SMART_BANNER. Instead of that, I changed the client to BANNER and boom, it starts showing ads in landscape and rotation works. And it occurs to me this happened in the past as well with this plugin, on another project.

**Comment by chrisschaub** [comment]
Actually, it seems like the error might be related to density and ad sizes after all. It seems with DFP you have to manually enter some of the SMART_BANNER sizes to match this table: https://developers.google.com/admob/ios/banner#smart_banners

Do you know if it will not server a 1.5 density ad to a 2.x density device?

**Comment by floatinghotpot** [comment]
I guess it's not the smart banner issue. Usually admob ad server will have many different ad size, and it will always serve the suitable ad banner size after detecting the device size.

**Comment by chrisschaub** [comment]
Just documenting this, as of 6/16/2015 ... Telerik says to ....

- Use an older version of the AdMob Plugin Pro

- Change the Cordova version for your project to 4.0.0 (Android 4.0.2, iOS 3.8.0, WP 3.8.0-2) - Experimental - you can do this from the General tab of your project's Properties page. However, you should have in mind that this version is still tagged as experimental in AppBuilder, because not everything has been tested with it.
