### ISSUE TITLE
VS2015RC doesn't find cordova-admob-pro plugin.

### ISSUE THREAD

**Issue by softexe** [floatinghotpot/cordova-admob-pro#152]
During build project I get this error:

-----

Currently installed plugins: org.apache.cordova.statusbar@0.1.10,org.apache.cordova.inappbrowser@0.6.0,org.apache.cordova.device@0.3.0
1>  ------ Currently installed dependent plugins:
1>  ------ Currently configured plugins: org.apache.cordova.statusbar@0.1.10,org.apache.cordova.inappbrowser@0.6.0,org.apache.cordova.device@0.3.0,cordova-plugin-admobpro@2.8.1
1>  ------ Adding plugin: cordova-plugin-admobpro@2.8.1
1>  Calling plugman.fetch on plugin "cordova-plugin-admobpro@2.8.1"
1>  Fetching plugin "cordova-plugin-admobpro@2.8.1" via plugin registry

----

No problem was with version 2.7.7 and cordova-admob plugin. 
How to fix it?

**Comment by sunnyluthra** [comment]
Try this
```cordova plugin add com.google.cordova.admob```

**Comment by floatinghotpot** [comment]
Cordova CLI newer than 5.0 support plugin published in npm. The plugin published in npm need follow name rule of npm and is renamed as cordova-plugin-admobpro.

It seems that VS2015RC use old version of Cordova CLI and does not support npm yet.

You can use the old id of this plugin, com.google.cordova.admob, which is published in Cordova plugin registry.

**Comment by softexe** [comment]
Thanks!
Seems VS's scripts try to search plugin on git anyway, but not found with old id and build is failed...

**Comment by floatinghotpot** [comment]
You can try installing npm and Cordova, then use Cordova to add plugin.

**Comment by softexe** [comment]
Will try,,, or will wait new verision Cordova Tools/VS2015 with full support CLI5+/npm based plugins.

**Comment by neilloispy** [comment]
Hi, Thanks for creating this plugin! 

I am using the 2013 Visual Studio and have came up against a similar problem - I initially used the IDE config screen to install your plugin within VS, and I also tried to install over CLI using 

'cordova plugin add cordova-plugin-admobpro' 

But both methods leave the following error message on build: 

Failed to Install 'cordova-plugin-admobpro'
and 
404 Not Found: cordova-plugin-extension 

Could you suggest how to resolve this? 

Many thanks

**Comment by floatinghotpot** [comment]
upgrade your cordova CLI to v5.0 or newer:

```npm install cordova -g```

**Comment by softexe** [comment]
I got working this admob plugin whilel windows 10 update destroy my virtual machines...
What's I did:
download plugin to local computer, extract it to folder, replace version 2.8.2 to 2.7.7,
cordova-plugin-admobpro to com.google.cordova.admob  in all files, then install plugin from local filesystem.

**Comment by floatinghotpot** [comment]
Instead of change the plugin id yourself, just directly use the old plugin id: ```com.google.cordova.admob```, it will load the plugin from Cordova plugin registry.

See: 
https://github.com/floatinghotpot/cordova-admob-pro/wiki/Difference-of-Plugin-IDs

**Comment by softexe** [comment]
thanks. but vs2015 ide is still required link to git repo with plugin, not "old plugin id"

**Comment by floatinghotpot** [comment]
If you prefer add the plugin from local path, just download this branch zip code and unzip to local folder.
https://github.com/floatinghotpot/cordova-admob-pro/archive/regio.zip

**Comment by softexe** [comment]
Thanks. It works. Anyway I am still having a same trouble with WP8 webview and admob plugin (strange scrolling cordova frame when admod banner is active ). New version of plugin doesn't fix it for me.

**Comment by wendellmouzaliruiz** [comment]
To solve this same problem I just replace this:

<vs:plugin name="cordova-plugin-admobpro" version="x.x.x" />

For it:

<vs:plugin name="com.google.cordova.admob" source="plugins.cordova.io" />

**Comment by softexe** [comment]
thx. will try.

**Comment by temala** [comment]
Hi,
Thanks for this plugin, I think once it work it will be great. but currently I'm not able to run it with visual studio 2015, it keep send me the same error (Erreur	2	404 Not Found: cordova-plugin-extension)

I installed it from git first, then I downloaded the plugin from:
 https://github.com/floatinghotpot/cordova-admob-pro/archive/regio.zip

but no success

Can you please help me with this ?
Thanks

**Comment by temala** [comment]
when runnig npm install cordova -g
I get some errors:
npm : npm http GET https://registry.npmjs.org/cordova
At line:1 char:1
+ npm install cordova -g
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm http GET ht...mjs.org/cordova:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
