### ISSUE TITLE
cannot create demo project or add cordova plugin

### ISSUE THREAD

**Issue by astroanu** [floatinghotpot/cordova-admob-pro#154]
$ plugin-verify cordova-plugin-admobpro

    Creating a new cordova project with name "Demo" and id "com.rjfun.demo" at location "c:\www\tmp"
    Fetching plugin "cordova-plugin-admobpro" via plugin registry
    npm http GET http://registry.cordova.io/cordova-plugin-admobpro
    npm http 404 http://registry.cordova.io/cordova-plugin-admobpro
    Error: 404 Not Found: cordova-plugin-admobpro

**Comment by astroanu** [comment]
cordova plugin add cordova-plugin-admobpro

this does not work either.. give the same 404

**Comment by floatinghotpot** [comment]
Please upgrade your Cordova to v5.0 or newer, then it can get plugin from npm.

npm install -g cordova
