### ISSUE TITLE
Can't install iAd adapter with cordova 5.0?

### ISSUE THREAD

**Issue by gnoumaster** [floatinghotpot/cordova-admob-pro#155]
Hello,

I update my cordova version to 5.0 then removed the previous admob pro plugin to the new admobpro but i can't install the iAd Adapter:

sudo cordova plugin add cordova-plugin-admob-iad

Fetching plugin "cordova-plugin-admob-iad" via npm
npm http GET https://registry.npmjs.org/cordova-plugin-admob-iad
npm http 404 https://registry.npmjs.org/cordova-plugin-admob-iad
TypeError: Cannot read property 'latest' of undefined
    at next (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/cache.js:687:35)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/cache.js:675:5
    at saved (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
    at Object.oncomplete (fs.js:107:15)

No problem with Facebook adapter or flurry adapter.

Thanks.

**Comment by floatinghotpot** [comment]
Now it's fixed, please try again.
