### ISSUE TITLE
Can't build for Android if plugin source is npm

### ISSUE THREAD

**Issue by trejder** [floatinghotpot/cordova-admob-pro#156]
I'm using AdMob Pro plugin with PhoneGap Build. Since [plugins.cordova.io is deprecated](http://phonegap.com/blog/2015/05/26/npm-plugins-available/) and all developers are encouraged to use npm source, after following [instructions](https://www.npmjs.com/package/cordova-plugin-admobpro), I have changed [plugins.cordova.io repository](http://plugins.cordova.io/#/package/com.google.cordova.admob):

    <gap:plugin name="com.google.cordova.admob" source="plugins.cordova.io" />

to [npm](https://www.npmjs.com/package/cordova-plugin-admobpro) one:

    <gap:plugin name="cordova-plugin-admobpro" source="npm"/>

However, building in PhoneGap Build for Android failed with following error in logs:

    BUILD FAILED /home/ec2-user/android-sdk/tools/ant/build.xml:573: ../../../../../../home/ec2-user/android-sdk/com.google.android.gms:play-services-ads:+ resolve to a path with no project.properties file for project /project

(building for WP8 was successfull and building for iOS omitted since I don't have proper signing keys)

Changing above back to _plugins.cordova.io_:

    <gap:plugin name="com.google.cordova.admob" version= "2.7.7" source="plugins.cordova.io" />

resolved the issue. App now build without any problems for both Android and WP8.

Any idea, what can cause this?

**Comment by Ashwell** [comment]
I'm having a similar issue, it looks to me like one of the dependencies isn't getting installed when using the npm install method. Specifically the google play services plugin...


When running `cordova plugins add cordova-plugin-admobpro` I see:
```
Fetching plugin "cordova-plugin-admobpro" via npm
npm http GET https://registry.npmjs.org/cordova-plugin-admobpro
npm http 304 https://registry.npmjs.org/cordova-plugin-admobpro
Installing "cordova-plugin-admobpro" for android
Fetching plugin "cordova-plugin-extension" via npm
npm http GET https://registry.npmjs.org/cordova-plugin-extension
npm http 304 https://registry.npmjs.org/cordova-plugin-extension
Installing "cordova-plugin-extension" for android
Installing "cordova-plugin-admobpro" for ios
Installing "cordova-plugin-extension" for ios
```

when running `cordova plugins add com.google.cordova.admob` I see:
```
WARNING: com.google.cordova.admob has been renamed to cordova-plugin-admobpro. You may not be getting the latest version! We suggest you `cordova plugin rm com.google.cordova.admob` and `cordova plugin add cordova-plugin-admobpro`.
Fetching plugin "com.google.cordova.admob" via cordova plugins registry
npm http GET http://registry.cordova.io/com.google.cordova.admob
npm http 200 http://registry.cordova.io/com.google.cordova.admob
npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/com.google.cordova.admob/-/com.google.cordova.admob-2.7.7.tgz
npm http 200 http://cordova.iriscouch.com/registry/_design/app/_rewrite/com.google.cordova.admob/-/com.google.cordova.admob-2.7.7.tgz
Installing "com.google.cordova.admob" for android
WARNING: com.rjfun.cordova.extension has been renamed to cordova-plugin-extension. You may not be getting the latest version! We suggest you `cordova plugin rm com.rjfun.cordova.extension` and `cordova plugin add cordova-plugin-extension`.
Fetching plugin "com.rjfun.cordova.extension" via cordova plugins registry
npm http GET http://registry.cordova.io/com.rjfun.cordova.extension
npm http 200 http://registry.cordova.io/com.rjfun.cordova.extension
npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/com.rjfun.cordova.extension/-/com.rjfun.cordova.extension-1.1.4.tgz
npm http 200 http://cordova.iriscouch.com/registry/_design/app/_rewrite/com.rjfun.cordova.extension/-/com.rjfun.cordova.extension-1.1.4.tgz
Installing "com.rjfun.cordova.extension" for android
Fetching plugin "https://github.com/floatinghotpot/google-play-services" via git clone
Repository "https://github.com/floatinghotpot/google-play-services" checked out to git ref "r19".
Installing "com.google.playservices" for android
Installing "com.google.cordova.admob" for ios
Installing "com.rjfun.cordova.extension" for ios
```

It would be nice if there was a list of dependencies for this plugin in the "Install" section of the readme

**Comment by floatinghotpot** [comment]
Here is the github repo, the project home of this plugin to maintain the versions and history.

Besides, the plugin is also published to two online repo:

Cordova plugin registry, http://plugins.cordova.io/#/package/com.google.cordova.admob
npm, https://www.npmjs.com/package/cordova-plugin-admobpro
If you use Cordova CLI older than v5.0, it can download the plugin from cordova plugin registry, with id: ```com.google.cordova.admob```.

Since cordova CLI v5.0, cordova team announced npm is also supported and plan to deprecate cordova plugin registry in 6 months, and suggest plugins to be migrated to npm repo, and follow the new name rule, so it's new package id is renamed to: ```cordova-plugin-admobpro```.

And, to simplify dependency, new cordova allow adding support to use the google-play-services.jar in your default android SDK with tag framework. 
```xml
<framework src="com.google.android.gms:play-services-ads:+" />
```

But some build service is still using old version of cordova CLI and did not support it welll yet. I've report a bug to PhoneGap build service, see:
https://github.com/phonegap/build/issues/439

Currently, using the old package ```com.google.cordova.admob``` is a workaround.

**Comment by Ashwell** [comment]
I'm using the v5.0 CLI but still had the problem with the latest build.

I just reverted back to the version I had installed this morning (2.7.8) before I tried to upgrade to the latest release, `cordova plugin add cordova-plugin-admobpro@2.7.8`

**Comment by floatinghotpot** [comment]
Please type ```android``` to  open your android SDK manager, check and install the Extra -> google play service library / repository, they will be required for build.

**Comment by Ashwell** [comment]
I have the "Google Play services" package installed but still get a build issue: 

```
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-ads:+.
```

**Comment by floatinghotpot** [comment]
You need get the items installed in your Android SDK manager.

![android-sdk-framework](https://cloud.githubusercontent.com/assets/2339512/8176143/20533ec0-1429-11e5-8e17-a748373d5110.png)

**Comment by Ashwell** [comment]
Ahh, I was missing Google Repository, thanks for all your help!

I would still suggest you add these dependencies to the readme as part of the install process.

**Comment by floatinghotpot** [comment]
It's updated into the wiki:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/Difference-of-Plugin-IDs
