### ISSUE TITLE
DFP and House Ads

### ISSUE THREAD

**Issue by chrisschaub** [floatinghotpot/cordova-admob-pro#157]
So, this might be a DFP thing, but, we have sponsored house type ads setup in DFP. All at 100%, all should be serving and are. But, when I first start the app, a paid network ad shows up! If I close the app and restart, I only see our house ads. We've followed the doc to a tee. Is the plugin doing any kind of fallback in case it can't get an ad when the app first loads?

**Comment by floatinghotpot** [comment]
Can you paste a screenshot and your code ?

**Comment by chrisschaub** [comment]
The code is almost verbatim from the example. But I am definitely seeing
some non-house ads. Do you have any kind of mediation enabled or fallback
if no ad is gotten?

On Tue, Jun 16, 2015 at 4:58 AM, Raymond Xie <notifications@github.com>
wrote:

> Can you paste a screenshot and your code ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/floatinghotpot/cordova-admob-pro/issues/157#issuecomment-112370146>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by floatinghotpot** [comment]
Hard to tell before seeing some screenshot, code or logs ...

**Comment by chrisschaub** [comment]
What would you like to see a screen shot of? It's just an ad, a banner ad
that I did not sell appearing in a slot at the bottom. There is only one ad
unit for the bottom footer of the app.  As for code,
```
      // AdMob
      if (onDevice) {
        if (!_.isEmpty(AdMob)) {
          // vars
          var ad_units = {
            ios : {
              banner: '/######/ios-footer-ad'
            },
            android : {
              banner: '/######/ios-footer-ad'
            }
          };
          // select the right Ad Id according to platform
          var admobid = ( /(android)/i.test(navigator.userAgent) ) ?
ad_units.android : ad_units.ios;
          AdMob.createBanner({
            adId:admobid.banner,
            overlap:true,
            position:AdMob.AD_POSITION.BOTTOM_CENTER,
            autoShow:true,
            license: '###########',
            isTesting: false,
            success: function() {
              //console.log('ads are showing');
            },
            error: function() {
              //console.log('ads are not showing');
            }
          });
        }
      }

On Tue, Jun 16, 2015 at 5:21 AM, Raymond Xie <notifications@github.com>
wrote:

> Hard to tell before seeing some screenshot, code or logs ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/floatinghotpot/cordova-admob-pro/issues/157#issuecomment-112375506>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by floatinghotpot** [comment]
No problem, your code is correctly calling the plugin API...

Would you mind to send your DFP ad unit id and your license key to me for a testing? I'd like to see if I can reproduce your issue or not.

**Comment by floatinghotpot** [comment]
Send to email address: rjfun.mobile@gmail.com

**Comment by chrisschaub** [comment]
Sent, thx.

**Comment by chrisschaub** [comment]
So, after doing this update to remove fallback ads allowFallback, we don't see ads with Android 5.1.1. 4.4 is working fine along with iOS. Are you experiencing any issues with Android 5.

**Comment by ridwanridiawan** [comment]
hi Raymond..

to install ad network mediation
add plugin id:
 "com.google.cordova.admob-iad" and "com.google.cordova.admob-flurry"

my script code:

<script>
var admobid = {};
if( /(android)/i.test(navigator.userAgent) ) { 
    admobid = { // for Android
        banner: 'ca-app-pub-xxxxxxxxxxxxxx/yyyyyyyyyyyyyy',
        interstitial: 'ca-app-pub-xxxxxxxxxxxxxx/yyyyyyyyyyyyyy'
    };
} else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
    admobid = { // for iOS
        banner: 'ca-app-pub-xxxxxxxxxxxxxx/yyyyyyyyyyyyyy',
        interstitial: 'ca-app-pub-xxxxxxxxxxxxxx/yyyyyyyyyyyyyy'
    };
} else {
    admobid = { // for Windows Phone
        banner: 'ca-app-pub-xxxxxxxxxxxxxx/yyyyyyyyyyyyyy',
        interstitial: 'ca-app-pub-xxxxxxxxxxxxxx/yyyyyyyyyyyyyy'
    };
}

if(( /(ipad|iphone|ipod|android|windows phone)/i.test(navigator.userAgent) )) {
    document.addEventListener('deviceready', initApp, false);
} else {
    initApp();
}

function initApp() {
    if (! AdMob ) { alert( 'admob plugin not ready' ); return; }

    AdMob.createBanner( {
        adId: admobid.banner, 
        isTesting: false,
        overlap: false, 
        offsetTopBar: false, 
        position: AdMob.AD_POSITION.BOTTOM_CENTER,
        bgColor: 'black'
    } );
    
    AdMob.prepareInterstitial({
        adId: admobid.interstitial,
        autoShow: true
    });
}
</script>

and i configure  the mediation networks in AdMob portal. 
Is it true?
