### ISSUE TITLE
Android Kitkat Issues

### ISSUE THREAD

**Issue by wendellmouzaliruiz** [floatinghotpot/cordova-admob-pro#159]
Hi, how are you?

I have some issues to you:

1) Overlap the Bottom Banner regarding my application:

![error_0001](https://cloud.githubusercontent.com/assets/10159490/8185211/58aa107e-1419-11e5-8d8e-2dcec8849f13.png)

2) The Banner Interstitial isn't working very well:

A) It becomes transparent:

![error_0002](https://cloud.githubusercontent.com/assets/10159490/8185292/ae748a66-1419-11e5-8017-501ac18cd424.png)

B) It becomes black: 

![error_0003](https://cloud.githubusercontent.com/assets/10159490/8185303/b929ac5c-1419-11e5-8341-578bc0ed5c27.png)

I realized also that the Banner Interstitial isn't enabling the option close to the user, then the same can't leave the Banner.

And I realized that the back button sometimes disables Banner Interstitial and sometimes doesn't disable it.

Tks and good luck!

**Comment by floatinghotpot** [comment]
in your js code, set option: overlap:false

banner is a small ad, interstitial is full time ad, which one do you mean exactly?

And, read the docs and wiki, you will find most of the answer.
https://github.com/floatinghotpot/cordova-admob-pro/wiki

**Comment by floatinghotpot** [comment]
1) in your js code, set option: overlap:false

2/A) usually a banner cannot fit all size of screen, a smart banner will keep centered with some space filled with gray.

2/B) a black screen but with a X displayed, it seems the ad is loaded but nothing displayed, you may need ask google team instead.

BTW, 
* banner is a small ad, interstitial is full time ad, which one do you mean exactly?
* read the docs and wiki, you will find most of the answer.
https://github.com/floatinghotpot/cordova-admob-pro/wiki

**Comment by wendellmouzaliruiz** [comment]
Hi, tks for your answer!

Your tip about overlap option is great, I'll test it. But I correct it using the redimension option and adapting my layout.

About the ads erros, I'll send a message to Google Team.

I use the two types ads. When I say "Banner Interstitial" I meant "Ads Interstitial", sorry to confusion.

I have another question, exists somehow to force close an interstitial ads?

**Comment by floatinghotpot** [comment]
No, you cannot close interstitial ad by code, user interaction is required.

**Comment by kongmeng** [comment]
@floatinghotpot , hi, i found that if set overlay = false, when the banner ad was loaded, it will like auto refresh the whole page, and after it refresh, it cause my back button misfunction (Before the ad loaded, the onHardwareBack still work fine, after ad loaded then misfunction). This mean when after  the ad loaded, whenever the user at which state or page, when the user click on hardware back button, it will directly exit the apps without back to previous state and ignore my $ionicPlatform.registerBackButtonAction function.
--Furthermore, if the overlay = true, everything was work fine, and even the banner ads load, it wont refresh the whole page.
Below is my issue and details consist the version and code I apply, please help :(
https://github.com/floatinghotpot/cordova-admob-pro/issues/161

**Comment by saksham09** [comment]
Hey i am getting it on sidebar also, i want that it must overlap but sidebar content must overlap banner as. Any solution please?
