### ISSUE TITLE
Ads Aren't Showing up on Android Tablets

### ISSUE THREAD

**Issue by foochuck** [floatinghotpot/cordova-admob-pro#160]
I'm using the recommended ad sizes on this page for DFP:

https://developers.google.com/mobile-ads-sdk/android-legacy/docs/dfp/smart-banners

However ads are not showing up for me on Android tablets. Testing on 4.4.2 & 5.1.1

**Comment by floatinghotpot** [comment]
I heard that set ad type to banner instead of smart banner will fix this, but I did not verify it myself.

You may ask Google team for confirmation.
