### ISSUE TITLE
app always exit on backbutton if focus is on ad view, if ad banner overlay=false

### ISSUE THREAD

**Issue by kongmeng** [floatinghotpot/cordova-admob-pro#161]
Very strange that if my overlay=true for ad banner, my $ionicPlatform.registerBackButtonAction and onHardwareBack work perfectly, when user click on back button it will back to previous state or prompt toast message before user exit. But once I change the overlay=false (by default) for ad banner, it will cause problems. Whenever the app was at main page or other page, when i click onHardwareBack it will direct exit the apps without going back previous state or prompt toast message. And I found that if my overlay=false, before the ad banner was load, the onHardwareBack still able confirm to work correctly, after the ad banner was loaded and appear, whole screen like being refresh and onHardwareBack will become not working correct. But overlay=true don have this issue at all. 
Remark: I already try many difference method like deviceready, addeventlistener onAdload only call that function of ionicPlatform.registerBackButtonAction also not working. My platform is android, with newest cordova.js 4.0.2. Node v0.12.4 and cordova CLI also newest v5.1.1.

Below is my code.

angular.module(XXXX)

.config(XXX) {

    $stateProvider.
        state('menu', {
           XXXX
        }).
        state('menu.about', {
            XXX
        }).
        state('menu.setting', {
           XXX
        }).
        state('menu.main', {
            XXX
        });
 
    $urlRouterProvider.otherwise('XXXX');
})

.run(function($ionicPlatform, $localStorage, $rootScope, $location, $timeout, $ionicHistory, $cordovaToast, $state,) {

    $ionicPlatform.ready(function () {

        if(window.cordova && window.cordova.plugins.Keyboard) {
          cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
        }
        
        if(window.StatusBar) {
          StatusBar.styleDefault();
        }
        
        //Admob
        var admobid = {};
        if( /(android)/i.test(navigator.userAgent) ) { 
            admobid = { // for Android
                banner: 'XXXX',
                interstitial: 'XXX'
            };
        } else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
            admobid = { // for iOS
                 banner: 'XXXX',
                 interstitial: 'XXX'
            };
        } else {
            admobid = { // for Windows Phone
                 banner: 'XXXX',
                 interstitial: 'XXX'
            };
        }

        AdMob.createBanner( {
            adId:  admobid.banner, 
            isTesting: false,
            overlap: true, 
            offsetTopBar: false, 
            position: AdMob.AD_POSITION.BOTTOM_CENTER,
            autoShow: true
        } );
        
        AdMob.prepareInterstitial({
            adId:  admobid.interstitial,
            autoShow: false
        });
    });
    
    $ionicPlatform.registerBackButtonAction(function (e) {

        if ($location.path() == '/menu/main') {
            if ($rootScope.backButtonPressedOnceToExit) {
                if(AdMob) AdMob.showInterstitial();
                ionic.Platform.exitApp();
            } else {
                $rootScope.backButtonPressedOnceToExit = true;
                $cordovaToast.showShortTop('Press again to Exit :)');
                setTimeout(function () {
                    $rootScope.backButtonPressedOnceToExit = false;
                }, 2000);
            }
        }else if ($ionicHistory.backView()) {
            $ionicHistory.goBack();
        } else {
            $state.go($rootScope.previousState);
        }
        e.preventDefault();
        return false;
    }, 101);

});

**Comment by t-nonque** [comment]
Hi,

I encounter the exact same problems (screen refreshing and back button exiting the app after ads loaded).
Any news on this?

**Comment by kongmeng** [comment]
too sad no good news :(

**Comment by floatinghotpot** [comment]
Will look into this issue.

**Comment by kongmeng** [comment]
thank you, will wait you good news :+1:

**Comment by t-nonque** [comment]
I think it must be because the Adview (banner) takes the focus afer being shown, so the back button makes the app close. Fix should be to refocus the webview right after the ad is displayed.

**Comment by jkbh-86** [comment]
Thanks for looking into this!  
If it helps, I also experienced the same issue with the Mopub Plugin Pro plugin, leading me to believe the issue is possibly in the GenericAdPlugin class.

**Comment by t-nonque** [comment]
Yes it is probably in GenericAdPlugin class. But as it is contain in a .jar file, im affraid there is no way for us to look into it :(

**Comment by floatinghotpot** [comment]
Since cordova-android v4.x, the cordova core code has been changed a lot, especially in the layout, some heavy refactoring was done to support it, may introduce some unexpected defects. Will look into it, thanks for your detailed feedback.

**Comment by sprsoft** [comment]
Hi! Any news on this?
Thanks in advance!

**Comment by t-nonque** [comment]
No news yet. I am also waiting for this. The problem is we can not edit GenericAdPlugin's class code, only floatinghotpot can, so only him can help us. The best would be to share that code so anyone of us could fix the problems.

**Comment by floatinghotpot** [comment]
I've checked the code and don't find it's caused by generic code. Before the root cause is identified, I'd like to suggest you a workaround to avoid using split view of ad banner, use overlap:true, then set margin bottom of body element.

**Comment by sprsoft** [comment]
Yes. Using overlap:true works fine. I changed it on my project. Anyway it would be great not to loose the benefits of not overlapping the ads.

**Comment by t-nonque** [comment]
Indeed overlap:true is clearly the only solution. It can be pretty annoying if you have fixed elements, but as overlap:false is not usable at all an android, it is the only choice left ^^
Thanks for the tip ;)

**Comment by thenewvu** [comment]
This is my solution for this issue. Hope it helps you out guys.

```diff
From fe0cec5f2fee5035d6ec7835def728ebb4fbe238 Mon Sep 17 00:00:00 2001
From: Vu Le <thenewvu@gmail.com>
Date: Sat, 1 Aug 2015 00:10:28 +0700
Subject: [PATCH] * fix #29: back button is not handled after orientation
 changed

the reason is 'cordova-admob-pro' banner occupies the webview's focus, this makes back key events can not be handled by the webview, but CordovaActivity.
---
 .../src/org/apache/cordova/CordovaActivity.java    | 23 ++++++++++++++++++----
 1 file changed, 19 insertions(+), 4 deletions(-)

diff --git a/platforms/android/CordovaLib/src/org/apache/cordova/CordovaActivity.java b/platforms/android/CordovaLib/src/org/apache/cordova/CordovaActivity.java
index 3195fc0..ca6d851 100644
--- a/platforms/android/CordovaLib/src/org/apache/cordova/CordovaActivity.java
+++ b/platforms/android/CordovaLib/src/org/apache/cordova/CordovaActivity.java
@@ -37,6 +37,7 @@ import android.view.KeyEvent;
 import android.view.Menu;
 import android.view.MenuItem;
 import android.view.View;
+import android.view.View.OnFocusChangeListener;
 import android.view.ViewGroup;
 import android.view.Window;
 import android.view.WindowManager;
@@ -95,6 +96,8 @@ public class CordovaActivity extends Activity {
     protected ArrayList<PluginEntry> pluginEntries;
     protected CordovaInterfaceImpl cordovaInterface;
 
+    protected boolean foreground = true;
+
     /**
      * Called when the activity is first created.
      */
@@ -174,8 +177,16 @@ public class CordovaActivity extends Activity {
             // Background of activity:
             appView.getView().setBackgroundColor(backgroundColor);
         }

         appView.getView().requestFocusFromTouch();
+		
+		 // this workaround fixes focus lost after 'cordova-admob-pro' banner showed
+        appView.getView().setOnFocusChangeListener(new OnFocusChangeListener() {
+            @Override
+            public void onFocusChange(View v, boolean hasFocus) {
+                if(!hasFocus && CordovaActivity.this.foreground) {
+                    CordovaActivity.this.appView.getView().requestFocusFromTouch();           
+                }
+            }
+        });
     }
 
     /**
@@ -220,6 +231,8 @@ public class CordovaActivity extends Activity {
      */
     @Override
     protected void onPause() {
+        foreground = false;
+
         super.onPause();
         LOG.d(TAG, "Paused the activity.");
 
@@ -244,6 +257,8 @@ public class CordovaActivity extends Activity {
      */
     @Override
     protected void onResume() {
+        foreground = true;
+
         super.onResume();
         LOG.d(TAG, "Resumed the activity.");
         
@@ -457,7 +472,7 @@ public class CordovaActivity extends Activity {
         }
     }
```

**Comment by karan101292** [comment]
@thenewvu It works well.. :+1:

**Comment by jkbh-86** [comment]
@thenewvu Thank you, I finally got around to testing this in my project and it seems to be working.  Thank you for your solution and explanation!

**Comment by floatinghotpot** [comment]
Thanks to @thenewvu, the solution works pretty well. 

I tried to get this handled by plugin itself, but unfortunately it cannot. So modifying the CordovaActivity.java seems the only working solution so far.

**Comment by prantikv** [comment]
Can someone be clear as to where exactly the code is to be placed? Full file path and location of the code.
