### ISSUE TITLE
banner always showed on top left

### ISSUE THREAD

**Issue by raulromanp** [floatinghotpot/cordova-admob-pro#162]
On android, cordova5.0.0, cordovaCLI. Tested on 4.2.2.

      AdMob.setOptions {
        adSize: 'BANNER',
        position: AdMob.AD_POSITION.BOTTOM_CENTER,
      }

Banner always is showed on TOP LEFT. Problems with 'position'. Others attributes on setOptions works.

Do you need any more data?

**Comment by floatinghotpot** [comment]
Test with my demo first

Run: 
plugin-verify cordova-plugin-admobpro android

**Comment by floatinghotpot** [comment]
See: 
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/README.md

**Comment by raulromanp** [comment]
Thanks, really I'm using "com.google.cordova.admob" plugin cause of the other one bring me build errors. This plugin path would be the same plugin??

The error is something like .. "Command failed with exit code 8. You may not have the required environment or OS to build this project".

**Comment by floatinghotpot** [comment]
then you can try: ```plugin-verify com.google.cordova.admob android``` to see the demo

**Comment by floatinghotpot** [comment]
BTW, if build locally using ```cordova-plugin-admobpro```, to avoid build error, you need install some extras in Android SDK manager (type ```android sdk``` to launch it):
![android extra](https://cloud.githubusercontent.com/assets/2339512/8176143/20533ec0-1429-11e5-8e17-a748373d5110.png)

**Comment by raulromanp** [comment]
Banner position Solved. In my App I eventually do 'hideBanner'. When I want to show it again I have to call 'showBanner()' with the 'position' as param. Even if I setted it on AdMob.setOptions. I don't know if that's the expected behavior.
