### ISSUE TITLE
AdMob is not defined

### ISSUE THREAD

**Issue by bbaki** [floatinghotpot/cordova-admob-pro#166]
Hey, I need your help. This probably a common error but I can't seem to fix it on my own. (To make it clear I get an error AdMob is not defined in the console log and the plugin simply does not work).

I've tried quite a few things, options and versions and currently I'm not even sure what I have installed.

But, what I can say is that:
- I have cordova 5.1.1,
- I'm using windows 7 (don't kill me plz)
- Cordova plugin ls gives me these 3:
 a) cordova-plugin-admobpro 2.8.3 "AdMob Plugin Pro" 
 b) cordova-plugin-extension 1.1.4 "Cordova Plugin Extension"
 c) cordova-plugin-whitelist 1.0.0 "Whitelist"
- I installed the app through the command prompt
- I get the error on both my app and the test app
(https://github.com/floatinghotpot/cordova-admob-pro)
- The app doesn't work on PC nor on my telephone

Thanks in advance.

**Comment by floatinghotpot** [comment]
Let's make it clear:
1. You need install Android SDK;
2. Better if you can also install Eclipse, so you can see some debug log in the LogCat window.
2. It only open the index.html on PC with a browser, it won't work.
4. You have to build into APP and install the APP into your smartphone.

If you already have the correct env, try re-add the platform and then re-build:
```bash
cordova platform remove android
cordova platform add android
cordova prepare
cordova run android
```

**Comment by bbaki** [comment]
I kinda solved the problem myself. The problem was that I was testing the app with my wi-fi turned off (I thought that the test version does not require internet access, adding information about this may be a good idea).

Another thing I noticed was that I was missing:
    
    	<script type="text/javascript" src="cordova.js"></script>

I had no idea this was required, the app worked fined without it but I guess cordova-admob-pro depends on this.

Problem solved, closed.
