### ISSUE TITLE
Issue: AdMob is not defined! (PhoneGap Desktop)

### ISSUE THREAD

**Issue by jaalders** [floatinghotpot/cordova-admob-pro#167]
Hey,

I am trying to follow along with the instructions as per this page:

https://github.com/floatinghotpot/cordova-admob-pro/wiki/00.-How-To-Use-with-PhoneGap-Build

However whenever I go to run it in my builder it keeps stating that "ReferenceError: AdMob is not defined" 

I don't believe that I am missing any files, but also when I try to download the demo example there is no ads there either and the same error occurs.

**Comment by floatinghotpot** [comment]
You may look at #166 

Also many closed issues about "AdMob not defined", please see how they are resolved.
https://github.com/floatinghotpot/cordova-admob-pro/issues?utf8=%E2%9C%93&q=not+defined

**Comment by jaalders** [comment]
My situation is slightly different. I am using the app to show my files on my device as opposed to building an .apk and testing on my device

http://app.phonegap.com/

Perhaps they are not compatible since the desktop app is still in beta, but I would really like to see if there is a way to fix this :)

**Comment by floatinghotpot** [comment]
As the admob plugin contains native code, you have to build it into your own APP and install to device.

The phonegap app only contains the Cordova core plugins as default, I don't think they build the admob plugin into the app.

**Comment by jaalders** [comment]
I apologize for I do not fully understand you.

I have access to all the project files. Basically the PhoneGap Desktop App works like a WAMP/LAMP server. if I modify any of the files included in my project I can see them change on my phone when I pull using the mobile app synced with the desktop app as per http://app.phonegap.com/

I have even followed the steps from https://github.com/floatinghotpot/cordova-admob-pro/wiki/00.-How-To-Use-with-PhoneGap-Build. Should it not just appear as per the instructions that have been given on the http://app.phonegap.com/ and https://github.com/floatinghotpot/cordova-admob-pro/wiki/00.-How-To-Use-with-PhoneGap-Build page?

**Comment by floatinghotpot** [comment]
To use the admob plugin to show ad on your device, you have to build the plugin AND your files into your own APP instead of view it in the APP from phonegap.
