### ISSUE TITLE
Admobpro plugin with iAd mediation adapter issue: Banner shifted (screenshot joined)

### ISSUE THREAD

**Issue by t-nonque** [floatinghotpot/cordova-admob-pro#168]
Hi,

On iOS, using the iAd mediation adapters, the banner is shifted, so Apple refuses to publish my app.
The banner is bottom center, overlap false. Admob banners are displayed correctly, only iAd one are shifted.

Thanks by advance ^^

![img_0010](https://cloud.githubusercontent.com/assets/12875229/8346655/8a91faf0-1b32-11e5-9e00-cc5925fb966c.PNG)
![img_0013](https://cloud.githubusercontent.com/assets/12875229/8346656/8be46c08-1b32-11e5-8e46-4f7f7e9a25d4.PNG)

**Comment by floatinghotpot** [comment]
Unfortunately, the iAd adapter is from Google, in binary form, so I cannot modify or debug it.

See:
https://developers.google.com/admob/android/mediation-networks

Here is the adapter:
https://dl.google.com/dl/googleadmobadssdk/libadapteriad.zip

**Comment by t-nonque** [comment]
Okay i'll report the bug to them.

Thanks for your answer

**Comment by floatinghotpot** [comment]
Is there anything to configure for the iAd banner? Size, position, etc.

Before the root cause is found, as a workaround, you may try removing the iad adapter and publish app with admob only.

As I know, AdMob has very high fill rate, >95%, while other ad network is quite low. FYI.

**Comment by t-nonque** [comment]
I dont think there is anything to configure else than the usual working for the Admob banners.
Yes that is what i did, just removed iAd for now to get the app published. Admob is great with a high fill rate, but iAd offer higher eCPMs, so the use of the mediation is perfect to get advantages of both.

Thank you again for the help ^^
