### ISSUE TITLE
Android build fail with error "com.google.android.gms:play-services-ads:+"

### ISSUE THREAD

**Issue by RangerRick** [floatinghotpot/cordova-admob-pro#169]
I just (re-)added the admobpro plugin in my project, and when I build on Android, I get the following error:

```
Booting up emulator (this may take a while)...BOOT COMPLETE
Running: /Users/ranger/rcs/opennms-compass/tmp/platforms/android/gradlew cdvBuildDebug -b /Users/ranger/rcs/opennms-compass/tmp/platforms/android/build.gradle -PcdvBuildArch=x86 -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-ads:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads/
     Required by:
         :android:unspecified
```

Cordova version: 5.1.1
Node version: v0.12.2
cordova-android version: 4.0.2

Let me know if there's anything I can do to provide more debug info.

**Comment by floatinghotpot** [comment]
Answer is here:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/Difference-of-Plugin-IDs

**Comment by opennms-bamboo** [comment]
D'oh.  Google failed me and I didn't find that.  Thanks, and sorry for the noise.

**Comment by RangerRick** [comment]
D'oh.  Google failed me and I didn't find that.  Thanks, and sorry for the noise.

**Comment by prosenjit-itobuz** [comment]
Check this https://github.com/floatinghotpot/cordova-admob-pro/wiki/Difference-of-Plugin-IDs#4-build-error-with-message-not-found-comgoogleandroidgmsplay-services-ads 

This issue solved after all component installed in extra option.
