### ISSUE TITLE
flickering on banner change

### ISSUE THREAD

**Issue by do-web** [floatinghotpot/cordova-admob-pro#170]
If the banner appears or the banner changed the view is flickering. With overlay:true
Android 5.0
Crosswalk 12

**Comment by McKennaHH** [comment]
Same Problem here. Every time the banner gets Refreshed the whole App seems to refresh/reload.

Android 4.4.2 on Samsung galaxy Tab 3

**Comment by danielocdh** [comment]
Same here, setting option overlap to true might help, but is not good if you don't want that style

**Comment by ruudruud** [comment]
I have the same problem. Unfortunately I was not able to find a solution.

**Comment by piterwilson** [comment]
*bump* any information on this?

**Comment by CookieCookson** [comment]
+1, when the advert first loads the entire app flickers black a split second for me!

**Comment by lordamon** [comment]
same for me: when the advert first loads the entire app flickers black (only on android).

**Comment by perttuim** [comment]
The same here. Every time the banner loads or changes the whole app flickers. This seems to happen even when overlap is set to true.

**Comment by perttuim** [comment]
The same here. Every time a banner loads or changes the whole app flickers. A workaround I found is to set the overlap to true and adding a little padding to the content area at the bottom.

**Comment by floatinghotpot** [comment]
The code related with this issue has been refactored. I did not observe flickers in new version any more. Could you verify it in your test?

At first time the ad loaded, if set overlap:true, the plugin will resize the webview, a flicker is not avoidable. 

If the banner is already visible, only ad content refresh won't cause app flicker.

**Comment by floatinghotpot** [comment]
As this is same issue as #280, will close this tracker. If any further discussion, please follow up in #280.
