### ISSUE TITLE
App Crashed with AdMob on Crosswalk

### ISSUE THREAD

**Issue by do-web** [floatinghotpot/cordova-admob-pro#171]
Somtimes the apps crash only with AdMob. Here is the crash log:

06-28 13:21:33.477: E/qdmemalloc(1564): ion: Failed to map memory in the client: Out of memory
06-28 13:21:33.477: E/qdgralloc(1564): Could not mmap handle 0x119e5560, fd=297 (Out of memory)
06-28 13:21:33.477: E/qdgralloc(1564): gralloc_register_buffer: gralloc_map failed
06-28 13:21:33.477: W/GraphicBufferMapper(1564): registerBuffer(0x119e5560) failed -12 (Out of memory)
06-28 13:21:33.477: E/GraphicBuffer(1564): unflatten: registerBuffer failed: Out of memory (-12)
06-28 13:21:33.477: E/Surface(1564): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -12
06-28 13:21:33.477: W/Adreno-EGLSUB(1564): <DequeueBuffer:720>: dequeue native buffer fail: Out of memory, buffer=0x0, handle=0x0
06-28 13:21:33.487: W/Adreno-EGL(1564): <qeglDrvAPI_eglSwapBuffers:3702>: EGL_BAD_SURFACE
06-28 13:21:33.487: E/chromium(1564): [ERROR:gles2_cmd_decoder.cc(9842)] Context lost because SwapBuffers failed.
06-28 13:21:33.487: E/chromium(1564): [ERROR:gles2_cmd_decoder.cc(4028)] Error: 5 for Command kSwapBuffers
06-28 13:21:33.497: E/Adreno-ES20(1564): <check_framebuffer_attachment:854>: Invalid texture format! Returning error!
06-28 13:21:33.497: E/Adreno-ES20(1564): <check_framebuffer_object_status:1237>: Framebuffer color attachment incomplete. Returning GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT!
06-28 13:21:33.627: W/google-breakpad(1564): ### ### ### ### ### ### ### ### ### ### ### ### ###
06-28 13:21:33.627: W/google-breakpad(1564): Chrome build fingerprint:
06-28 13:21:33.627: W/google-breakpad(1564): 0.0.3
06-28 13:21:33.627: W/google-breakpad(1564): 32
06-28 13:21:33.627: W/google-breakpad(1564): 92675e2e-3e24-4fdd-9bc9-d979deace950
06-28 13:21:33.627: W/google-breakpad(1564): ### ### ### ### ### ### ### ### ### ### ### ### ###
06-28 13:21:33.627: E/chromium(1564): ### WebView Version 43.0.2357.121 (code 2357121)
06-28 13:21:33.637: A/libc(1564): Fatal signal 4 (SIGILL), code 1, fault addr 0x9f33a134 in tid 1694 (Thread-219978)

**Comment by floatinghotpot** [comment]
Out of memory?

**Comment by do-web** [comment]
Yes but only if i use AdMob.

**Comment by do-web** [comment]
i solved this bug by calling clear gc before a new ad is loaded

**Comment by floatinghotpot** [comment]
Can you paste the code?

**Comment by t-nonque** [comment]
I also would be interested in the code you used to fix it as i also get some crashes. Thanks by advance

**Comment by floatinghotpot** [comment]
same as #137, please discuss and follow up in that issue tracker.
