### ISSUE TITLE
Video Admob ad disable the game sounds

### ISSUE THREAD

**Issue by qngnht** [floatinghotpot/cordova-admob-pro#173]
Today I run the Admob interstitials ad , the video ads disable my game sounds after the ads is dismissed. I tried to turn off and on the sound, its still muted.  Either way, I set the options in Admob not to show video ads, but it is still showed lol  . Thank you for any helps !

**Comment by floatinghotpot** [comment]
It's not plugin issue, please turn to Google admob service team for support.

**Comment by qngnht** [comment]
Thank Raymond, I reported the bug to the Admob support and I am waiting for their reply.

**Comment by wuxiaomo6174** [comment]
@qngnht Hi, we meet the same issue. Do you have resloved it?  Very thanks.

**Comment by qngnht** [comment]
I wrote a feedback to Admob team, and they fixed the videos which caused those errors.
