### ISSUE TITLE
Is this plugin working perfectly alright?

### ISSUE THREAD

**Issue by ekambarrao** [floatinghotpot/cordova-admob-pro#174]
I have implemented this and tried to run it in Ripple nexus for android and have been facing problem with error 404 - cordova extension plugin not found.

How to get around this!? Quick reply would be very helpful.

**Comment by floatinghotpot** [comment]
It seems that your Cordova did not install it correctly.

Please upgrade your Cordova CLI to v5.x, then add plugin with its ID:

cordova plugin add cordova-plugin-admobpro

**Comment by ekambarrao** [comment]
Nope....it is not working..in visual studio 2013.Was asking again the same.

**Comment by floatinghotpot** [comment]
Could you please paste the detailed logs?

Visual studio seems using some older version of cordova 4.x which did not support loading plugin from npm yet.

Using the old plugin id "com.google.cordova.admob" is a workaround.

See:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/Difference-of-Plugin-IDs
