### ISSUE TITLE
Android/Admob Keyboard open + banner refresh = Webview resize very small

### ISSUE THREAD

**Issue by t-nonque** [floatinghotpot/cordova-admob-pro#175]
Hi,

When the keyboard is open and the banner refresh, the webview is resized, then if i close the keyboard, the webview still very tiny.

I received many users complain so i had to remove the plugin for now :(

Thanks by advance ;)

**Comment by floatinghotpot** [comment]
It's recommended to use full screen interstitial ad than banner, better user experience and 5-10 times revenue.

**Comment by t-nonque** [comment]
Hi,

Yes but it doesn't change the fact that I need a banner and there is a bug ^^
By the way it is working pretty well on iOS.

Thanks by advance

**Comment by floatinghotpot** [comment]
I see, will look into this issue and hope can resolve it.

Using interstitial ad is a workaround to avoid the bug, and in fact, most guys get better revenue by using interstitial ad. That's why I recommend it.

**Comment by t-nonque** [comment]
Okay thank you ^^
I can help if you want but it seems to come from cordova-generic-ad.jar, it is possible to have an access to the code?

Yes indeed but on my app users hate interstitial ads (i got some bad reviews because of it) so i can not show more than 1 per day. Beside, it doesn't annoy them if a banner is always present at the bottom of the app (never got a bad review about the banner, others than the bug about the webview resized).

**Comment by t-nonque** [comment]
Any news on that one? Is it possible to access cordova-generic-ad.jar's code?

Thanks

**Comment by prisonier** [comment]
I do have exactly the same problem. I'm running on version 2.8.3

**Comment by floatinghotpot** [comment]
After carefully study, the root cause is identified: 
When focus in input area, the soft keyboard will resize the webview. 
If the ad banner displayed in split mode (overlap:false), it will also resize the webview to avoid overlap the web content. 
If both resize the webview at the same time, this will cause conflict. 

When soft keyboard display, it will always try to resize the existing view at bottom. If the banner ad displayed at bottom, it will give up resizing. This issue cannot be resolved perfectly.

Here a few workaround methods are suggested to avoid the conflict happen:
1. When you have some input box or textarea on UI, avoid show banner at bottom. You can either hide banner, or show banner at top.
2. Use ```overlap:true``` (as the banner will overlap web content, you need reserve some margin area for it.)

**Comment by prisonier** [comment]
You cannot show banner at top. I have the problem with banner at top

**Comment by floatinghotpot** [comment]
Please re-try, I've just optimized it.

**Comment by prisonier** [comment]
Still the same problem with version 2.10.0

If the banner is shown when keyboard is open, webview is resized. 

Can't you resize the webview with real screen height ? Or maybe can you avoid show banner when keyboard is open ? 

For me the only valid workaround is to avoid loading banner when client can open keyboard or block the app while banner isn't loaded yet.

My code : 

```javascript
                    AdMob.createBanner({
                        adId: $rootScope.banner_id,
                        position: AdMob.AD_POSITION.TOP_CENTER,
                        autoShow: false, //Banner is show in AppCtrl.js to avoid admob-pro-plugin issue if banner is not shown when keyboard is opened-> https://github.com/floatinghotpot/cordova-admob-pro/issues/175
                        isTesting: $rootScope.dev,
                        overlap: false
                    })
```

**Comment by floatinghotpot** [comment]
Ok, it's fixed. When banner at either bottom or top, it works perfectly with soft keyboard. 

Please update to cordova-plugin-admobpro v2.11.0, enjoy. :-)

**Comment by floatinghotpot** [comment]
![img_3293](https://cloud.githubusercontent.com/assets/2339512/12327047/3827ffb2-bb0f-11e5-880f-65337212985c.jpg)

**Comment by prisonier** [comment]
Maybe we don't speak about the same issue ? 

When I open the keyboard, the banner isn't loaded yet, then the banner load : 
-> http://hpics.li/ff9e5f1

When the banner loads the webview is resized and even if I close the keyboard, the web view is very small 
-> http://hpics.li/dea104b

I double checked that I use the 2.11.0 version in "cordova plugin list" and my android.json file : 

```javascript
    "plugin_metadata": {
        "cordova-plugin-extension": "1.1.4",
        "cordova-plugin-device": "1.0.1",
        "cordova-plugin-inappbrowser": "1.0.1",
        "cordova-plugin-whitelist": "1.0.0",
        "ionic-plugin-deploy": "0.4.1",
        "phonegap-plugin-push": "1.4.4",
        "cordova-plugin-admobpro": "2.11.0"
    }
```

It looks to be a complicated issue !

**Comment by floatinghotpot** [comment]
You need remove cordova-plugin-admobpro and its dependency cordova-plugin-extension, then add back.

**Comment by prisonier** [comment]
I didn't know that cordova-plugin-extension was a dependency.
This is working ! Congratulations ! Thanks for your incredibely reactivity !

IMHO you can consider this issue as solved ;)

**Comment by prisonier** [comment]
Just a small note, I only tried it on android, I don't know if the issue also exists on iOS
