### ISSUE TITLE
Ad refreshing 

### ISSUE THREAD

**Issue by Amechi101** [floatinghotpot/cordova-admob-pro#177]
Wanted to ask what is the proper way to refresh an add using this plugin? The current setup I have reloads the ad every time you enter a particular view using angularJS and my fear is that the ads stack up on one another, and are not just loading a new banner ad.

**Comment by floatinghotpot** [comment]
Only a banner will be displayed at a time. In admob web portal, you can configure ad refresh time, the default interval is 60 seconds.

**Comment by Amechi101** [comment]
Thank you! So within the plugin itself how would you manually refresh the ad? Or the better question where is the  admob web portal located?

**Comment by floatinghotpot** [comment]
admob portal is where you create ad unit id.

https://apps.admob.com/
