### ISSUE TITLE
Unable to build for android

### ISSUE THREAD

**Issue by Dineshrajaa** [floatinghotpot/cordova-admob-pro#178]
Hello,
 I am trying to use this "Cordova-admob-pro" plugin in my project by installing it through "cordova-cli-5.1.1" but when I execute "cordova build android" I am getting this error 

uses-sdk:minSdkVersion 7 cannot be smaller than version 9 declared in library /home/dinesh/Development/Mywork/SoCo/platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play-services-ads/7.5.0/AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="com.google.android.gms.ads" to force usage
:processDebugManifest FAILED

kindly help me to fix this issue.

**Comment by floatinghotpot** [comment]
I think the error message is quite clear.

Check your AndroidManifest.xml, if there is a number 7, then change it to a bigger number, like 9 or something.

**Comment by Dineshrajaa** [comment]
yes I tried doing that but soon after executing "cordova build android" the changes which I made to AndroidManifest.xml getting changed to 7 
I think its because of Gradle but I couldn't find&change the setting in build.gradle

**Comment by Dineshrajaa** [comment]
I am so sorry, it was a issue raised because of the config.xml which I have used and now i have updated that  minsdkversion to 10 so now its building.
Thanks for the support.
