### ISSUE TITLE
Can't build a release version from command line

### ISSUE THREAD

**Issue by Daz66** [floatinghotpot/cordova-admob-pro#179]
Hi,

I've been attempting to solve an issue with your plugin that is throwing an error when trying to do a release build of my cordova project from the command line (on Win7)

I've backtracked from my project to eliminate it from the problem, and have built your Demo1 project - which I can build and install onto my Android phone beautifully using:
>cordova run

So, I try:
>cordova build --release
That works fine.

Then change to the platforms\android folder and type (to generate a build.xml):
>android update project --subprojects --target android-22 --path . 
This seems okay.

But then when I type:
>ant release
There's a disaster!......see:

Buildfile: C:\DocRoot\apps\tmp\platforms\android\build.xml

-set-mode-check:

-set-release-mode:

-release-obfuscation-check:
     [echo] proguard.config is ${proguard.config}

-pre-build:

-check-env:
 [checkenv] Android SDK Tools Revision 24.3.3
 [checkenv] Installed at C:\android-sdk

-setup:
     [echo] Project Name: MainActivity
  [gettype] Project Type: Application

-build-setup:
[getbuildtools] Using latest Build Tools: 23.0.0 rc2
     [echo] Resolving Build Target for MainActivity...
[gettarget] Project Target:   Android 5.1.1
[gettarget] API level:        22
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: C:\DocRoot\apps\tmp\platforms\android\bin\rsObj
    [mkdir] Created dir: C:\DocRoot\apps\tmp\platforms\android\bin\rsLibs
     [echo] ----------
     [echo] Resolving Dependencies for MainActivity...
[dependency] Library dependencies:
[dependency]
[dependency] ------------------
[dependency] Ordered libraries:
[dependency]
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'release'...

nodeps:

-set-mode-check:

-set-release-mode:

-release-obfuscation-check:
     [echo] proguard.config is ${proguard.config}

-pre-build:

-check-env:
 [checkenv] Android SDK Tools Revision 24.3.3
 [checkenv] Installed at C:\android-sdk

-setup:
     [echo] Project Name: CordovaLib
  [gettype] Project Type: Android Library

-build-setup:
[getbuildtools] Using latest Build Tools: 23.0.0 rc2
     [echo] Resolving Build Target for CordovaLib...
[gettarget] Project Target:   Android 5.1.1
[gettarget] API level:        22
     [echo] ----------
     [echo] Creating output directories if needed...
     [echo] ----------
     [echo] Resolving Dependencies for CordovaLib...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency]
[dependency] ------------------

-code-gen:
[mergemanifest] Found Deleted Target File
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Found new input file
     [aapt] Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] No need to generate new BuildConfig.

-pre-compile:

-compile:
     [echo] Creating library output jar file...

-post-compile:

-obfuscate:

-dex:
     [echo] Library project: do not convert bytecode...

-crunch:
   [crunch] Crunching PNG Files in source dir: C:\DocRoot\apps\tmp\platforms\android\CordovaLib\res
   [crunch] To destination dir: C:\DocRoot\apps\tmp\platforms\android\CordovaLib\bin\res
   [crunch] Crunched 0 PNG files to update cache

-package-resources:
     [echo] Library project: do not package resources...

-package:
     [echo] Library project: do not package apk...

-post-package:

-release-prompt-for-password:

-release-nosign:
     [echo]
[propertyfile] Updating property file: C:\DocRoot\apps\tmp\platforms\android\CordovaLib\bin\build.prop
[propertyfile] Updating property file: C:\DocRoot\apps\tmp\platforms\android\CordovaLib\bin\build.prop
[propertyfile] Updating property file: C:\DocRoot\apps\tmp\platforms\android\CordovaLib\bin\build.prop
[propertyfile] Updating property file: C:\DocRoot\apps\tmp\platforms\android\CordovaLib\bin\build.prop

-release-sign:

-post-build:

release:

-code-gen:
[mergemanifest] Found Deleted Target File
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Found Deleted Target File
     [aapt] Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 8 source files to C:\DocRoot\apps\tmp\platforms\android\bin\classes
    [javac] C:\DocRoot\apps\tmp\platforms\android\src\com\rjfun\cordova\admob\AdMobMediation.java:5: error: package com.
google.android.gms.ads does not exist
    [javac] import com.google.android.gms.ads.AdRequest;
    [javac]                                  ^
    [javac] C:\DocRoot\apps\tmp\platforms\android\src\com\rjfun\cordova\admob\AdMobMediation.java:9: error: package AdRequest does not exist
    [javac]     public abstract AdRequest.Builder joinAdRequest(AdRequest.Builder builder);
    [javac]                                                              ^
    [javac] C:\DocRoot\apps\tmp\platforms\android\src\com\rjfun\cordova\admob\AdMobMediation.java:9: error: package AdRequest does not exist
    [javac]     public abstract AdRequest.Builder joinAdRequest(AdRequest.Builder builder);
    [javac]                              ^
    [javac] C:\DocRoot\apps\tmp\platforms\android\src\com\rjfun\cordova\admob\AdMobPlugin.java:19: error: package com.google.android.gms.ads does not exist
    [javac] import com.google.android.gms.ads.AdListener;
    [javac]                                  ^
    [javac] C:\DocRoot\apps\tmp\platforms\android\src\com\rjfun\cordova\admob\AdMobPlugin.java:20: error: package com.google.android.gms.ads does not exist
    [javac] import com.google.android.gms.ads.AdRequest;
    [javac]                                  ^
   .......and many many errors after that......

I have no idea what's going wrong or why this has changed.
I'm guessing that it's something to do with the inclusion/version of the google play services?

Please can you help?!

Many thanks in advance, Daz

**Comment by floatinghotpot** [comment]
Some hints:
1. cordova build uses gradle instead of ant.
2. check and make sure in your android sdk, the extra items are installed.

**Comment by Daz66** [comment]
I'm such an idiot!  For anyone else as lost as me the solution was that I just needed a build.json in my project root to path to my keystore file (documentation here: https://cordova.apache.org/docs/en/edge/guide_platforms_android_tools.md.html)
After that a cordova release build  did all the work perfectly producing a signed apk.

Thanks very much for pushing me gently in the right direction,
Daz

**Comment by skhouseholder** [comment]
For anyone else with this issue, after applying Daz66's solution I kept getting a syntax error. I'm not sure why it didn't work, but I was able to find success with this method instead: http://shallowsky.com/blog/programming/cordova-create-signed-app.html
