### ISSUE TITLE
designed for families program

### ISSUE THREAD

**Issue by JoeAlg** [floatinghotpot/cordova-admob-pro#180]
It seems that ads are not displayed when the android app is the part of "Designed for Families" program on Google Play. There is an Admob help page "Using AdMob with the Designed for Families program" (https://support.google.com/admob/answer/6223431?hl=en) but this code seems not to work with this plugin. please help.

**Comment by floatinghotpot** [comment]
What do you want?

**Comment by floatinghotpot** [comment]
Apps that show ads from AdMob and opt in to the Designed for Families program can be divided into two categories:

Primarily child-directed apps are apps that target "Ages 5 & Under", "Ages 6 to 8", and/or "Ages 9 to 12" in the Designed for Families program. Once your app is admitted to the program under one of these age targets, AdMob will automatically begin serving Designed for Families-compliant ads for all ad requests coming from the app.

Mixed-audience apps are apps that target both child and adult audiences and opt into the Designed for Families program. These apps will need to include code that sets "is_designed_for_families" to true and calls the tagForChildDirectedTreatment() method for ad requests served to a child audience. Upon seeing both "is_designed_for_families" and tagForChildDirectedTreatment() set to true, AdMob will return Designed for Families-compliant ads for that ad request.

What does your app belong to?

**Comment by JoeAlg** [comment]
Thank you for your quick reply!
I have multiple apps. Some of them target "Ages 5 & Under" and "Ages 6 to 8". And some of them target both child and adult audiences and opt into the Designed for Families program. None of them shows Admob ads. I am sure that I am using the plugin in correct way, because if I just edit the package name in config.xml and set it to the one of any of our apps that is not part of "designed for families" program or even to any other package name everything works.

**Comment by floatinghotpot** [comment]
If you set to "Primarily child-directed", it should work. But if your apps are "Mixed-audience apps", this plugin does not support the family option yet. I will consider adding this feature when have time.

**Comment by pdelorme** [comment]
any progress on this ? I have a mixed-audience apps... thanks.

**Comment by pdelorme** [comment]
Hi, here is some patch doing just this. Hope it helps. I'm testing it now in prod.
[AdMobPlugin.patch.txt](https://github.com/floatinghotpot/cordova-admob-pro/files/132892/AdMobPlugin.patch.txt)
