### ISSUE TITLE
cannot compile eclipse project

### ISSUE THREAD

**Issue by smorstabilini** [floatinghotpot/cordova-admob-pro#181]
I have created an app with cordova 5.1.1 and ionic. I can run it on an android device and i can see ads. But I'm not able to create the apk file using eclipse because of compile errors. 
In AdMobPlugin.java and in AdMobMediation.java, all the imports of com.google.android.gms.ads.* fail.
I have also tried with a blank project just to be sure the problem is not related to other plugins. But even on a blank project I have the same problem. 
I tried also on a different pc without lucky.
A friend of mine has the same problem, we don't know what to do...
Any idea?
Thanks

**Comment by floatinghotpot** [comment]
If you mix the use of CLI to build then import into eclipse, may encounter some trouble. At lease I did encounter such trouble before.

Try only ONE of following methods:

1, use the CLI to build signed apk, check the doc on how to configure:
https://cordova.apache.org/docs/en/edge/guide_platforms_android_tools.md.html

2, or else, after create and add platform and plugin, do not build with CLI, directly import into eclipse, run and build with eclipse.

Be sure you have the extra items installed in android SDK and make sure eclipse can find them. As to how, try Google it.

**Comment by smorstabilini** [comment]
using the CLI has worked flawlessly. thanks
