### ISSUE TITLE
PhoneGap Build config.xml line?

### ISSUE THREAD

**Issue by jamminjames** [floatinghotpot/cordova-admob-pro#182]
You say in your description this plugin will work with PhoneGap Build, but provide no config.xml line. How can I add it to config.xml? Thanks.

**Comment by floatinghotpot** [comment]
https://github.com/floatinghotpot/cordova-admob-pro/wiki/00.-How-To-Use-with-PhoneGap-Build

**Comment by jamminjames** [comment]
Okay, thanks. However, it seems the plugin will only work with the latest Phonegap -- is that true? 

The admob plugin worked with Phonegap (cli-5.1.1), but because of other problems, I switched back to Phonegap (3.7.0), and now the admob plugin is not working. On the test page, clicking on the ad creation links does nothing.

**Comment by jamminjames** [comment]
Okay, it works in Phonegap (3.7.0), but only if the script is included on the page. Since I'm using jquery.mobile, which prefers that the script be called from a separate file, I use the script in a file, with the line `$(document).on("pagecreate", function() {' to start it, and the file is called with a `<script src='js/admob-test.js'></script>` line on the page. That works for other plugins I've tried so far, but not with this one. Can you tell me what I may be missing here? Thanks for any help.

**Comment by floatinghotpot** [comment]
you can use it like any other cordova plugin, but make sure the plugin is ready, by starting the procedure after "deviceready" event.
