### ISSUE TITLE
AdMobPro - phonegap PushPlugin incompatibility

### ISSUE THREAD

**Issue by prisonier** [floatinghotpot/cordova-admob-pro#183]
Hi, 

I opened the issue on the ionic project as I tested it within the Ionic envionement.
You can find all error messages and how to reproduct the error on [issue #4049](https://github.com/driftyco/ionic/issues/4049).

**Comment by floatinghotpot** [comment]
Check wiki: https://github.com/floatinghotpot/cordova-admob-pro/wiki/Difference-of-Plugin-IDs

See FAQ No. 3

**Comment by prisonier** [comment]
Ok thank, I guess it is absolutey not the fault of your plugin. But as the PushPlugin repo seems dead I really on't what should I do.

I close the issue here.
