### ISSUE TITLE
Best way to trigger interstatial with swipe?

### ISSUE THREAD

**Issue by jamminjames** [floatinghotpot/cordova-admob-pro#185]
I would like to store a full page ad in the cache and show it between images in a swipeable gallery. So I have this to store it:
`    AdMob.requestInterstitial({
        adId: admobid.interstitial,
        autoShow: false
    }); `

Then, what is the best way to get it to show between swipes in a gallery? Would something like this work?

`document.addEventListener('swiperight',function(data){
AdMob.prepareInterstitial({
    adId: admobid.interstitial,
    autoShow: true
}); `

Also, would it be possible to make the ad appear in a predetermined amount of time?

**Comment by floatinghotpot** [comment]
You can preload the ad resource by calling prepareInterstitial() earlier with option autoShow:false, then call showInterstitial() in the swipe event handler.
