### ISSUE TITLE
Overlap doesnt works on Windows Phone

### ISSUE THREAD

**Issue by calebeaires** [floatinghotpot/cordova-admob-pro#186]
Even if overlap is false, admob goes on app content.

**Comment by calebeaires** [comment]
I am working with Ionic.  It calculates the screen size to create the "scroll content". Make sense if I tell you that Admob and "app scroll content" is fighting for the same screen space!?

Some info:
Windows 8.1 - Device;
Cordova 5.1.1

**Comment by bradrlaw** [comment]
Running into the same issue with a jquery mobile application.

**Comment by dmotion** [comment]
It's true - the overlap doesn't work on WP.

I created some code, so I add extra padding on the bottom of the screen (where the ad is) on WP devices... Android is doing fine, so it can ignore that extra padding.

It's just a CSS-thing, not rocket-science.
