### ISSUE TITLE
Using npm repository version gets rejected by Phonegap Build

### ISSUE THREAD

**Issue by jamminjames** [floatinghotpot/cordova-admob-pro#189]
You noted that you added the plugin to the npm repository, and said to use "cordova-plugin-admobpro" in the config.xml file. However, it is getting rejected. I used this line in config:

`<gap:plugin name="cordova-plugin-admobpro" source="npm" />`

... and I got this error:

Error: Project contains at least one plugin that requires a system library. This is not supported with ANT. Please build using gradle.

When I went back to the old line, it works again:

`<gap:plugin name="com.google.cordova.admob" source="plugins.cordova.io" />`

**Comment by floatinghotpot** [comment]
Yes, you are correct. PhoneGap Build service did not support the ```<framework ...>``` tag yet. Using the old one is a workaround so far.

See:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/Difference-of-Plugin-IDs

**Comment by hasancakmak** [comment]
o yeah
