### ISSUE TITLE
DFP Ad Not Displaying

### ISSUE THREAD

**Issue by theblanchard** [floatinghotpot/cordova-admob-pro#195]
Hello,

I've looked through the API and example code, and have adjusted the example to fit my own app. If i set it up to use the default AdMob ads, everything works fine. When I switch to my own DFP ad, nothing displays. 

Is there anything else I need to do for DFP, other than switching out the ```admobid.banner```?

Code I'm using is below. ```initApp``` function is being called properly in ```onDeviceReady```.

```
var admobid = {
	// AdMob works properly
	banner: 'ca-app-pub-6869992474017983/9375997553'
	// DFP does not display anything
	// banner: '/xxxxxxx/app-cube'
}

function initApp() {
    if (AdMob) {
        AdMob.createBanner({
            adId : admobid.banner,
            position : AdMob.AD_POSITION.BOTTOM_CENTER,
            isTesting: false,
            autoShow : true,
            bgColor: '#0093FF'
        });
    }
}
```

**Comment by floatinghotpot** [comment]
Are you testing in Simulator? Try connecting your device to USB and test in it.

**Comment by theblanchard** [comment]
It worked out to being an issue with the ad on my end. Thanks for the follow up.

**Comment by karan101292** [comment]
I am having a same problem. what was the problem with your ad?

**Comment by theblanchard** [comment]
It came down to using the proper ad sizes. I was off in my code vs. what my ad was displaying at. The same code does work properly. Once I had my issue fixed, everything displayed properly.
