### ISSUE TITLE
'GoogleMobileAds/GoogleMobileAds.h' file not found

### ISSUE THREAD

**Issue by brtsos** [floatinghotpot/cordova-admob-pro#197]
Hi,

i can't build my project. I have error : "'GoogleMobileAds/GoogleMobileAds.h' file not found" in files CDVAdmobPlugin.m and AdMobMediation.h.

Could You help me? :(

regards

**Comment by floatinghotpot** [comment]
It seems that the plugin is not installed properly. Sometimes, the cordova CLI will run into error with unknown reasons.

You can try refresh the files like this:
```bash
cordova platform remove ios
cordova platform add ios
```

**Comment by brtsos** [comment]
Work! Thanks!
