### ISSUE TITLE
Sent Paypal payment - Have not received license

### ISSUE THREAD

**Issue by Scott-Magnan** [floatinghotpot/cordova-admob-pro#198]
Sent paypal payment on 
Item Title:AdMobPluginPro License Key
Date: Jul 3, 2015
Time: 16:46:46 GMT-04:00
Status: Completed  

I also forwarded on Jul 22 at 9:41 AM a notice to liming.xie@gmail.com and  rjfun.mobile@gmail.com. Have not received any reply. And still do not have a AdMobPluginPro License Key.

**Comment by floatinghotpot** [comment]
We double check the payment history and found your record. The license has been sent. Sorry for any inconvenience.
