### ISSUE TITLE
Error: more than one library with package name 'com.google.android.gms'

### ISSUE THREAD

**Issue by LeedleDev** [floatinghotpot/cordova-admob-pro#199]
I have already made sure I have all the packages required installed via the SDK manager. When I try to build I get the follow error:

    :processArmv7DebugResources FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':processArmv7DebugResources'.
    > Error: more than one library with package name 'com.google.android.gms'
      You can temporarily disable this error with android.enforceUniquePackageName=false
      However, this is temporary and will be enforced in 1.0

**Comment by floatinghotpot** [comment]
Could you please list all the plugins, and check if any other plugin causing conflict?

**Comment by TheodoreLogan** [comment]
I am also having this issue; plugin list:
````
com.flyingsoftgames.xapkreader 0.9.0 "Cordova Expansion File Reader"
com.google.playservices 21.0.0 "Google Play Services for Android"
cordova-plugin-admobpro 2.8.4 "AdMob Plugin Pro"
cordova-plugin-extension 1.1.4 "Cordova Plugin Extension"
cordova-plugin-shake 0.5.1 "Shake Gesture Detection"
cordova-plugin-whitelist 1.0.0 "Whitelist"
org.apache.cordova.device 0.3.0 "Device"
org.apache.cordova.device-motion 0.2.11 "Device Motion"
````

**Comment by floatinghotpot** [comment]
com.google.playservices 21.0.0 "Google Play Services for Android"

Please remove the plugin, as it's deprecated and not needed any more. It will cause conflict.

It's documented in the wiki page, please read for more details.

**Comment by oddoye-david** [comment]
Which file to make the changes in?

**Comment by floatinghotpot** [comment]
```bash
cordova plugin remove com.google.playservices
```

**Comment by LeedleDev** [comment]
This worked for me. Thank you very much.

**Comment by saksham09** [comment]
getting same error on phonegap build. will u help me please?

**Comment by floatinghotpot** [comment]
Please check if you have the same reason. The google play framework is described as dependent in plugin.xml, it will be auto loaded. You should not install the library as another plugin, or else it will cause conflict.

**Comment by saksham09** [comment]
i checked its conflicting with cordova admob plugin, but i want both working, what to do ? any help?

**Comment by floatinghotpot** [comment]
please list all the plugins you have in your project.

**Comment by saksham09** [comment]
<plugin name="cordova-plugin-media-capture" source="npm" spec="~1.2.0"/>
<plugin name="com.admob.google" spec="4.0.8" source="pgb" />
  <plugin name="cordova-plugin-console" source="npm" spec="~1.0.2"/>
  <plugin name="cordova-plugin-device" source="npm" spec="~1.1.1"/>
  <plugin name="cordova-plugin-device-motion" source="npm" spec="~1.2.0"/>
  <plugin name="cordova-plugin-device-orientation" source="npm" spec="~1.0.2"/>
  <plugin name="cordova-plugin-dialogs" source="npm" spec="~1.2.0"/>
  <plugin name="cordova-plugin-file" source="npm" spec="~4.1.1"/>
  <plugin name="cordova-plugin-file-transfer" source="npm" spec="~1.5.0"/>
  <plugin name="cordova-plugin-globalization" source="npm" spec="~1.0.3"/>
  <plugin name="cordova-plugin-inappbrowser" source="npm" spec="~1.3.0"/>
  <plugin name="cordova-plugin-media" source="npm" spec="~2.2.0"/>
  <plugin name="cordova-plugin-network-information" source="npm" spec="~1.2.0"/>
  <plugin name="cordova-plugin-splashscreen" source="npm" spec="~3.2.1"/>
  <plugin name="cordova-plugin-statusbar" source="npm" spec="~2.1.2"/>
  <plugin name="cordova-plugin-vibration" source="npm" spec="~2.1.0"/>
  <plugin name="cordova-plugin-whitelist" source="npm" spec="~1.2.1"/>
  <plugin name="io.litehelpers.cordova.sqlitestorage" spec="0.7.5" source="pgb" />
  <plugin name="org.tt.plugin.tts" spec="1" source="pgb" />
  <gap:plugin name="nl.x-services.plugins.socialsharing" />

**Comment by saksham09** [comment]
<plugin name="phonegap-plugin-push" source="npm">
    <param name="SENDER_ID" value="1234567891011" />
	</plugin>
  <plugin name="com.admob.google" spec="4.0.8" source="pgb" />
  <plugin name="cordova-plugin-media-capture" source="npm" spec="~1.2.0"/>
  <plugin name="cordova-plugin-console" source="npm" spec="~1.0.2"/>
  <plugin name="cordova-plugin-device" source="npm" spec="~1.1.1"/>
  <plugin name="cordova-plugin-device-motion" source="npm" spec="~1.2.0"/>
  <plugin name="cordova-plugin-device-orientation" source="npm" spec="~1.0.2"/>
  <plugin name="cordova-plugin-dialogs" source="npm" spec="~1.2.0"/>
  <plugin name="cordova-plugin-file" source="npm" spec="~4.1.1"/>
  <plugin name="cordova-plugin-file-transfer" source="npm" spec="~1.5.0"/>
  <plugin name="cordova-plugin-globalization" source="npm" spec="~1.0.3"/>
  <plugin name="cordova-plugin-inappbrowser" source="npm" spec="~1.3.0"/>
  <plugin name="cordova-plugin-media" source="npm" spec="~2.2.0"/>
  <plugin name="cordova-plugin-network-information" source="npm" spec="~1.2.0"/>
  <plugin name="cordova-plugin-splashscreen" source="npm" spec="~3.2.1"/>
  <plugin name="cordova-plugin-statusbar" source="npm" spec="~2.1.2"/>
  <plugin name="cordova-plugin-vibration" source="npm" spec="~2.1.0"/>
  <plugin name="cordova-plugin-whitelist" source="npm" spec="~1.2.1"/>
  <plugin name="io.litehelpers.cordova.sqlitestorage" spec="0.7.5" source="pgb" />
  <plugin name="org.tt.plugin.tts" spec="1" source="pgb" />
  <gap:plugin name="nl.x-services.plugins.socialsharing" />

**Comment by saksham09** [comment]
hey not able to post plugin:
plugin name="phonegap-plugin-push" source="npm">
    <param name="SENDER_ID" value="289031261344" />
	</plugin>
  <plugin name="com.admob.google" spec="4.0.8" source="pgb" />
  <plugin name="cordova-plugin-media-capture" source="npm" spec="~1.2.0"/>
  <plugin name="cordova-plugin-console" source="npm" spec="~1.0.2"/>
  <plugin name="cordova-plugin-device" source="npm" spec="~1.1.1"/>
  <plugin name="cordova-plugin-device-motion" source="npm" spec="~1.2.0"/>
  <plugin name="cordova-plugin-device-orientation" source="npm" spec="~1.0.2"/>
  <plugin name="cordova-plugin-dialogs" source="npm" spec="~1.2.0"/>
  <plugin name="cordova-plugin-file" source="npm" spec="~4.1.1"/>
  <plugin name="cordova-plugin-file-transfer" source="npm" spec="~1.5.0"/>
  <plugin name="cordova-plugin-globalization" source="npm" spec="~1.0.3"/>
  <plugin name="cordova-plugin-inappbrowser" source="npm" spec="~1.3.0"/>
  <plugin name="cordova-plugin-media" source="npm" spec="~2.2.0"/>
  <plugin name="cordova-plugin-network-information" source="npm" spec="~1.2.0"/>
  <plugin name="cordova-plugin-splashscreen" source="npm" spec="~3.2.1"/>
  <plugin name="cordova-plugin-statusbar" source="npm" spec="~2.1.2"/>
  <plugin name="cordova-plugin-vibration" source="npm" spec="~2.1.0"/>
  <plugin name="cordova-plugin-whitelist" source="npm" spec="~1.2.1"/>
  <plugin name="io.litehelpers.cordova.sqlitestorage" spec="0.7.5" source="pgb" />
  <plugin name="org.tt.plugin.tts" spec="1" source="pgb" />
  <gap:plugin name="nl.x-services.plugins.socialsharing" /

**Comment by saksham09** [comment]
plugin name="phonegap-plugin-push" source="npm">
    param name="SENDER_ID" value="289031261344" />
	/plugin>
  plugin name="com.admob.google" spec="4.0.8" source="pgb" />
  plugin name="cordova-plugin-media-capture" source="npm" spec="~1.2.0"/>
  plugin name="cordova-plugin-console" source="npm" spec="~1.0.2"/>
  plugin name="cordova-plugin-device" source="npm" spec="~1.1.1"/>
  plugin name="cordova-plugin-device-motion" source="npm" spec="~1.2.0"/>
  plugin name="cordova-plugin-device-orientation" source="npm" spec="~1.0.2"/>
  plugin name="cordova-plugin-dialogs" source="npm" spec="~1.2.0"/>
  plugin name="cordova-plugin-file" source="npm" spec="~4.1.1"/>
  plugin name="cordova-plugin-file-transfer" source="npm" spec="~1.5.0"/>
  plugin name="cordova-plugin-globalization" source="npm" spec="~1.0.3"/>
  plugin name="cordova-plugin-inappbrowser" source="npm" spec="~1.3.0"/>
  plugin name="cordova-plugin-media" source="npm" spec="~2.2.0"/>
  plugin name="cordova-plugin-network-information" source="npm" spec="~1.2.0"/>
  plugin name="cordova-plugin-splashscreen" source="npm" spec="~3.2.1"/>
  plugin name="cordova-plugin-statusbar" source="npm" spec="~2.1.2"/>
  plugin name="cordova-plugin-vibration" source="npm" spec="~2.1.0"/>
  plugin name="cordova-plugin-whitelist" source="npm" spec="~1.2.1"/>
  plugin name="io.litehelpers.cordova.sqlitestorage" spec="0.7.5" source="pgb" />
  plugin name="org.tt.plugin.tts" spec="1" source="pgb" />
  gap:plugin name="nl.x-services.plugins.socialsharing" />

**Comment by floatinghotpot** [comment]
You are using the wrong AdMob plugin, please remove the plugin `com.admob.google`, use `cordova-plugin-admobpro`.
