### ISSUE TITLE
iOS StatusBar disappears after clicking on Interstitial.

### ISSUE THREAD

**Issue by mxuko** [floatinghotpot/cordova-admob-pro#201]
I have an interstitial that opens a website in safari when the ad is clicked.

In config.xml the StatusBarOverlaysWebView is false. Means the StatusBar is always there.

If I click the "x" to close the interstitial, the StatusBar remains there, nothing wrong.

But if I click the ad to go to Safari, and then I switch back to the app, the StatusBar disappears.

Is this plugin issue or the SDK issue?

**Comment by floatinghotpot** [comment]
AdMob team has fixed in SDK, please update to latest plugin.
