### ISSUE TITLE
Not working/crashes with cordova-plugin-crosswalk-webview 1.3.0 and cordova android platform 4.1.0

### ISSUE THREAD

**Issue by t-nonque** [floatinghotpot/cordova-admob-pro#202]
The app force close everytime I open it. Here is the logcat:

W/dalvikvm(19926): threadid=1: thread exiting with uncaught exception (group=0x41a12ce0)
W/dalvikvm(19926): threadid=1: uncaught exception occurred
W/System.err(19926): java.lang.StringIndexOutOfBoundsException: length=0; index=0
W/System.err(19926): 	at com.rjfun.cordova.admob.AdMobPlugin.__createAdView(AdMobPlugin.java:100)
W/System.err(19926): 	at com.rjfun.cordova.ad.GenericAdPlugin$1.run(GenericAdPlugin.java:326)
W/System.err(19926): 	at android.os.Handler.handleCallback(Handler.java:808)
W/System.err(19926): 	at android.os.Handler.dispatchMessage(Handler.java:103)
W/System.err(19926): 	at android.os.Looper.loop(Looper.java:193)
W/System.err(19926): 	at android.app.ActivityThread.main(ActivityThread.java:5312)
W/System.err(19926): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(19926): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(19926): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
W/System.err(19926): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
W/System.err(19926): 	at dalvik.system.NativeStart.main(Native Method)

The thing is, if users update the app on the Play Store, they get that crash, but if it is a fresh install, it is working fine.
Previous version was using cordova-plugin-crosswalk-webview 1.2.0

Thanks by advance for the help

**Comment by moussaoui91** [comment]
Did you solve this problem ? and How ?

**Comment by 2msd** [comment]
Had the same problem: I misspelled adId property when adding keys....
