### ISSUE TITLE
Cordova-admob-pro crashes app

### ISSUE THREAD

**Issue by thanhrossi** [floatinghotpot/cordova-admob-pro#203]
Hi all .I'm using the latest cordova-admob-pro for my ionic app. After installation, my app increased from 2.54MB to 4.19MB and after it opened to about 1 second, the ad show up and crash.
Please help me. Thanks

**Comment by szasanyi** [comment]
I'm having the same problem. The may have been a new version uploaded that just doesn't work. I'm using a simple PhoneGap app without Ionic.

**Comment by floatinghotpot** [comment]
Do you have any crash log? Any info on platform (android/ios), OS version, cordova CLI version, etc?

BTW, are you using it with crosswalk?

**Comment by thanhrossi** [comment]
I used Ionic 1.0.1 (Ionic CLI 1.6.4), Cordova 5.1.1, android. And I just install only one a plugin is cordova-admob-pro. Everything was running smoothly until I installed this plugin. Please help me . Thanks

**Comment by floatinghotpot** [comment]
Any logs or error message?

**Comment by thanhrossi** [comment]
I build android version ,it's just push up  one notice : 
>Note: Some input files use or override a deprecated API.  
Note: Recompile with -Xlint:deprecation for details.  
And build successfull . I start with simple ionic template (ionic start myapp tabs), and i follow index.html file (https://github.com/floatinghotpot/cordova-admob-pro/blob/master/test/index.html)

**Comment by sixdas** [comment]
hello, me too closes at startup. Here is my log

08-18 19:55:23.000: I/WebViewFactory(2319): Loading com.android.webview version 39 (1737576-x86_64) (code 300008)
08-18 19:55:23.010: V/WebViewChromiumFactoryProvider(2319): Binding Chromium to main looper Looper (main, tid 1) {28371448}
08-18 19:55:23.010: I/LibraryLoader(2319): Expected native library version number "",actual native library version number ""
08-18 19:55:23.010: I/chromium(2319): [INFO:library_loader_hooks.cc(104)] Chromium logging enabled: level = 0, default verbosity = 0
08-18 19:55:23.010: I/BrowserStartupController(2319): Initializing chromium process, singleProcess=true
08-18 19:55:23.010: W/art(2319): Attempt to remove local handle scope entry from IRT, ignoring
08-18 19:55:23.020: W/chromium(2319): [WARNING:resource_bundle.cc(304)] locale_file_path.empty()
08-18 19:55:23.020: I/chromium(2319): [INFO:aw_browser_main_parts.cc(65)] Load from apk succesful, fd=30 off=46184 len=3037
08-18 19:55:23.020: I/chromium(2319): [INFO:aw_browser_main_parts.cc(78)] Loading webviewchromium.pak from, fd:31 off:229484 len:1089587
08-18 19:55:23.030: E/chromium(2319): [ERROR:gl_surface_egl.cc(165)] No suitable EGL configs found.
08-18 19:55:23.030: E/chromium(2319): [ERROR:gl_surface_android.cc(23)] GLSurfaceEGL::InitializeOneOff failed.
08-18 19:55:23.030: E/chromium(2319): [ERROR:browser_main_loop.cc(988)] GLSurface::InitializeOneOff failed
08-18 19:55:23.050: W/chromium(2319): [WARNING:data_reduction_proxy_settings.cc(331)] SPDY proxy OFF at startup
08-18 19:55:23.150: D/gralloc_goldfish(2319): Emulator without GPU emulation detected.
08-18 19:55:23.260: D/JsMessageQueue(2319): Set native->JS mode to OnlineEventsBridgeMode
08-18 19:55:23.310: I/chromium(2319): [INFO:CONSOLE(23)] "No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.", source: file:///android_asset/www/plugins/cordova-plugin-whitelist/whitelist.js (23)
08-18 19:55:23.360: D/GenericAdPlugin(2319): createBanner: ca-app-pub-6869992474017983/9375997553, true
08-18 19:55:28.780: I/Process(2319): Sending signal. PID: 2319 SIG: 9

**Comment by floatinghotpot** [comment]
The crash cannot be reproduced. Please updated to latest version.
