### ISSUE TITLE
How to remove all admob instantly? 

### ISSUE THREAD

**Issue by tryagains** [floatinghotpot/cordova-admob-pro#204]
On iOS I have added a IAP to remove ads and Apple said when its bought all ads need to be removed instantly without restarting the app. 

How can I get rid of the banner and interstitial ads instantly?
I tried doing
removebanner(); 
hidebanner(); 

But it doesnt remove the banners

**Comment by floatinghotpot** [comment]
the API is case sensitive. So, call:

```javascript
AdMob.removeBanner();

// or AdMob.hideBanner();
```

**Comment by tryagains** [comment]
Thank you :)
What about interstitial ads(full screen ads)?
Apple wants ads to be removed instantly when removed ads IAP is bought. Anyway to remove/stop  interstitial ads without restarting the app?

**Comment by floatinghotpot** [comment]
The interstitial Ad is one-time use, only when you prepare & show, it's created and presented to screen. 

If you want to remove interstitial AD, just don't call prepare & show. That's it.

**Comment by tryagains** [comment]
how would I not prepare and show it after the user buys the remove ads IAP?

**Comment by floatinghotpot** [comment]
you need control it in your apps, after user buy, then you do not display ad anymore.

**Comment by MiLeung** [comment]
What is the difference between removeBanner and hideBanner?  They seem to do the same thing in my iOS simulator.  I thought removeBanner > showBanner would show a different banner, but doesn't.

**Comment by floatinghotpot** [comment]
createBanner() -> removeBanner()

showBanner() -> hideBanner(), if hide, the banner is invisible, but still there.

**Comment by jayveezaragosa** [comment]
how to remove admod ads in cordova sir ??

**Comment by DigitalMystery** [comment]
@jayveezaragosa I'm sure you figured something out by now, but for banner do as above

`AdMob.removebanner();`

Then for all interstitial or video ads add a role check on your user before calling the show (if they are a subscription user or bought your IAP):

`if(AdMob && userRole === "NonSubscriptionUser") AdMob.showInterstitial();`
