### ISSUE TITLE
Build android failed on ionic after adding admob pro

### ISSUE THREAD

**Issue by jiannius** [floatinghotpot/cordova-admob-pro#205]
I have successfully created my app in ionic, build android was successful and I was able to test it in my android devices. Now I try to use AdMob Pro, after I've added the plugin by issueing ionic plugin add cordova-plugin-admobpro, I was not able to build android, it failed with error:

Running: /home/vagrant/app/android-quotes/platforms/android/gradlew cdvBuildDebug -b /home/vagrant/app/android-quotes/platforms/android/build.gradle -
Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-ads:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.603 secs

/home/vagrant/app/android-quotes/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /home/vagrant/app/android-quotes/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/vagrant/app/android-quotes/plat
forms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /home/vagrant/app/android-quotes/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /home/vagrant/app/android-quotes/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by floatinghotpot** [comment]
You need install the extra libs of Android SDK. 

See FAQ 4:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/Difference-of-Plugin-IDs

**Comment by jiannius** [comment]
Ok, I have installed the extra libs by issueing `android update sdk -u -a -t 139,140,145,146,148`. Now when I try to rebuild the android, the error is different:

    :preDexDebug FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':preDexDebug'.
    > com.android.ide.common.internal.LoggedErrorException: Failed to run command:
            /home/vagrant/android-sdk-linux/build-tools/22.0.1/dx --dex --output /home/vagrant/app/quotes/platforms/android/build/intermediates/pre-dexed/
    debug/classes-482f9ad21fd8e0326e6fc690d0e5c5941100cc1b.jar /home/vagrant/app/quotes/platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play-services-analytics/7.5.0/classes.jar
      Error Code:
            137
    
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    
    BUILD FAILED
    
    Total time: 2 mins 30.71 secs
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Failed to notify build listener.
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    
    /home/vagrant/app/quotes/platforms/android/cordova/node_modules/q/q.js:126
                        throw e;
                              ^
    Error code 1 for command: /home/vagrant/app/quotes/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/vagrant/app/quotes/platforms/android/bu
    ild.gradle,-Dorg.gradle.daemon=true
    ERROR building one of the platforms: Error: /home/vagrant/app/quotes/platforms/android/cordova/build: Command failed with exit code 1
    You may not have the required environment or OS to build this project
    Error: /home/vagrant/app/quotes/platforms/android/cordova/build: Command failed with exit code 1
        at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
        at ChildProcess.emit (events.js:110:17)
        at maybeClose (child_process.js:1015:16)
        at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by floatinghotpot** [comment]
I don't know what's the error means. I just guess it may come from the dirty build data.

Please try create a clean project and use the cordova CLI to build again.

**Comment by thanhrossi** [comment]
You can try install some extras look like image  
![Google extra](https://cloud.githubusercontent.com/assets/2339512/8176143/20533ec0-1429-11e5-8e17-a748373d5110.png)
