### ISSUE TITLE
Error: more than one library with package name 

### ISSUE THREAD

**Issue by csvendsen** [floatinghotpot/cordova-admob-pro#208]
Having an issue with the build have tried removing and adding back the platform also uninstalled all plugins and reinstalled works fine when i uninstall admob.

FAILURE: Build failed with an exception.

What went wrong: Execution failed for task ':processDebugResources'. > Error: more than one library with package name 'com.google.android.gms'

**Comment by floatinghotpot** [comment]
I guess you may add the google play services jar more than once. 

please show me all the plugins:
```bash
cordova plugin ls
```

**Comment by andresigualada** [comment]
It's happening to me too. It is something related to another plugin which also uses com.google.android.gms, in my case is [this one about native google maps](https://github.com/wf9a5m75/phonegap-googlemaps-plugin).

I don't have duplicated plugins (I've checked with **cordova plugin s**)

What I did is comment the tag <framework src="com.google.android.gms:play-services-ads:+" /> in plugin.xml and remove and add the platform again. 

I am pretty sure this is not the solution but works for me, though.

**Comment by floatinghotpot** [comment]
The framework tag is using the default google jar in android sdk, which is recommended. Some other plugin may includes google jar, which will cause conflict. 

See:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/Difference-of-Plugin-IDs#3-build-error-with-message-multiple-dex-files-define-lcomgoogle
