### ISSUE TITLE
Cannot find Google AdMob symbol in Eclipse

### ISSUE THREAD

**Issue by sixdas** [floatinghotpot/cordova-admob-pro#209]
Hello, I am trying to use your plugin to monetize, my app html5 cordova apache. I tried to create a test project, following your guide, but when I import the project in Eclipse, I returns 96 errors. can you help me figure out what is wrong.

<a href='http://postimg.org/image/6lc0jfu21/' target='_blank'><img src='http://s28.postimg.org/6lc0jfu21/Cattura2.jpg' border='0' alt="Cattura2" /></a>
thanks a lot.

PS sorry for my english

**Comment by floatinghotpot** [comment]
Check issue #169, I guess you did not have google libs installed properly.

**Comment by sixdas** [comment]
I did not understand what to do, I downloaded all the extras, such as a guide.
<a href='http://postimg.org/image/sx255ux2n/' target='_blank'><img src='http://s11.postimg.org/sx255ux2n/Cattura0.jpg' border='0' alt="Cattura0" /></a>

<a href='http://postimg.org/image/qv8d7wuy5/' target='_blank'><img src='http://s22.postimg.org/qv8d7wuy5/Cattura1.jpg' border='0' alt="Cattura1" /></a>

**Comment by floatinghotpot** [comment]
The error means the google play service jar is not found, so must be something wrong with the path of sdk or configuration.

Can you build with Cordova CLI?

cordova build android

**Comment by sixdas** [comment]
If the launch command gives me this:

C:\Users\Tore\test1>cordova build android
Running command: cmd "/s /c "C:\Users\Tore\test1\platforms\android\cordova\build
.bat""
[Error: ANDROID_HOME is not set and "android" command not in your PATH. You must
 fulfill at least one of these conditions.]
ERROR building one of the platforms: Error: cmd: Command failed with exit code 2

You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 2
    at ChildProcess.whenDone (C:\Users\Tore\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\src\cordova\superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

C:\Users\Tore\test1>

**Comment by floatinghotpot** [comment]
Error: ANDROID_HOME is not set and "android" command not in your PATH. You must
fulfill at least one of these conditions.

Quite clear: You did not configure the Android SDK env properly. Please check the android docs and set the env variable ANDROID_HOME to your android SDK folder.

**Comment by sixdas** [comment]
I solved the problem of ANDROID_HOME, it was not set the environment variable. BUT once amount eclipse gives me the same problem in the first place my 96 errors

**Comment by floatinghotpot** [comment]
What happen if you use Cordova CLI to build? 

Remember to start a new command line to get the valid ANDROID_HOME first.

**Comment by sixdas** [comment]
Use version 5.1.1 Cordova CLI 

The error appears only when imported into eclipse. I attach video of the steps executed

https://youtu.be/q6kfsDWDEok

**Comment by floatinghotpot** [comment]
If you can build with Cordova CLI, then the plugin should work. 

As to eclipse, there must be some configuration missing.

**Comment by sixdas** [comment]
I uninstalled and reinstalled sdk and eclipse. I added the environment variables.
Cordova with CLI starts. with eclipse gives me this error when I import the project
<a href='http://postimg.org/image/89s02ywu3/' target='_blank'><img src='http://s1.postimg.org/89s02ywu3/Caterttura.jpg' border='0' alt="Caterttura" /></a>
and after these other two.
<a href='http://postimg.org/image/wzm9wixov/' target='_blank'><img src='http://s11.postimg.org/wzm9wixov/Catitura.jpg' border='0' alt="Catitura" /></a>
I do not know what to do, I could try with Android study?

**Comment by floatinghotpot** [comment]
As to the errors above, clean up your workspace folder, the try again. When import the project, import the folder /path/to/your/project/platforms/android only.

The errors are very basic, find a senior developer or teacher around you and ask for help step by step, will be more efficient.

**Comment by sixdas** [comment]
Hello, I was able to fix all the errors listed above. But now the app is closed when you start going to crash. I saw that other users have this problem:
[issue #203](https://github.com/floatinghotpot/cordova-admob-pro/issues/203)

Can you help me?

**Comment by floatinghotpot** [comment]
A good issue report should include more info, like crash log, etc. Or else I don't know what happens.

**Comment by floatinghotpot** [comment]
As the eclipse error is resolved, I'd like to close this issue.

For same crash problem, you can discuss in that issue #203.
