### ISSUE TITLE
Flurry won't show ad (android)

### ISSUE THREAD

**Issue by Bnaya** [floatinghotpot/cordova-admob-pro#210]
We are trying to display bottom ad using flurry mediation adapter
I *think* it worked for once, and the ad was displayed, not nothing happen and in the log we see:
```
I/Ads     (12623): Trying mediation network: 3376427960656545613
I/Ads     (12623): Instantiating mediation adapter: com.google.ads.mediation.flurry.FlurryAdapter
V/FlurryAdapter(12623): Requesting Banner Ad
V/FlurryAdapter(12623): Destroy Ad
V/FlurryAdapter(12623): Banner view is created for {width = 960px, height = 150px}
I/art     (12623): Rejecting re-init on previously-failed class java.lang.Class<com.flurry.sdk.bp>
I/art     (12623): Rejecting re-init on previously-failed class java.lang.Class<com.flurry.sdk.bp>
I/art     (12623): Rejecting re-init on previously-failed class java.lang.Class<com.flurry.sdk.br>
I/art     (12623): Rejecting re-init on previously-failed class java.lang.Class<com.flurry.sdk.br>
E/SQLiteLog(25988): (2067) abort at 53 in [INSERT INTO messages(key_remote_jid, key_from_me, key_id, status, needs_push, data, timestamp, media_url, media_mime_type, media_wa_type, media_size, media_name, media_caption, media_hash, medi
D/c       (12623): onError(com.flurry.android.ads.FlurryAdBanner@ceba18bFETCH20)
V/FlurryAdapter(12623): Calling onFailedToReceiveAd for Interstitial with errorCode: Ad request successful, but no ad returned due to lack of ad inventory.
V/FlurryAdapter(12623): Destroy Ad
I/Ads     (12623): No fill from any mediation ad networks.
V/FlurryAdapter(12623): Destroy Ad
W/Ads     (12623): Failed to load ad: 3
```

We've also added the device to the test devices Ids

**Comment by floatinghotpot** [comment]
The error message is clear: Ad request successful, but no ad returned due to lack of ad inventory.

It means the ad server has no ad for you, as flurry has no enough ad business in your country. 

I suggest you use AdMob only, as AdMob fill rate is 95% or higher.

**Comment by Bnaya** [comment]
I forgot to mention,
The log shows its trying to load Interstitial ad, {width = 960px, height =
150px}
We are trying to display regular bottom ad(that works with admod)

**Comment by floatinghotpot** [comment]
In your admob portal, mediation, you need configure the correct flurry ad space name. 

If you plan to show a banner, then specify a "banner" ad space name instead of full screen one.

**Comment by Bnaya** [comment]
We are using DFP + DFP mediation (and not admob directly)
The 'Ad Space Name' and android 'Project API Key (Android)' are configured properly in the DFP creative
The flurry banner is configured as 'Banner Bottom' + the device id is configured as 'Test Device Ids' to ensure fulfilment
Still same results as the above.

I would guess that for some reason it ignores the 'Ad Space Name' from the DFP banner and trying to load Interstitial as fallback

**Comment by Bnaya** [comment]
CC @Bartzy

**Comment by Bnaya** [comment]
@floatinghotpot Should that plugins work with DFP mediation at all?

**Comment by Bnaya** [comment]
Our problem was that we didn't specify 
```
adSize: 'BANNER'
```
