### ISSUE TITLE
Having issues building with Intel XDK v2366

### ISSUE THREAD

**Issue by tysjiang** [floatinghotpot/cordova-admob-pro#212]
Getting failed builds with Intel XDK Cordova Android builds
The error is:
[dependency] Found 2 versions of google-play-services.jar in the dependency list,
[dependency] but not all the versions are identical (check is based on SHA-1 only at this time).
[dependency] All versions of the libraries must be the same at this time.
[dependency] Versions found are:
[dependency] Path: .../BlueChatBox/platforms/android/com.google.playservices/google-play-services_lib/libs/google-play-services.jar
[dependency] 	Length: 3416020
[dependency] 	SHA-1: 0f6d5c1ef2e982c3b7858408e3df389cf5d202da
[dependency] Path: .../BlueChatBox/platforms/android/libs/google-play-services.jar
[dependency] 	Length: 5415820
[dependency] 	SHA-1: 8d5f3fa25437d7d8ffdfb1a0f251adf682f14649

BUILD FAILED
/Developer/android-sdk-linux/tools/ant/build.xml:573: Jar mismatch! Fix your dependencies

Note: This just started happening today, yesterday it was fine.

I was pulling this from the Cordova registry and with the id: com.google.cordova.admob

Today, I tried pulling it from the registry and github with a mix of ids:
com.admob.pro
cordova-plugin-admobpro
com.google.cordova.admob

But they're all failing. (If I remove admob, the build goes through fine)

**Comment by tysjiang** [comment]
Closing.

Turns out there was a conflict with the latest Pushwoosh plugin 3.6.5
After downgrading the Pushwoosh plugin, everything worked again.  
Not sure if the fault lies 100% with Pushwoosh and some with Admob or a mixture, but since the builds are now going through, I am closing this.

**Comment by almemar87** [comment]
Sorry Tysjiang to open this issue again. 
but Have you tried lower version of Pushwoosh than 3.6.5? 
and if so which version was that? 
and does go along with Intel xdk admob? 
many thanks,

**Comment by almemar87** [comment]
I found the pushwoosh v.3.6.2 works just fine with admob on intel xdk :dancer:
