### ISSUE TITLE
Google Ads Policy changed - getting user consent to display ads 

### ISSUE THREAD

**Issue by koalabeer** [floatinghotpot/cordova-admob-pro#213]
Hi,

The Google Ads Policy has changed in the EU and it is not mandatory to get user consent to display ads.

See:
https://thomas.vanhoutte.be/miniblog/google-ads-policy-cookies/
http://adsense.blogspot.nl/2015/07/introducing-new-user-consent-policy.html

It would be great if this user consent could be built in to this wonderfull plugin :)
Or is there a good javascript library to obtain this consent to be allowed to display Google Ads in Phonegap Build apps? 

Best regards, 
Tim

**Comment by floatinghotpot** [comment]
the plugin is based on google admob sdk, for mobile apps, not for adsense for website, so maybe not related with it. do you have any info from admob?

**Comment by koalabeer** [comment]
Thanks for your response.

Google points to this site to help better understanding and implemening the cookie consent: http://www.cookiechoices.org/

AdMob itself is not spefically mentioned. But to be honest, i'm not 100% sure on the difference between AdSense and AdMob... And they do mention AdSense:

> If you’re using Google products like Google AdSense or DoubleClick for Publishers, you’ll be required by your contract to follow Google’s EU user consent policy.

So i'm still not sure whether or not apps using AdMob to display advertisements need to implement this user consent policy as well.

**Comment by floatinghotpot** [comment]
I did not receive such notification from AdMob team till now, so I guess you may handle that when they contact you. Before that you can concentrate on how to integrate the ad into your apps and focus on monetization.

**Comment by koalabeer** [comment]
I did receive the email. But it is a generic mail, they don't specifically mention my apps.

I have my apps up and running, including your plugin which serves the ads. Your plugin made that a breeze, really great work on that!

Thanks
Tim

**Comment by floatinghotpot** [comment]
Glad to hear that you use it and do think it helps. Cheers. 

So far I did not see anything violate the basic rules. As the email is quite generic, I guess you can ignore it, unless any concrete action is asked to do.

**Comment by koalabeer** [comment]
Yeah but unfortunetely, if i am required to change something, the Apple approval process usually takes about 10 - 14 days. So if possible i like to stay ahead of any problemns :)

Keep me posted if you learn anything (in the near future) that Ads served with your plugin also need this user consent.

All the best,
Tim

**Comment by floatinghotpot** [comment]
Sure. If any concrete action is asked, I will follow up, as it will be same to all developers.
