### ISSUE TITLE
iOS admob pro showing test ads randomly

### ISSUE THREAD

**Issue by mxuko** [floatinghotpot/cordova-admob-pro#215]
I set up DFP interstitial and it works perfectly.

But for a few times in the day, it will show ads unrelated to my account!

I did a trace in Charles and found that the plugin is requesting interstitial using ca-app-pub-6869992474017983/3271550750

That's your test account. I looked through the source code and found that it's defined as TEST_INTERSTITIALID

Why is it randomly getting ads from the test id instead of respecting my DFP id?

**Comment by floatinghotpot** [comment]
Here are the few possibilities that the test ad is showing:
1. If set option isTesting:true, it's running in test mode, mainly for test purpose. 
2. If no license is set, it will run in partnership mode and 2% ad traffic is sent to test ad id. For DFP house ad, you can get a license to disable the behavior.
3. When ad resource loading failed, to avoid blank ad, it will load ad resource from admob test ad id as fallback. You can set option fallback:false to disable that behavior.
