### ISSUE TITLE
Build failure - com.android.dex.DexException: Multiple dex files define Landroid/support/v4/app/NotificationCompatHoneycomb;

### ISSUE THREAD

**Issue by marlonhsantos** [floatinghotpot/cordova-admob-pro#216]
I'm trying to build an app using Ionic Framework with admob-pro, but having that error: **com.android.dex.DexException: Multiple dex files define Landroid/support/v4/app/NotificationCompatHoneycomb;**

I've read about a similar problem at https://github.com/floatinghotpot/cordova-admob-pro/wiki/Difference-of-Plugin-IDs that says: 

```
3. Build error with message "Multiple dex files define Lcom/google/..."

_Caused by duplicated google-play-services.jar.

This plugin properly referenced to the google-play-services.jar in your android sdk with tag framework , which is recommended by Google team.

While some other plugins contains the jar, or depends on a plugin named com.google.playservices which is already deprecated.

Please list all plugins and check which plugin use it improperly, then report a bug to that plugin.
```

That Isn't exactly the same error, but i'd like to try that solution.
But how do I check which plugin could be conflicting?
Is there a workaround?

That is my plugin list:
com.ionic.keyboard 1.0.3 "Keyboard"
com.smartmobilesoftware.androidinappbilling 3.0.2 "Android InAppBilling"
cordova-plugin-admobpro 2.8.3 "AdMob Plugin Pro"
cordova-plugin-extension 1.1.4 "Cordova Plugin Extension"
cordova-plugin-geolocation 1.0.2-dev "Geolocation"
cordova-plugin-whitelist 1.1.1-dev "Whitelist"
de.appplant.cordova.plugin.local-notification 0.8.1 "LocalNotification"
nl.x-services.plugins.socialsharing 4.3.19 "SocialSharing"
org.apache.cordova.console 0.2.11 "Console"
org.apache.cordova.device 0.2.12 "Device"

**Comment by floatinghotpot** [comment]
I just guess, maybe this one is using google play for payment, which cause the conflict.

com.smartmobilesoftware.androidinappbilling 3.0.2 "Android InAppBilling"

**Comment by marlonhsantos** [comment]
Your guess was right, but it had some issues with another plugin too: **de.appplant.cordova.plugin.local-notification 0.8.1 "LocalNotification"**.
So, I did the following:

-Removed the plugin **"com.smartmobilesoftware.androidinappbilling"**;

-Removed the plugin **"de.appplant.cordova.plugin.local-notification"**;

-Added **"cordova-plugin-admobpro"**;

-Re-added the plugin **"com.smartmobilesoftware.androidinappbilling"**;

-Re-added the plugin **"de.appplant.cordova.plugin.local-notification"**, which automatically added the plugin **"cordova-plugin-android-support-v4"** as a dependency;

-Changed the dependency from **plugin.xml** on **"de.appplant.cordova.plugin.local-notification"** folder, swapping the line *<dependency id="cordova-plugin-android-support-v4" />* for *<dependency id="android.support.v4" />*;

-Deleted the dependency of plugin **"cordova-plugin-android-support-v4"** erasing that lines on the file **[app_root]/plugins/android.json**
        *"cordova-plugin-android-support-v4": {
            "PACKAGE_NAME": "com.ionicframework.app364481"
        }*

After all that, it builded OK, and everthing seems to work fine!
