### ISSUE TITLE
Unable to display ads on ios Phone Gap app

### ISSUE THREAD

**Issue by ClemLake** [floatinghotpot/cordova-admob-pro#217]
Hello,

I have been facing an unexpected issue today with admob pro. I am currently testing my app hosting it with PhoneGap on Windows and opening it with the iOS PhoneGap app. However, ads never show up. 
My code is exactly the same as the example (despite the id of my ads).

Did anyone face the same problem ?

**Comment by ittus** [comment]
I'm not able to display interstitial ads on iOS simulator, too.

**Comment by floatinghotpot** [comment]
I can prove it still works if build with cordova CLI. There must be something wrong with your env.

Remember, in simulator, you can only get test Ad, to get live Ad, you have to run it in device.

A fast way to verify the plugin with its demo app:
```bash
[sudo ] npm install -g plugin-verify;
plugin-verify cordova-plugin-admobpro ios;
```

BTW, my env: Mac OS, cordova CLI 5.2, Xcode 6.4

See screenshot:
![admob](https://cloud.githubusercontent.com/assets/2339512/9648146/9730351c-5217-11e5-916b-6d513e02e75a.png)
