### ISSUE TITLE
Build Error with xCode

### ISSUE THREAD

**Issue by evandentremont** [floatinghotpot/cordova-admob-pro#218]
I'm unable to build my app in xcode after adding cordova-admob-pro plugin. Any ideas?

    Undefined symbols for architecture arm64:
    "_kCLLocationAccuracyBest", referenced from:
      -[CDVAdMobPlugin __buildAdRequest:] in CDVAdMobPlugin.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by evandentremont** [comment]
Had to manually add CoreLocation.framework to the project to get it to compile.

**Comment by floatinghotpot** [comment]
The plugin is valid, as you can see the framework in its plugin.xml:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/plugin.xml
```xml
         <framework src="CoreLocation.framework" />
```

I guess it's random error when cordova CLI handle it.

BTW, you can quickly verify the plugin like this:
```bash
[sudo] npm install -g plugin-verify;
plugin-verify cordova-plugin-admobpro ios;
```
