### ISSUE TITLE
plugin issue in ios

### ISSUE THREAD

**Issue by umesh25** [floatinghotpot/cordova-admob-pro#221]
lexical or preprocessor issue expected ':' in GADinterstital.h file

same issue in GADAdReward.h file

please help to solve this error i try google and this issue section but i did not find any solution for this.

![screen shot 2015-09-06 at 3 00 59 pm](https://cloud.githubusercontent.com/assets/2259238/9703678/789f423a-54a8-11e5-9924-61023c0714b0.png)

![screen shot 2015-09-06 at 3 04 12 pm](https://cloud.githubusercontent.com/assets/2259238/9703688/bbb68e02-54a8-11e5-9100-3f3ed434b4ff.png)

![screen shot 2015-09-06 at 3 04 37 pm](https://cloud.githubusercontent.com/assets/2259238/9703685/b0f07aaa-54a8-11e5-9a3e-50184b99d505.png)

**Comment by floatinghotpot** [comment]
The files are directly from Google SDK, and I verified the plugin before publish, should be no problem.

What Xcode version do you have?

**Comment by umesh25** [comment]
xcode version 5.1.1, this is perfectly work with android and windows phone . but this issue only in ios.

**Comment by floatinghotpot** [comment]
Please upgrade your xcode to 6.x, as NS_DESIGNATED_INITIALIZER macro is introduced by Apple in Xcode 6.
