### ISSUE TITLE
Can not build using ionic after adding plugin

### ISSUE THREAD

**Issue by aviadhahami** [floatinghotpot/cordova-admob-pro#222]
Hey,
I've added the plugin as described in your manual and since then I can not build my app (I'm using Ionic). Here's the log:

FAILURE: Build failed with an exception.
 
* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-ads:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads/
     Required by:
         :android:unspecified

Any ideas ?

**Comment by floatinghotpot** [comment]
It seems that you did not install required android sdk libraries. Read: https://github.com/floatinghotpot/cordova-admob-pro/wiki/Difference-of-Plugin-IDs#4-build-error-with-message-not-found-comgoogleandroidgmsplay-services-ads

**Comment by aviadhahami** [comment]
Realized it only after I posted... :-1: 

Nevertheless - Now I can build yet I see nothing on my device

**Comment by aviadhahami** [comment]
Ok fixed the stuff and rebooted. For some reason it did the magic. Can close the issue thx for the fast reply tho :D
