### ISSUE TITLE
AndroidManifest.xml does not have the right value

### ISSUE THREAD

**Issue by diegotole** [floatinghotpot/cordova-admob-pro#223]
E/AndroidRuntime( 6225): java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 7895000 but found 7571000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
E/AndroidRuntime( 6225): 	at com.google.android.gms.common.GooglePlayServicesUtil.zzad(Unknown Source)
E/AndroidRuntime( 6225): 	at com.google.android.gms.common.GooglePlayServicesUtil.isGooglePlayServicesAvailable(Unknown Source)
E/AndroidRuntime( 6225): 	at com.google.android.gms.ads.internal.util.client.zza.zzR(Unknown Source)
E/AndroidRuntime( 6225): 	at com.google.android.gms.ads.internal.client.zze.zza(Unknown Source)
E/AndroidRuntime( 6225): 	at com.google.android.gms.ads.internal.client.zzy.zzcT(Unknown Source)
E/AndroidRuntime( 6225): 	at com.google.android.gms.ads.internal.client.zzy.zzcS(Unknown Source)
E/AndroidRuntime( 6225): 	at com.google.android.gms.ads.internal.client.zzy.zza(Unknown Source)
E/AndroidRuntime( 6225): 	at com.google.android.gms.ads.AdView.loadAd(Unknown Source)
E/AndroidRuntime( 6225): 	at com.rjfun.cordova.admob.AdMobPlugin.__loadAdView(AdMobPlugin.java:122)
E/AndroidRuntime( 6225): 	at com.rjfun.cordova.ad.GenericAdPlugin$1.run(GenericAdPlugin.java:340)
E/AndroidRuntime( 6225): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 6225): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 6225): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 6225): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 6225): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6225): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 6225): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 6225): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 6225): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by floatinghotpot** [comment]
Expected 7895000 but found 7571000

It seems that your Google play service is causing conflict with the version declared. Using the SDK default one should not cause such conflict. 

What other plugins are you using?

**Comment by diegotole** [comment]
com.google.play.services 25.0.0 "Google Play Services for Android"
cordova-plugin-admobpro 2.8.3 "AdMob Plugin Pro"
cordova-plugin-extension 1.1.4 "Cordova Plugin Extension"
cordova-plugin-google-analytics 0.7.2 "Google Universal Analytics Plugin"
cordova-plugin-whitelist 1.0.0 "Whitelist"
de.appplant.cordova.plugin.email-composer 0.8.3dev "EmailComposer"
org.apache.cordova.camera 0.3.6 "Camera"
org.apache.cordova.device 0.3.0 "Device"


Probably the analytics plugin?

**Comment by diegotole** [comment]
most likely, i found this in the analytics plugin.xml:
<platform name="android">
    <dependency id="com.google.playservices@19.0.0" />

but would just change/delete that line fix? do i need to find and delete the asset?

**Comment by floatinghotpot** [comment]
com.google.play.services 25.0.0 "Google Play Services for Android"

this dependent plugin is no more needed, as the default jar in your android sdk will be used.

**Comment by diegotole** [comment]
fixed thx!
