### ISSUE TITLE
Android Banner not responding to AdMob.createBanner properties

### ISSUE THREAD

**Issue by MiLeung** [floatinghotpot/cordova-admob-pro#228]
AdMob.createBanner({
                    adId: admobid.banner,
                    position: AdMob.AD_POSITION.TOP_CENTER,
                    autoShow: true,
                    isTesting: false,
                    overlap: true
                });

Works fine in iOS simulator, but doesn't overlap or show real ads in any Android emulator;

**Comment by floatinghotpot** [comment]
Try it on a real android device.

On emulator, admob will only present test ad.

**Comment by MiLeung** [comment]
Got it fixed.  It might have just been that Cordova did not update the www folders fast enough, so I was still seeing the test ads, but it works on emulators now.  Thanks!
