### ISSUE TITLE
The Event onAdPresent is never triggert.

### ISSUE THREAD

**Issue by RonnySchleicher** [floatinghotpot/cordova-admob-pro#229]
See the documentation:

https://github.com/floatinghotpot/cordova-admob-pro/wiki/1.5-Events

##### onAdPresent
* Triggered when Ad will be showed on screen.

But the event **onAdPresent** is not triggered! Other events like **onAdLoaded** will be triggered, however.

Am I doing something wrong or is it a bug?

So I use it:

```JavaScript
initAddMob : function () {
            var admobid = {
                 banner       : 'aaaa',
                 interstitial : 'aaaa'
            };            

            AdMob.createBanner({
                adId     : admobid.banner,
                adSize   : AdMob.AD_SIZE.SMART_BANNER,
                position : AdMob.AD_POSITION.BOTTOM_CENTER,
                overlap  : true,
                autoShow : true
            });

             document.addEventListener('onAdPresent', function(){
                console.log('onAdPresent');
             }, false);
        }
```

**Comment by RonnySchleicher** [comment]
#### Used Software Versions
cordova VERSION = "4.1.1"
"cordova-plugin-whitelist": "1.0.0",
"cordova-plugin-device-motion": "1.1.1",
"cordova-plugin-media-capture": "1.0.1",
"cordova-plugin-device-orientation": "1.0.1",
"cordova-plugin-network-information": "1.0.1",
"cordova-plugin-contacts": "1.1.0",
"cordova-plugin-device": "1.0.1",
"cordova-plugin-battery-status": "1.1.0",
"cordova-plugin-file-transfer": "1.2.1",
"cordova-plugin-geolocation": "1.0.1",
"cordova-plugin-globalization": "1.0.1",
"cordova-plugin-inappbrowser": "1.0.1",
"cordova-plugin-media": "1.0.1",
"cordova-plugin-dialogs": "1.1.1",
"cordova-plugin-vibration": "1.2.0",
"cordova-plugin-splashscreen": "2.1.0",
"cordova-plugin-console": "1.0.1",
"cordova-plugin-statusbar": "1.0.1",
"cordova-plugin-admobpro": "2.9.2",
"cordova-plugin-file": "3.0.0",
"cordova-plugin-extension": "1.1.4"

#### Used Device
Samsung Galaxy Note 3 SM-N9005
Android Version 5.0

**Comment by floatinghotpot** [comment]
You are correct. The event ```onAdPresent``` only works for interstitial Ad.

**Comment by RonnySchleicher** [comment]
Thank you for your quick response.
