### ISSUE TITLE
Banner location bug when keyboard is open

### ISSUE THREAD

**Issue by AlexeyToksarov** [floatinghotpot/cordova-admob-pro#23]
I think the screens speak for themselves

overlap: true, position: AdMob.AD_POSITION.BOTTOM_CENTER
plugin version: 1.0.7

UPDATE: same behavior with 1.1.1

![2014-09-22 16 54 07](https://cloud.githubusercontent.com/assets/3192682/4360341/fa170fa0-427a-11e4-9882-80964198b995.png)  | ![2014-09-22 16 54 23](https://cloud.githubusercontent.com/assets/3192682/4360340/fa0475b6-427a-11e4-839d-17e3a4a71c7d.png) 
------------ | -------------
![2014-09-22 16 55 15](https://cloud.githubusercontent.com/assets/3192682/4360338/fa1c3444-427a-11e4-86b2-ce5e5e5ba36e.png)  | ![2014-09-22 16 55 22](https://cloud.githubusercontent.com/assets/3192682/4360339/f9fab918-427a-11e4-86fd-98a17a27a570.png)

**Comment by AlexeyToksarov** [comment]
@floatinghotpot Should I create a new issue for the problem described above?

**Comment by floatinghotpot** [comment]
No need, just re-open this issue.

**Comment by calebeaires** [comment]
Do you have some roadmap about this issue?

**Comment by floatinghotpot** [comment]
Your cordova CLI version and cordova-android version please?

**Comment by calebeaires** [comment]
Cordova CLI: 5.0.0;
Cordova Android 4.0.0;
Build at an Android 5.02

**Comment by vhk** [comment]
i have the same problem. When the keyboard pops up before the initialisation, the add is in the middle of the screen. The keyboard disappear and the add stays in the middle

**Comment by calebeaires** [comment]
I have found some workaround: on activity I changed the code to

``` android:windowSoftInputMode="adjustPan" ```


*** Maibe this could help you find some solution

**Comment by mikealo** [comment]
about this issue: adjustPan setting gave me some problem, anyway in most case this could be a good workaround, i also found that using an input inside an iframe with adjustResize keep the banner under the keyboard like adjustPan setting, i don't know if this can be of any use.

Anyway i ended up using this solution, using jquery it will be like this: 

 $("input").focus(function (e) {      
         setTimeout(function(){               
                      AdMob.showBanner(AdMob.AD_POSITION.BOTTOM_CENTER);              
        }, 250)
    }).blur(function (e) {        
        setTimeout(function(){            
               AdMob.showBanner(AdMob.AD_POSITION.BOTTOM_CENTER);              
        }, 250)
    })

it will refresh position of the banner almost in real time, not perfect but good enough effect is not even that bad

**Comment by ozkanyanik** [comment]
@floatinghotpot Is there any solution for this bug yet ? I have same problem.

**Comment by Rickgbw** [comment]
Same issue here.
It occurs when I opened the keyboard quickly, before banner load.

**Comment by Rickgbw** [comment]
Here my workaround while this issue isn't solved:

```js
//put on deviceready event:
var firstLoad = false;
document.addEventListener('onAdLoaded', function(e){
    if(!firstLoad && document.activeElement && document.activeElement.type && document.activeElement.type == 'text') {
        firstLoad = true;
        var callback = function() { 
            this.removeEventListener('blur',callback,false);   
            setTimeout(function() {
                AdMob.showBanner(AdMob.AD_POSITION.BOTTOM_CENTER); 
            },250);
        }
        document.activeElement.addEventListener('blur',callback,false);
    }
});
```

**Comment by alierdogan70** [comment]
if you use ionic-plugin-keyboard this fix the problem, at least for now :)
```javascript
var AdLoaded = false;
var BlackHidden = false;

document.addEventListener('onAdLoaded', function (e) { AdLoaded = true; });
window.addEventListener('native.keyboardhide', keyboardHideHandler);
function keyboardHideHandler(e) {
    if (AdLoaded && !BlackHidden) {

            AdMob.showBanner(AdMob.AD_POSITION.BOTTOM_CENTER);
            BlackHidden = true;
        
    }
}

```

**Comment by floatinghotpot** [comment]
After carefully study, the root cause is identified: 
When focus in input area, the soft keyboard will resize the webview. 
If the ad banner displayed in split mode (overlap:false), it will also resize the webview to avoid overlap the web content. 
If both resize the webview at the same time, this will cause conflict.

When soft keyboard display, it will always try to resize the existing view at bottom. If the banner ad displayed at bottom, it will give up resizing. This issue cannot be resolved perfectly.

Besides the code you guys suggest, here a few workaround methods are suggested to avoid the conflict happen:
1. When you have some input box or textarea on UI, avoid show banner at bottom. You can either hide banner, or show banner at top.
2. Use overlap:true (as the banner will overlap web content, you need reserve some margin area for it.)

BTW, the control lose focus issue has been fixed, after banner displayed, will force focus on webview.
