### ISSUE TITLE
Phonegap Build Failed for Android

### ISSUE THREAD

**Issue by scottopolis** [floatinghotpot/cordova-admob-pro#230]
Hi, thanks for your plugin!

My Android build is failing on PG Build.  I am using the latest version (cli-5.2) and this tag in my config.xml

    <gap:plugin name="cordova-plugin-admobpro" source="npm" />

It does not give me an error message, just "Oh geez, your build failed."

Any recommendations?

**Comment by floatinghotpot** [comment]
Can you get build log from the web page?

cordova-plugin-admobpro use framework tag which requires gradle to build android app, PhoneGap Build yesterday announced that gradle is supported, it should work if it's true.

Or, you can try this one to use legacy jar dependency:
'''xml 
<gap:plugin name="cordova-plugin-admob" source="npm" />
'''

**Comment by floatinghotpot** [comment]
Yes, see Twitter, phonegap build team says: @PhoneGapBuild: Having some issues with the new Android gradle builds! We've reverted to build with ant by default again. Sorry for the hassle.

So, before they resolve it, use this one:
gap:plugin name="cordova-plugin-admob" source="npm"

**Comment by scottopolis** [comment]
That worked, thanks @floatinghotpot !

**Comment by jrm0695** [comment]
Still not working with the pro version while Phonegap Build says it now compiles with Graddle .. 
In admob without pro version, some functions are missing. 
Any solution to make pro version available ?
