### ISSUE TITLE
Publisher id different from mine sometimes.

### ISSUE THREAD

**Issue by TakayukiSakai** [floatinghotpot/cordova-admob-pro#234]
When I monitored my network history between my app with this plugin and AdMob server, I saw very weird request sometimes (about once in 10 times).

```
GET /mads/static/formats/app_promo_ima.js HTTP/1.1
Host: googleads.g.doubleclick.net
Accept: */*
Connection: keep-alive
Proxy-Connection: keep-alive
Cookie: test_cookie=CheckForPermission
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_0 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13A340 (140712042936464)
Accept-Language: en-us
Referer: https://googleads.g.doubleclick.net/mads/gma?submodel=x86_64&cap_noiap=0&ios_base_sdk=9.0&app_name=xxxxxxxxxxx&u_sd=2&hl=en&u_h=667&request_id=2&u_audio=4&cap_bs=1&net=wi&platform=iPhone&u_w=375&format=interstitial_mb&js=afma-sdk-i-v7.5.0&u_so=p&ms=11&an=xxxxxxxxxxxxx&preqs=1&currts=32&seq_num=2&basets=1&output=html&region=mobile_app&u_tz=540&client_sdk=1&ex=1&client=ca-app-pub-6869992474017983&askip=1&_hl=en-us&gsb=wi&num_ads=1&vpt=8&vfmt=18&vst=0&sdkv=o.7.5.0&sdmax=0&dmax=1&sdki=5&swdr=false&caps=interactiveVideo_inlineVideo_mraid1_mraid2_th_autoplay_mediation_av_sdkAdmobApiForAds_di_transparentBackground&_efs=false&forceHttps=true&blockAutoClicks=1&eid=46621136%2C46621051&tcar=2&jsv=188&urll=802
Accept-Encoding: gzip, deflate
```

The part "client=ca-app-pub-6869992474017983" in referrer is very weird, because it's different from my publisher id.
Actually, you can find this publisher id [here](https://github.com/floatinghotpot/cordova-plugin-admob/blob/ea33979d6f5e634c40d8cc662c443576c96f2219/test/index.html).
Given this situation, I'm guessing the publisher id belongs to this plugin's owner.

If so, doesn't it mean that the plugin's owner takes our revenue secretly?

**Comment by floatinghotpot** [comment]
Before using my product, please read and accept the license agreement:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/License-Agreement

If you ship my code within your product, it's very fair either pay for a license, or share a little revenue to cover my effort. Please respect my intellectual property.

**Comment by TakayukiSakai** [comment]
Oh, I didn't notice the license agreement.
I was just afraid that you take our revenue secretly.

Now I understand your license agreement and agree with revenue sharing.

But lastly, please consider to write about revenue sharing on top page README, 'cause the license agreement page is very hard to find.
