### ISSUE TITLE
Fails to compile for Android Phonegap "One of your plugins required the gradle android build tool to build"

### ISSUE THREAD

**Issue by kunal95** [floatinghotpot/cordova-admob-pro#236]
When I try to compile the demo repository (https://github.com/floatinghotpot/phonegap-admob-demo) over phonegap for Android, it fails with following error:
"Error - One of your plugins required the gradle android build tool to build"

**Comment by floatinghotpot** [comment]
Gradle is supported by phonegap build now, but by default it still use ant.

See phonegap build Twitter message: @PhoneGapBuild: gradle builds are working now and can be tested by including the following <preference name="android-build-tool" value="gradle" />

**Comment by floatinghotpot** [comment]
I've updated the demo config.xml as following:
```xml
    <preference name="android-build-tool" value="gradle" /> 
    <gap:plugin name="cordova-plugin-admobpro" source="npm" />
```

Please try again.

**Comment by sdhvlz** [comment]
Hi. Same problem here. When i try to build my app by PGB, i get same error: One of your plugins required the gradle android build tool to build.

Im using in my config
```xml
<preference name="android-build-tool" value="gradle" /> 
<gap:plugin name="cordova-plugin-admobpro" source="npm" />
```
,but  it doesnt work.

In PGB report i get this: 
`BUILD FAILED
/android-sdk/tools/ant/build.xml:573: ../../../../../../android-sdk/com.google.android.gms:play-services-ads:+ resolve to a path with no project.properties file for project /project.`

Any ideas?

**Comment by floatinghotpot** [comment]
it seems the build still using "ant", you can see it in the error message.

**Comment by sdhvlz** [comment]
Yep, but, why? Config pref android-build-tool doesnt work? How can i force PGB build it in gradle?

**Comment by floatinghotpot** [comment]
Only PhoneGap Build guys know that. As I get this from PhoneGap Build official twitter message. See: https://twitter.com/PhoneGapBuild

**Comment by kentmw** [comment]
Did this get resolved? I am still having this issue

**Comment by kunal95** [comment]
Yes, it got resolved. It works perfectly fine now

**Comment by gtouzeau** [comment]
Hello @kunal95 
Could you let us know how did you resolved the issue please ?

**Comment by mariano-aguero** [comment]
@gtouzeau Add this preference and will work

<preference name="android-build-tool" value="gradle" />

**Comment by 1leonkaden** [comment]
Im using in my config

<preference name="android-build-tool" value="gradle" /> 
<gap:plugin name="cordova-plugin-admobpro" source="npm" />
,but it doesnt work.

**Comment by davideng14** [comment]
I added both lines in my config.xml and it doesn't work.

**Comment by 1leonkaden** [comment]
Hello, finally, i found out

this is my config.xml file, it should have all this line phonegap build will work


<preference name="phonegap-version" value="cli-5.2.0" />
<preference name="android-minSdkVersion" value="14" />
<preference name="android-maxSdkVersion" value="23" />
<preference name="android-build-tool" value="gradle" />
<plugin name="cordova-plugin-whitelist" />
<gap:plugin name="cordova-plugin-admobpro" source="npm" />

not know for sure you shoud have this
You also have to add new icon nad splash screen:

Icon size 192x192
Splash screen 960x1600 xxhdpi
Splash screen 1280x1920 xxxhdpi

**Comment by davideng14** [comment]
I had set up the version 3.7.0 and the error dissapear but I have another error different, I'm compiling my app from the web site phonegap.build before the change phonegap-version attribute in the config.xml the code compiled without errors, with the change to cli-5.2.0 is throwing me errors with the splash and icon. I have the next values to these attributes:

<icon src="icon.png" />    
<splash src="splash.png" />

There is an error with png file, I'm uploading the splash.png at the root and the icon.png inside the folder www, to be more clear this is my structure folder.

|--config.xml
|--splash.png
|--|www
|--|--index.html
|--|--icon.png
|--|--lcss
|--|--ljs
 
I appreciate any help!

**Comment by 1leonkaden** [comment]
Hello
This is my config for icon and slash png seen i update to phonegap 5.2.0 
`<icon src="res/icon/android/icon-36-ldpi.png" gap:platform="android" gap:density="ldpi" />
		<icon src="res/icon/android/icon-48-mdpi.png" gap:platform="android" gap:density="mdpi" />
		<icon src="res/icon/android/icon-72-hdpi.png" gap:platform="android" gap:density="hdpi" />
		<icon src="res/icon/android/icon-96-xhdpi.png" gap:platform="android" gap:density="xhdpi" />
		<icon src="res/icon/android/icon-192-xxhdpi.png" gap:platform="android" gap:density="xxhdpi" />
		<icon src="res/icon/android/icon-144-xxhdpi.png" gap:platform="android" gap:density="xxhdpi" />
		<gap:splash src="res/screen/android/screen-ldpi-portrait.jpg" gap:platform="android" gap:density="ldpi" />
		<gap:splash src="res/screen/android/screen-mdpi-portrait.jpg" gap:platform="android" gap:density="mdpi" />
		<gap:splash src="res/screen/android/screen-hdpi-portrait.jpg" gap:platform="android" gap:density="hdpi" />
		<gap:splash src="res/screen/android/screen-xhdpi-portrait.jpg" gap:platform="android" gap:density="xhdpi" />` 

You can see, because my config.xml is in www folder, not alike you, so i put these icon to www/res/icon/android/ and www/res/screen/android/

as you can see, phone gap 5,20 need all this file(png) and put it link to config.xml / i also crate 2 file Splash screen 960x1600 xxhdpi
Splash screen 1280x1920 xxxhdpi

and put it in www/res/screen/android/ too, i dont config 2 file to my config.xml, i dont know why, but since i done this, phonegap build run without error.

Hope this help

**Comment by nelsonBlack** [comment]
if you are using the adobe site to upload and build just delete the app from adobe and rebuild it again with the above changes, this will work for you
