### ISSUE TITLE
App perpetually Increases in size 

### ISSUE THREAD

**Issue by MiLeung** [floatinghotpot/cordova-admob-pro#237]
I believe it may be because I prepare interstitial ads many times through out my app, even when you open the app because I prepare an interstitial in the preload screen.  In Xcode, I can check the container of my app in my device and there's a lot of stuff in the "fsCachedData" folder.  Is there a way to stop my app from getting bigger?

**Comment by floatinghotpot** [comment]
it should be the cached ad resource loaded from ad server. If you hope to minimize the ad resource, try login into your admob portal, change all ad type to text.

**Comment by MiLeung** [comment]
Thank you!  Does the ad cache eventually cap off?  Or will my app keep increasing in size the more you play it?

**Comment by floatinghotpot** [comment]
I am not very sure how the AdMob SDK manage the cache. But I just guess, it won't keep growing the cache size.

You may contact AdMob forum to ask Google staff directly, if you are interested in the internals. https://groups.google.com/forum/#!forum/google-admob-ads-sdk

**Comment by jamesl1001** [comment]
http://stackoverflow.com/questions/6148812/android-admob-causes-memory-leak

This thread suggests fixing the banner ads leak by destroying the ad view: `mAdView.destroy();`

I have tested this on Android by calling `removeBanner();` before closing the app, however the cache still continues to grow.

Does the `removeBanner()` actually call `mAdView.destroy();` internally?
