### ISSUE TITLE
Build Error with Android

### ISSUE THREAD

**Issue by soniyj** [floatinghotpot/cordova-admob-pro#240]
I've added the plugin to a project with different plugins namely:

```shell
com.ionic.keyboard 1.0.4 "Keyboard"
com.phonegap.plugins.facebookconnect 0.11.0 "Facebook Connect"
cordova-plugin-admobpro 2.9.8 "AdMob Plugin Pro"
cordova-plugin-camera 1.2.0 "Camera"
cordova-plugin-console 1.0.1 "Console"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-dialogs 1.1.1 "Notification"
cordova-plugin-extension 1.1.6 "Cordova Plugin Extension"
cordova-plugin-file 3.0.0 "File"
cordova-plugin-geolocation 1.0.1 "Geolocation"
cordova-plugin-network-information 1.0.1 "Network Information"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-vibration 1.2.0 "Vibration"
cordova-plugin-whitelist 1.0.0 "Whitelist"
hu.dpal.phonegap.plugins.SpinnerDialog 1.3.1 "SpinnerDialog"
```

If i try to run **ionic build android**, I get different messages:

```java
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;

Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
```

This is my CLI:
```shell
Cordova CLI: 5.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.5
Ionic App Lib Version: 0.3.9
```

Any idea?

**Comment by floatinghotpot** [comment]
Have you identified which plugin causes the conflict? 

Maybe you can try remove one by one and re-build to find out. Possibly you can start from: 
```
com.phonegap.plugins.facebookconnect
hu.dpal.phonegap.plugins.SpinnerDialog
```

**Comment by soniyj** [comment]
Hello thanks for your response. I will try, in the meantime I did other experiments.

I removed all plugin and all platform, after that I added the android platform and all plugins except the AdMobPro, I built it, and I didn't get any errors.
After that I've added the AdMobPro and I ran the build again and it worked!

I also changed the configuration, android target is always 22 :
```shell
Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.1
Ionic CLI Version: 1.7.0
Ionic App Lib Version: 0.5.1-beta.0
```
```shell
Installed platforms: android 4.0.2
```

It might be a stupid question, but how is it possible that those plugins are in conflict between each other, if they are part of the same system?

I need all of them, so in case I found which one make the conflict, what I should do?

Is there any way to avoid the conflict?

**Comment by floatinghotpot** [comment]
It's good that it works now. 

As to your question, in fact, only a few plugins are developed by apache, other hundreds of plugins are developed by various parties and not tested enough with others, and there is no system to auto test all the plugins together, so there is possibility to cause conflict.

If any conflict, just identify the plugin, and turn to the plugin author for help.

**Comment by soniyj** [comment]
Works just within certain configurations, this is quite annoying because you do not know which one is the correct, I will do more experiments and I will share a "working solution".

I'm aware of it, but a plugin system should be designed in order to simply the integration between different components, if it doesn't work, means that something it's wrong into the design of the plugin system itself.

Thanks for your time, anyway.

**Comment by creakosta** [comment]
Hi!
I would be grateful for any help. I create game on Construct 2 and build on XDK v2548 cordova SLI 5.1.1. for android crosswalk and wp8.1, but no one does not show ads.

**Comment by soniyj** [comment]
@creakosta can you check if the plugin is initialised correctly? printing for example the AdMob var.
```javascript
console.log(AdMob, "OR", window.AdMob);
```
have you set up the banner and/or interstitial?

**Comment by creakosta** [comment]
@soniyj yes, i set set up the banner and interstitial, and they show with old admob plugin with CLI 4.2.1. on android crosswalk and ios. And show with cranberrygame/cordova-plugin-ad-admob with CLI 5.1.1. But no one plugins does not show ads on wp8.1

**Comment by soniyj** [comment]
@creakosta, ok sorry for the stupid question. Unfortunately I never tried cordova on a windows mobile, so I don't have any idea about the error.

**Comment by creakosta** [comment]
@soniyj Thank you to pay attention to my problem) Maybe the creator @floatinghotpot  knows the solution this problem? Specifically about wp8.1 and xdk.

**Comment by soniyj** [comment]
No problem, I hoped to help a bit more. I have to say that cordova's plugins sometimes drive me crazy.
