### ISSUE TITLE
Plugin doesn't work with Ionic View

### ISSUE THREAD

**Issue by grazealous** [floatinghotpot/cordova-admob-pro#243]
I have been trying to get this plugin to work with Ionic View for about three days no to no avail. I have tried to hack it every which way in the application I have already made but I can't get it to work. I can get the ads to work in an emulator or if building directly to the phone, but when I upload to Ionic View, nothing works.

I have even uploaded the demo application to Ionic View, completely out of the box, and it doesn't display ads, banner or interstitial. 

The code I'm using to try to get your demo working is
```
npm install -g cordova
npm install -g plugin-verify
plugin-verify admob-demo-app-ionic
ionic upload
```
When plugin verify runs, both emulators pop open and ads display correctly. When I go onto my mobile device and download the app and view, no ads show up. Is there something I am missing? Can this plugin be used with Ionic View?

````
Your system information:

Cordova CLI: 5.3.3
Ionic CLI Version: 1.7.3
Ionic App Lib Version: 0.5.3
ios-deploy version: 1.8.2 
ios-sim version: 5.0.2 
OS: Mac OS X El Capitan
Node Version: v4.0.0
Xcode version: Xcode 7.0.1 Build version 7A1001 
````

-Nick

**Comment by floatinghotpot** [comment]
Ionic view only upload and download your web content for preview, it will not handle the plugins.

You need build your project into an app and install into your device. Connect your device, then run: 
cordova run ios 
Or, ionic run ios (it actually call cordova CLI)

**Comment by grazealous** [comment]
Oh ok, I was afraid of that. I wish that they would say that in large bolded letters somewhere. I can get it to work no problem using ionic run, thanks for the reply.
