### ISSUE TITLE
Xcode 7 symbol file build generates several warnings due to local file references

### ISSUE THREAD

**Issue by jmelvin** [floatinghotpot/cordova-admob-pro#244]
Using the latest Xcode 7, several warnings are issued while building the application symbol file (.dSYM).  The warnings are due to local file references generated at build time for cordova-plugin-extension/libCordovaGenericAd.a (GenericAdPlugin.o).  Attached is a screenshot showing the warnings.  The app still runs fine, but may not be fully debuggable, etc.  Not sure if this will be an app store submission issue.  Thanks for your consideration.
<img width="844" alt="screen shot 2015-10-22 at 11 46 54 pm" src="https://cloud.githubusercontent.com/assets/5302648/10684222/92cc3a0c-7918-11e5-896f-d14bdbf27e0b.png">

**Comment by robtro** [comment]
same here

**Comment by floatinghotpot** [comment]
Please update the plugin, it's fixed. I did see the warning when verifying the new version.

**Comment by jmelvin** [comment]
Unfortunately, I still see the warnings after upgrading to the latest AdmobPro (2.9.9).  Note: I'm using all default Xcode 7 build settings, except of course Enable Bitcode which is set to 'No'.  Running Xcode 7.1 on OSX Yosemite.  I'd be happy to provide any other info.

$ cordova platform ls -l
Installed platforms: android 4.1.1, ios 3.9.2
$ cordova plugin ls -l
cordova-plugin-admobpro 2.9.9 "AdMob Plugin Pro"
cordova-plugin-ats-rules 1.0.0 "App Transport Security Rules"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-device-motion 1.1.1 "Device Motion"
cordova-plugin-extension 1.2.2 "Cordova Plugin Extension"
cordova-plugin-geolocation 1.0.1 "Geolocation"
cordova-plugin-inappbrowser 1.0.1 "InAppBrowser"
cordova-plugin-network-information 1.0.1 "Network Information"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-whitelist 1.0.0 "Whitelist"

**Comment by floatinghotpot** [comment]
Sorry for the slow follow up, I find some clue from this post:
https://forums.developer.apple.com/thread/17921

Will fix it soon.

**Comment by floatinghotpot** [comment]
Fixed.

**Comment by floatinghotpot** [comment]
Sorry, it appears again, will fix it with following solution, from https://forums.developer.apple.com/thread/17921

Precompile Prefix (GCC_PRECOMPILE_PREFIX_HEADER) = NO
Debug Information Format (DEBUG_INFORMATION_FORMAT) = DWARF with dSYM
Enabled Modules (C and Objective-C) (CLANG_ENABLE_MODULES) = NO
