### ISSUE TITLE
prepareInterstitial always returns "Error" even no problem on android

### ISSUE THREAD

**Issue by balicekt** [floatinghotpot/cordova-admob-pro#246]
Hi, 

I have problem with prepareIntertitial. On iOS everything working just fine but on android I can not init interstitial. All the time I call prepareInterstitial I get "Error". Does anyone know where could be a problem? 

it look like a bug. Because the add is loaded without problem but on android is firred ERROR

Thank you for any help. 

TB

**Comment by floatinghotpot** [comment]
Could you please state the steps to re-produce the bug, or any error logs?

**Comment by balicekt** [comment]
yes sure sorry. 

my code looks like this: 

        var prepareInterstitial = function () {
            typeof  AdMob !== 'undefined' && !isPrepare && AdMob.prepareInterstitial({
                adId: admobid.interstitial //ID admob
            }, function (success) {
                console.log('prepared suc');
                isPrepare = true;
            }, function (error) {
                console.log('prepared false '+ error);
                isPrepare = false;
            });
        };

and on android is called error function and in the log I can see: "prepared false Error" but when I call fcn AdMob.showInterstitial(); everything works fine. When I tested on iOS is called success function and everything works fine. 

TB

**Comment by floatinghotpot** [comment]
Yes, you are correct, it's a bug. The prepareInterstitial() now always return error even in fact it succeeds. You can just ignore the error it returns.

Will fix it in next build. Thanks for the bug report.
