### ISSUE TITLE
plugin not working on android 5.0 and higher

### ISSUE THREAD

**Issue by balicekt** [floatinghotpot/cordova-admob-pro#247]
I tried this plugin on android 4.4 and 4.3 and everything is working fine but on android 5.0 and 5.1 is not working at all and I have no idea why I just found in console this: 

"Document was loaded from Application Cache with manifest https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.appcache", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html (0)
I/chromium( 2546): [INFO:CONSOLE(0)] "Application Cache Checking event", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html (0)
I/chromium( 2546): [INFO:CONSOLE(0)] "Application Cache NoUpdate event", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html (0)

Does anyone know what could help me? Thank a lot. 

//EDIT
I even tried to install just this plugin to the clean cordova project without ionic: 

```
cordova create test1 com.rjfun.test1 Test1
cd test1
cordova platform add android

cordova plugin add cordova-plugin-admobpro

rm -r www/*;
cp plugins/cordova-plugin-admobpro/test/* www/;

cordova prepare; 
cordova run android; 
```

and on android 5.0 is not working just alert: 
error: 0, reason: Internal error, adNetwork: AdMob, adType:banner, adEvent:onAdFailLoad. 

in console I can see: 
I/chromium( 1740): [INFO:CONSOLE(12)] "Not allowed to load local resource: file:///android_asset/webkit/android-weberror.png", source: data:text/html,chromewebdata (12)
I/chromium(31371): [INFO:CONSOLE(25)] "No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.", source: file:///android_asset/www/plugins/cordova-plugin-whitelist/whitelist.js (25)

TB

**Comment by floatinghotpot** [comment]
I find some clues from here (someone else post the exact same error): https://groups.google.com/forum/#!topic/google-admob-ads-sdk/q5gK-ahBjTE

```
The Android team is phasing out any access to file based resources. I believe this is being enforced more strongly in L. So any "file://" URLs are likely to fail going forward.
```

But it's weird that admob / android team conflict with each other. There must be some solutions. I will continue study and give you feedback when having further info.

**Comment by floatinghotpot** [comment]
Update: Some explanation here: http: //stackoverflow.com/questions/19997146/kitkat-kills-not-allowed-to-load-local-resource-file-android-asset-webkit-a

> "Not allowed to load local resource" is a security origin error. The KitKat WebView has stronger security restrictions and it seems like these are kicking in. FWIW I tried just loading a file:///android_asset URL and it worked fine.

> Did you call any of the file-related WebSettings APIs (like setAllowFileAccess(false)) by any chance? Are you trying to load the resource from an https: URL?

Seems getting closer... Continue study.

**Comment by floatinghotpot** [comment]
As I cannot reproduce your issue, could you please try the following 2 experiments?

1. Add this line to your ```AndroidManifest.xml```:

```xml
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

2. remove the plugin ```cordova-plugin-whitelist```

Then give me feedback, thanks.

**Comment by balicekt** [comment]
Yes I tried this but it didn't help. I can still see this log in console: 

I/chromium(22479): [INFO:CONSOLE(23)] "No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.", source: file:///android_asset/www/plugins/cordova-plugin-whitelist/whitelist.js (23)
I/chromium(17195): [INFO:CONSOLE(12)] "Not allowed to load local resource: file:///android_asset/webkit/android-weberror.png", source: data:text/html,chromewebdata (12)
I/chromium(22479): [INFO:CONSOLE(25)] "No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.", source: file:///android_asset/www/plugins/cordova-plugin-whitelist/whitelist.js (25)


When I remove whitelist plugin immediately after "cordova run andorid" it start to install by itself again. I also tried to add some meta Content-Security-Policy and this error with "No Content-Security-Policy" dissapeared but I still don't see any add. :( 



But thank you for help.

**Comment by floatinghotpot** [comment]
Can you add this line to your index.html:
```html
<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'"/>
```

**Comment by balicekt** [comment]
Didn't help I also tried some others meta but nothing helped. Still the same error :(

I/chromium(17195): [INFO:CONSOLE(12)] "Not allowed to load local resource: file:///android_asset/webkit/android-weberror.png", source: data:text/html,chromewebdata (12)

**Comment by balicekt** [comment]
Hey I found this article. Maybe could help. 

http://www.eelingshi.com/questions/173715/kitkat-kills-not-allowed-to-load-local-resource-file-android-asset-webkit-a

I will try my best to figure it out. If you found out something please let me know. Thanks

**Comment by balicekt** [comment]
Did you find anything? Because this is my last issue in my app and there is question if I should already send app to appsotre with no support for android 5.0 or wait wait few more days for a solution. But I didn't find out anything. 

And I'm just curious if this plugin is not working to anyone on android 5.0 or just me? 

Thank you for answer. T

**Comment by floatinghotpot** [comment]
Let's seek support from Google AdMob team, it seems that only they can answer this as the AdMob SDK is implemented by them: 
https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android

**Comment by balicekt** [comment]
ok, will you post there this issue like the author of admob-pro or should I do that?

**Comment by floatinghotpot** [comment]
@balicekt Could you please re-try the new version of plugin/SDK to see whether the issue is still there?

Just with a simple tool like this:
```bash
[sudo] npm install -g plugin-verify
plugin-verify cordova-plugin-admobpro
```

**Comment by balicekt** [comment]
Hi, I've just tried.
iOS is working fine, 
android emulator works fine,
other android works fine, 

but android 5.0.1 is not working at all. See attached screen shots. 
![img_2245](https://cloud.githubusercontent.com/assets/6289261/12372156/8e83fffc-bc4d-11e5-839b-22bb052185d6.jpg)
![img_2246](https://cloud.githubusercontent.com/assets/6289261/12372157/8eb51c72-bc4d-11e5-9670-72ba44a98b7c.jpg)

**Comment by floatinghotpot** [comment]
What's your cordova CLI and cordova-android version please?

**Comment by balicekt** [comment]
When I put to the terminal: 
------------------------------
cordova -v 
5.4.1 
-------------------------------
cordova platform version
Installed platforms: android 4.1.1, ios 3.9.2
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, osx, webos

**Comment by calanti** [comment]
Any news on this? I am having the exact same problem. 

cordova version 6.1.0
jdk1.8.0_74

Asus Zenfone 2 (5.0) I get "error: undefined, reason: undefined...." on app open.
Samsung Galaxy S4 (4.4.2) I just get "Unfortunately, <app_name> has stopped." on app open.

Also tried the the test method outlined under "Quick start" that generated "Demo for AdMob Plugin" and none of the app options do anything.

**Comment by balicekt** [comment]
Absolutely nothing. I will try to find another plugin because after one month I didn't find out anything at all and this still not working :(

**Comment by calanti** [comment]
Fortunately for me it was just a rookie error, I renamed "admobid" to "adMobId" but didn't change it when setting my real id's (I was very tired), effectively passing null or undefined to the createBanner method. Since you are getting the same error maybe you could do a quick alert(admobid.banner) before creating, just to make sure you are passing a valid argument.

Otherwise a quick search on github shows there are a few alternative admob plugins, this one is by far the most popular though.

**Comment by floatinghotpot** [comment]
After troubleshooting, some root cause of the "undefined" error is found. 
See: #343 

Are you using jQuery together with the plugin?

If yes, try the solution described in #343
