### ISSUE TITLE
Network Error on 3G/4G network

### ISSUE THREAD

**Issue by hachicom** [floatinghotpot/cordova-admob-pro#251]
Hi,

I added Admob Pro plugin in my phonegap build project, and it works fine when using Wifi, but in 3G or 4G network it doesn't show banners or interstitial. Instead it goes to onAdFailLoad event giving error code 2 and the reason "Network Error". Is there any configuration on config.xml or in the plugin itself that I need to set?

**Comment by hachicom** [comment]
Isn't there any solution? I still have this problem.

**Comment by floatinghotpot** [comment]
I just verified the plugin with wifi off and 4g network on, both banner & interstitial works well.

so, may I ask, do you really have a 3g/4g network connection on your device when testing?

**Comment by floatinghotpot** [comment]
see my screenshot on my iphone6:

![img_3086_small](https://cloud.githubusercontent.com/assets/2339512/11303847/17c27342-8fe0-11e5-97e9-5f20b07ab6b7.jpg)

**Comment by floatinghotpot** [comment]
BTW, are you testing on iOS device or Android device?

**Comment by floatinghotpot** [comment]
You see, here is the screenshot on android phone, also works well.

![admob-android](https://cloud.githubusercontent.com/assets/2339512/11304379/c1b129aa-8fe2-11e5-86eb-baf210b7d61a.jpg)

**Comment by floatinghotpot** [comment]
So I guess you do have a "Network Error" with your 3G/4G network.

**Comment by hachicom** [comment]
Thanks for the response and yes, I have 4G connection during the tests, also I tried an example app in my Android phone and it didn't work either, even though I can access internet normally with this connection. Maybe the network isn't that good, gonna make some tests in other operator network
