### ISSUE TITLE
iOS app crash when calling createBanner()

### ISSUE THREAD

**Issue by bAstimc** [floatinghotpot/cordova-admob-pro#252]
Hi,
I've got a problem after updating my Cordova to 5.3.1 + this plugin to 2.9.9. The App crashes at creating the banner after the showBanner is written in the log.

In CDVAdmobPlugin.m:
![bildschirmfoto 2015-11-06 um 18 41 33](https://cloud.githubusercontent.com/assets/2527400/11004005/10ac13ae-84b6-11e5-91b8-9150e872e692.png)

Does anyone had this problem before on XCode 7?

**Comment by bAstimc** [comment]
Anyone?

**Comment by floatinghotpot** [comment]
@bAstimc it seems that your adId is not set? Can you show me your javascript code?

**Comment by bAstimc** [comment]
Oh I tried it again and it works. I guess there wasn't a plugin up to date at this time.
Thx for answering.
