### ISSUE TITLE
Keyboard close when ad refresh

### ISSUE THREAD

**Issue by ahmadzaki** [floatinghotpot/cordova-admob-pro#253]
Hi,
I've implemented admob in my cordova ionic app. The problem is, if keyboard is open, it will be hidden when the ad refresh. Anyone encounter this problem? Any fix available?

For now, I set the refresh rate to 60 seconds (previously 30 seconds).

**Comment by hotgeart** [comment]
I just tested and yes I've this bug too :angry: . God this plugin is full of bugs. Without this plugin all works fine an with the plugin I've :
+ [Flash app](http://forum.ionicframework.com/t/admob-screen-flash-on-load/25526)
+ [The keyboard hide my input](https://github.com/floatinghotpot/cordova-admob-pro/issues/250)
+ And now this bug

**Comment by ahmadzaki** [comment]
I've no idea what's causing the problem... Ignoring it for now...

**Comment by floatinghotpot** [comment]
When the banner is first time loaded and displayed, it will resize the web view to avoid overlap (if set overlap:false). The UI resize will flash the app once. If the soft keyboard is visible, it will be impacted.

If the banner is already visible, ad content refresh won't cause keyboard to hide. If it happened before, it's fixed, as it's tested in most recent version, and soft keyboard won't be closed.
