### ISSUE TITLE
Failed to build on ios 

### ISSUE THREAD

**Issue by arlindpajaziti** [floatinghotpot/cordova-admob-pro#255]
![ios](https://cloud.githubusercontent.com/assets/9741337/11171741/d07f75d4-8bf7-11e5-8adf-c0576f637938.png)

-i use same code on android and ios  = in android it build without problems and in ios it show me this(see image)
if i remove plugin it is building normaly

![ios2](https://cloud.githubusercontent.com/assets/9741337/11171769/bd1bff70-8bf8-11e5-968f-aa7ca228a56e.png)
![ios3](https://cloud.githubusercontent.com/assets/9741337/11171770/bd21f01a-8bf8-11e5-9350-dee84de426e6.png)

this error happen in lot of apps not just in single app

**Comment by floatinghotpot** [comment]
could you please tell me your version of cordova, plugin, and xcode?

**Comment by arlindpajaziti** [comment]
latest version of admobpro and xcode 5.1.1

**Comment by floatinghotpot** [comment]
This macro is introduced by Apple in newer version of Xcode. My xcode is v7.1.1, it build quite well.

You need upgrade xcode.
