### ISSUE TITLE
Show the first interstitial after N seconds 

### ISSUE THREAD

**Issue by somtam** [floatinghotpot/cordova-admob-pro#257]
Hello everybody, and thanks for this plugin!
On the AdMob console we can decide impr/min for our banner.
I set the option "autoShow: true", in this way my ad shows every, as an example, 1 impr / 5 min.
I would like to know if there's a setting that let showing the first interstitial after N seconds from launching the app, or do we have to do it with setTimeout?

Thanks in advanced for support.

**Comment by floatinghotpot** [comment]
You can decide when to call the prepareInterstitial() and showInterstitial() yourself, just set autoShow:false.

**Comment by somtam** [comment]
Hi! and thanks for answer.
I am asking this to use the natural setting of the ad that it is shown every 5 min, instead using the javascript timeout and interval which consuming a lot.
So probably, for my purpose, the better way is to launch prepareInterstitial() after N seconds and leave the autoShow:true.

**Comment by floatinghotpot** [comment]
the interval in admob console is only for banner to refresh ad.

for interstitial ad, you have to prepare then show, once user dismiss it, you have to repeat prepare & show again.

**Comment by somtam** [comment]
Oh really? I didn't know about that since it is the first time I am going to use AdMob.
Thanks so much for support!
