### ISSUE TITLE
Binary .a wrongly bundled in .app

### ISSUE THREAD

**Issue by colonna-mike** [floatinghotpot/cordova-admob-pro#259]
Hi my app has always been approved at apple I just upgraded to your latest version and now my app is being rejected because of the below issue:

 Invalid Bundle Structure - The binary file 'Family Reunion.app/www/plugins/com.rjfun.cordova.extension/src/ios/libCordovaGenericAd.a' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure.

Invalid Bundle Structure - The binary file 'Family Reunion.app/www/plugins/com.google.cordova.admob/src/ios/GoogleMobileAds.framework/GoogleMobileAds' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure. 

what do I need to do to get around or fix this issue. works great on Android

**Comment by floatinghotpot** [comment]
I think you did something wrong... the .a binary files should be linked but never be in the app.

what tool do you use to build the app?

**Comment by colonna-mike** [comment]
Intel XDK,  Now that you said that I downloaded the src and I'm  I wondering now  if I linked it wrong.
thanks for fixing the title and answer my question quickly. I will try to see what I did and get back to you thanks again. (ps: This always worked for apple in the pass so it through me for a real loop)

**Comment by colonna-mike** [comment]
okay retested it and its something to to with the latest build that Intel XDK uses does not like. so I went back to a older version and I now get a error when installing the plugin   (see attachment)  I'm at a loss here and my app is stuck in limbo.
![capture](https://cloud.githubusercontent.com/assets/5395978/11352120/21169dfc-9200-11e5-8395-e01d201d0031.PNG)
