### ISSUE TITLE
App crashes on installs after adding prepareInterstitial to code with wikipedia app

### ISSUE THREAD

**Issue by souly1** [floatinghotpot/cordova-admob-pro#260]
Hi,
I've been having a weird issue with my app ever since I've added interstitial ads: a new exception appears- able to reproduce only if wikipedia app is installed on device (Exception attached below).
Any idea as to where to start in solving this? aside to asking my users to not install wikipedia app or not use interstitial :P
Tried removing the prepareInterstitial  command and app works, tried removing the create banner which existed code above and return prepareInterstitial and still crashes.
The command i use for interstitial that leads to the crash:
prepareInterstitial({adId:adMobIds.interstitial, autoShow:false});

Thanks

exception:
W/dalvikvm(28718): threadid=1: thread exiting with uncaught exception (group=0x41b1fce0)
I/ActivityManager( 2271): START u0 {act=android.intent.action.VIEW dat=file:///android_asset/www/undefined cmp=org.wikipedia/.settings.LicenseActivity} from pid 28718
W/ActivityManager( 2271): Permission Denial: starting Intent { act=android.intent.action.VIEW dat=file:///android_asset/www/undefined cmp=org.wikipedia/.settings.LicenseActivity } from ProcessRecord{443d9778 28718:com.fitnessmeals.fitnessmealplanner/u0a137} (pid=28718, uid=10137) not exported from uid 10125
E/AndroidRuntime(28718): FATAL EXCEPTION: main
E/AndroidRuntime(28718): Process: com.fitnessmeals.fitnessmealplanner, PID: 28718
E/AndroidRuntime(28718): java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=file:///android_asset/www/undefined cmp=org.wikipedia/.settings.LicenseActivity } from ProcessRecord{443d9778 28718:com.fitnessmeals.fitnessmealplanner/u0a137} (pid=28718, uid=10137) not exported from uid 10125
E/AndroidRuntime(28718): 	at android.os.Parcel.readException(Parcel.java:1472)
E/AndroidRuntime(28718): 	at android.os.Parcel.readException(Parcel.java:1426)
E/AndroidRuntime(28718): 	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2115)
E/AndroidRuntime(28718): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1419)
E/AndroidRuntime(28718): 	at android.app.Activity.startActivityForResult(Activity.java:3424)
E/AndroidRuntime(28718): 	at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:337)
E/AndroidRuntime(28718): 	at android.app.Activity.startActivityForResult(Activity.java:3385)
E/AndroidRuntime(28718): 	at android.app.Activity.startActivity(Activity.java:3627)
E/AndroidRuntime(28718): 	at android.app.Activity.startActivity(Activity.java:3595)
E/AndroidRuntime(28718): 	at org.apache.cordova.inappbrowser.InAppBrowser.openExternal(InAppBrowser.java:346)
E/AndroidRuntime(28718): 	at org.apache.cordova.inappbrowser.InAppBrowser$1.run(InAppBrowser.java:176)
E/AndroidRuntime(28718): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(28718): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(28718): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(28718): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime(28718): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(28718): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(28718): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime(28718): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime(28718): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 2271):   Force finishing activity com.fitnessmeals.fitnessmealplanner/.MainActivity
I/dalvikvm(28835): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.GooglePlayServicesUtil.a
W/dalvikvm(28835): VFY: unable to resolve virtual method 421: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
D/dalvikvm(28835): VFY: replacing opcode 0x6e at 0x000b
W/ActivityManager( 2271): Activity pause timeout for ActivityRecord{42b0ffa8 u0 com.fitnessmeals.fitnessmealplanner/.MainActivity t931 f}
W/BroadcastQueue( 2271): Skipping deliver [background] BroadcastRecord{43c55660 u-1 android.net.wifi.RSSI_CHANGED} to ReceiverList{435f00a8 28718 com.fitnessmeals.fitnessmealplanner/10137/u0 remote:42a98608}: process crashing

**Comment by floatinghotpot** [comment]
I did not find any relationship with this plugin.

Your app is visiting some files obviously not existing: file:///android_asset/www/undefined 

Why your app will call activity from another process? Did your app or the wikipedia app do something wrong?

I/ActivityManager( 2271): START u0 {act=android.intent.action.VIEW dat=file:///android_asset/www/undefined cmp=org.wikipedia/.settings.LicenseActivity} from pid 28718
W/ActivityManager( 2271): Permission Denial: starting Intent { act=android.intent.action.VIEW dat=file:///android_asset/www/undefined cmp=org.wikipedia/.settings.LicenseActivity } from ProcessRecord{443d9778 28718:com.fitnessmeals.fitnessmealplanner/u0a137} (pid=28718, uid=10137) not exported from uid 10125

**Comment by souly1** [comment]
Good question, I have no idea as to what is going on with the Wikipedia plugin, but I do know that I'm not calling any activities in other processes (at least not intentionally).
What I do know this consistently happens when I use the prepareInterstitial with wikipedia app installed. Have emails from users that the same happens and they do not have wikipedia but do additional info.
I'm releasing a version soon where i disabled prepareInterstitial, I'll see if this indeed solves the issue for now...

**Comment by floatinghotpot** [comment]
I just guess, the wikipedia plugin hijack the http protocol in order to jump to wikipedia app. That should be the bug of the wikipedia plugin.

**Comment by souly1** [comment]
OK, so some updates:
* Notice the correction i made able. there is not Wikipedia plugin in play, I meant wikipedia app. once it's installed my app does not work with prepareInterstitial (doesn't event download, showing error 505 for some users, which i do not understand how this happens before app code even runs...)
after the headache of upgrading cordova, attempting v4.1.1 and 5.0.0 of cordova-android, upgrading all the plugins (I'll have to do some major testing for the app later, but one problem at a time) I still have no problem running the app, WITHOUT wikipedia app installed without prepareInterstitial.

What i found so far looking around online did not help. tried changing keys for app since there was a suggestion there can be an issue with it, did not change anything. tried to add export="true" to activities in the config.xml, nothing. tried adding all whitelist approvals for cordova, same output.

commented prepareInterstitial, works. can't get what's going on...

**Comment by souly1** [comment]
Some more updates:
Don't know why I didn't start with this, i presume because interstitial ads worked, but removed wikipedia app and my app works, so far no news.
this time I wrote the method call with the success and failure callbacks, and it fails.
this shows me two errors in the alert depending the method i call:
AdMob.prepareInterstitial(appConfigService.adMobId.interstitial, function(){
                    alert("success");
                }, function(err){
                    alert("failed " + err);
                });
Shows:
<img width="332" alt="screen shot 2015-11-21 at 10 31 48 pm" src="https://cloud.githubusercontent.com/assets/6670452/11320408/1ff433aa-90a0-11e5-8b93-ab7118a06b70.png">

Whereas running:
AdMob.prepareInterstitial({adId:appConfigService.adMobId.interstitial, autoShow:false}, function(){
                    alert("success");
                }, function(err){
                    alert("failed " + err);
                });
Shows:
<img width="192" alt="screen shot 2015-11-21 at 10 37 08 pm" src="https://cloud.githubusercontent.com/assets/6670452/11320427/6ee02474-90a0-11e5-93d4-18fb2aeb1c10.png">

Aside to receiving two different messages this seems weird because i'm calling AdMob.showInterstitial after the failure and it works and shows ad!

Now, looking at logcat there are two weird issues appearing, take note everything seems to be working, I wouldn't check the log if it wasn't for this issue.
Issue 1({adId:.., autoshow:...}):
I/ActivityManager(  479): START u0 {act=android.intent.action.VIEW dat=file:///android_asset/www/undefined (has extras)} from uid 10133 on display 0


Issue 2 (adId directly):

E/PluginManager(18723): Uncaught exception from plugin
E/PluginManager(18723): java.lang.NullPointerException: Attempt to invoke virtual method 'int org.json.JSONObject.length()' on a null object reference
E/PluginManager(18723): 	at com.rjfun.cordova.ad.GenericAdPlugin.execute(GenericAdPlugin.java:195)
E/PluginManager(18723): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:95)
E/PluginManager(18723): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:130)
E/PluginManager(18723): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
E/PluginManager(18723): 	at org.crosswalk.engine.XWalkExposedJsApi.exec(XWalkExposedJsApi.java:40)
E/PluginManager(18723): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
E/PluginManager(18723): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
E/PluginManager(18723): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/PluginManager(18723): 	at android.os.Looper.loop(Looper.java:135)
E/PluginManager(18723): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by souly1** [comment]
@floatinghotpot , What would you recommend as next steps?

**Comment by marcusds** [comment]
I am also running into this issue, hopefully a fix can be delivered.

**Comment by floatinghotpot** [comment]
the prepareInterstitial() has a bug and always return error even success, I will fix it soon. as no negative impact, you can simply ignore it now.

valid args should be an object, ```AdMob.prepareInterstitial({ adId: 'your_ad_unit_id' }, ...)```, will fail if pass string as arg only. however, I think passing a string is reasonable, and I will change to accept it later.

**Comment by souly1** [comment]
Can the error message be more informative? after the fix I will run it again and see it it gives better clues as to why app crashes with wikipedia app.

P.S has anyone else checked the bug out? download the wikipedia app and run your app with this plugin, do you reach the same failures?

**Comment by souly1** [comment]
Don't know what it was, but I can confirm issue is solved
