### ISSUE TITLE
Error when install in intel XDK 2727

### ISSUE THREAD

**Issue by xai1985** [floatinghotpot/cordova-admob-pro#261]
Hi, i try to install it in intel xdk 2727 the last version, try with cli4.1.2 and 5.1.1 and gives install error, with my own proyect, and with template proyects... Any idea why?

**Comment by xai1985** [comment]
I am adding it using add a third party plugin and writing com.google.cordova.admob, it choose the last version but when i build it in Crosswalk android it gaves the error...

**Comment by xai1985** [comment]
Don't know what is ther problem but i can solve it downloading the plugin to my computer and uploading direct into the Intel XDK from my computer.

**Comment by floatinghotpot** [comment]
It seems that the Cordova registry has been closed in Oct or Nov. XDK used to load plugin from Cordova plugin registry, but in May this year, Cordova team announced to phase out their own registry and moved to npm registry. Hope XDK team can support loading plugin from npm registry soon.
