### ISSUE TITLE
removeBanner() VS hideBanner()

### ISSUE THREAD

**Issue by somtam** [floatinghotpot/cordova-admob-pro#263]
Hello everybody,
performance speaking is it better to hide a banner, or to remove and create it every time it is shown?
In case the hide solution is better, does the banner stay somewhere in memory so we have to update the impression from the AdMob console, right?
thanks for support!!

**Comment by floatinghotpot** [comment]
Usually you only need call createBanner() to display the banner, either removeBanner() or hideBanner() is rarely used, as only banner viewed and clicked, it will bring you revenue.
