### ISSUE TITLE
ios build error - plugins confilcts ?

### ISSUE THREAD

**Issue by boten** [floatinghotpot/cordova-admob-pro#265]
hi i just installed the plugin.
i can see in my plugins list:

cordova-plugin-admobpro 2.9.9 "AdMob Plugin Pro"
cordova-plugin-extension 1.2.2 "Cordova Plugin Extension"

but i cant build ios any more ?
error:
"ld: library not found for -lCordovaGenericAd
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

i am using
ionic 1.1.1
 cordova 5.4.0
xcode 7.1.1

if any one can help :)

p.s: android build is ok

**Comment by floatinghotpot** [comment]
Sometimes cordova CLI may miss some files by mistake with unknown reason.

Try refresh the stuffs for ios platform in your project like this:
```bash
cordova platform remove ios;
cordova platform add ios;
```
