### ISSUE TITLE
 adSize: 'CUSTOM' height, with 100% device width ?

### ISSUE THREAD

**Issue by boten** [floatinghotpot/cordova-admob-pro#267]
hi
i want to change the banner height only (not the width , that will remain 100% of device)

i tried :   
adSize: 'CUSTOM',
width: screen.width, 
height: 50, 

but when i change device ordination the banner width is wrong?
is there a way to only effect the banner height but still making the banner fit 100 % of the device width?
the reason is because on tablets the banners hight is huge.
thankx

**Comment by floatinghotpot** [comment]
You should use ```adSize:'SMART_BANNER'```. 

Or else, you have to detect the screen orientation change and set the ad size again.

**Comment by boten** [comment]
unfortunately adSize:'SMART_BANNER' does give the correct screen width, but the banner hight is to big. is there a way to change SMART_BANNER to height: 50 hard coded into the code  ?

**Comment by floatinghotpot** [comment]
Almost all the Ad networks are following the IAB (Interactive Advertising Bureau) standards. Here are the standards for ad:
https://en.wikipedia.org/wiki/Web_banner#Standard_sizes

If you want fully customized sizes, as I mentioned, you need detect orientation change, then set the ad size again.
