### ISSUE TITLE
change banner margins color 

### ISSUE THREAD

**Issue by boten** [floatinghotpot/cordova-admob-pro#268]
hi 
is there a way for me to change the margin between the banner and my app ?
screen shot attached 
its weird  having white margins left and right to the banner 
if the banner is not 100% width 

i tired :  
bannerOptions = {
            adId:key,
            position:admob.AD_POSITION.BOTTOM_CENTER,
            overlap: true,
            autoShow:false,
            adExtras : {
              color_bg: 'FF6347',
              color_bg_top: 'FF6347',
              color_border: 'FF6347',
              color_link: 'FF6347',
              color_text: 'FF6347',
              color_url: 'FF6347'
            }

but its not working ?

![margins](https://cloud.githubusercontent.com/assets/6900130/11719198/4b47304a-9f62-11e5-9151-3c25d7a49342.png)

**Comment by technotip** [comment]
..any fix for this?

**Comment by floatinghotpot** [comment]
It's now controlled dynamically in your admob portal:

See:
https://github.com/floatinghotpot/cordova-admob-pro/issues/322
