### ISSUE TITLE
Mach-O Linker Error – linker failed exit code 1 duplicate symbols – when building to device not emulator

### ISSUE THREAD

**Issue by jimbergman** [floatinghotpot/cordova-admob-pro#273]
Project build fails to link project after build ONLY WHEN BUILDING FOR DEVICE, NOT EMULATOR.

Happens with my app, and also with your **plugin-verify** app.
Runs great in the iOS Simulator, fails when building to device.
Using Cordova 5.4.1, Xcode 6.2, OSX Mavericks 10.9.5

This is the error in Xcode:
28 duplicate symbols for architecture arm64
Linker command failed with exit code 1 (use -v to see invocation)
Activity Log Complete - 1 error

![screenshot 2015-12-16 00 26 48](https://cloud.githubusercontent.com/assets/1404273/11836403/62c1d000-a38f-11e5-8a2c-cf285d1edc0c.png)

Thanks for your help with this. Appreciate your work building this Cordova plugin.

Complete Build Log errors for plugin-verify building to iPad Mini 2:

Ld /Users/JimB/Library/Developer/Xcode/DerivedData/Demo-fvmgjahuxpjgbchijwnxxvtnezvq/Build/Products/Debug-iphoneos/Demo.app/Demo normal arm64
    cd /Users/JimB/Dev/build/tmp/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.2.sdk -L/Users/JimB/Library/Developer/Xcode/DerivedData/Demo-fvmgjahuxpjgbchijwnxxvtnezvq/Build/Products/Debug-iphoneos -L/Users/JimB/Dev/build/tmp/platforms/ios/Demo/Plugins/cordova-plugin-extension -F/Users/JimB/Library/Developer/Xcode/DerivedData/Demo-fvmgjahuxpjgbchijwnxxvtnezvq/Build/Products/Debug-iphoneos -FDemo/Plugins/cordova-plugin-admobpro -filelist /Users/JimB/Library/Developer/Xcode/DerivedData/Demo-fvmgjahuxpjgbchijwnxxvtnezvq/Build/Intermediates/Demo.build/Debug-iphoneos/Demo.build/Objects-normal/arm64/Demo.LinkFileList -dead_strip -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=7.0 -framework AssetsLibrary /Users/JimB/Library/Developer/Xcode/DerivedData/Demo-fvmgjahuxpjgbchijwnxxvtnezvq/Build/Products/Debug-iphoneos/libCordova.a -framework CoreGraphics -framework StoreKit -framework MobileCoreServices -lCordovaGenericAd -framework GoogleMobileAds -framework AdSupport -framework AudioToolbox -framework AVFoundation -framework CoreLocation -framework CoreTelephony -framework EventKit -framework EventKitUI -framework Foundation -framework MessageUI -framework QuartzCore -framework SystemConfiguration -framework UIKit -Xlinker -dependency_info -Xlinker /Users/JimB/Library/Developer/Xcode/DerivedData/Demo-fvmgjahuxpjgbchijwnxxvtnezvq/Build/Intermediates/Demo.build/Debug-iphoneos/Demo.build/Objects-normal/arm64/Demo_dependency_info.dat -o /Users/JimB/Library/Developer/Xcode/DerivedData/Demo-fvmgjahuxpjgbchijwnxxvtnezvq/Build/Products/Debug-iphoneos/Demo.app/Demo

duplicate symbol l017 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADBannerAdViewDelegate.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADRewardBasedVideoAd+Mediation.o)
duplicate symbol l018 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADCSITimeRecorder.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADRewardBasedVideoAd+Mediation.o)
duplicate symbol l008 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADNativeAdAttributionView.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADPushTransitionView.o)
duplicate symbol l014 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADPinger.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdAppViewController.o)
duplicate symbol l016 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADBannerAdViewDelegate.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADNativeAdImage.o)
duplicate symbol l005 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADMWebViewRenderedChecker.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdViewRenderedChecker.o)
duplicate symbol l006 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADMWebViewRenderedChecker.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdViewRenderedChecker.o)
duplicate symbol l012 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADCSI.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADCSIReporter.o)
duplicate symbol l009 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADInterstitialPool.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdView+VideoAdditions.o)
duplicate symbol l010 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADInterstitialPool.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdView+VideoAdditions.o)
duplicate symbol l022 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADLocation.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADMAdapterHTML.o)
duplicate symbol l023 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADLocation.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADCSIConfiguration.o)
duplicate symbol l016 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADBannerAdViewDelegate.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdNetworkJavaScriptAdViewDelegate.o)
duplicate symbol l017 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADBannerAdViewDelegate.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdNetworkJavaScriptAdViewDelegate.o)
duplicate symbol l002 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdViewTouchGestureRecognizer.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAbsoluteTime.o)
duplicate symbol l018 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADCSITimeRecorder.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADMRAIDPicture.o)
duplicate symbol l021 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADLocation.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADMRAIDResizeProperties.o)
duplicate symbol l022 in:
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADLocation.o)
    Demo/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADMRAIDResizeProperties.o)
ld: 28 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by AjinkyaKher** [comment]
Any updates on this? I am facing the exact same issue!!

**Comment by jimbergman** [comment]
I was partially able to solve this problem. I got rid of the duplicate symbols error by removing the "-ObjC" linker flag from the "Other Linker Flags" section of build settings (see http://stackoverflow.com/a/32490158/1678813).

This caused an "unrecognized selector" when building in Xcode, which is then solved by adding "-force_load $(BUILT_PRODUCTS_DIR)/libCordova.a" to "Other Linker Flags" (see http://stackoverflow.com/a/27240779/1678813). I also had to add "-force_load "yourprojectname/Plugins/cordova-plugin-extension/libCordovaGenericAd.a" (replacing yourprojectname with the actual name of your project).

So with both of those problems solved, by app would build successfully, except now the problem was the banner ad would appear just a pixel or three below my app screen. Interstitials worked just fine.

At this point I gave up and used this plugin instead (which worked great, no problems): https://github.com/appfeel/admob-google-cordova

**Comment by floatinghotpot** [comment]
I double verified this plugin, it has no problem.

You need upgrade your Xcode to 7.x to make it work.

This plugin is always up to date with Google most recent AdMob SDK, current iOS version is v7.6.0. I think it's built with Xcode 7.

The other plugin you mentioned, is using Google AdMob SDK v7.3.1, which is already out of date.
