### ISSUE TITLE
Admob Pro Ad Mediation - mmedia 

### ISSUE THREAD

**Issue by angusykl** [floatinghotpot/cordova-admob-pro#275]
Hello There, 

I was trying to add the mediation plugin for mmedia. After adding the plugin, it failed to build the ios version of my cordova app. 

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_GADAdMobExtras", referenced from:
      _OBJC_CLASS_$_GADMillennialExtras in libAdapterMillennial.a(GADMillennialExtras.o)
  "_OBJC_METACLASS_$_GADAdMobExtras", referenced from:
      _OBJC_METACLASS_$_GADMillennialExtras in libAdapterMillennial.a(GADMillennialExtras.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could you please take a look? 

Thanks!

**Comment by floatinghotpot** [comment]
Duplicated, as it's same thing as #254.
