### ISSUE TITLE
How to show interstitial with this plugin?

### ISSUE THREAD

**Issue by xai1985** [floatinghotpot/cordova-admob-pro#276]
Hi, i've tried everything that occurs to me and is not working, also try with the easy show tutorial that Rymond Xie shows in the part where you can download it and nothing, also use the .js attached and call it into my index.html of my proyect and nothing, i'm using html5+cordova in intel XDK2727, i was able to show the normal banner, but not the interstitial, not in any way.... And i can't find any example with the insterstitial working with this pluggin so i can see if i'm doing something wrong... Can anybody help me? If i just see it working i'll how to :S

**Comment by floatinghotpot** [comment]
Did you create another ad unit id for interstitial?

You can use my default index.html under test/ folder for testing purpose.

**Comment by xai1985** [comment]
Sorry, i have solved the problem :P, 3 weeks with the problem and the day i decide to write it here for help i solve it XD. Thanks anyway

**Comment by xai1985** [comment]
you can close it :D

**Comment by floatinghotpot** [comment]
What's the root cause of your problem, and how you resolve it?

**Comment by xai1985** [comment]
It was me, seems that i didn't realice that i have to write:
<script type="text/javascript" src="admob.js"></script>
instead of:
<script src="admob.js"></script>
because seems that if not it didn't realice it's javascript text and didn't load it correctly :S
