### ISSUE TITLE
How to get size of smart banner displayed

### ISSUE THREAD

**Issue by mxuko** [floatinghotpot/cordova-admob-pro#277]
Is there a way to find out the size of the banner being displayed when I use the SMART_BANNER?

Perhaps as a callback in "AdMob.createBanner" or as an "onAdLoaded" event.

**Comment by floatinghotpot** [comment]
No API is provided to retrieve the ad size, but you can detect your device orientation and calculate the size. See admob size supported by AdMob: https://support.google.com/admob/answer/3098666?hl=en
