### ISSUE TITLE
Intermittent 404 page from the ad network in Cordova WebView (iOS)

### ISSUE THREAD

**Issue by greg84** [floatinghotpot/cordova-admob-pro#278]
I have a Cordova app that has two ".html" pages. It's possible to navigate between these pages using a button on each page.

The app has a banner ad at the bottom of the screen. If I continually press the buttons that switch between the two HTML pages, eventually the app attempts to load the page relative to the *ad's* base URL inside the Cordova WebView. You end up looking at a 404 page from the ad provider, with the ad still displayed at the bottom:

![image](https://cloud.githubusercontent.com/assets/4529974/11961813/026901ee-a8d3-11e5-8c71-4e22d3f5b253.png)

This is tricky to reproduce, but if you make an app with two pages, and quickly switch between them over and over, eventually you'll see what I mean. I was unable to reproduce the behavior in Android, so it seems only iOS is affected.

I'm using version 2.10.0 of the plugin.

Looking at the log, it seems that it happens when I try to navigate as the ad is loading. Specifically, check out the page that it's loaded - authority-wide.html is a page in my app, but it's trying to load it in the main WebView!

    2015-12-22 17:37:42.891 createBanner
    2015-12-22 17:37:43.290 AdMob, onAdLoaded, {'adNetwork':'AdMob','adType':'banner','adEvent':'onAdLoaded'}
    2015-12-22 17:37:43.339 Resetting plugins due to page load.
    2015-12-22 17:37:43.725 Finished load of: https://googleads.g.doubleclick.net/mads/authority-wide.html

On each page I call `createBanner`, and I'm guessing when the page changes and the previous banner hasn't finished being created, it causes a problem calling the same method again?

**Comment by floatinghotpot** [comment]
It's a bad idea to use multiple html pages in a cordova app. When you navigate frequently, every time you reload the html page, it will re-initialize the plugins, which is definitely wrong.

Cordova app should be a single html page app, and you need learn how to update part of the page content instead of reloading it.

**Comment by greg84** [comment]
Thanks for replying. I use my own navigation framework on each html page, which switches between the different "screens". It works well. The reason I've split the app up into multiple pages is because each page is a different logical section of the app. There's a primary "selection" screen, then two "main" screens - one for phones and one for tablets.

The app is already available for download, but in the current version I'm using a native AdMob implementation. I've upgraded the app to use this plugin instead, so I don't have to keep fiddling with the native implementations when the SDK gets updated.

**Comment by greg84** [comment]
I have a selection screen and a main screen. Each one uses my own navigation framework to display various sections, along with KnockoutJS to load data from the server.

I split the pages up because they're different sections of the app.

During normal use it would be unusual for a user to switch between the "selection" and "main" screens, especially quickly enough to reproduce this issue, so I'm not overly concerned about submitting the update.

It would be useful if I could find out whether a banner has been created, and only create one if there isn't one there already. Although I've been looking at the iOS native code and can't really understand how it works! For example, what invokes methods such as `__showBanner`, and where's the implementations of `GenericAdPlugin`?

**Comment by greg84** [comment]
I've managed to implement a workaround. My default page is 'start.html', which clears a localstorage value called `adsinit`. When the user hits their first page (which depends on their preference and whether they're using a tablet or not), the app only calls `createBanner` if `adsinit` is empty. This ensures that the app only creates the banner once.
