### ISSUE TITLE
Game FPS drop when AdMob banner showing

### ISSUE THREAD

**Issue by matrixreal** [floatinghotpot/cordova-admob-pro#279]
Hi,
i use intel xdk trying with cli 4.1.2 and CLI 5.1.1 ... with and without the wkwebplugin
my game is runing good but when i call banner it show but the game start to be laggy 
any advise please ?
thanks

**Comment by floatinghotpot** [comment]
Try login to your admob portal, set your ad unit id to use text ad only.

**Comment by matrixreal** [comment]
@floatinghotpot 
hi,
already try it before ... still same

**Comment by floatinghotpot** [comment]
How much is the impact on FPS drop?

Maybe you can consider using interstitial ad instead of banner. Not always show the banner, but pop up the interstitial ad at end of level. I guess it will reduce the impact.

**Comment by matrixreal** [comment]
@floatinghotpot 
good approch ... but by the analytics ... i got better revenue from banner that's why i'm focused on

**Comment by floatinghotpot** [comment]
really?! as I know, interstitial ad has 5-10x RPM value... you can trust your conclusion if has data support.

**Comment by matrixreal** [comment]
yes, strange ... but my users like my banner and not my interstitials
intersitial are show on game over scene
banner all time
![admob](https://cloud.githubusercontent.com/assets/6823974/11997594/335eb0ba-aa80-11e5-9813-e205d8509b6d.png)

**Comment by floatinghotpot** [comment]
After some investigation, I found that the FPS issue caused by banner is quite common, here you can find some discussion in AdMob official forum:
* https://groups.google.com/d/msg/google-admob-ads-sdk/pBCrFaqLhsA/wGI23cfKEBUJ
* https://groups.google.com/d/msg/google-admob-ads-sdk/tML31YEbo90/i-fmr3zd3aAJ

So there is nothing I can do from plugin perspective.

As suggested by Andrew from AdMob team:

> Banner ads (from any provider) can sometimes require significant resources to load and display, and as you saw they can negatively impact game performance, especially on older devices.  There really isn't any way around this fact.

> For this reason, AdMob recommends placing banners on pause screens, end-of-level screens, and so on -- screens that are displayed when the user isn't actively playing the game.  This will help your framerate, and has the added bonus of a better CTR, since users are less likely to tap on an ad (even one they're interested in) if they're actively playing a game.

> See our best practices for game developers for more info on these topics.
