### ISSUE TITLE
Interstitial Ad after resume event

### ISSUE THREAD

**Issue by soachishti** [floatinghotpot/cordova-admob-pro#283]
I'm using this plugin in Ionic/Cordova app.
I'm trying to show ad after resume event. It works fine. but after calling AdMob.showInterstitial(), it call resume and pause event again which is causing repeated showing of ad. I have tried commenting AdMob.showInterstitial() then no repeated resume events is fired.

I'll look forward to hearing your thoughts on this.

Here is the code.
```
document.addEventListener("deviceready", function() {

       if(AdMob) {
		AdMob.prepareInterstitial( {adId:admobid.interstitial, autoShow:false} );
	}
	else {
		console.log("AdMob not found");
	} 
		
	document.addEventListener("resume", function() {
		console.log("resume event");
		if(AdMob) AdMob.showInterstitial()
	}, false);
});
```

**Comment by floatinghotpot** [comment]
It's weird, because the admob plugin only listen the pause/resume event, to pause/resume the banner ad refresh, but will not fire the event itself. I will test this.

**Comment by soachishti** [comment]
Thanks for the response. It would great that I get fix. However currently I am handling the issue like this.

```
if(AdMob) AdMob.prepareInterstitial( {adId:admobid.interstitial, autoShow:false} );

document.addEventListener("resume", showInterstitialAd, false);
var adShowed = false;
function showInterstitialAd() {
	if (adShowed == false) {
		adShowed = true;
		if(AdMob) AdMob.showInterstitial();					
	}
	else adShowed = false;
}
```

Hope this will help other.

**Comment by floatinghotpot** [comment]
Thanks for the bug report. It's now fixed. 

You can find the test case in the index.html:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/test/index.html#L176

**Comment by soachishti** [comment]
Thanks.
