### ISSUE TITLE
size of ad?

### ISSUE THREAD

**Issue by kevinleequinn** [floatinghotpot/cordova-admob-pro#284]
using createBanner I would like to determine the size of the banner that was displayed (i.e. SMART_BANNER).

is that somehow passed to success?

**Comment by floatinghotpot** [comment]
You cannot tell the size of Ad when creating it. When the device orientation changes, the ad size also changes.

You can try detecting orientation changes, then calculate the ad size yourself. 

Here are the size of AdMob banners:
Screen width x 32|50|90	Smart Banner	Phones and Tablets	SMART_BANNER

See more details here:
https://developers.google.com/admob/android/banner?hl=en
