### ISSUE TITLE
Using cordova , Ads is not Working for wp8.

### ISSUE THREAD

**Issue by Prav92** [floatinghotpot/cordova-admob-pro#285]
I just follwed issue #47 and #84, i follwed all the instruction mentioned in the plug-in.But still i got the blank space and got a same issue mensioned in issue #47 by @ricardobarrospereira. please help me.

**Comment by floatinghotpot** [comment]
Please describe your environment and versions.

**Comment by Prav92** [comment]
I am using cordova 5.4.0 and wp8.1. i tried with older version admob plugin its working fine but i don't give the position for that ads.
