### ISSUE TITLE
Android build problem

### ISSUE THREAD

**Issue by rubossq** [floatinghotpot/cordova-admob-pro#291]
Hi!
I have a problem with cordova CLI. When i try to launch a "quick-start" project i have next exceptions
![image](https://cloud.githubusercontent.com/assets/16590371/12336366/dc4ddede-bb0c-11e5-83e9-8d3e7e753e0a.png) Thanks very much!

**Comment by floatinghotpot** [comment]
You did not install Google play services lib & repo, please open android SDK manager to install it.

**Comment by rubossq** [comment]
@floatinghotpot Thanks! Now it works fine =)
