### ISSUE TITLE
Rate limiting not being honored 100% of time

### ISSUE THREAD

**Issue by Createstandard** [floatinghotpot/cordova-admob-pro#292]
Admob allows you to rate limit your ads, however it does not work 100% of the time when using this plugin. You can try this on your own, just add an interstitial on the "resume" event in Cordova on IOS. 

$(document).on("resume", function () {
         AdMob.prepareInterstitial( {adId:app.config.adMobInterstitial, autoShow:true} );
});

What happens is that if this call get's made too many times very quickly, it still shows the ad. Try it yourself, just click on the ad and come back to the app really fast or close the app with the ad shown, when you open it back up another ad will appear. 

The only way I can fix it is to put a set timeout and do a mini rate limit of my own in there to wait 10 seconds or something before calling it again - but doesn't this defeat the purpose of the rate limit on the API? This also doesn't always persist when the app is resumed. Is this session based on the GAPlugin session? If you init that on resume, does it kill this rate limi session?

If the rate limiting is based on session, which I think get's dropped sooner than what the API will let you configure. It also leads me to believe that perhaps there is a session issue and that maybe there are multiple sessions going on in the app at the same time if you fire this off really fast within a few seconds of each other.

I'm still uncertain at the exact way this plugin and Admob handle the rate limiting so if someone could elaborate on this we could come up with a more elegant solution and proper place to fix it in the architecture. 

It seems like the rate limiting should be on device ID instead of on session ID. It is not real clear on the Admob UI what exactly this rate limiting means.

**Comment by Createstandard** [comment]
In addition, this is IOS - on Android the resume event is fired off several times and you can't call it on that. The fact still stands, though there has to be a minimum amount of time in which to call this thing that doesn't honor rate limiting - so whatever that is let me know so I can wait the appropriate time or we can build it into the plugin to wait that time.

**Comment by floatinghotpot** [comment]
Thanks for the info, I never tried the time rate feature before, and of course did not control or cache it in plugin code. Not clear how or whether AdMob SDK handled it or not.

I will ask Google team for this. meanwhile, before get the answer, you can write some logic in your JavaScript to control the time rate.

**Comment by Createstandard** [comment]
Ok great, thanks. The the only thing I can think of is that GAPlugin exit() on pause and intit() on resume before this ad call is creating a new session but it doesn't really explain why it would do it 3 times then stop which happened today. Maybe there is something with resuming the app that is killing the session between the Cordova and Admob.
