### ISSUE TITLE
Event 'onAdDismiss' never trigger (interstitial)  - AdMob

### ISSUE THREAD

**Issue by escolhatecnologia** [floatinghotpot/cordova-admob-pro#293]
Why event  'onDismiss' never trigger ??
When  click close ad "X"   'onDismiss'  doesn't  fire 

```javascript
        document.addEventListener("onAdDismiss", function(data) {
            //never fire
        });

```

Phonegap: 4.2.0-0.24.1  
Android: 6.0.1
cordova-admob-pro:  last version

**Comment by davidfig** [comment]
Not sure what caused the OP's problem, but I ran into a similar problem. I caused it by calling prepareInterstitial() before onAdDismiss triggered. You have to wait until the onAdDismiss is triggered before calling the next prepare.
