### ISSUE TITLE
Non-closable rewarded media ad

### ISSUE THREAD

**Issue by Ajaxy** [floatinghotpot/cordova-admob-pro#294]
Thank you for plugin.
Is it possible to show full-screen ad (interstitial) without close button and to catch some event when the add is done (video is finshed)? I want to honor users with in-app valuables for watching video ads.

**Comment by floatinghotpot** [comment]
No, it's not allowed. Google's policy is never force user to do something, so you should give user the freedom to close the Ad if not attractive at all.

**Comment by floatinghotpot** [comment]
BTW, the close button is implemented by Google's AdMob SDK, not by my plugin code.

**Comment by Ajaxy** [comment]
Okay, and what about some event to figure out the end of the video?

**Comment by floatinghotpot** [comment]
Unfortunately, the AdMob did not provide such event. You can see the available events available here:
https://developers.google.com/admob/android/ad-events

They have been exposed as plugin javascript API already.
