### ISSUE TITLE
black box where keyboard should be

### ISSUE THREAD

**Issue by MazzMazz** [floatinghotpot/cordova-admob-pro#295]
I think this problem should have been solved by now. Or at least a thought a read it in an issue that it is solved.

My bannerSettings are like this

```javascript
AdMob.createBanner({
          adId: admobid.banner,
          isTesting: false,
          autoShow: true,
          position: AdMob.AD_POSITION.BOTTOM_CENTER,
          bgColor: 'black'
        });
```

If the banner is loaded properly (is showing), and the user opens the keyboard (e.g. clicking in an input field) it's working fine.
However if the user opens the keyboard, before the banner is shown, and the banner starts to show while the keyboard is open i got this problem. The keyboard turns black  and the user can't remove it until restart of the app.

**Comment by floatinghotpot** [comment]
This issue has been resolved, please update the plugin ```cordova-plugin-admobpro``` and its dependency ```cordova-plugin-extension```.

**Comment by MazzMazz** [comment]
cordova-plugin-extension wasn't up-to-date
