### ISSUE TITLE
Is there any way to pass key-values to DFP for targeting ADs?

### ISSUE THREAD

**Issue by eleva** [floatinghotpot/cordova-admob-pro#298]
Hi,
DFP allows targeting ADs: it could serve ADs based on defined key-values (as age, gender or preferences).

Reference here: https://support.google.com/dfp_premium/answer/188092
Android https://developers.google.com/mobile-ads-sdk/docs/dfp/android/targeting
IOS https://developers.google.com/mobile-ads-sdk/docs/dfp/ios/targeting

Does this plugin allow us to pass key-values to DFP for targeting AD?
Is there any way to achieve this?

Thank you,
Best regards

**Comment by floatinghotpot** [comment]
It's not able to do this yet, but it's possible to add this feature in near future. 

What's your use case for this feature?

**Comment by eleva** [comment]
Hi,
this is needed when you profile users in apps (basically they have preferences and settings), and you need to target ADs for them, passing those preferences to DFP to let it choose the right AD to serve.

Let me explain with a simple use case: there are two different group of users, one tagged as "sailors" and the second one tagged as "phisician". They should see different ADs that match their interest. DFP can serve them different ADs if you pass the value for the key "job" (previously mapped in DFP console, serve AD X for job="sailors" while serve AD Y for job="phisician"). Plugin needs a way to pass key-values to DFP.

Android and IOS reference seems to show how native code should work.
Maybe it should exist a function named addCustomTargeting(key,value) where value can be string or array of string. 

AdMob.addCustomTargeting("job","sailor");
AdMob.addCustomTargeting("age", ["24", "25", "26"]);

or a dedicated preference when creating banner

AdMob.createBanner( {
    adId: admobid.banner, 
    position: AdMob.AD_POSITION.TOP_CENTER, 
    customTargeting: {
          job: "sailor",
          age: "23",
          interest: ["boats","ports"]
    }
} );

**Comment by floatinghotpot** [comment]
Thanks for explanation. I'd rather re-use the existing API:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/1.2-Method:-AdMob.setOptions()

Like:
```javascript
AdMob.setOptions({
  customTargeting: {
    job: "sailor",
    age: "23",
    interest: ["boats","ports"],
  },
});
```

As options can be passed to createBanner() and prepareInterstitial(), your second proposal is great.

Will find time to implement this, but I cannot give a schedule.

**Comment by eleva** [comment]
Cool, 
I'll just wait for some news here (asap for you please!). 
I think this is a must-have feature to use plugin with DFP, since everyone using DFP will search a way how to targeting users.

Thanks in advance for your time!

**Comment by eleva** [comment]
Is there any news about this?
Thank you.

**Comment by Papipo** [comment]
I am also interested in this feature. In my case the app is the official application of a famous blogger and I want the ads to be relevant, otherwise I can get some ugly ones and it's a matter of reputation of the public figure.

**Comment by floatinghotpot** [comment]
See docs:
https://github.com/floatinghotpot/cordova-admob-pro/tree/master/docs#targetting-options

**Comment by eleva** [comment]
Great job!
Thank you!
