### ISSUE TITLE
Crash on iOS when calling createBanner if adId is undefinied

### ISSUE THREAD

**Issue by JoeSchr** [floatinghotpot/cordova-admob-pro#299]
Just a minor, low priority bug I just found.
createBanner crashes my App on iOs if it receives an undefinied adId

### Steps to Reproduce
Suppose _adID_/_bannerID_ is _undefined_:
and createBanner is called like e.g.
```
admob.createBanner({
                            adId: admobParam.bannerID,
                            autoShow: true,
                            success: function(){ },
                            error: function(){ console.error("SetupAd.failed to createBanner"); }
                        });
```

### Actual Behavior:
Crashes App on iOS, somehow works on Android (I also use Interstitials)

### Expected Behavior:
Calling error callback function when adId is undefined/not valid

Just costed me a couple of hours finding it, so I thought I will post it as well, maybe it helps somebody else...

**Comment by floatinghotpot** [comment]
Ok, will add safe check to return a callback instead of crashing. Thanks.
