### ISSUE TITLE
Build failed with new cordova android 5.1.0

### ISSUE THREAD

**Issue by Titoine** [floatinghotpot/cordova-admob-pro#300]
Thanks for the great job, everything was perfect before the new cordova android platform update.
Now I got a lot of error (symbol : variable ADTYPE_INTERSTITIAL) and the build fail.

![capture](https://cloud.githubusercontent.com/assets/3514286/12660453/21a13816-c614-11e5-9282-c6c8b2c99221.JPG)

If I remove the plugin, the build goes well.
Any help is welcome :)

Cordova 6.0.0
Cordova android 5.1.0

**Comment by floatinghotpot** [comment]
it seems that the dependency `cordova-plugin-extension` files is missing during your upgrade. Sometimes Cordova CLI does make such mistakes.

please try refresh your android platform by:
```bash
cordova platform remove android
cordova platform add android
```

Or, you can also re-install the plugin by:
```bash
cordova plugin remove cordova-plugin-admobpro

# dependency auto installed:
# cordova plugin add cordova-plugin-extension
cordova plugin add cordova-plugin-admobpro
```

**Comment by Titoine** [comment]
Really don't understand what happened. Already tried that the day before but with Cordova 5.4.0 and It doesn't worked. But know everything is back to normal.
Thanks !
