### ISSUE TITLE
Wrong Banner size on iPhone 6 Plus

### ISSUE THREAD

**Issue by RonnySchleicher** [floatinghotpot/cordova-admob-pro#301]
In the documentation of AdMob there is a definition of used banner sizes that does not apply to the iPhone 6+ from Admob plugin in this form.

According to the documentation the banner takes on the iPhone 6+ has a height of 90 dp (in density-independent pixels [dp]) have. However, the banner claimed only 50dp. Why?

In the screenshots, it becomes clear again. The wrong amount when iPhone 6 Plus has the banner in portrait and landscape mode.

![image](https://cloud.githubusercontent.com/assets/1914203/12725949/6c7eec30-c915-11e5-9ab0-aacdb9c00d97.png)

![image](https://cloud.githubusercontent.com/assets/1914203/12726025/b0b9a994-c915-11e5-9bca-3ac000c4ece1.png)

##### An excerpt from the documentation

https://developers.google.com/admob/android/banner

###### Three ad heights (in density-independent pixel [dp]) are implemented in smart banners:
* 32: device screen height <= 400
* 50: 400 < device screen height <= 720
* 90: device screen height > 720

#####  iPhone 6+ dp in the Webview
* 414 * 736 dp

![image](https://cloud.githubusercontent.com/assets/1914203/12726202/a50abae2-c916-11e5-9f58-9a43bf5f32d5.png)

Accordingly, the banner would have a height of 90 dp in portrait, not 50 dp.

#### My Enviroment
My app objected Smart Banner with overlay true. The area of the banner I manage itself.

JavaScript Configuration
```Javascript
AdMob.createBanner({
   adId     : admobid.banner,
   adSize   : AdMob.AD_SIZE.SMART_BANNER,
   position : AdMob.AD_POSITION.BOTTOM_CENTER,
   overlap  : true,
   autoShow : true
});
```

**Comment by RonnySchleicher** [comment]
My issue entered but nothing happens. Lack any information? Ask if something is missing. Thank you!

**Comment by floatinghotpot** [comment]
I think the 728x90 size only happen on Pad. 

If you read carefully (https://developers.google.com/admob/ios/banner), you will see:

> Three ad heights (in density-independent pixel [dp]) are implemented in smart banners:

> * 32: device screen height <= 400
* 50: 400 < device screen height <= 720
* 90: device screen height > 720

> For some devices, such as phones, the height of the device will vary with its orientation. Typically, smart banner ads on phones are full width x 50dp in portrait and full width x 32dp in landscape, while on tablets ads are full width x 90dp in both orientations.

See? Typically, smart banner ads on phones are full width x 50dp in portrait and full width x 32dp in landscape, while on tablets ads are full width x 90dp in both orientations.
