### ISSUE TITLE
Fire an event when the add is closed or not shown after AdMob.showInterstitial()

### ISSUE THREAD

**Issue by bbaki** [floatinghotpot/cordova-admob-pro#307]
Hey,
I'm aware that you can add a callback function to AdMob.prepareInterstitial but can you also do that to AdMob.showInterstitial()? Is there a way to detect if the add has ended? I'm using ionic and I would have scope problems when firing the event at AdMob.prepareInterstitial.

What I'm trying to achieve:
```
function myController() {
	AdMob.showInterstitial().then(function() {
		// fire this function when the add closes
		// or when it is not displayed
		playVideo();
	});

	function playVideo() {
		// Starts to play a video
	}
}
```

Big thanks for your time.

**Comment by floatinghotpot** [comment]
You can listen to event. 

document.addEventListener('onAdDismiss', function(){
  // your code here
});

**Comment by floatinghotpot** [comment]
Of course your suggestion is good, I will consider how to make it easier to use.

**Comment by bbaki** [comment]
Thanks! It works perfectly :)
