### ISSUE TITLE
Multiple ads on top of eachother

### ISSUE THREAD

**Issue by petertenhoor** [floatinghotpot/cordova-admob-pro#309]
Hello there,

I really like your plugin. It does exactly what I hoped it would do! I use the following code to initiate an insterstitial banner every minute:
```
setInterval(function(){ 
		AdMob.removeBanner();
		initAdMob();
	}, 60000);

function initAdMob() {
	var admobid = {interstitial: 'ca-app-pub-blablablablablabla'};

	AdMob.prepareInterstitial({
	 	adId:admobid.interstitial, 
		autoShow:true
	});
}
```
The problem is that in this way the banners stack on top of each other when not closed. Example: After 5 minutes there are 5 ads stacked on eachother. I'd like there to be only one ad active at once. I have tried the AdMob.removeBanner(): function but that didn't do the job.

Any ideas?

Greetings,

Peter ten Hoor

**Comment by floatinghotpot** [comment]
You are using interstitial Ad (full size), it's not banner ad.

Show Ad with setInterval() is not a good idea. The recommended approach is: prepareInterstitial() with autoShow:false, then call showInterstitial() at best timing (for example, when a game level is over). Then, when listen to 'onAdDismiss' event, and call prepareInterstitial() again.

**Comment by petertenhoor** [comment]
Thanks for your fast reply. I will try your approach!
