### ISSUE TITLE
I got issue like Failed to locate callback for id : AdMob1995903392 in wp8

### ISSUE THREAD

**Issue by Prav92** [floatinghotpot/cordova-admob-pro#310]
@floatinghotpot  When i run the app in Visual studio 2012 Ads not showed and in my console its shows Failed to locate callback for id : AdMob1995903392 like that. But when i try demo app it will works fine. any version problem?

**Comment by floatinghotpot** [comment]
If the demo app works fine, the plugin should be working fine. 

Please check, whether you are using a correct ad unit id. In admob portal, is it created for windows phone? Are you using one created not for winphone but for ios or android?

**Comment by floatinghotpot** [comment]
As the demo app works fine, it's a good start point, please study it carefully, to see if anything wrong with your own code...
