### ISSUE TITLE
Interstitial issue when "KeepRunning" preference is set to false (Android only)

### ISSUE THREAD

**Issue by casati** [floatinghotpot/cordova-admob-pro#311]
Setting in Cordova **config.xml** the preference "KeepRunning" to false:
```
<?xml version='1.0' encoding='utf-8'?>
<widget id="XXXXX" version="XX" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
<preference name="loglevel" value="DEBUG" />
<preference name="KeepRunning" value="false"/>
...
</widget>
```
interstitial adv with videos stop working correctly: an empty rectangle is shown instead of the video.

I've also notice of an another related issue with AdMob Pro plugin: sometimes showing an interstitial fires the "pause" event and closing the adv fires the "resume" event (in my app's onResume I put the code to show the interstitial so it falls in an infinite loop)

**Comment by floatinghotpot** [comment]
When showing interstitial, it will pause your app, or else, it work keep running in background of Ad, which is not correct. 

Try changing your logic, do not bind the showing ad with pause event.
