### ISSUE TITLE
Hide Ad on Different Pages

### ISSUE THREAD

**Issue by denzelwamburu** [floatinghotpot/cordova-admob-pro#312]
Hi, Great project :)
Is There a way to hide ads from appearing on certain pages, say login page? or make the ad appear on a particular div?

**Comment by floatinghotpot** [comment]
call `AdMob.showBanner()` or `AdMob.hideBanner()` when you enter the page.

But show Ad in a DIV is not possible with current plugin, as the Ad view is a native view, not a DOM element.

**Comment by denzelwamburu** [comment]
Am Working with ionic, can't seem to call the function unless i write on each page which is kinda tiresome.

**Comment by floatinghotpot** [comment]
You can write some common logic to handle it, for example, set a style class or DOM property, your common code just check the class or property, then show or hide.
