### ISSUE TITLE
PhoneGap Build: can't build for android

### ISSUE THREAD

**Issue by radoxFTW** [floatinghotpot/cordova-admob-pro#316]
Actually it seems that using Adobe PhoneGap Build does not work for Android template, while it does for iOS and WP.
It used to work until a few months ago, but now (after moving to npm) it always gives an unclear error.

I modified my config.xml with: 

```xml
<preference name="android-build-tool" value="gradle" /> 
<gap:plugin name="cordova-plugin-admobpro" source="npm" />
<gap:plugin name="cordova-plugin-admobpro" source="npm" />
```

but it stil does not work. Any suggestion? Previously I had this:

```
<gap:plugin` name="com.admob.plugin" version="3.0.0" source="plugins.cordova.io" />
```

PS: I'm using DevExtreme suite but I don't think it matters

**Comment by floatinghotpot** [comment]
Try following in your config.xml:
```xml
<preference name="android-build-tool" value="gradle" /> 
<gap:plugin name="cordova-plugin-admobpro" source="npm" />
```

Or,
```xml
<gap:plugin name="cordova-plugin-admob" source="npm" />
```

Do not try `com.admob.plugin` or `plugins.cordova.io`, as Cordova registry has been closed, all plugins have been migrated to npm.

**Comment by ingalb** [comment]
Hello, 

I have the same issue on Android. 
In my xml file I have insert:
`    <gap:plugin name="cordova-plugin-admob" source="npm" />`

Here are some info from the log file:

`plugman install --platform android --project /project --plugin cordova-plugin-admob": Fetching plugin "cordova-plugin-admob" via npm
Forward-slash in opening tag not followed by >
Line: 49
Column: 60
Char:`

**Comment by WHarris22** [comment]
I had the same problem using the PhoneGap Build service. I was getting this error returned:

> Error: Project contains at least one plugin that requires a system library. This is not supported with ANT. Please build using gradle.

Doing what @floatinghotpot said fixed it for me:

```
<preference name="android-build-tool" value="gradle" /> 
<gap:plugin name="cordova-plugin-admobpro" source="npm" />
```
