### ISSUE TITLE
admob adpolicy update. please, add admob parameter "isForChild"

### ISSUE THREAD

**Issue by nichekeys** [floatinghotpot/cordova-admob-pro#317]
admob adpolicy update. 
"The ads shown within your app must be appropriate for the intended audience of your app, even if the content by itself is otherwise compliant with our policies."

please, add admob parameter "isForChild"

**Comment by nichekeys** [comment]
ref : https://developers.google.com/admob/ios/targeting#child-directed_setting

**Comment by floatinghotpot** [comment]
See docs:
https://github.com/floatinghotpot/cordova-admob-pro/tree/master/docs#targetting-options
