### ISSUE TITLE
cordova-plugin-extension build error

### ISSUE THREAD

**Issue by lejeune** [floatinghotpot/cordova-admob-pro#318]
Hi,
I have an issue when trying to build an ionic project including the plugin cordova admob pro.

I have the following errors when trying to build : 

 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/lejeune/ionic/platsdumaroc/platforms/ios/build/emulator/PlatsDuMaroc.app/PlatsDuMaroc -o /Users/lejeune/ionic/platsdumaroc/platforms/ios/build/emulator/PlatsDuMaroc.app.dSYM
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: /Users/liming/Library/Developer/Xcode/DerivedData/ModuleCache/28XEC0RUQIF2J/AdSupport-N94D31PLFESQ.pcm: No such file or directory
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: /Users/liming/Library/Developer/Xcode/DerivedData/ModuleCache/28XEC0RUQIF2J/AdSupport-N94D31PLFESQ.pcm: No object file for requested architecture
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: /Users/liming/Library/Developer/Xcode/DerivedData/ModuleCache/28XEC0RUQIF2J/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: /Users/liming/Library/Developer/Xcode/DerivedData/ModuleCache/28XEC0RUQIF2J/Darwin-38I6DLZ5IH61J.pcm: No object file for requested architecture
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: /Users/liming/Library/Developer/Xcode/DerivedData/ModuleCache/28XEC0RUQIF2J/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: /Users/liming/Library/Developer/Xcode/DerivedData/ModuleCache/28XEC0RUQIF2J/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: /Users/liming/Library/Developer/Xcode/DerivedData/ModuleCache/28XEC0RUQIF2J/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: /Users/liming/Library/Developer/Xcode/DerivedData/ModuleCache/28XEC0RUQIF2J/UIKit-1V5UHAPTOD24G.pcm: No object file for requested architecture
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: /Users/liming/Library/Developer/Xcode/DerivedData/ModuleCache/28XEC0RUQIF2J/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: /Users/liming/Library/Developer/Xcode/DerivedData/ModuleCache/28XEC0RUQIF2J/ObjectiveC-1RQA2RIXJIE19.pcm: No object file for requested architecture
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: /Users/liming/Library/Developer/Xcode/DerivedData/ModuleCache/28XEC0RUQIF2J/CoreGraphics-N94D31PLFESQ.pcm: No such file or directory
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: /Users/liming/Library/Developer/Xcode/DerivedData/ModuleCache/28XEC0RUQIF2J/CoreGraphics-N94D31PLFESQ.pcm: No object file for requested architecture
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: Could not resolve external type c:objc(cs)UIWebView
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: Could not resolve external type c:objc(cs)UIViewController
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: Could not resolve external type c:objc(cs)UIColor
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: Could not resolve external type c:objc(cs)UIView
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: Could not resolve external type c:objc(cs)NSDictionary
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: Could not resolve external type c:objc(cs)NSNumber
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: Could not resolve external type c:@S@CGRect
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: Could not resolve external type c:objc(cs)NSNotification
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: Could not resolve external type c:objc(cs)NSMutableString
while processing /Users/lejeune/ionic/platsdumaroc/platforms/ios/PlatsDuMaroc/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o):
warning: Could not resolve external type c:objc(cs)NSScanner

Thanks for your help ;)

**Comment by lejeune** [comment]
Hello,
Compiling for android also giving an error : 
Note: /Users/lejeune/ionic/platsdumaroc/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java uses or overrides a deprecated API.

**Comment by floatinghotpot** [comment]
Please upgrade your XCode and Cordova CLI to latest version, then try again.
