### ISSUE TITLE
Display admob banner within listview

### ISSUE THREAD

**Issue by albertytau** [floatinghotpot/cordova-admob-pro#320]
Within the Admob, we can create the banner with following options

AdMob.AD_POSITION.NO_CHANGE     = 0,
AdMob.AD_POSITION.TOP_LEFT      = 1,
AdMob.AD_POSITION.TOP_CENTER    = 2,
AdMob.AD_POSITION.TOP_RIGHT     = 3,
AdMob.AD_POSITION.LEFT          = 4,
AdMob.AD_POSITION.CENTER        = 5,
AdMob.AD_POSITION.RIGHT         = 6,
AdMob.AD_POSITION.BOTTOM_LEFT   = 7,
AdMob.AD_POSITION.BOTTOM_CENTER = 8,
AdMob.AD_POSITION.BOTTOM_RIGHT  = 9,
AdMob.AD_POSITION.POS_XY        = 10, // use the given X and Y, see params 'x' and 'y'

How can I create the banner which is embedded in the ListView (put banner as a item in the ListView) ?

**Comment by floatinghotpot** [comment]
As the banner is a native view, not a DOM, you can not do it with AdMob.

But you can do that with following 2 ad plugins, using the native ad feature:
https://github.com/floatinghotpot/cordova-plugin-flurry
https://github.com/floatinghotpot/cordova-plugin-facebookads

**Comment by albertytau** [comment]
Many thanks
BTW, cordova-admob-pro is a very easy and developer friendly plugin :)

**Comment by Adri-7** [comment]
I have another question for floatinghotpot. Do you plan to integrate the admob native ad feature in cordova-admob-pro ?

**Comment by floatinghotpot** [comment]
As I know, AdMob native Ad is still in beta phase in some selected publishers, not open to all yet. Are you in their list?

**Comment by Adri-7** [comment]
Yeah, it's still in beta and no i'm not in their list. I don't even created my admob account yet :)
I'm just searching the best way to integrate ads in my app and the native ads seems to be a nice one. Since it's still in beta with admob, I think I will try your facebook ads plugin. Thanks for all the work you put in these plugins !
