### ISSUE TITLE
background color option not working ..

### ISSUE THREAD

**Issue by technotip** [floatinghotpot/cordova-admob-pro#322]
adExtras: {
    color_bg: 'green',
    color_bg_top: 'green',
    color_border: 'green',
    color_link: '000080',
    color_text: '808080',
    color_url: '008000'
}

OR

bgColor = 'green'

both these options not working. Everytime black background appears.

**Comment by technotip** [comment]
anybody know how to fix this?

**Comment by floatinghotpot** [comment]
Hi, it seems that options in SDK has been outdated. Try using the following method:

This is actually achieved through AdMob's dashboard.

Go to AdMob.com portal: https://apps.admob.com
* Select Monetize on the top toolbar
* Select the application on the left side bar that you want to change the background color for
* Select the Ad Unit of the banner

In the Text ad style drop down menu select Customized
* Select Background color and change it to whichever color you desire
* Select Save and you're all done

See:
![screen](http://i.stack.imgur.com/zaXWW.png)

It may take a few minutes for changes to appear in your application.

**Comment by technotip** [comment]
We can control the background color of the ad unit via AdMob dashboard ..
But I want to change the color of the element or component upon which the ad is being displayed.

![screenshot_20160317-145639](https://cloud.githubusercontent.com/assets/4805549/13841861/3c1d6b0c-ec51-11e5-8081-c9d94760408c.png)

See the red color boxes, I want to change the color of that. The blue color on the other hand will be the one I can control via AdMob dashboard - if that was a text ad.

btw, you can check it inside my app <a href="https://play.google.com/store/apps/details?id=com.technotip.scanIT">ScanIT</a> (screenshot from ScanIT app)

**Comment by KishanIos007** [comment]
same issue here ... +1

**Comment by mitch619911** [comment]
I am having a problem with even changing my ads colors.. I change the colors and they never update in the app!...

**Comment by KishanIos007** [comment]
Yes, i am having the same.. In banner AD i select the custom option but still can't reflect in my app.!

**Comment by technotip** [comment]
The background color issue was never solved. And now as you people pointed out the colors of the ad itself isn't reflecting in the ad banner :-( Maybe AdMob SDK has been updated and this plugin isn't.

Waiting for the author of the plugin to fix these issues.
