### ISSUE TITLE
Banner disappears on orientation change

### ISSUE THREAD

**Issue by unstableair** [floatinghotpot/cordova-admob-pro#323]
I create a SMART_BANNER with 

_autoShow: false, 
 orientationRenew: true_ 

I then use **showBanner** to display it at the appropriate time.
However if I change orientation the banner disappears until I call showBanner again.

If I do the following the orientation change works but the banner overlaps the content after orientation change (but not before). Setting _overlap: false_ has no effect.

_autoShow: false, 
 orientationRenew: false_ 

If I do this, everything works but the ad is displayed too early.

_autoShow: true, 
 orientationRenew: true_ 

Cordova 6.0.0, iOS 4.0.1, admobpro 2.12.1

Example code attached.
[index.txt](https://github.com/floatinghotpot/cordova-admob-pro/files/165713/index.txt)

**Comment by floatinghotpot** [comment]
orientationRenew, in most case, you do not need it if your app is designed for fixed orientation, either landscape or portrait.

If your app supports both orientation, when you display banner at landscape, it's longer than portrait mode, sometimes it cannot be displayed when change to portrait mode, as the width of screen is not enough. If set this option, the plugin will re-create the banner.

**Comment by unstableair** [comment]
Thanks for the response.  I now understand the problem a little more but I think the current implementation may be flawed.

If _autoShow_ is **false** then on orientation change the renewed banner is not displayed even if I have done a _showBanner()_ before the orientation change.

I think the correct response on orientation change would be for the code to detect if the banner is currently shown or hidden (either through _autoShow_ **or** _showBanner()_) and retain this. It should not automatically honor the _autoShow_ **false** on orientation change.

I tried to work around this by doing  _AdMob.setOptions( {autoShow: true } );_ **after** calling _createBanner_ but it didn't  work.

**Comment by technotip** [comment]
I'm also facing some issues with **orientationRenew  **..

when I have **orientationRenew ** set to **true**, upon changing the orientation of my device the position of the ad is changed :-( Upon setting the orientation back to original, the position doesn't get back to what we have set. Is there a way to fix it?

**Comment by floatinghotpot** [comment]
I am looking into this issue, need see how to re-produce. Can you paste some screenshot?

**Comment by unstableair** [comment]
There's not much to see in a screenshot as the ad disappears on orientation change. (see example code attached to first post).

If I *createBanner* with _autoShow: false_ & _orientationRenew: true_, then do *showBanner* the ad will disappear on orientation change.

I've worked around this by using *create* & *remove* every time I need the ad (instead of *show* and *hide* )
