### ISSUE TITLE
confused with 'orientationRenew' and 'offsetTopBar' options

### ISSUE THREAD

**Issue by technotip** [floatinghotpot/cordova-admob-pro#324]
I set both 'true' and 'false' values for 'orientationRenew' and 'offsetTopBar'  and tried to understand them. But still these options are confusing as to what their usage is ..could anyone please explain.

Please let me know if you've actually worked with these options ..
(I can understand the word meaning, but not its working!)

**Note:** I'm using latest ionic and cordova versions

**Comment by floatinghotpot** [comment]
offsetTopBar, is working for iOS only, to avoid the top status bar overlap your app & admob ad.

orientationRenew, in most case, you do not need it if your app is designed for fixed orientation, either landscape or portrait. 

If your app supports both orientation, when you display banner at landscape, it's longer than portrait mode, sometimes it cannot be displayed when change to portrait mode, as the width of screen is not enough. If set this option, the plugin will re-create the banner.

**Comment by technotip** [comment]
thanks for the explanation ..it really helps in understanding AdMobPro more
