### ISSUE TITLE
SDK-less Mediation

### ISSUE THREAD

**Issue by calebeaires** [floatinghotpot/cordova-admob-pro#325]
Google have doing some working about use less external SDK on mediation. Is cordova-admob-pro prepared to it?

Reference: https://admob.googleblog.com/2016/02/sdk-less-mediation.html

**Comment by floatinghotpot** [comment]
I think current plugin is SDK-less ready. As Google mentions, the SDK-less is handled by SDK and server-side service. You can configure the mediation from AdMob portal.
