### ISSUE TITLE
Extra authority check to prevent abuse of AdMob service

### ISSUE THREAD

**Issue by ratson** [floatinghotpot/cordova-admob-pro#326]
Is this plugin tracking users? Is it documented?
I need to confirm that users' privacy is respected.

**Comment by floatinghotpot** [comment]
This plugin won't collecting any user information, and won't spy any user privacy. You have my word. Here is the actual protocol interface:
```javascript
checkAdLicense(appId, platform, adNetwork, license);
```

You may also notice that, some new warning message is added to README here:
https://github.com/floatinghotpot/cordova-admob-pro#tips

Recently, Google contact me this popular plugin was abused by a few developers to violate AdMob rules, but I could not provide any info about this. 

To reduce abuse and serve Cordova/HTML5 community better, now the plugin will check from server-side database, if the app is blacklisted by Google, it won't send any Ad request. 

![Warning](https://github.com/floatinghotpot/cordova-admob-pro/raw/master/docs/warning.png)

BTW, warning again to all AdMob publisher:

Remember Google's slogan: "Don't be evil". Invalid usage violating Google rules, may cause your APP removed from Google Play, and even AdMob account suspended !

AdMob publisher may NOT abuse or encourage abuse any Google products, including Google Play, YouTube or Bolgger, incuding allow user downloading YouTube video, or embed YouTube video in your own apps.

Publishers may NOT click their own ads or use any means to inflate impressions and/or clicks artificially, including manual methods. Testing your own ads by clicking on them is not allowed.

⚠：请记住谷歌的口号：“不作恶”。任何违反合作规范、损害广告商和用户利益的行为，会导致你的 APP 被下架，甚至你的 AdMob 帐号被禁用！

AdMob发布商不得滥用或鼓励滥用任何Google产品，如Google Play、YouTube或Blogger。这包括规避任何Google产品的政策或条款或提供规避途径，例如允许用户下载YouTube视频等。不得刻意引诱用户点击广告，也不可以在自己的APP中点击广告（测试只能使用非正式的测试广告）。

More details, please read [AdMob & AdSense policies](https://support.google.com/admob/answer/6128543?hl=en&ref_topic=2745287)

**Comment by ratson** [comment]
Thanks for the answer, good to know that it is by design.
I searched the repository and did not find any code about http://adlic.rjfun.com, I was wondering it was a malware sending out the malicious request.

One more question, is only Ad-sharing Ad requests or all Ad requests will be blocked from server-side?

**Comment by floatinghotpot** [comment]
In fact, it's almost same, once your app violate AdMob rules, Google will blacklist your app, remove it from Google Play, and stop sending your ad. And, even suspend your admob account. So, do not touch the red line.

**Comment by ratson** [comment]
I see, thanks. Feel free to close this issue as you like.
