### ISSUE TITLE
How to integrate MobFox with this plugin

### ISSUE THREAD

**Issue by zaka786khan** [floatinghotpot/cordova-admob-pro#328]
Hi Dear floatinghotspot!

Nice work developing such plugin. I need to integrate MobFox into my application how do I accomplish this using AdMob Pro plugin. Please it possible? if yes then how it is possible does it needs any extra adapter to be installed to let it work or how?

I tried using my MobFox publisher id as followings but it is not working.

admobid = {
      //banner: 'ca-app-pub-xxxxxxxxxxxxxxxxxxxx', // instead using admob id
      banner: '<< MobFox publisher ID HERE>>',  // inserted my publisher ID here
      interstitial: 'ca-app-pub-xxxxxxxxxxxxxxxxxxxxxxxxxx' // here AdMob id for interstitial
      };

thanks.

**Comment by floatinghotpot** [comment]
No, you cannot do it like this, you must specify AdMob unit id there. 
Instead, try the following:

After install the AdMob plugin, also install the plugin for MobFox mediation adapter:
```bash
cordova plugin add cordova-plugin-admob-mobfox
```

Specify the admob ad unit Id when create banner or interstitial.

Then, in your web portal, find your ad unit id, edit mediation, then add your mobfox id there.
