### ISSUE TITLE
How to please integrate InMobi (cordova-inmobi-sdk) into cordova application

### ISSUE THREAD

**Issue by zaka786khan** [floatinghotpot/cordova-admob-pro#330]
Please I am newbie and I want a complete short guide about how to add InMobi into android application. for example first add plugin into project using the following command

cordova plugin add cordova-inmobi-sdk

Now what javascript code do I need to write to integrate InMobi Ads into my application If I have got the property ID from InMobi for application. Also does any workaround more is need/require after adding plugin into project such as unzip, replace the framework and jar. Which is that file and where that jar file is to be replaced in cordova project directory etc.

I will be thankful to you in this regards If I have a reply Thanks.

**Comment by floatinghotpot** [comment]
This project is for AdMob and related mediation. InMobi is not supported.
