### ISSUE TITLE
Where do i find the plugin version when using meteor ?

### ISSUE THREAD

**Issue by Kunal1985** [floatinghotpot/cordova-admob-pro#331]
As per the documentation provided under https://github.com/floatinghotpot/cordova-admob-pro/wiki/06.-How-To-Use-with-Meteor, within the AddPlugin section, I found the below information.
Add plugin: meteor add cordova:cordova-plugin-admobpro@x.x.x
Replace x.x.x with current version number, see the version here: https://www.npmjs.com/package/cordova-plugin-admobpro

But I still cannot find the exact version required for adding to meteor.
Kindly suggest.

Thanks & Regards,
Kunal Kishor Ugale

**Comment by floatinghotpot** [comment]
I guess you can omit the version number to always use the most recent version.

If you do wish to see the version number, see it in npm repo:
https://www.npmjs.com/package/cordova-plugin-admobpro

**Comment by Kunal1985** [comment]
Thanks, Got the version number from npm repository
