### ISSUE TITLE
Whitelisting?

### ISSUE THREAD

**Issue by Cooknick** [floatinghotpot/cordova-admob-pro#333]
I'm working in Intel XDK and building for iOS 9.

Can anyone tell me what URL to whitelist to connect to the ad server? Whitelisting "*" works just fine, but I'd like something more specific. Can't find it anywhere!

Thanks! #

**Comment by floatinghotpot** [comment]
You can find the info from Google AdMob official site: https://developers.google.com/admob/ios/ios9

iOS 9 Considerations

App Transport Security (ATS) is a privacy feature introduced in iOS 9. It's enabled by default for new applications and enforces secure connections. This may affect your app's integration with the Google Mobile Ads SDK.

All iOS 9 devices running apps built with Xcode 7 that don't disable ATS will be affected by this change. The following log message appears when a non-ATS compliant app attempts to serve an ad via HTTP on iOS 9:
> App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.

To ensure your ads are not impacted by ATS, Apple has provided the following exception that you can add to your app's Info.plist file.
![xcode](https://developers.google.com/admob/images/ios_exceptions.png)

```xml
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```
