### ISSUE TITLE
Android build fails.

### ISSUE THREAD

**Issue by anonrig** [floatinghotpot/cordova-admob-pro#334]
Hello,

Android build fails as follows.
<img width="1016" alt="screen shot 2016-03-20 at 7 17 18 pm" src="https://cloud.githubusercontent.com/assets/1935246/13905715/6c0ffa2e-eed0-11e5-8797-f1e2e1f46ae8.png">

I've installed the necessary plugins from Android SDK Manager:
<img width="670" alt="screen shot 2016-03-20 at 7 17 59 pm" src="https://cloud.githubusercontent.com/assets/1935246/13905719/7b4948ba-eed0-11e5-9344-632b80d4fed3.png">

My SDK tools are:
<img width="666" alt="screen shot 2016-03-20 at 7 18 11 pm" src="https://cloud.githubusercontent.com/assets/1935246/13905721/845c0fa0-eed0-11e5-9dc2-998cd85a249f.png">

My plugin list is

```
cordova-plugin-admobpro 2.13.0 "AdMob Plugin Pro"
cordova-plugin-android-support-v4 21.0.1 "Android Support v4"
cordova-plugin-extension 1.3.0 "Cordova Plugin Extension"
cordova-plugin-inappbrowser 1.3.1-dev "InAppBrowser"
cordova-plugin-whitelist 1.2.1 "Whitelist"
```

**Comment by floatinghotpot** [comment]
install also the one: local maven repository for support libraries
