### ISSUE TITLE
AdMobPlugin.java error on eclipse

### ISSUE THREAD

**Issue by softhutdev2** [floatinghotpot/cordova-admob-pro#336]
<a href="http://www.mx7.com/view2/yZEuAkGhXluLTyHA" target="_blank"><img border="0" src="http://www.mx7.com/i/15e/d4p1iV.png" /></a>

<a href="http://www.mx7.com/view2/yZEvpJBb4yaZjtXr" target="_blank"><img border="0" src="http://www.mx7.com/i/900/tbsHr0.png" /></a>

Description	Resource	Path	Type	Location
The method addCustomTargeting(String, String) is undefined for the type PublisherAdRequest.Builder	AdMobPlugin.java	/a/src/com/rjfun/cordova/admob	Java Problem	line 387

how to fix?
pleate help.thank you.

**Comment by floatinghotpot** [comment]
try installing newer Google play services library in your android sdk

**Comment by softhutdev2** [comment]
I update Google play services library to new version
<a href="http://www.mx7.com/view2/yZIaJqraHvyjdyz5" target="_blank"><img border="0" src="http://www.mx7.com/i/57c/WSTiJy.png" /></a>
but not work for me.
please help.thank you.

**Comment by floatinghotpot** [comment]
Try manually finding the google-play-services.jar in your SDK, then replace the google-play-services.jar in project folder.

if you use android studio, it will be no problem, simply import it as gradle project.

**Comment by floatinghotpot** [comment]
BTW, how to you use the plugin? Using id `cordova-plugin-admobpro`, or `cordova-plugin-admob` from npm, or from github repo directly?

**Comment by softhutdev2** [comment]
I use > cordova plugin add cordova-plugin-admobpro

**Comment by floatinghotpot** [comment]
Now you have trouble with eclipse, can you build with simply command line?
```
cordova build android
cordova run android --device
```

I also use eclipse before, but now switch to Android Studio for less trouble.

You may be more familiar with eclipse, but Android Studio is recommended by Google as default IDE for android project. https://developer.android.com/sdk/index.html

Cordova project use gradle instead of ant as default, which can be simply imported into Android Studio, and build without any problem.

**Comment by softhutdev2** [comment]
I will switch to android studio.
Thank you vary mouch for good suggestion.
regard.

**Comment by softhutdev2** [comment]
Hi.
Android Studio it work for me.
There is no problem at all.
Thank you @floatinghotpot

**Comment by floatinghotpot** [comment]
Okay, nice to hear that your issue is fixed. :+1:
