### ISSUE TITLE
showBanner not working on some circumstances

### ISSUE THREAD

**Issue by ianra001** [floatinghotpot/cordova-admob-pro#337]
Hello... new to this community.
Situation:
- I'm using the 'cordova-plugin-admobpro' plugin. 
- want to show banner adds only on selected html pages.
- have created banner using AdMob.createBanner with 'autoShow: false'.
- intend to use 'AdMob.showBanner' on pages with ads.
- intend to use 'AdMob.hideBanner' on pages without ads.
- 'AdMob.showBanner' works fine (in my .js file) when called immediately after 'createBanner'.
- identical code does NOT work when called as `<script>...</script>` from html pages.
There's the problem. Any guidance would be appreciated.
Many thanks... Ian_A
PS: If this is not the place for this issue, I'd be grateful for a pointer to the correct place. Thanks...

**Comment by floatinghotpot** [comment]
Please be aware:

1, cordova.js is required in your html, though you may not see it in your folder:

```html
<!-- must-have, which will be created by cordova prepare/build -->
<script type="text/javascript" src="cordova.js"></script>
```

2, test after build and install the app to device or emulator. 

If load html page in your PC browser, it won't work, as the plugin has android/ios native code, which only run on mobile device/emulator.

3, please find the working example here:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/test/index.html

If you are working on Mac, you can quickly test it by run command:
```bash
    # install cordova CLI
    [sudo] npm install cordova -g

    # install a small utility to run all the commands for you
    [sudo] npm install plugin-verify -g

    # Demo 1: run admob demo with sample index.html
    plugin-verify cordova-plugin-admobpro
```

**Comment by floatinghotpot** [comment]
BTW, do not call `AdMob.showBanner` immediately after `AdMob.createBanner`. Instead, pass one more param `autoShow:true` to AdMob.createBanner()
