### ISSUE TITLE
Test ad shows admob picture only

### ISSUE THREAD

**Issue by almemar87** [floatinghotpot/cordova-admob-pro#339]
Dear, 
My apology for this post, this is first time using admob pro. I'm migrating from 'cordova-plugin-admob' due to comparability with new Intel XDK release. 
admob pro keep showing me 'test ad from admob' picture. I want to update my app that is currently on production. Does it mean that admobpro will work on production or do I have to change some parameters?
![screenshot 104](https://cloud.githubusercontent.com/assets/17637658/14072177/eb271e58-f4ef-11e5-8156-c96a574c39b0.png)
There's this line in 'www/js/admob.js'
`
var admobid = {};
if( /(android)/i.test(navigator.userAgent) ) {
  admobid = { // for Android
    banner: 'ca-app-pub-xxxxxxxxxxxxxx',
    //interstitial: 'ca-app-pub-xxxxxxxxxxxxxx'
  };

`
Do I have to change it from 'test' to something else? 

my software: Intel XDK
my platform: Android

**Comment by floatinghotpot** [comment]
Please find `isTesting:true` when createBanner() or setOptions(), remove it, or change it to `isTesting:false`

**Comment by almemar87** [comment]
Many thanks bro. 
Thanks for your reply. I appreciate it
