### ISSUE TITLE
Keep showing error on portrait orientation

### ISSUE THREAD

**Issue by almemar87** [floatinghotpot/cordova-admob-pro#340]
Dear, 
I've searching for a solution to banner issue that I'm facing with the orientation 'I guess'. I tried the app on tablet it show banner perfectly. 
however, when I try it on phone device it shows me this error 

`
error: 
        reason: 
       adNetwork:' 
        adType:' 
        adEvent:' 
`
software: Intel XDk
platform: Android
I tried smart banner and custom one (320x100) and all same it doesn't work. 
`
function createSelectedBanner(){
  AdMob.createBanner({
    adId: admobid.banner,
      adSize   : AdMob.AD_SIZE.SMART_BANNER,
      offsetTopBar: true,    
   position: AdMob.AD_POSITION.TOP_CENTER,
  });
}
function showBannerAtPosition(){
  AdMob.showBanner( AdMob.AD_POSITION.TOP_CENTER );
}

function initAd(){
  AdMob.setOptions({
     adSize: 'CUSTOM',
    width: 320, // valid when set adSize 'CUSTOM'
    height: 100, // valid when set adSize 'CUSTOM'
    position: AdMob.AD_POSITION.TOP_CENTER,
    // offsetTopBar: false, // avoid overlapped by status bar, for iOS7+
    bgColor: 'black', // color name, or '#RRGGBB'
    // x: integer,    // valid when set position to 0 / POS_XY
    // y: integer,    // valid when set position to 0 / POS_XY
    isTesting: false, // set to true, to receiving test ad for testing purpose
   // autoShow: true // auto show interstitial ad when loaded, set to false if prepare/show
  });
`
and also the original one with adSize: 'SMART_BANNER'

has it been resolved? or am I missing something? 
sorry to bother you guys,
many thanks in advance :D

**Comment by floatinghotpot** [comment]
try 320 * 50 on phone, or use smart banner and let sdk decide the size.

**Comment by floatinghotpot** [comment]
If you are not sure, try copying the index.html under plugin/test/ folder for a testing.

**Comment by almemar87** [comment]
Thank dear for your reply, 
I tried my best and keep getting this error
![screenshot 107](https://cloud.githubusercontent.com/assets/17637658/14109345/2a93850e-f5f4-11e5-8621-96e7779e872f.png)
however it works on tablet like this
![screenshot 108](https://cloud.githubusercontent.com/assets/17637658/14109369/3c7efe24-f5f4-11e5-9d97-75299cd8683a.png)

and a screenshot from project admob js file is like this
![screenshot 109](https://cloud.githubusercontent.com/assets/17637658/14109385/4f838d46-f5f4-11e5-8b4f-212cefd061d3.png)

**Comment by almemar87** [comment]
Many thanks Raymond, you smart guy. 
we can't thank you enough for this plugin and your interest in helping us :D

**Comment by floatinghotpot** [comment]
Good to hear the tips is useful to you.

BTW, as to the "undefined" info error, I've found some root cause. See: #343
