### ISSUE TITLE
Windows 10 Mobile and Windows 10 support

### ISSUE THREAD

**Issue by podelo** [floatinghotpot/cordova-admob-pro#341]
Hi,

Does cordova-admob-pro support Windows 10 Mobile and Windows 10 ?

Thanks

**Comment by floatinghotpot** [comment]
This plugin is implemented based on the SDK. 

Google only provides SDK for Android, iOS, and WP8 (windows phone 8).

You can try the WP8 implementation, but not very sure it's compatible with Win 10 or not.

**Comment by podelo** [comment]
You are right, it doesn't support wp8.1 / Windows 10 mobile and Windows 10.

Thanks for your answer
