### ISSUE TITLE
Getting Package Errors when imported into Eclipse

### ISSUE THREAD

**Issue by mayed505** [floatinghotpot/cordova-admob-pro#344]
I get these package errors how to fix them i even tried with new project and i have cordova updated to latest version.
Heres the package error:
https://gyazo.com/6f6ce9a23d32faa5c53c0e918edbd3e8
Heres the SDK i installed:
https://gyazo.com/d18181019aa829a7c9442735aa7a1d27
Please Help ASAP!

**Comment by floatinghotpot** [comment]
try use android studio instead of eclipse. 

android studio is recommended by Google as default IDE for android project, and Cordova project is by default using grade instead of ant.

**Comment by mayed505** [comment]
@floatinghotpot the problem i dont know how to use android studio.

**Comment by floatinghotpot** [comment]
Just download it for free from Android website: 
http://developer.android.com/sdk/index.html

I used eclipse before, and now switch to Android Studio, it's quite similar and not hard.

**Comment by mayed505** [comment]
@floatinghotpot im using jquery mobile where do i place the code? in <head> ?

**Comment by mayed505** [comment]
@floatinghotpot  im following this method http://pointdeveloper.com/how-to-add-banner-ads-to-jquery-mobile-apps-with-phonegap-using-admob/ but it doesnt work
