### ISSUE TITLE
Arguments for createBanner method in iOS seem not working.

### ISSUE THREAD

**Issue by TakayukiSakai** [floatinghotpot/cordova-admob-pro#346]
When I create a banner view like below, everything works properly.
```
AdMob.setOptions({
  position: AdMob.AD_POSITION.BOTTOM_CENTER
});
AdMob.createBanner({
  adId: admobid.banner,
  autoShow: true,
});
```

But, this code doesn't work as I expect. Even though I set position at `BOTTOM_CENTER`, the banner appears at the top.
```
AdMob.createBanner({
  adId: admobid.banner,
  position: AdMob.AD_POSITION.BOTTOM_CENTER,
  autoShow: true,
});
```

`createBanner` method seems to call a native code defined in an archived binary. So I couldn't find out what is the problem...
https://github.com/floatinghotpot/cordova-extension/blob/master/src%2Fios%2FGenericAdPlugin.h#L61

**Comment by floatinghotpot** [comment]
I re-test it with the demo app, it works fine. Please try again.

You can read the code here:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/test/index.html

Or, just run the demo directly, it will build a demo project and load it in emulator:
```bash
[sudo] npm install -g plugin-verify
plugin-verify cordova-plugin-admobpro ios
```
Then, click "removeBanner" then click "createBanner".

**Comment by dannygunawan** [comment]
Hi,
I got the same issue with @TakayukiSakai. The banner always appeared in the top position even I defined the position properties to AdMob.AD_POSITION.BOTTOM_CENTER.

I solved this issue with this code (inside device ready event): 
```
if (typeof("AdMob")!="undefined") {
	AdMob.createBanner( {
	    adId: "ca-app-pub-3554674821795847/9286759214",
	    adSize: 'SMART_BANNER',
	    position: AdMob.AD_POSITION.BOTTOM_CENTER,
	    autoShow: false,
	    isTesting:false,
	    offsetTopBar:true,
	    success:function() {
               console.log("ads created"); 
               AdMob.showBanner();
            },
	    error:function(){
               console.log("fail create ads");
           }	
       });
}

```

Maybe Admob plugin started before the Jquery Mobile layout completed. (????)
Cordova 6.0 + Cordova IOS 4.1.0 + JQM 1.4.5

**Comment by dannygunawan** [comment]
OK, I solved my issue.
I forgot to place on deviceready event inside jquery on ready event.
