### ISSUE TITLE
Smart Banner from DFP is not centered

### ISSUE THREAD

**Issue by lucianomlima** [floatinghotpot/cordova-admob-pro#347]
I'm add a banner from DFP with Smart Banner adSize.
In DFP panel, banner is configured as SMART_BANNER and the image has 320x50.
When isTesting is true, the banner (from AdMob network) is centered, but when I disable isTesting option and try banner from DFP, always show left aligned.

```
		AdMob.createBanner({
			adId: myDFPTag,
			adSize: AdMob.AD_SIZE.SMART_BANNER,
			position: AdMob.AD_POSITION.BOTTOM_CENTER,
			offsetTopBar: true,
			overlap: true,
			bgColor: 'white',
			autoShow: true,
			isTesting: false
		});
```

**Comment by floatinghotpot** [comment]
Use BANNER for DFP.

**Comment by lucianomlima** [comment]
Ok, with BANNER works, but only if autoShow is true.
When I create a banner and show later with AdMob.showBanner() not respect the banner options used in createBanner method and show banner always in TOP_LEFT position.

**Comment by floatinghotpot** [comment]
please pass argument to showBanner(position), for example:
```javascript
AdMob.showBanner(AdMob.AD_POSITION.BOTTOM_CENTER);
```

**Comment by floatinghotpot** [comment]
Read detailed docs here:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/docs/README.md#methods-1

**Comment by lucianomlima** [comment]
Oh, sorry. I read the documentation but I thought that I only need call showBanner() with position when the position was not setted in createBanner options.

Now, works. Thanks.
