### ISSUE TITLE
admobpro plugin issue with android studio

### ISSUE THREAD

**Issue by sumeeth66** [floatinghotpot/cordova-admob-pro#349]
i am using cordova to build apps and use ionic sometimes....the problem is all plugins work fine and i can run my app in android studio but only admobpro plugin if i install in my project then i cant run my app at all...it sows some 100 errors...no idea...

something like com.google.ads doesnt exists...i have installed all extras in sdk along with play services...

**Comment by floatinghotpot** [comment]
I just guess you have not installed something of android sdk extras. 

Please check the picture in readme and check android studio setup carefully.

**Comment by sumeeth66** [comment]
I already installed everything in extras....I already told that...I don't know whats happening

**Comment by sumeeth66** [comment]
Do I need any extra setup while importing the Project in android studio...?  It works good while I Import non Admob plugin projects...

**Comment by floatinghotpot** [comment]
What do you mean by "everything"?

[extras](https://cloud.githubusercontent.com/assets/2339512/8176143/20533ec0-1429-11e5-8e17-a748373d5110.png)

**Comment by floatinghotpot** [comment]
Please paste some screenshot and logs...

**Comment by sumeeth66** [comment]
below i have attached screenshot and logs error file
![1](https://cloud.githubusercontent.com/assets/17476520/14225194/94249d42-f8d7-11e5-9e47-5374adbe26a4.PNG)
![2](https://cloud.githubusercontent.com/assets/17476520/14225196/99d823da-f8d7-11e5-97a5-33609bd28167.PNG)
[error.txt](https://github.com/floatinghotpot/cordova-admob-pro/files/200739/error.txt)

**Comment by floatinghotpot** [comment]
It seems that the extra libraries are not found by Android Studio. Did you setup the environment variable correctly?

**Comment by sumeeth66** [comment]
I don't have idea about that...how to set it so that android studio finds those libraries...?

**Comment by floatinghotpot** [comment]
Did you set env ANDROID_HOME=... ?

**Comment by sumeeth66** [comment]
Yeah I have set that in environment variables...

**Comment by floatinghotpot** [comment]
I checked my env, here are some path set, but I don't remember which one is related:
```
ANDROID_SDK_ROOT=/Users/liming/bin/android-sdk-macosx
SDK_ROOT=/Users/liming/bin/android-sdk-macosx
ANDROID_HOME=/Users/liming/bin/android-sdk-macosx
```
You can have a try.

It must be path related, as the error is definitely the jar not found.

**Comment by sumeeth66** [comment]
Ok I will have a try

**Comment by sumeeth66** [comment]
I need to point the root of sdk folder only right? Or i need to point sub folders too?

**Comment by floatinghotpot** [comment]
I guess only root of sdk folder... Just try, as I didn't meet very complex situation.

**Comment by sumeeth66** [comment]
Ok

**Comment by sumeeth66** [comment]
that dint work either....

**Comment by sumeeth66** [comment]
when i import the project folder it gives error but when i import the platform/android folder it runs fine...is it ok to import android folder? i have seen many saying to import project folder

**Comment by sumeeth66** [comment]
i tried many times...this only happens when i have admob plugin...rest all plugins work fine

**Comment by floatinghotpot** [comment]
From your message, I only know the reason is: google extra library is not found by your Android Studio. 

As the library cannot be found, not this plugin won't work, other plugins depending on the library won't work either, for example:
`cordova-plugin-googleplus`
`cordova-plugin-google-analytics`
...

How to resolve the library path issue? Please google, or ask in stackoverflow.com

**Comment by sumeeth66** [comment]
i copied the jar file from google play services in sdk folder and pasted in lib folder of my cordova project and made it as library...now i get few errors
![1](https://cloud.githubusercontent.com/assets/17476520/14226645/1009fb00-f905-11e5-90aa-be0a31b4a8ef.PNG)

**Comment by floatinghotpot** [comment]
"multiple dex files define Lcom/rjfun/cordova/ad/GenericAdPlugin", means you may have jar conflict this time. You may specify multi path with cordova-generic.ad.jar.

If I remember correctly, no need to copy jar to your folder, as it should be handled by maven. I guess you can find the clue from maven and gradle. But I never see such things happen.

Let's check the most basic checklist:
1. Did you ceate the cordova project with most recent cordova? 5.x or 6.x?
2. Did you import the project to Android Studio as a gradle project?

**Comment by sumeeth66** [comment]
I created cordova Project with 6... I dint use cordova build function i used cordova prepare and then I imported the Project root folder in android studio...I dint Import platform/android folder...

**Comment by floatinghotpot** [comment]
method 1. try run cordova cli directly to build your project, no need use android studio.

method 2. create a clean project, cordova prepare, then import the platform/android folder. NOT the cordova project folder.

**Comment by sumeeth66** [comment]
Ok thanks

**Comment by sumeeth66** [comment]
Do I need to use cordova build before opening in android studio?

**Comment by sumeeth66** [comment]
after lots of tries it worked...i opened android folder i was opening project folder till now...thanks a lot
