### ISSUE TITLE
Flickering of screen in Android with Banner Ad

### ISSUE THREAD

**Issue by iCREAM** [floatinghotpot/cordova-admob-pro#353]
See if anyone got similar issue?
Occationally, the screen would be flickering with the banner ad (the flicker sync with the change of the i / x sign in the banner).

I tried to enable the overlap, still got the flickering screen.

FYI, I just copied the files and code from cordova-plugin-admobpro/test/ into www folder, then execute "cordova run android".

**Comment by floatinghotpot** [comment]
The banner ad content will be refreshed every 60 seconds (and you can configure the interval in AdMob portal). I guess it related with the UI refresh.
