### ISSUE TITLE
Error by AdMobPlugin.java:103 and Build Failed

### ISSUE THREAD

**Issue by thomaskanzig** [floatinghotpot/cordova-admob-pro#354]
Hi guys,

When I build my project, happen this problem by archive  [AdMobPlugin.java](https://github.com/floatinghotpot/cordova-admob-pro/blob/master/src/android/AdMobPlugin.java) in line 103 See this bellow:

![ScreenShot](http://otimo.pro.br/neuro-easy/img/error.png)

I did everything for fix this problem, and my Android SDK is update.
Help me everyone, please!

**Comment by floatinghotpot** [comment]
Could you please check the version of dependent cordova-plugin-extension?

You may need update it also, to v1.5.1, see:
https://www.npmjs.com/package/cordova-plugin-extension

**Comment by thomaskanzig** [comment]
I solved this problem in other way.
Thanks for response me and I want to say which this plugin is very cool, congratulation =D
