### ISSUE TITLE
Intermittent Blank Ad 

### ISSUE THREAD

**Issue by eleva** [floatinghotpot/cordova-admob-pro#355]
Hi,
I'm facing an intermittent issue using the plugin in Ionic, with DFP integration.
It seems that sometimes the plugin successfully create the space for the ad (view is successfully resized) but it do not serve the ad (it is just a blank space at the bottom of the page).
This is not happening every time, neither in particular network condition (wifi connection).
Plugin is not throwing any error while creating banner (success callback seems to be called).

The workflow I use to manage the banner is:
1) Create it with createBanner function and simple options reported below
```
adId: my_banner_ad_key,
position: adMobPosition.BOTTOM_CENTER,
autoShow: false,
overlap: false
```
2) Show/Hide banner in my views (in beforeEnter/beforeLeave events)

I'm using latest version of the plugin.
I'm using also the interstitial which does not seems to have this issue (it is always served by DFP)

Do you have some hints about that?
Please feel free to ask more info if you need it.

**Comment by floatinghotpot** [comment]
If you listen to the 'onAdLoaded' or 'onAdFailLoad' event, will one of the event is fired?

**Comment by eleva** [comment]
Sorry for the little delay.
Here is what i got on "onAdFailLoad" event

`{"adNetwork":"AdMob","adType":"banner","adEvent":"onAdFailLoad","error":1,"reason":"Request Error: No ad to show."}`

We have set a simple ad in DFP (and it is correctly shown in quite all situations ..)
Any suggestions?

**Comment by floatinghotpot** [comment]
Error message is very clear: "No ad to show". Please fix it in ad server to provide valid ad resources.

**Comment by eleva** [comment]
Thank you,
it seems I made some mistake configuring DFP and i figured out how to solve it.
