### ISSUE TITLE
Interstitial show/hide

### ISSUE THREAD

**Issue by eleva** [floatinghotpot/cordova-admob-pro#356]
Hi,
i'm wondering if this plugin auto-manages delay or timing while showing interstitials ads.

I'm using Ionic and following this workflow to show interstitials ads 
1) prepareInterstitial function with simple options as reported below
```
adId: adMobId.admob_interstitial_key_ios,
autoShow: false
```
2) showInterstitial function wrapped in isInterstitialReady function on several view enter
```
$scope.$on('$ionicView.enter', function() {
  if(window.AdMob){
    window.AdMob.isInterstitialReady(function(ready){ 
	if(ready){
	  window.AdMob.showInterstitial();
	} 
    });
  }		
});
```

However interstitials ads are shown only on first time when entering the view, or after some arbitrary time while navigating the app and entering one view which is supposed to show the ad.

Is this a want feature or it depends on my DFP settings (I've not set any delay or stuff like that)?
Have you got any hints about that?

**Comment by floatinghotpot** [comment]
The interstitial Ad is one time Ad, once it's dismissed, you need prepare again before show again.

You can listen to 'onAdDismiss' event (which is triggered when ad is closed by user), then call prepareInsterstitial() there.

**Comment by eleva** [comment]
Thank you for your support.
It was clear to me I was missing something!
