### ISSUE TITLE
Problem to use with ConnectSDK - Build Failed

### ISSUE THREAD

**Issue by Valkno** [floatinghotpot/cordova-admob-pro#357]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'
```

I have those plugins, but i detect the problem is with ConnectSDK plugin

```
com.dawsonloudon.videoplayer 1.0.0 "VideoPlayer"
cordova-plugin-admobpro 2.16.0 "AdMob Plugin Pro"
cordova-plugin-connectsdk 1.6.0 "Connect SDK"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-extension 1.5.1 "Cordova Plugin Extension"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-splashscreen 3.2.1 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
ionic-plugin-keyboard 2.0.1 "Keyboard"
```

**Comment by floatinghotpot** [comment]
https://github.com/ConnectSDK/Connect-SDK-Cordova-Plugin/blob/master/Connect-SDK-Android/build.gradle#L73
```
compile 'com.google.android.gms:play-services-cast:7.8.0'
```

cordova-plugin-connectsdk has some bugs, it use a fixed version of google play jar, which is very easy to cause conflict with other plugins, if other plugins are not using version v7.8.0.

Please report a bug to them and suggest use a flexible version, like this:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/plugin.xml#L48
```xml
<framework src="com.google.android.gms:play-services-ads:+" />
```

**Comment by Valkno** [comment]
Hi, thanks for the help.
I follow these steps: https://github.com/floatinghotpot/cordova-admob-pro/issues/286#issuecomment-171845551
And work perfectly..

Greetings!.
