### ISSUE TITLE
iOS build errors: missing interstitialReady and ADTYPE_REWARDVIDEO

### ISSUE THREAD

**Issue by dunksmith** [floatinghotpot/cordova-admob-pro#358]
Installation appeared successful via the following:

    cordova plugin add cordova-plugin-admobpro

The plugin classes and frameworks where automatically added to my `.pbxproj` file.

However, building in XCode gives two errors relating to missing objects:

1. `self.interstitialReady = false;`
_<< Property 'interstitialReady' not found on object of type 'CDVAdMobPlugin *'; did you mean 'interstitialId'?_

2. `NSString* json = [NSString stringWithFormat:@" ..., ADTYPE_REWARDVIDEO, ...`
_<< Use of undeclared identifier 'ADTYPE_REWARDVIDEO'_

**Update:**
Similar errors when building for Android, and an extra one about inheritance:

```
AdMobPlugin.java:103: error: method does not override or implement a method from a supertype
  @Override
```

```
AdMobPlugin.java:244: error: cannot find symbol
    interstitialReady = false;
```

```
AdMobPlugin.java:635: error: cannot find symbol
      fireAdErrorEvent(EVENT_AD_FAILLOAD, errorCode, getErrorReason(errorCode), ADTYPE_REWARDVIDEO);
  symbol:   variable ADTYPE_REWARDVIDEO
```

What am I doing wrong?

Many thanks.

**Comment by dunksmith** [comment]
**Update:**
Similar errors when building for Android, and an extra one about inheritance:

```
AdMobPlugin.java:103: error: method does not override or implement a method from a supertype
  @Override
```

```
AdMobPlugin.java:244: error: cannot find symbol
    interstitialReady = false;
```

```
AdMobPlugin.java:635: error: cannot find symbol
      fireAdErrorEvent(EVENT_AD_FAILLOAD, errorCode, getErrorReason(errorCode), ADTYPE_REWARDVIDEO);
  symbol:   variable ADTYPE_REWARDVIDEO
```

**Comment by floatinghotpot** [comment]
Please also update dependent plugin `cordova-plugin-extension`.

**Comment by dunksmith** [comment]
Thanks, this worked.
