### ISSUE TITLE
Proposals for code revision

### ISSUE THREAD

**Issue by kirs26** [floatinghotpot/cordova-admob-pro#359]
In AdMobPlugin.cs:
1) remove the line 434 - setCordovaViewHeight(frame, view); because it does not work overlap: false for interstitial ad. 
2) Add: if (options.autoShow.HasValue) autoShow = options.autoShow.Value; in line 282
3) remove the line 631 - fireAdEvent (EVENT_AD_LOADED, ADTYPE_INTERSTITIAL); because it appears unceasing progress bar

**Comment by floatinghotpot** [comment]
I've reviewed the proposal. Below are my comments.

1) The setCordovaViewHeight() is in __showBanner(), for banner only, not for full screen interstitial. 
2) Ok.
3) The purpose is trigger event 'onAdLoaded', for javascript to handle the event.

Could please explain a bit more about 1) and 3)?

**Comment by kirs26** [comment]
1) The setCordovaViewHeight() is in __showBanner(), for banner only, not for full screen interstitial. 
I'm talking about the banner only. 
Variable bannerVisible is set to true after the call setCordovaViewHeight. Because of this `bool deduct = bannerVisible && (! overlap); `sets the value of the variable deduct in false, that leads to: `view.Height = initialViewHeight - (deduct ? BANNER_HEIGHT_PORTRAIT : 0);` where deduct = false, and this in turn results in inoperable overlay: false.
