### ISSUE TITLE
Build error with message "Not found com.google.android.gms:play-services-ads:+"

### ISSUE THREAD

**Issue by ftunde** [floatinghotpot/cordova-admob-pro#360]
I got error message while build "Not found com.google.android.gms:play-services-ads:+" although I have all necessary Android SDK Extra tool installed as shown in the FAQ 4.
https://github.com/floatinghotpot/cordova-admob-pro/wiki/Difference-of-Plugin-IDs

What could caused the issue and what is the solution?

Thanks.

**Comment by floatinghotpot** [comment]
The cordova project by default is for using gradle or importing into Android Studio.

Which tool are you using? Did you set env variables correctly?

**Comment by ftunde** [comment]
I am using App Builder with CLI. There is no place to set any variables

**Comment by floatinghotpot** [comment]
I mean environment variables, like:
```bash
iMac:~ liming$ env | grep HOME
ANDROID_HOME=/Users/liming/bin/android-sdk-macosx

iMac:~ liming$ env | grep SDK
ANDROID_SDK_ROOT=/Users/liming/bin/android-sdk-macosx
SDK_ROOT=/Users/liming/bin/android-sdk-macosx
```

**Comment by ftunde** [comment]
OK, I am using Android_Home = C:\AndroidSDK\build-tools, Ant_Home = C:\Ant-bin, my environment system is correct because I can create *.apk manually, but if cordova-plugin-admob is added to the *.apk then the error will displace.

**Comment by floatinghotpot** [comment]
use cordova-plugin-admobpro

**Comment by ftunde** [comment]
Thanks, issue solved with cordova-plugin-admobpro.
