### ISSUE TITLE
Reward video not displayed

### ISSUE THREAD

**Issue by NathanVss** [floatinghotpot/cordova-admob-pro#362]
Hello ! Great plugin ! 

I'm working on the setup of rewarded videos, but I can't get it to work.

```
    AdMob.prepareRewardVideoAd({
        adId: admobid.reward,
        isTesting: true
    }, function(e) {
        console.log('SUCCESS');
        console.log(e);
    }, function(e) {
        console.log('FAIL');
        console.log(e);
    });

document.addEventListener('onAdPresent', function (data) {
    console.log('AD PRESENT');
    console.log(data);
    if (data.adType == 'rewardvideo') {
        console.log(data.rewardType);
        console.log(data.rewardAmount);
    }
});
```

The console print "SUCCESS" and "OK" from prepareRewardVideoAd.
But when I call "AdMob.showRewardVideoAd();" nothing happens .. 
Ideas ?
EDIT : I put some debug print in the plugin java sources, and the video is never loaded. The STEP 3 is never printed : 

```

      if(ad.isLoaded()){
        System.out.println("REWARD : STEP 3");
        ad.show();
      }
```

EDIT 2 : 
I got a onAdFailLoad event with this event : 

```

adEvent: "onAdFailLoad"
adNetwork: "AdMob"
adType: "rewardvideo"
bubbles: false
cancelBubble: false
cancelable: false
currentTarget: null
defaultPrevented: false
error: 3
eventPhase: 0
isTrusted: false
isTrusted: false
path: Array[2]
reason: "No fill"
returnValue: true
srcElement: document
target: document
timeStamp: 1460814983099
type: "onAdFailLoad"
__proto__: Event
```

I don't know why I am getting a "no fill" reason. 

I already have a banner ad, today I just created a AdColony account and enabled the mediation for a new rewarded video unit only by giving my AdColony API Key. Did I forgot something ? 

EDIT 4 : I put adcolony.jar into the /android/libs folder. No changes.

EDIT 5 : I tried to use the Test ad by setting the json object to null, the video successfuly displays but the event "onRewarded" in java or "onAdPresent" in JS are never triggered, the dismiss one is triggered. This is strange because I wait the video to be finished before closing the overlay...

Thanh you.

**Comment by floatinghotpot** [comment]
Instead of checking result of prepareRewardVideoAd(), please listen to event 'onAdLoaded' to check whether the Ad resource is ready or not.

I think your EDIT 4 is very close to success. AdMob show rewarded video with resources from mediation, the SDK and adapter of mediated ad network is required. Does adcolony.jar contain the SDK and also the mediation adapter?

**Comment by NathanVss** [comment]
I can't get it to work.
I also added 
`AdColony.configure(cordova.getActivity(), "", "xx", "xx");`

Into pluginInitialize() method and nothing changes. 
What the isTesting boolean if used to in the prepareRewardVideoAd method ?
It will be cool if you provide a working example of rewarded videos. Is it in your plans ? 
Thank you !

**Comment by greneham** [comment]
i'm having a similar problem also trying to get adcolony working, a working example would be great!

**Comment by crownclown90** [comment]
i have "ChartBoost" setup on my "admob" mediation portal and when i attempt to prepareRewardVideoAd i receive "onAdFailLoad" with the "no fill"
[error: 3, reason: No fill, adNetwork:AdMob, adType:rewardvideo, adEvent:onAdFailLoad]

does the plug in not support "ChartBoost"  or am i missing a step or something to include?

**Comment by rajesh-mobicules** [comment]
Hi,

I am getting the same error which NathanVss is getting in his first thread. Can you please suggest to resolve this. I have to show unityads along with vungal ads with mediation.

**Comment by palmtreeint** [comment]
Was this ever resolved? I am a customer with a license and I'm hoping to find out the solution. My emails thus far have gone unanswered. Thanks for any guidance.

**Comment by floatinghotpot** [comment]
As some dev guys reply in the previous issue trackers, the reward video did work. I will find time to work out a demo project. Stay tuned.

**Comment by crownclown90** [comment]
any update on this?

**Comment by alexvandun** [comment]
I'm having the same 'No fill' problem while trying to implement the reward video, using InMobi. I believe the AdMob and InMobi accounts are setup correctly. 

Is there any way to better debug this problem?

**Comment by floatinghotpot** [comment]
Now AdMob offers its own reward video, you can use it without mediation. 

Please retry the demo index.html in this project. I've just updated it with the test reward video ad unit ids provided by admob team.
