### ISSUE TITLE
Admob Banner is not displaying in InAppBrowser

### ISSUE THREAD

**Issue by Divyaadz** [floatinghotpot/cordova-admob-pro#364]
Admob Banner is not displaying in InAppBrowser

Is there solution for this? Any workaround? I'm using Phonegap.

**Comment by floatinghotpot** [comment]
AdMob banner is a native view, not a DOM element. So it won't display in InAppBrowser.

**Comment by Divyaadz** [comment]
Is there any other solution to show the ads in inappbrowser?

**Comment by floatinghotpot** [comment]
You can try 'cordova-plugin-facebookads' or 'cordova-plugin-flurry', and use native Ad. Retrieve the ad resource and insert into your DOM content. It's a bit more complex than the common usage of banner or interstitial.

**Comment by brookyoh** [comment]
@floatinghotpot   still banner is not showing inappbrowser , any suggestions ?
