### ISSUE TITLE
How to add license key ?

### ISSUE THREAD

**Issue by chomdoi** [floatinghotpot/cordova-admob-pro#365]
I want to buy pro ver. but have some question. I see tutorial >> https://github.com/floatinghotpot/cordova-admob-pro/wiki/03.-How-to-Use-with-Construct-2

but when I opened c2runtime.js by edit plus it showed like this >> http://picture.in.th/id/129513221afdce0fbdf307b4d8bbada7

Can't find the line  "insert_your_license_key_here"  ?

What should i do ?

Note : Create app by C2 R227  with AdmobAds offical C2 plugin and build by intelxdk R3240

**Comment by floatinghotpot** [comment]
It can be more simple. 

Just copy this file to your folder, and reference it in your index.html.
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/test/admob_simple.js

**Comment by chomdoi** [comment]
Sorry I didn't understand you mean I don't need C2 plugin ?  just copy admob_simple.js to my project right ?

**Comment by floatinghotpot** [comment]
Yes, simply add the admob_simple.js to your project, then reference it and cordova.js in your index.html
