### ISSUE TITLE
Banner integration with Ionic ion-refresher

### ISSUE THREAD

**Issue by eleva** [floatinghotpot/cordova-admob-pro#371]
Hi,
I am showing a banner in a Ionic View, everything is working but we have some problem with the ion-refresher: it seems that the ion-refresher pull down is interrupted when reaching the bottom banner, it stops at middle page without running the related function. It seems that the banner is interrupting the top-to-bottom-swipe gesture.
This is the directive http://ionicframework.com/docs/api/directive/ionRefresher/
I had not this problem with the previous version of this plugin (I recently update it with the latest one).

Do you have some hints about that?

**Comment by floatinghotpot** [comment]
I don't think so, the banner is some content in another native view, it should not conflict with the main webview. I cannot verify your exact situation. please double check your code, or just use the previous version if it does work without any problem.
