### ISSUE TITLE
ads id in java code instead of JavaScript

### ISSUE THREAD

**Issue by meowwuff2015** [floatinghotpot/cordova-admob-pro#372]
is it possible to add my ads id in java code instead of Javascript code  ?
To prevent others from changing it

**Comment by floatinghotpot** [comment]
yes, it's possible, you need modify the java code, set ad id there, assume you have java competence. this works when you build cordova app locally instead cloud build service.

**Comment by meowwuff2015** [comment]
hi, if i hard coded the id in __createAdView method the else part , would that affect mediation or is this the correct way ?

**Comment by floatinghotpot** [comment]
yes.
