### ISSUE TITLE
Can provide keywords to admob for targeted Ads?

### ISSUE THREAD

**Issue by Disco69** [floatinghotpot/cordova-admob-pro#373]
Can i send keywords and targeting info to AdMob for better ads as same as this topic

[Send keywords and targeting info to AdMob for better ads](http://stackoverflow.com/questions/26501765/send-keywords-and-targeting-info-to-admob-for-better-ads)

**Comment by floatinghotpot** [comment]
Yes, almost all AdMob and DFP targeting features are supported. 

Please read docs:
https://github.com/floatinghotpot/cordova-admob-pro/tree/master/docs#targetting-options
