### ISSUE TITLE
Update to iOS SDK v7.8.0

### ISSUE THREAD

**Issue by ezazwar1** [floatinghotpot/cordova-admob-pro#374]
You are currently using version 7.7.0 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be downloaded from http://goo.gl/iGzfsP. A full list of release notes is available at https://developers.google.com/admob/ios/rel-notes.

**Comment by floatinghotpot** [comment]
Yes, SDK v7.8.0 is released. Will update soon.

**Comment by ezazwar1** [comment]
Thanks @floatinghotpot

**Comment by floatinghotpot** [comment]
The iOS SDK has been upgraded to v7.8.0.

Please update to plugin v2.17.0 to enjoy it.

**Comment by ezazwar1** [comment]
Thanks @floatinghotpot  can you please update the docs so that if some new feature is there people can know about that
