### ISSUE TITLE
ios build failed: use of undeclared identifier 'ADTYPE_REWARDVIDEO'

### ISSUE THREAD

**Issue by emanfu** [floatinghotpot/cordova-admob-pro#375]
I just upgraded the plugin to version 2.17.0 and also cordova-plugin-extension to 1.5.1. When I built ios app, I got the following error:

/Users/emanfu/Documents/projects/coffeesheep/dodat/platforms/ios/Vasona/Plugins/cordova-plugin-admobpro/CDVAdMobPlugin.m:441:28: error: use of undeclared identifier 'ADTYPE_REWARDVIDEO'
                      obj, ADTYPE_REWARDVIDEO, EVENT_AD_PRESENT, reward.type, [reward.amount doubleValue]];
                           ^
/Users/emanfu/Documents/projects/coffeesheep/dodat/platforms/ios/Vasona/Plugins/cordova-plugin-admobpro/CDVAdMobPlugin.m:446:48: error: use of undeclared identifier 'ADTYPE_REWARDVIDEO'
    [self fireAdEvent:EVENT_AD_LOADED withType:ADTYPE_REWARDVIDEO];
                                               ^
/Users/emanfu/Documents/projects/coffeesheep/dodat/platforms/ios/Vasona/Plugins/cordova-plugin-admobpro/CDVAdMobPlugin.m:450:53: error: use of undeclared identifier 'ADTYPE_REWARDVIDEO'
    [self fireAdEvent:EVENT_AD_WILLPRESENT withType:ADTYPE_REWARDVIDEO];
                                                    ^
/Users/emanfu/Documents/projects/coffeesheep/dodat/platforms/ios/Vasona/Plugins/cordova-plugin-admobpro/CDVAdMobPlugin.m:454:53: error: use of undeclared identifier 'ADTYPE_REWARDVIDEO'
    [self fireAdEvent:EVENT_AD_WILLPRESENT withType:ADTYPE_REWARDVIDEO];
                                                    ^
/Users/emanfu/Documents/projects/coffeesheep/dodat/platforms/ios/Vasona/Plugins/cordova-plugin-admobpro/CDVAdMobPlugin.m:458:49: error: use of undeclared identifier 'ADTYPE_REWARDVIDEO'
    [self fireAdEvent:EVENT_AD_DISMISS withType:ADTYPE_REWARDVIDEO];
                                                ^
/Users/emanfu/Documents/projects/coffeesheep/dodat/platforms/ios/Vasona/Plugins/cordova-plugin-admobpro/CDVAdMobPlugin.m:462:50: error: use of undeclared identifier 'ADTYPE_REWARDVIDEO'
    [self fireAdEvent:EVENT_AD_LEAVEAPP withType:ADTYPE_REWARDVIDEO];
                                                 ^
/Users/emanfu/Documents/projects/coffeesheep/dodat/platforms/ios/Vasona/Plugins/cordova-plugin-admobpro/CDVAdMobPlugin.m:467:117: error: use of undeclared identifier 'ADTYPE_REWARDVIDEO'
    [self fireAdErrorEvent:EVENT_AD_FAILLOAD withCode:(int)error.code withMsg:[error localizedDescription] withType:ADTYPE_REWARDVIDEO];
                                                                                                                    ^
1 warning and 7 errors generated.

I saw another issue complaining something similar but got resolved by updating cordova-plugin-extension, but I do update cordova-plugin-extension to the latest version and still get the above error. Please kindly help.

**Comment by emanfu** [comment]
The problem was solved by removing the ios platform and add it again. No idea what went wrong by simply remove the admob and extension plugins and add them in.

**Comment by floatinghotpot** [comment]
The feature of rewardvideo is newly added in latest cordova-plugin-extension, so you need update it.
