### ISSUE TITLE
Ad Position In-between Divs

### ISSUE THREAD

**Issue by Divyaadz** [floatinghotpot/cordova-admob-pro#376]
Hi,
I'm using your plugin in phonegap. Thanks for your great effort.

I have a single page app with multiple subsections, ie., its one long page app with multiple divisions

I like to show ads between section while user swipe down. As of now at bottom fixed banner is getting displayed. Is it possible to show the ads in customized places?

**Comment by floatinghotpot** [comment]
No, since AdMob banner is in a native view, not a DOM element, it cannot be inserted into DIV.

If you do want it very much, you can try flurry or facebook ad plugins, and then use its native ad.
* cordova-plugin-flurry
* cordova-plugin-facebookads

**Comment by lucianomlima** [comment]
A workaround for this case is put a empty div with same sizes of the banner and use showBanner(x,y) to position the banner over the empty div. But it is an ugly solution.

**Comment by floatinghotpot** [comment]
Yes, you can do like this, only if you web content won't scroll.
