### ISSUE TITLE
App auto close with mmedia mediation and cordova 5

### ISSUE THREAD

**Issue by m2ok** [floatinghotpot/cordova-admob-pro#377]
Hello,

The AdMob plugin and the mmdia Adaptater were working great for me ! But now with the cordova 5  my app auto close few seconds after loading.

I update all plugins but still doesn't work.

I tried to use the AdMob plugin without mmdia Adaptater, it works ! The problem comes when I add the cordova-plugin-admob-mmedia. I have no message, no log.

What can I do please ?

**Comment by floatinghotpot** [comment]
mMedia is no longer updated, and no plan for it, as I sent support request to mMedia team but never receive any response.
