### ISSUE TITLE
mediation not working

### ISSUE THREAD

**Issue by emanfu** [floatinghotpot/cordova-admob-pro#378]
I am trying to add Flurry into my Admob mediation. I added Flurry in the admob ad unit as a new ad source, installed the adapter plugin cordova-plugin-admob-flurry, and the rebuilt my app. When I run my app, I notice my banner ad still always come from Admob. I don't see any ad coming from Flurry.

Could you let me know if I set up things correctly? What else I should do besides what I have done above?

**Comment by floatinghotpot** [comment]
Please ask Google for this mediation ad content. 

Here is their official forum:
https://groups.google.com/forum/#!forum/google-admob-ads-sdk
