### ISSUE TITLE
Got same ads 90% of the time on iOS

### ISSUE THREAD

**Issue by emanfu** [floatinghotpot/cordova-admob-pro#379]
I notice that the banner and interstitial ads my iOS app receives are usually the same 90% of the time. For banner ads, although I configure in admob to refresh every 30 seconds, the same ad could stay for a very long time (sometimes the whole day) before another ad is shown. Even when it does switch to new ads, usually there are only 4-5 ads keep cycling.

It's worse for the interstitial ads. After my app launches, it almost always receives the same interstitial ad. It happens on a really device much more than on emulator.

This is what I do in my app:

For banner:
1. After deviceready, call createBanner with the adId, adSize, position, and autoShow false. If the user allows me to get GPS location, I also add location into the option.
2. Every time when I receive onAdLoaded, I call showBanner. I do receive onAdLoaded every 30 seconds, but when I call showBanner, a lot of time it's just showing the same ad.

For interstitial:
1. After deviceready, call prepareInterstitial.
2. When I receive onAdLoaded for an interstitial ad, set interstitalReady=true.
3. When the user does a specific action and interstitialReady is true, I call showInterstitial, and immediately call prepareInterstitial to get the next interstitial ad ready.

Could you let me know what I did wrong?

**Comment by floatinghotpot** [comment]
Please ask Google for this question, as they provide ad service and ad service.

Here is their official support forum:
https://groups.google.com/forum/#!forum/google-admob-ads-sdk
