### ISSUE TITLE
It works with 16 April 2016 build but not with 04 May build...

### ISSUE THREAD

**Issue by lse123** [floatinghotpot/cordova-admob-pro#380]
It works with 16 April 2016 build but After upgrade Intel XDK (in the mid)... and make a new version do not with 04 May build.... I never touch admob plugin js code ... new version was on other matters... fixes.

well?

**Comment by lse123** [comment]
Android platform

**Comment by floatinghotpot** [comment]
Is it XDK build service issue? Sometimes they may fail.

**Comment by lse123** [comment]
AS I SEE plugin upgraded to 2.17.0 <<< this should work... with newest xdk?
I will try now...

**Comment by floatinghotpot** [comment]
You can follow Intel XDK on twitter, they usually publish message if build service fail or fixed.
