### ISSUE TITLE
DFP Smart Banner with HORIZONTAL_CENTER layout

### ISSUE THREAD

**Issue by lucianomlima** [floatinghotpot/cordova-admob-pro#381]
Is there any way to make this work?
Always the banner loads left aligned.

**Comment by floatinghotpot** [comment]
when using DFP banner, use type BANNER instead of SMART_BANNER

**Comment by lucianomlima** [comment]
I'm know. You explain in another issue. But there is some way to use SMART_BANNER with DFP and set banner position through the AD_SIZES parameters?

In DFP docs for Android SDK, they use HORIZONTAL_CENTER in the layout configuration. It's not possible to set this layout param with DFP and SMART_BANNER in AdMobPro plugin?

**Comment by floatinghotpot** [comment]
Please change to BANNER, then the plugin will calculate the size, and then put it to center if you specify position: AdMob.AD_POSITION.BOTTOM_CENTER.

**Comment by lucianomlima** [comment]
I know, I'm using this way.
The problem is that when I am set DFP with Smart banners, the code always brings the same banner regardless of the screen size.

Let me give an example:
In DFP site, create a Smart banner set with 3 different sizes: 320x50, 468x60 and 970x90.

When testing on a smartphone with a resolution of 480x960 -> get 320x50 banner.
When testing on a tablet with a resolution of 1280x1920 -> get 320x50 banner again.

If the smart banner works well, in tablet will get 970x90 banner.

**Comment by floatinghotpot** [comment]
In few cases reported by other guys, I did not see any success of smart banner for DFP, always fixed size of BANNER. I will contact Google DFP team for this problem.

**Comment by xarlotie** [comment]
Is there an update for this? I also need to center the material when the loaded creative is smaller than the device's width. Please help. Thanks a lot!

**Comment by floatinghotpot** [comment]
I got answer that DFP banner is fixed only, so you need use BANNER, not SMART_BANNER. You cannot resize it to fit device width.
