### ISSUE TITLE
Interstitial  Ad not displaying consistently

### ISSUE THREAD

**Issue by Divyaadz** [floatinghotpot/cordova-admob-pro#383]
I have multiple games, user can play any game as they wish
Interstitial is behaving not consistent. Whether it calculate any time interval for displaying the ad?
I can see banner ads are more consistently displayed at bottom

//Called prepareAdmob function during starting of a game
prepareAdmob()

//Called when exit of an game
 if(AdMob) AdMob.showInterstitial();

`function prepareAdmob(){
			
			
			// select the right Ad Id according to platform
			if( /(android)/i.test(navigator.userAgent) ) { 
				admobid = { // for Android
					banner: 'ca-app-pub-1814894186126899/1495777765',
					interstitial: 'ca-app-pub-1814894186126899/4449224169'
				};
			} else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
				admobid = { // for iOS
					banner: 'ca-app-pub-1814894186196899/1495777765',
					interstitial: 'ca-app-pub-1814894186196899/4449244169'
				};
			} else {
				admobid = { // for Windows Phone
					banner: 'ca-app-pub-1814894186196899/1495777765',
					interstitial: 'ca-app-pub-1814894186196899/4449244169'
				};
			}
			
				// preppare and load ad resource in background, e.g. at begining of game level
				if(AdMob) AdMob.prepareInterstitial( {adId:admobid.interstitial, autoShow:false} );
			
		}`

**Comment by floatinghotpot** [comment]
What do you mean by "not consistently"?

**Comment by maxkfranz** [comment]
@floatinghotpot I can confirm this issue occurs on 2.17 with *production* ads.  I'm not sure if it's reproducible with test ads.

The issue is that 2.17 does not give interstitials consistently -- they work less than 50% of the time after the first one.  The exact same code with 2.13 works great and gets interstitials *every time*.  Something changed between 2.13 and 2.17 to make interstitials less reliable.

**Comment by maxkfranz** [comment]
@Divyaadz Downgrade to 2.13, and interstitials should work again.

**Comment by russellchapin** [comment]
Still broken...
