### ISSUE TITLE
Build Failed on iOS

### ISSUE THREAD

**Issue by inceptiveDipak** [floatinghotpot/cordova-admob-pro#385]
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_SFSafariViewController", referenced from:
      objc-class-ref in GoogleMobileAds(flat-i386)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/emulator/DemoApp.app/DemoApp normal i386
(1 failure)
Error: /Users/Workspace/Ionic_Projects/DemoApp/platforms/ios/cordova/build: Command failed with exit code 65

My ionic info is:

Cordova CLI: 6.1.1
Ionic Framework Version: 1.1.0
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X Yosemite
Node Version: v5.10.1
Xcode version: Xcode 6.4 Build version 6E35b 

How to resolve it.
Thank You !!

**Comment by floatinghotpot** [comment]
Please upgrade your xcode to new version.

**Comment by floatinghotpot** [comment]
Does it work for you after upgrade xcode?

**Comment by fpena06** [comment]
Same here

`Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.4 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v6.1.0
Xcode version: Xcode 7.3.1 Build version 7D1014 
`

**Comment by fpena06** [comment]
I found what my issue was. I had both of these on my config.xml file. `    <plugin name="cordova-admob" spec="~4.1.11" />
    <plugin name="cordova-plugin-admobpro" spec="~2.17.0" />`

**Comment by floatinghotpot** [comment]
Ok.

**Comment by jbeuckm** [comment]
Is there a version that would work on iOS 8? I have to keep my dev machine on Mavericks for a separate reason.

**Comment by floatinghotpot** [comment]
Sorry, I did not specifically keep release for specific iOS version. But, you can try some of the old versions or commits, as they worked.

BTW, what will happen if you using current version for iOS? Usually you can install an APP if the min-iOS set to lower version when you build app.
