### ISSUE TITLE
Not able to build for Android 

### ISSUE THREAD

**Issue by sutheesh** [floatinghotpot/cordova-admob-pro#387]
Showing below error

AGPBI: {kind:error,text:Error converting bytecode to dex:\nCause: com.android.dex.DexException: Multiple dex files define Lcom/google/ads/AdRequest$ErrorCode;,sources:[{}],

**Comment by floatinghotpot** [comment]
I guess you are using some duplicated plugin or library, which cause "multiple dex" error. Please double check and remove extra one.
