### ISSUE TITLE
Smart banner size

### ISSUE THREAD

**Issue by creativemobil** [floatinghotpot/cordova-admob-pro#389]
When I launch the app on iOS the first smart banner is not fit to the correct size, as in pictures. When the banner is renewed, it is presented properly. What it is wrong?

![img_3865](https://cloud.githubusercontent.com/assets/6963311/15330050/82cf9358-1c31-11e6-93ec-99d4c46cc29e.PNG)
![img_3866](https://cloud.githubusercontent.com/assets/6963311/15330051/82d20c32-1c31-11e6-850d-f83964449856.PNG)

Thanks.

**Comment by floatinghotpot** [comment]
I did not see what's the problem, can it be more specific?

**Comment by floatinghotpot** [comment]
I will close this tracker as no more feedback details or follow up.
