### ISSUE TITLE
App crash on startup with cordova-admob-pro installed

### ISSUE THREAD

**Issue by neslinesli93** [floatinghotpot/cordova-admob-pro#390]
Hi, I just made a fresh project to test this plugin.
I went and downloaded the latest Google Play Service from Android Studio, but the app crashes on startup. adb logcat reports that the issue is related to some firebase library, so maybe the plugin needs to be updated to reflect the changes that were introduced yesterday after Google I/O.
Here is the stack trace:

```
D/AndroidRuntime(19028): Shutting down VM
E/AndroidRuntime(19028): FATAL EXCEPTION: main
E/AndroidRuntime(19028): Process: com.test.app, PID: 19028
E/AndroidRuntime(19028): java.lang.RuntimeException: Unable to get provider
com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: Incorrect provider authority in manifest. Most likely due to a missing applicationId variable in application's build.gradle.
```

**Comment by neslinesli93** [comment]
Ok, I got it to work by following [this advice on SO](https://stackoverflow.com/questions/37312103/unable-to-get-provider-com-google-firebase-provider-firebaseinitprovider), which worked like a charm.
Unfortunately I don't know gradle enough to sumbit a PR :(

**Comment by floatinghotpot** [comment]
I think this issue has no much relationship with this plugin, as it won't change build.gradle.
