### ISSUE TITLE
Error : 0 with banner

### ISSUE THREAD

**Issue by m2ok** [floatinghotpot/cordova-admob-pro#395]
Hello,

I'm using cordova 6.1.1 and the lastest version of the AdMob plugin.

I have this error message : Error: 0, reason: Internal error...

I tried to uninstall the plugin, remove the platform but I still have the problem.

My code : 

```
if (AdMob) {
AdMob.createBanner( {
  adId: ADMOB_ID.banner,
  position: AdMob.AD_POSITION.BOTTOM_CENTER,
  isTesting: true
});
}
```

Could you help me please ?

**Comment by floatinghotpot** [comment]
please check:
1. do you have a network?
2. are you using the same ad unit id for both android and ios? you can only use the ad unit created for the specific platform.

**Comment by m2ok** [comment]
I tested it in the emulator.

I only have one ad unit for android.

**Comment by m2ok** [comment]
It works fine on a real device.

Thank you.
