### ISSUE TITLE
Interstitial test ads work fine, live ads don't work:  Ionic app for Android

### ISSUE THREAD

**Issue by tooraje** [floatinghotpot/cordova-admob-pro#396]
Hi flotinghotpot,

I have a similar issue as issue #386.
 
In my case I have an interstitial ad for Android.
When I set "isTesting: true" everything works fine, but when I set "isTesting: false", when I run the app on an Android phone I get this Alert message:

error: 0, reason: Internal error,
adNetwork:AdMob, adType:interstitial,
adEvent:onAdFailLoad

When I wanted to create the ad unit on AdMob, it asked for my app name, and when I entered the name it found it in Google play store, so I assume it has correctly created an ad unit for Android? Or there is a manual way to select Android or ios as platform?

Any help on this is really appreciated.

**Comment by floatinghotpot** [comment]
as you can see the test Ad, it proves the admob SDK and plugin work fine. Now you should focus on checking whether your ad unit id is valid.

1. for android, you need create an entry for android app in admob, then create an interstitial ad unit. if you use a banner ad unit id, or use an ios ad unit id, it won't work.

2. it will take some moment before your admob account become effective.

3. only on a device, you can see the live ad. on emulator, you can only see test ad.

**Comment by tooraje** [comment]
Thanks, 

Although my AdMob account was not new, but the ad unit I generated was new, and it took a few hours till that ad unit got activated. Now it is working fine.
Thanks for creating this great plugin.
