### ISSUE TITLE
Google Play services plugin is not being installed with admobpro

### ISSUE THREAD

**Issue by Gulmohr** [floatinghotpot/cordova-admob-pro#397]
When I am adding admob pro plugin to cordova it is not automatically fetching google play services. I tried to install google play servives manually before installing admob pro, then on running the build it is showing error that it cannot locate symbol files.

**Comment by floatinghotpot** [comment]
Please use cordova CLI to build project, or import into Android Studio (default IDE for android project and cordova project), do not use Eclipse.
