### ISSUE TITLE
Admob & Facebook AudNet

### ISSUE THREAD

**Issue by zaouifahd** [floatinghotpot/cordova-admob-pro#398]
Hi, 

It is possible to use the two plugins in same app, when i testing to initialize the two plugins the ads no display.

someone has already succeeded? if so what are the initialization code.

thank you

**Comment by floatinghotpot** [comment]
Yes, you can use both in same app. But, it's more recommended to use AdMob plugin `cordova-plugin-admobpro` with mediation adapter to Facebook AudNet `cordova-plugin-admob-facebook`.

**Comment by juxfr** [comment]
Is it possible to have FB Audience Network Native on cordova-admob-pro ? Or do we have to install both?

**Comment by floatinghotpot** [comment]
No, to use FB AudNet native Ad, you should use `cordova-plugin-facebookads` instead.
