### ISSUE TITLE
AdMob enforces an authentication at iTunes

### ISSUE THREAD

**Issue by RonnySchleicher** [floatinghotpot/cordova-admob-pro#399]
#### Steps to reproduce

Create a new PhoneGap Project on your iMac

```batch
cordova create PhoneGap_ios de.test.test Test

cd PhoneGap_ios

cordova platform add ios

cordova plugin add https://github.com/floatinghotpot/cordova-admob-pro.git
```

Open the new Project with X-Code an running the Test-App on your iPhone.

Following Message-Box appear:

![image](https://cloud.githubusercontent.com/assets/1914203/15651949/1b4875c2-2683-11e6-844c-fc85ef702494.png)

:question: :question: :question: Why this logon box :question: :question: :question: 

 **Since makes no serious impression when an iTunes authentication is required when starting an application.**

#### Without AddMob

```batch
cordova create PhoneGap_ios de.test.test Test2

cd PhoneGap_ios

cordova platform add ios
```

Also is fine. No authentication appear. Accordingly, the AdMob plugin for this notification is responsible.

![image](https://cloud.githubusercontent.com/assets/1914203/15651969/3fdcab1a-2683-11e6-9571-8130af4efa92.png)

**Comment by RonnySchleicher** [comment]
#### Enviorement
* iMac with OS X El Capitan
* X-Code 7.3 (7D175)
* iOS 9.3.2
* latest PhoneGap/Cordova and AddMob Version

**Comment by RonnySchleicher** [comment]
Hello AddMob Team.
Are still more information needed to recreate the problem?

**Comment by floatinghotpot** [comment]
I cannot understand the content in the popup box, can you translate it into English?

**Comment by RonnySchleicher** [comment]
#### The popup content is:
Tap "Next" and log in to search for the available downloads.

**Comment by RonnySchleicher** [comment]
This is the login screen appears when I open the App Store on the iPhone.

**Comment by floatinghotpot** [comment]
did you enable Apple IAP for this app id? cause I see some text about sandbox, which is for IAP testing only.

**Comment by RonnySchleicher** [comment]
It is possible that these Apple ID is registered for IAP. I'm going to the check tomorrow at a correct statement to make.

**Comment by RonnySchleicher** [comment]
You're right. When for the used AppId are IAP is enable, the popup appears.
But only in combination with the AdMob plugin.
Without the AdMob plugin the message does not appear.
Why do the Plugin?

**Comment by floatinghotpot** [comment]
Ok, the reason is clear.

The AdMob SDK requires StoreKit.framework, (for its IAP Ad I guess).
see: https://github.com/floatinghotpot/cordova-admob-pro/blob/master/plugin.xml#L109

If your APP id is registered for IAP, the StoreKit.framework will check with SandBox when testing on device. If your APP is in production stage, it won't be a problem I think.

**Comment by RonnySchleicher** [comment]
Thanks for your help!
