### ISSUE TITLE
Help with visual studio

### ISSUE THREAD

**Issue by blacksad29** [floatinghotpot/cordova-admob-pro#404]
Hello,
I apologize for my bad English level.

I try to use the plugin on a new application but it does not work .

When compiling the application (even an empty with just the plugin) , it takes enormously time to start generating .. and ends up putting me :

Erreur  1   connect ETIMEDOUT   Failed to install 'cordova-plugin-admobpro' 

I tried with the simple plugin admob and pro.

can you help me?
I 'd forgotten to install something?

**Comment by floatinghotpot** [comment]
visual studio should support npm now.
