### ISSUE TITLE
Black Screen after Interstitial close on Samsung S6/S4

### ISSUE THREAD

**Issue by ingalb** [floatinghotpot/cordova-admob-pro#405]
Hello, 

I have a problem on Android Samsung S6 and Samsung S4:
 when the user tap the close icon on Interstitial, the screen remain black. 
Only in case that I rotate the phone the black screen is removed. 

The application is build on phonegap build and with cli version 6.1 with gradle enable.

```
<preference name="phonegap-version" value="cli-6.1.0" />
<preference name="android-build-tool" value="gradle" />
<plugin name="cordova-plugin-admobpro" spec="2.18.0" />
```

Please can you check it. 

Regards

**Comment by ingalb** [comment]
Just an update. 

The problem persist also with admob option:  isTesting: true

**Comment by vintage** [comment]
I've been reported with same issue by my users. I checked on three emulators:
- Samsung Galaxy S3 (4.2.2)
- Samsung Galaxy S5 (4.4.4)
- Google Nexus 6 (6.0.0)

and on every of them the screen goes white after I close the Interstitial Ad.

**Comment by vintage** [comment]
@ingalb: Any chance that you are using Ionic framework? I've just solved my issue and everything works correctly now. Check your codebase if you are not doing any navigation stuff after showing full screen ad. If so -> move the code responsible for showing the ad after navigation is done. You could also check in chrome the "chrome://inspect/#devices" & see if in the page navigation DOM there is any element which has "show-page" class.

Let me know if you need further details or have any other questions.

**Comment by ingalb** [comment]
Hello @vintage , thanks for your comments. 

Yes I'm using Ionic Framework version 1 and build on Phonegap Build. 

How did you have resolve the problem?
Please can you post you fix. 

Regards

**Comment by vintage** [comment]
I'm using Ionic2, so it's gonna be a bit different, but overall here is my approach:

Original code:
`
this.ads.showFullScreen();
this.nav.push(NextPage).then(() => {
    this.nav.remove(this.nav.indexOf(this.viewCtrl));
});
`

Fixed code:
`
this.nav.push(NextPage).then(() => {
        this.nav.remove(this.nav.indexOf(this.viewCtrl)).then(() => {
            this.ads.showFullScreen();
        }
    });
});
`

I've been showing the ad and after that immediately navigating to the next page in the navigation stack & removing previous one. The solution was to first navigate to correct page and when ready - show the ad. If you have any further questions, paste your code here, we can figure out what's happening in there.

**Comment by ingalb** [comment]
The black screen remain only on real device (Tested on Galaxy S4 and Galaxy S6). 
On the emulator the problem does not appear. 
I just have build the demo project from @floatinghotpot on Phonegap Build. 
Here is the project:
https://github.com/ingalb/admob-ionic.git
And here you can download the apk:
https://build.phonegap.com/apps/2143545/share

Thanks for the support.
