### ISSUE TITLE
import  com.google.*   not  getting imported

### ISSUE THREAD

**Issue by brookyoh** [floatinghotpot/cordova-admob-pro#406]
after i create a cordova project , add the platform and install the admob plugin pro  , i get import error
on the import that start with com.google. ......    , i have istalled all the  need repose and dependencies from andorind sdk as you showed in the picture  , hwy am i getting import issue with this  what is missing  ? @floatinghotpot     can you guide me pls ..

![admob](https://cloud.githubusercontent.com/assets/5868410/15995014/4eb95cc4-3113-11e6-8307-ffe8d877c0fc.PNG)

**Comment by floatinghotpot** [comment]
Please use Android Studio instead of Eclipse.

Android Studio is the default IDE for Android project and Cordova Project.
