### ISSUE TITLE
Ionic Cordova WebView with cordova-admob-pro

### ISSUE THREAD

**Issue by naguchennai** [floatinghotpot/cordova-admob-pro#407]
I try cordova-admob-pro in my app its working fine ads working all html page. but in my cordova webview ads not show why

```javascript
.controller('register', function($scope, $cordovaAdMobPro) {
$scope.openCordovaWebView = function()
{
window.open('http://www.google.com','_self','location=no');
};

})
```

I used this code for webview. in this page i need show ads at bottom. i added admob bro code in my app.js .. ads working all other html files in android emulator . not work when i go to webview

**Comment by floatinghotpot** [comment]
this plugin is implemented based on AdMob SDK, it create a native webview and show the ad content in the native view. If you wanna open some ad in your own webview, I think it won't work.
