### ISSUE TITLE
<Google> Invalid Request. Cannot determine request type.

### ISSUE THREAD

**Issue by Mrglut** [floatinghotpot/cordova-admob-pro#408]
When program loaded I initialize AdMob plugin. Sometimes i have an error: 

> "<Google> Invalid Request. Cannot determine request type. Is your ad unit id correct?"

 and event "onAdFailedLoad'  triggered. 
Output from this event: 

> AdMob, onAdFailLoad, {'adNetwork':'AdMob','adType':'rewardvideo','adEvent':'onAdFailLoad','error':0,'reason':'Request object configured wrong.'}

But sometimes plugin loads and all working fine. Note, that when this error occurs, in this app session when trying re initialize plugin error occurs again and again. Also my unit id correct.

I am using only reward video ads and i didnt test the other ad types.

My code:

```
AdsService.service('AdsService', function($rootScope, $ionicLoading, ServerService){
  var admob = {
    rewarded_video: "ca-app-pub-XXXXX"
  };

  var rewardVideoLoaded = false;

  this.GetRewardVideoLoaded = function(){
    if (rewardVideoLoaded){
      return true;
    }
    else{
      return false;
    }
  }

  function SetRewardVideoLoaded(value){
    rewardVideoLoaded = value;
    $rootScope.$broadcast('SetRewardVideoLoaded');
  }

  this.Initialization = function(){
      rewardVideoLoaded = false;
      LoadRewardVideoAd();
  }

  function LoadRewardVideoAd(){
    AdMob.prepareRewardVideoAd({adId: admob.rewarded_video, autoShow: false}, function(result){
      }, function(error){
    });
  };

  this.ShowRewardVideoAd = function(){
    $ionicLoading.show('<ion-spinner icon="bubbles" class="spinner-stable"></ion-spinner><br/>');
    AdMob.showRewardVideoAd();
  }

  document.addEventListener('onAdFailLoad',function(data){
    if(data.adType == 'rewardvideo')
      SetRewardVideoLoaded(false);
      setTimeout(function () { 
        LoadRewardVideoAd();
      }, 2000);
    }
  });

  document.addEventListener('onAdLoaded', function(result){
    if (result.adType == 'rewardvideo')
      SetRewardVideoLoaded(true);
    }
  });

  document.addEventListener('onAdPresent', function(data){
    if(data.adType == 'rewardvideo')
      SetRewardVideoLoaded(false);
      ServerService.UserWatchedVideo().then(function(result){
      }, function(error){
      });
      LoadRewardVideoAd();
    }
    $ionicLoading.hide();
  });

  return this;
});
```

Testing on real device iPhone 5s iOS 8.1.1

 System information:

> Cordova CLI: 6.1.1
> Ionic Framework Version: 1.2.4
> Ionic CLI Version: 1.7.15
> Ionic App Lib Version: 0.7.2
> ios-deploy version: 1.8.4 
> ios-sim version: 5.0.6 
> OS: Mac OS X Yosemite
> Node Version: v5.4.0
> Xcode version: Xcode 7.2 Build version 7C68

**Comment by sarahsga** [comment]
same issue. Did you find a solution?

**Comment by Mrglut** [comment]
@sarahsga no, I am still looking for it

 Just update  LoadRewardVideoAd function to this: 

```
  function LoadRewardVideoAd(){
    if (AdMob){  //like in docs
      AdMob.prepareRewardVideoAd({adId: admob.rewarded_video, autoShow: false}, function(result){
        }, function(error){
      });
    }
  };
```
