### ISSUE TITLE
Show test banners in iOS

### ISSUE THREAD

**Issue by remisture** [floatinghotpot/cordova-admob-pro#409]
`isTesting: true` gives me this message: `<Google> To get test ads on this device, call: request.testDevices = @[ @"xxx" ];` and no banners.

How to avoid that?

**Comment by floatinghotpot** [comment]
<Google> To get test ads on this device, call: request.testDevices = @[ @"xxx" ];
This has been handled by the plugin.

If no banners show, it must be some other reason. Did you check the events "onAdLoaded" or "onAdFailLoad"?

**Comment by remisture** [comment]
`{'adNetwork':'AdMob','adType':'banner','adEvent':'onAdFailLoad','error':1,'reason':'Request Error: No ad to show.'}`

Do I have to do anything manual with Admob to get test banners?

**Comment by floatinghotpot** [comment]
it's weird if you already set isTesting:true. In many cases, only fails if there is no Ad in your area when running with isTesting:false on real device.

Can you paste your js code here?
