### ISSUE TITLE
 google admob to unity5 android  banner not shown in device 

### ISSUE THREAD

**Issue by nothingbuthappend** [floatinghotpot/cordova-admob-pro#410]
hello guys I have a trouble about admob since a week .
first I donloaded admob plugins from googleads/googleads-mobile-unity   
then opened  play servicesresolver right click selected then check resolve client jar in editor wrote succesfully done .
used this script for singleton .
-------
using UnityEngine;
using System.Collections;
using System;
using GoogleMobileAds.Api;

public class ReklamScript : MonoBehaviour
{
	private static ReklamScript instance = null;

	public string bannerID;
	public string interstitialID;

	public bool testMod = false;
	public string testDeviceID;

	private BannerView bannerReklam;
	private InterstitialAd interstitialReklam;

	void Awake()
	{
		if( instance == null )
		{
			instance = this;
			DontDestroyOnLoad( this );
		}
		else if( this != instance )
		{
			Destroy( gameObject );
			return;
		}
	}

	void Start()
	{
		if( this != instance )
			return;

		BannerReklamAl();
		InterstitialReklamAl();
	}

	void BannerReklamAl()
	{
		bannerReklam = new BannerView( bannerID, AdSize.SmartBanner, AdPosition.Top );

		AdRequest reklamiAl;
		if( testMod )
			reklamiAl = new AdRequest.Builder().AddTestDevice( AdRequest.TestDeviceSimulator )
				.AddTestDevice( testDeviceID ).Build();
		else
			reklamiAl = new AdRequest.Builder().Build();

		bannerReklam.LoadAd( reklamiAl );
		bannerReklam.Hide();
	}

	void InterstitialReklamAl()
	{
		if( interstitialReklam != null )
			interstitialReklam.Destroy();

		interstitialReklam = new InterstitialAd( interstitialID );
		interstitialReklam.OnAdClosed -= InterstitialDelegate;
		interstitialReklam.OnAdClosed += InterstitialDelegate;

		AdRequest reklamiAl;
		if( testMod )
			reklamiAl = new AdRequest.Builder().AddTestDevice( AdRequest.TestDeviceSimulator )
				.AddTestDevice( testDeviceID ).Build();
		else
			reklamiAl = new AdRequest.Builder().Build();

		interstitialReklam.LoadAd( reklamiAl );
	}

	public void InterstitialDelegate( object sender, EventArgs args )
	{
		InterstitialReklamAl();
	}

	/*void OnGUI()
    {
        if( GUI.Button( new Rect( Screen.width / 2 - 150, 0, 300, 150 ), "Banner Goster" ) )
            ReklamScript.BannerGoster();
             
        if( GUI.Button( new Rect( Screen.width / 2 - 150, 150, 300, 150 ), "Banner Gizle" ) )
            ReklamScript.BannerGizle();
         
        if( GUI.Button( new Rect( Screen.width / 2 - 150, 300, 300, 150 ), "Interstitial Goster" ) )
            ReklamScript.InsterstitialGoster();
    }
    */

	public static void BannerGoster()
	{
		if( instance == null )
			return;

		if( instance.bannerReklam == null )
			instance.BannerReklamAl();

		instance.bannerReklam.Show();
	}

	public static void BannerGizle()
	{
		if( instance == null )
			return;

		if( instance.bannerReklam == null )
			return;

		instance.bannerReklam.Hide();
	}

	public static void InsterstitialGoster()
	{
		if( instance == null )
			return;

		if( instance.interstitialReklam == null )
			instance.InterstitialReklamAl();

		instance.StopCoroutine( instance.InsterstitialCoroutine() );
		instance.StartCoroutine( instance.InsterstitialCoroutine() );
	}

	IEnumerator InsterstitialCoroutine()
	{
		while( !interstitialReklam.IsLoaded() )
			yield return null;

		interstitialReklam.Show();
	}
}

I am calling banner with ReklamScript.BannerGoster ();
here is android manifest 

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.google.unity"
    android:versionName="1.0"
    android:versionCode="1">
  <uses-sdk android:minSdkVersion="9"
      android:targetSdkVersion="19" />
  
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
  
  
  <application>
    
    <meta-data android:name="com.google.android.gms.version"
        android:value="@integer/google_play_services_version" />
    
    <activity android:name="com.google.android.gms.ads.AdActivity"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
        android:theme="@android:style/Theme.Translucent" />
    
    <activity android:name="com.google.android.gms.ads.purchase.InAppPurchaseActivity"
        android:theme="@style/Theme.IAPTheme"/>
  </application>
</manifest>
--------------------------
in editor succesfully loading ads .displaying dummy load ad ,etc.
but when I built to my device   and  boom.
there is no ads?
guys ı finished my app since 10 days but cant implementing ads to my game ..
PLS Any help will be appreciated .

**Comment by floatinghotpot** [comment]
You are using Google AdMob plugin for Unity, while this project is AdMob plugin for Cordova.

Please report bugs here:
googleads/googleads-mobile-unity

**Comment by nothingbuthappend** [comment]
thx for giving comment.can you send me a ling for download right plugin  ?
cordoba ?thx mister.
