### ISSUE TITLE
Plugin showing only isTesting = true

### ISSUE THREAD

**Issue by JohnExtatik** [floatinghotpot/cordova-admob-pro#411]
Hello,

When isTesting:true = no problem,
But if isTesting:false = "No ad to show" 

I have 2 ads campaign in google DFP (they works fine if I test on html page with Publisher Tags) but nothing in my app... 

Here is the code : 
`function LoadPub() {

          // select the right Ad Id according to platform
              var admobid = {};
              if( /(android)/i.test(navigator.userAgent) ) { 
                admobid = { // for Android
                  banner: '/139897868/RCHYBRID1',
                  interstitial: '/139897868/RCHYBRIDSPLASH'
                };
              } else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
                admobid = { // for iOS
                  banner: '/139897868/RCHYBRID1',
                  interstitial: '/139897868/RCHYBRIDSPLASH'
                };
              } else {
                admobid = { // for Windows Phone
                  banner: '/139897868/RCHYBRID1',
                  interstitial: '/139897868/RCHYBRIDSPLASH'
                };

              }

          if (! AdMob ) { console.log( 'admob plugin not ready' ); } else { console.log( 'admob plugin R E A D Y' );  }  

          	// this will create a banner on startup
            AdMob.createBanner( {
                  adId: admobid.banner,
                  position: AdMob.AD_POSITION.BOTTOM_CENTER,
                  isTesting: false, // TODO: remove this line when release
                  overlap: false,
                  offsetTopBar: false,
                  bgColor: 'black',
                  success: function(){
                    $rootScope.CloseBannerButton = true;
                    $rootScope.adDisplayed = true;
                  },
                  error: function(){
                    $rootScope.CloseBannerButton = false;
                    $rootScope.adDisplayed = false;
                  }
                } );
                document.addEventListener('onAdLoaded',function(data){
                      if(data.adType == 'banner') {
                      	AdMob.showBanner();
                      	$rootScope.CloseBannerButton = true;
                      } 
                      else if(data.adType == 'interstitial') { 
                      	interstitialIsReady = true;
                      } 
                  });
                  AdMob.prepareInterstitial({
                    adId: admobid.interstitial,
                    isTesting: false, // TODO: remove this line when release
                    autoShow: true
                  });

                   document.addEventListener('onAdFailLoad',function(data){
                      if(data.adType == 'banner') $rootScope.CloseBannerButton = false;
                  });

        }`

If someone have an idea.... 
Thx

**Comment by floatinghotpot** [comment]
If you can see the test Ad, it means the SDK and plugin are working fine.

Are you running test one a real device?

**Comment by JohnExtatik** [comment]
You're right, yes real iOS device, app from appStore (not from testflight)

**Comment by floatinghotpot** [comment]
I see that you are using the same ad unit ID for 3 platforms:
              banner: '/139897868/RCHYBRID1',
              interstitial: '/139897868/RCHYBRIDSPLASH'

I guess you cannot mix use it, and need create for each of the platforms. 

At lease for AdMob, it's one of the major fail reason. Please double check.

**Comment by JohnExtatik** [comment]
Ok, it's done, nut no result :(

Here is a console message, no links ?

`<Google:HTML> You are currently using version 7.7.0 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be downloaded from http://goo.gl/iGzfsP. A full list of release notes is available at https://developers.google.com/admob/ios/rel-notes.`

**Comment by floatinghotpot** [comment]
Then try upgrade the plugin to latest version (which is built with SDK v7.8.1), see:
 https://github.com/floatinghotpot/cordova-admob-pro/commits/master
