### ISSUE TITLE
I have implemented admobpro plugin it is working well but I need to use other mediation networks

### ISSUE THREAD

**Issue by dinu1389** [floatinghotpot/cordova-admob-pro#412]
Hi ,

Admobpro plugin is working great but i am seeing repeated ads from admob so i have added mobfox or inmobi mediation network as adsource in admob portal .Now i have installed mediation adapter.

cordova plugin add cordova-plugin-admob-mobfox

I have attached publisherid(mobfox) as adsource in the Admob portal but i am receiving ads from AdMob only . I have checked this using .

document.addEventListener('onAdLoaded',function(data){
console.log(data.adNetwork);
});

Then i have tried with mobfox test publishers id's taken from mobfox docs.

http://docs.mobfox.com/docs/inventory-hashes-for-testing?_ga=1.205760912.2024736310.1467296772

fe96717d9875b9da4339ea5367eff1ec (just added this publisher id as adsource in admob banner)
8769bb5eb962eb39170fc5d8930706a9 (banner)

I just added admob adunit id in my phonegap code.do i need to add mobfox/inmobi id's also?

admobid = { // for Android
banner: 'ca-app-pub-3929053540896618/9606309483',
};

Can you please give me a example what to do after installing other mediation plugin ?

step 1 : cordova plugin add cordova-plugin-admob-mobfox
step 2: added mobfox publisher id's for adunit in admob portal
step 3: what next ?

**Comment by floatinghotpot** [comment]
Then it should work fine. 

Just guess, as mobfox fill rate is lower than admob, to get a better fill rate, most time, the ads are from admob.

**Comment by dinu1389** [comment]
I just installed admob plugin first and then mobfox plugin, Specified adunit id in phonegap code base , added mobfox publisher id to that adunit id in admob portal 
thats it?
 if yes ,  shall i remove istesting:true property then it will fetch Mobfox ads also am I correct?

**Comment by floatinghotpot** [comment]
of course you need remove isTesting:true, as it's using the test ad unit id.

**Comment by Daz66** [comment]
Hi,

I’m having a very similar issue with no fills for the Facebook Audience Network.
I have been using AdMob Pro for some time and all is working well for AdMob’s own Ad source.
Plugin: cordova-plugin-admobpro

I recently added a Facebook AN Ad source to my AdMob banner advert, with a Placement ID as documented by Facebook.
Added plugin: cordova-plugin-admob-facebook
For testing purposes I have set the AdMob eCPM floor at $1.00 and the FAN eCPM floor to $0.01
This has ran for over a week now and Facebook say that no ad request has been made for my placement ID
What could possibly wrong?!

Many thanks in advance

**Comment by Daz66** [comment]
Additional:

I have received an email from Facebook support that says this:

1, The “cannot be bundled” means users have to manually copy the SDK to use it in the integration with AdMob. Base on agreement, Admob can develop a solution to mediate Audience Network, but has to info users to download and use latest Audience Network SDK.

2, “Facebook plugin” is not developed and maintained by Facebook in this case. I am not aware of it and do not have any information about it.

3, There are many third party solutions like Cordova AdoMob Pro Plugin try to utilize Audience Network. As long as you are using our SDK, we are trying to help the experience on Audience Network through SDK. But we cannot block these third party solutions or take over these solutions.

If you have further questions regarding to Audience Network, please contact us.
-------------------------------

So now I'm clueless!  Are they saying that what you are doing with the FB for AdMob Pro adapter is against their policies, and if not then does the adapter do all the work necessary to include the FB SDK?

what I'm really asking is is there any documentation on how these different Ad network adapters are supposed to be included into an AdMob Pro plugin setup?

I'm really struggling!

Thanks, Darren

**Comment by rodrigograca31** [comment]
Hi!

I'm with the same problem as @Daz66 ...
I've added FAN (Facebook Audience Network) plugin: `cordova plugin add cordova-plugin-admob-facebook --save` and then configured it on the AdMob site/platform, then opened the app to see if FAN ads were shown and only AdMob ads are shown....

Facebook is waiting for an ad request....

I've tried to lower the AdMod eCPM but It doesn't seem to work...

Thanks for the grate plugin!

**Comment by rodrigograca31** [comment]
I've just added a way to debug it:
```javascript
document.addEventListener('onAdLoaded',function(data){
	console.log(data.adNetwork);
	console.log(data);
	if (data.adNetwork != "AdMob") {
		alert("not AdMob!");
	}
});
```
This will give me an allert as soon as there's an ad from other than AdMob... But I'm not sure if this will work because AdMob is mediating... Does the "adNetwork" property change in this case?

**Comment by floatinghotpot** [comment]
The adNetwork is used to distinguish if you are using multiple ad plugins, like cordova-plugin-admobpro, cordova-plugin-facebookads, cordova-plugin-flury, etc.

As you are using cordova-plugin-admobpro with mediation, the adNetwork will be 'AdMob' only.

**Comment by rodrigograca31** [comment]
@floatinghotpot do we need `cordova-plugin-facebookads` to display facebook ads throu AdMob mediation? or `cordova-plugin-admob-facebook` is enough?

**Comment by Daz66** [comment]
At the moment I just have:
cordova plugin add cordova-plugin-admobpro
cordova plugin add cordova-plugin-admob-facebook

Facebook support are saying that no requests are being made to their FAN.
I'm wondering whether anyone has actually got this working, and if so can they please give their experience of how they managed it?

Many thanks.

**Comment by rodrigograca31** [comment]
@Daz66 I have the same plugins as you and the same problem, no requests....

I'm in development, I thought about releasing an update to the app with the mediation to see if the users would make requests but I think that will not work...
If I find any solution I will let you guys know.

**Comment by Daz66** [comment]
@rodrigograca31   Thanks for the info.

I was wondering whether it may be something to do with the test mode flag - but didn't want to anger the Google AdMob gods by setting it to false!  :)

**Comment by rodrigograca31** [comment]
Hey @Daz66 I just found the problem... How much are you willing to pay me to tell you the solution?

Just kidding: apparently `adSize: 'SMART_BANNER'` doesn't work with facebook....
Changing it to `adSize: 'BANNER'` made FAN ads appear.

This was pointed out by @Bnaya on issue #210 .

(Note: `isTesting: true` doesn't help either.... and I have a fixed eCPM on the AdMob site, that may also help to make this happen faster....)

@dinu1389 maybe this solves your problem too?

@floatinghotpot Can this be solved in any way? At least [should be mentioned on the documentation](https://github.com/floatinghotpot/cordova-admob-pro/wiki/1.2-Method:-AdMob.setOptions())

**Comment by Daz66** [comment]
Well done @rodrigograca31 - that was the problem in my case too.
FB are now happy and pumping ads at me. :)

I'll buy you a beer next time you're passing the Lake District, England.
But seriously, thanks - this has been bugging me for weeks.

**Comment by floatinghotpot** [comment]
Thanks to @rodrigograca31 , I was not aware of this trick before. You are really appreciated.

**Comment by shahafss** [comment]
Hey guys,

Shahaf from the Mobfox research team here :)
It seems like you guys already figured out what was the issue with dinu's code
In case you encounter any other issues or have any questions
Please shoot me an email to: Shahaf.sh@matomy.com

Thanks, and good luck !

**Comment by inepali** [comment]
i am using cordova-plugin-admobpro and tried to Mediation using MobFox, mMedia, Facebook, but result all requests with zero impressions. Any idea?

Also, once you add mMedia pluging, iOS complain during the build and Google Add SDK need to update in plugin (i saw the message one console during the simulator run on iOS), I did manually replaced working fine.

![Uploading admob.png…]()



![Uploading admob.png…]()
