### ISSUE TITLE
Android app closes after closing interstitial ad

### ISSUE THREAD

**Issue by FrancescoPallucchini** [floatinghotpot/cordova-admob-pro#413]
Published the app on Google Play. Banners and interstitials display properly, but when I touch the closing icon of the interstitial ad, the app closes.

**Comment by floatinghotpot** [comment]
Very weird behavior. Can you provide more details? version of your android, plugin, and your app id?

**Comment by FrancescoPallucchini** [comment]
Thank You for Your support and Your plugin! I am testing on a cell phone with Android 4.4.2. I downloaded cordova-admob-pro few days ago, so it should be the latest. This is the app: https://play.google.com/store/apps/details?id=com.francescopallucchini.raninemove

**Comment by FrancescoPallucchini** [comment]
The plugin I downloaded is cordova-plugin-admobpro.

**Comment by FrancescoPallucchini** [comment]
The fastest way to try the interstitial ad is to select game mode 5 (green play button with a question mark and 3 bars; press the little gear to change game mode). Then make some casual move until your energy is empty. Pressing play button in the following screen will make the interstitial appear.

**Comment by FrancescoPallucchini** [comment]
Notice that the apk builded in debug mode, with the poperty isTestig set to true, doesn't have this issue.

**Comment by floatinghotpot** [comment]
I installed and tested your app, it works fine. 

when click [X], the interstitial close and return to game. It won't quit the app.

But, if you click "return" hard key, it will exit the app. 

You'd better handle the cordova event "backbutton" and ask user to confirm exit, see: https://cordova.apache.org/docs/en/latest/cordova/events/events.html

**Comment by FrancescoPallucchini** [comment]
Thank You! I didn't use the "return" hard key, I touched the closing icon of the ad. However,  I will add the handling of backbutton and I will let You know if it fixes the problem on the cell phone I'm testing on. Thank You.

**Comment by FrancescoPallucchini** [comment]
New handlers didn't resolve the issue on my test cell phone. But I noticed that the issue happens only if the interstitial ad contains a video. If the interstitial ad contains text and illustration, the app keeps run after the closing of the ad. But if the interstitial ad contains video and audio, after closing the ad the app closes and the message "the app blocked in anomalous manner" (message translated from Italian) appears. I installed the cordova-plugin-media too, to manage the audio on Android.

Now I suspect that the reason of the block could be the audio. In my app I use few sound effect, and I never call the release method for the Media resources I created. From cordova-plugin-media documentation: 

> media.release: Releases the underlying operating system's audio resources. This is particularly important for Android, since there are a finite amount of OpenCore instances for media playback. Applications should call the release function for any Media resource that is no longer needed.

Maybe the audio in the ad is too much for my cheap test cell phone? Tomorrow I will try to work in this direction and I will let You know.

**Comment by FrancescoPallucchini** [comment]
Problem solved! Before calling AdMob.showInterstitial() I call .release() for every instance of Media I use. Then I reload the Media instances after the ad is closed, inside the handler of onAdDismiss event. Now everything works, after the interstitial ad the app continues to the next section, and every Media is again available. Thank You for Your support!
