### ISSUE TITLE
Does overlap option of Banner work?

### ISSUE THREAD

**Issue by wuxiaomo6174** [floatinghotpot/cordova-admob-pro#414]
In landscape screen, it doesn't work. 
Is it a Bug?

**Comment by floatinghotpot** [comment]
It worked quite well. As a bug report, any details?

**Comment by wuxiaomo6174** [comment]
@floatinghotpot   yea, it  wired that will leave some black border in the left and right. 
My code is like this:
   AdMob.createBanner( {
            adId: admobid.banner,
            position: AdMob.AD_POSITION.BOTTOM_CENTER,
            overlap:false,
            offsetTopBar: true,
            bgColor: 'black'
        } );
        if(AdMob) AdMob.showBanner(AdMob.AD_POSITION.BOTTOM_CENTER );

**Comment by wuxiaomo6174** [comment]
It will leave some black space in the right and left. 
My code is like this:    
AdMob.createBanner( {
            adId: admobid.banner,
            position: AdMob.AD_POSITION.BOTTOM_CENTER,
            //adSize:'SMART_BANNER',
            overlap:false,
            offsetTopBar: true,
            bgColor: 'black'
        } );
      AdMob.showBanner(AdMob.AD_POSITION.BOTTOM_CENTER );

**Comment by floatinghotpot** [comment]
It's quite normal behavior in AdMob, the ad format has some international standard, with fixed sizes. It won't exactly fit your screen sometimes, and AdMob display some dark area at left and right.
