### ISSUE TITLE
How to  specify location targeting information in creating a banner?

### ISSUE THREAD

**Issue by kalimulhaq** [floatinghotpot/cordova-admob-pro#421]
in android application we can set location when requesting Ad. 
reference: https://firebase.google.com/docs/admob/android/targeting
can we do this in cordova-admob-pro?

**Comment by floatinghotpot** [comment]
Yes, the plugin support almost all AdMob targeting. Please see docs:
https://github.com/floatinghotpot/cordova-admob-pro/tree/master/docs#targetting-options
