### ISSUE TITLE
ngCordova examples

### ISSUE THREAD

**Issue by jdnichollsc** [floatinghotpot/cordova-admob-pro#422]
Hi my friend,

What do you think to include ngCordova examples into README?

Thanks for all!

**Comment by floatinghotpot** [comment]
When cordova and plugin initialized, it will inject a child object in global `window` object. So usually you can access the object with `window.AdMob`.

In ngCordova, if you can access `window` or `$window` object, you should be okay to call the AdMob API.

BTW, make sure you have valid ad unit id, and reference cordova.js in your html file. 
```html
<script src="cordova.js"></script>
```

**Comment by jdnichollsc** [comment]
Yes, I'm agree, using **$window** service is the best way to work with Angular! :+1:
