### ISSUE TITLE
Black screen when showing interstitial ads 

### ISSUE THREAD

**Issue by Micnubinub** [floatinghotpot/cordova-admob-pro#423]
The screen is just black when showInterstitial ad is called using the cordova-plugin-admobpro plugin>>

Calling this to preload the ad:

    if (AdMob) AdMob.prepareInterstitial({
        publisherId:'pub-xxxx',
        adId: ca-app-xxxx,
        autoShow: false, isTesting: false 
    });
Then I'm calling this later to show the ad

    AdMob.isInterstitialReady(function (ready) {
        if (ready) {
             AdMob.showInterstitial();
          }
    });
When I log onAdLoaded, onAdShow and onAdFailLoad, everything seems to be loading, showing and not failing, but the screen is just black. I have tried different adIDs and have tried adding other ad networks to no avail

here is the screenshot : https://drive.google.com/file/d/0ByAYq0kXNuoVUy02ZWM3NGtLRms/view?usp=sharing

**Comment by floatinghotpot** [comment]
```javascript
if (AdMob) AdMob.prepareInterstitial({
    publisherId:'pub-xxxx', // please remove this line, publiserId is not a valid key for admob pro
    adId: ca-app-xxxx, // please use the valid ad unit id, like 'ca-app-xxx/yyy'
    autoShow: false, isTesting: false 
});
```

Please set isTesting:true to see the result of test Ad, if it works, the plugin and your code is correct.

Then, change isTesting:false, and run your app in a device.

BTW, if your admob account is new, it will take some time before your ad unit id becomes effective. (for AdMob sync their data among systems)

**Comment by Micnubinub** [comment]
Yea, I did test it on isTesting Tue, and everything was working fine, is just when I set it to false for the final release, it was just black. I wrote my own cordova-admob plugin from scratch (only supports android ATM, don't know swift or objectiveC yet, so no ios support for now) and it works, but I'll still help you guys debug

**Comment by floatinghotpot** [comment]
As everything works fine when isTesting:true, the code and plugin has nothing wrong. Please double check your ad unit id.

**Comment by floatinghotpot** [comment]
I also see such black interstitial, it seems the problem of ad content, not the plugin or SDK issue. please contact admob service team for this issue.
