### ISSUE TITLE
app crash when run createBanner()

### ISSUE THREAD

**Issue by vkatsar** [floatinghotpot/cordova-admob-pro#425]
App crashes after running createBanner function
Using cordova 6.3.0

Logs::
```
W/PluginManager(18059): THREAD WARNING: exec() call to AdMob.createBanner blocked the main thread for 1038ms. Plugin should use CordovaInterface.getThreadPool().
I/dalvikvm(18059): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.zze.zzl
W/dalvikvm(18059): VFY: unable to resolve virtual method 474: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
```
Manifest.xml includes
package="com.example.android.multidex.myapplication"
android:name="android.support.multidex.MultiDexApplication">

build.grandle

    defaultConfig {
        versionCode cdvVersionCode ?: Integer.parseInt("" + privateHelpers.extractIntFromManifest("versionCode"))
        applicationId privateHelpers.extractStringFromManifest("package")

        if (cdvMinSdkVersion != null) {
            minSdkVersion cdvMinSdkVersion
        }
	multiDexEnabled true
    }

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    compile 'com.android.support:multidex:1.0.0'    
    debugCompile project(path: "CordovaLib", configuration: "debug")
    releaseCompile project(path: "CordovaLib", configuration: "release")
    compile "com.google.android.gms:play-services-ads:+"
}

![screen shot 2016-08-03 at 02 16 25](https://cloud.githubusercontent.com/assets/1533478/17348695/af65ba38-5920-11e6-92bd-af1820e80553.png)
![screen shot 2016-08-03 at 02 15 48](https://cloud.githubusercontent.com/assets/1533478/17348702/c6a7ef54-5920-11e6-9eec-46415aaae60b.png)
![screen shot 2016-08-03 at 02 20 44](https://cloud.githubusercontent.com/assets/1533478/17348724/f19da654-5920-11e6-95c7-aef559d9fe03.png)

**Comment by floatinghotpot** [comment]
Usually when gradle or ant reports `multiple dex` error, it means multiple library conflicts, and I will resolve it by find the conflict and keep only one copy. 

Never tried to configure allowing multi dex, so not sure about the consequence.
