### ISSUE TITLE
missing exec:AdMob.createBanner

### ISSUE THREAD

**Issue by JoelAH** [floatinghotpot/cordova-admob-pro#426]
Im using the plugin with cordova in Visual studio and I am getting these errors:
missing exec:AdMob.createBanner
TypeError: Cannot read property 'createBanner' of undefined
at Object.exec 
at Object.admobExport.createBanner 
at ripple.js

**Comment by floatinghotpot** [comment]
Your plugin is not installed or initialized properly, so object "AdMob" cannot be found.

BTW, remember to refer cordova.js in your index.html.
```html
<!-- must-have, which will be created by cordova prepare/build -->
<script type="text/javascript" src="cordova.js"></script>
```

See example: 
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/test/index.html
