### ISSUE TITLE
0,Internal error - problem with open ads

### ISSUE THREAD

**Issue by eliaszkubala** [floatinghotpot/cordova-admob-pro#427]
Hello, I have a problem with your plugin so I added listeners. 

```
document.addEventListener('onAdFailLoad',function(data){
        console.log(data);
        console.log( data.error + ',' + data.reason );
        if(data.adType == 'banner') AdMob.hideBanner();
        else if(data.adType == 'interstitial') interstitialIsReady = false;
    });

    document.addEventListener('onAdLoaded',function(data){
        AdMob.showBanner();
    });
```

The error is **0,Internal error** [screenshot](https://s10.postimg.org/q2iaasoh5/error.png)
I have connection with Internet and I am testing app on real device. AdMob object is okey. 

Mayby I am doing something wrong. Let's we check together. Firstly I install your plugin

`cordova plugin add cordova-plugin-admobpro`

Next I added in config.xml below line

`<gap:plugin name="cordova-plugin-admobpro" source="npm"/>`

Then I crate this in main html file

```
var admobid = {};
    var admobdebug = false;
    admobid = {
        banner: 'ca-app-pub-4405419649702645/8667389216', // or DFP format "/6253334/dfp_example_ad"
        interstitial: 'ca-app-pub-4405419649702645/7190656012'
    };
document.addEventListener("deviceready", onDeviceReady, false);
```

Inside **onDeviceReady()** a init baner and interstitial

```
function onDeviceReady() {
        if (!AdMob) {
            //alert( 'admob plugin not ready' );
            initStore();
            return;
        } else {
            alert('admob is ready');
        }
        if (AdMob) {
            AdMob.prepareInterstitial({adId: admobid.interstitial, autoShow: true, isTesting: admobdebug});
            AdMob.createBanner({
                adId: admobid.banner,
                position: AdMob.AD_POSITION.TOP_CENTER,
                isTesting: admobdebug,
                autoShow: true
            });
        }

        initStore();
        console.log(navigator.notification);
    }
```

My banner and interstitial code are generated 1 year ago and work in 3 other apps.

**Comment by eliaszkubala** [comment]
Here is my plugin list
```
cc.fovea.cordova.purchase 6.0.0 "Purchase"
cordova-plugin-admobpro 2.19.1 "AdMob Plugin Pro"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-extension 1.5.1 "Cordova Plugin Extension"
cordova-plugin-whitelist 1.2.1 "Whitelist"
```

**Comment by eliaszkubala** [comment]
Your plugin doesn't work on HTC One m7 with Android 6.0.1. I tested it also on older device - Android 4.4.2 and it's works great. 

![13956806_1243672965664899_1217358741_n](https://cloud.githubusercontent.com/assets/5322456/17620683/48473fbe-608e-11e6-87b9-637f37e9572c.png)
![13988901_1243672985664897_964505420_n](https://cloud.githubusercontent.com/assets/5322456/17620684/484ce5cc-608e-11e6-851a-5fbe03a84070.png)

**Comment by floatinghotpot** [comment]
Error code 0 means AdMob report an internal error. Try updating your local play-service SDK, and rebuild the project.
