### ISSUE TITLE
Help, not Working Android API level 17 to 20, but OK API level 20 >  

### ISSUE THREAD

**Issue by fernandiscofernandel** [floatinghotpot/cordova-admob-pro#429]
Hi,
I am using cordova.admobpro plugin, not working me in the minor Apis to 20. In the upper yes.
6.3.0 Cordova, cordova use cli command.
-----------------
cordova-plugin-admobpro 2.19.1 "AdMob Plugin Pro"
plugin-compat-cordova 1.0.0 "Compat"
cordova-plugin-extension 1.5.1 "Cordova Plugin Extension"
cordova-plugin-extras-google-play-services 1.0.5 "Google Play Services for Android"
cordova-plugin-file 4.2.0 "File"
cordova 1.0.3-plugin-globalization "Globalization"
cordova-plugin-media 2.3.0 "Media"
cordova 1.2.2-plugin-whitelist "Whitelist"
---------------------

Not able to load it throws the error you can not load javascript.

Admob.js make the call:

enabledAdMob 
```javascript
var = true;
var admobid = {};
if (/(android)/i.test(navigator.userAgent)) {
    admobid = {
        interstitial: "ca-app-pub-xxxxxxxxxxxx / xxxxxxxxx"
    };
}

if (AdMob) AdMob.prepareInterstitial ({adId: admobid.interstitial, isTesting: false, Autoshow: false});

if (AdMob) AdMob.showInterstitial ();
```
I have not touched the config.xml Manifest.xml is not necessary or not? If you work in android api level> 20
Thank you very much and greetings.

**Comment by floatinghotpot** [comment]
This plugin is implemented based on Google AdMob SDK, it might have some API level dependency.

**Comment by fernandiscofernandel** [comment]
But admob sdk is already included in Extras-> GooglPlayService.
How I can know if I have some dependence API ?, in config.xml or Manifest.xml, it does not appear.
Cordova use cli, no Eclipse or Android Studio.
jdk1.7.0_79.jdk

Can you give me any clues?
Thank you very much for your help.

**Comment by floatinghotpot** [comment]
Run command `android sdk` to launch SDK manager, and keep the android SDK and extras (library and repo) up to date.

**Comment by fernandiscofernandel** [comment]
Thank you very much, I updated some sdk and a library.
And I deleted the plugin and add return and the problem seems solved.

Regards

**Comment by floatinghotpot** [comment]
Congratulations, good to see you have it fixed.
