### ISSUE TITLE
Interstitial display inside a browser

### ISSUE THREAD

**Issue by wilsonglasser** [floatinghotpot/cordova-admob-pro#430]
Sometimes an interstitial ads open a browser unit to display the ads.

I really don't know why...

Using Admob for interstitial ads.

![anuncio onde o game direcionou para o safari](https://cloud.githubusercontent.com/assets/342362/17746625/3eb4e710-6487-11e6-8110-5d0bce3c0336.png)

**Comment by floatinghotpot** [comment]
I think it's not an error. It's a correct behavior decided by Ad content.
