### ISSUE TITLE
Issue with danwilson/google-analytics-plugin

### ISSUE THREAD

**Issue by galcivar** [floatinghotpot/cordova-admob-pro#431]
Hi!

When I try to run your plugin with danwilson's google-analytics-plugin I get an error exactly like this one: [http://stackoverflow.com/questions/31451872/cordova-com-danielcwilson-plugins-googleanalytics-with-com-admob-google](http://stackoverflow.com/questions/31451872/cordova-com-danielcwilson-plugins-googleanalytics-with-com-admob-google)

Please see the issue I opened in their repo [#286](https://github.com/danwilson/google-analytics-plugin/issues/286). It seems it's as issue with your plugin [#262](https://github.com/danwilson/google-analytics-plugin/issues/262).

Is there an update on this? Any help will be appreciated!

**Comment by floatinghotpot** [comment]
I think you are using the wrong plugin. `com.admob.google` is not mine, it's fork from my project, but they did not make it right.

Correct plugin id is `cordova-plugin-admobpro`, and it won't conflict, as it use gradle external dependency, see: 
```xml
<framework src="com.google.android.gms:play-services-ads:+" />
```
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/plugin.xml#L48

**Comment by galcivar** [comment]
This is what I got: cordova-plugin-admobpro 2.19.1 "AdMob Plugin Pro"

**Comment by galcivar** [comment]
Seems to be the issue is with the **cordova-plugin-googleplayservices** dependency. As deleting the conflicting classes in the **/cordova-plugin-googleplayservices/google-play-services.jar** does solve the above mentioned issue although it creates new ones initaly for the analytics plugin (I'm guessing due to the missing classes).

**Comment by floatinghotpot** [comment]
it's dependent on framework instead of external `cordova-plugin-googleplayservices`, so remove `cordova-plugin-googleplayservices`

```xml
        <!-- cordova CLI using gradle and it working well -->
        <framework src="com.google.android.gms:play-services-ads:+" />
        <!-- but unfortunately, build.phonegap.com, Intel XDK, and some other tools still use ant -->
        <!-- dependency id="cordova-plugin-googleplayservices"/ -->
```

**Comment by galcivar** [comment]
And it worked! Should've known that updating the whole project needed some plugins to be removed :/ Thank you!
