### ISSUE TITLE
Text-only ad type still showing image ads

### ISSUE THREAD

**Issue by jamesl1001** [floatinghotpot/cordova-admob-pro#432]
I'd like to display only text ads in my app.

In my AdMob settings for this particular ad unit, I have only checked "Text" for the "Ad type", like so:
![Ad Type](https://cloud.githubusercontent.com/assets/2076731/17831277/34d2952e-66dc-11e6-8fb5-8fbc9b6cb526.png)

However I am still seeing image ads in my app.

I have checked the API for this plugin and can't seem to see any options regarding ad type.

I have rebuilt and reinstalled the app several times.

Is this a problem with this plugin or AdMob itself?

Thanks!

**Comment by floatinghotpot** [comment]
Could you please provide me some details, like ad unit id, your app package id or app bundle id for some troubleshooting? Send it to `rjfun.mobile@gmail.com`.
