### ISSUE TITLE
interstitials on ios 

### ISSUE THREAD

**Issue by hdmx-josef** [floatinghotpot/cordova-admob-pro#436]
i made an app with intel xdk  and jquery mobile with listview in the index.html file , i do not want the interstitial to show on startup but to show only when the user move to other page that he clicks from the listview , but interstitials never show up with the following code 

``` javascript
var admobid = {};
if( /(android)/i.test(navigator.userAgent) ) { 
    admobid = { // for Android
        banner: 'ca-app-pub-XXXXXX/XXXXXX',
        interstitial: 'ca-app-pub-XXXXXX/XXXXXX'
    };
} else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
    admobid = { // for iOS
        banner: 'ca-app-pub-XXXXXX/XXXXXX',
        interstitial: 'ca-app-pub-XXXXXX/XXXXXX'
    };
} else {
    admobid = { // for Windows Phone
        banner: 'ca-app-pub-XXXXXX/XXXXXX',
        interstitial: 'ca-app-pub-XXXXXX/XXXXXX'
    };
}

if(( /(ipad|iphone|ipod|android|windows phone)/i.test(navigator.userAgent) )) {
    document.addEventListener('deviceready', initApp, false);
} else {
    initApp();
}

function initApp() {
     if (! AdMob ) { alert( 'admob plugin not ready' ); return; } 

    AdMob.createBanner( {
        adId: admobid.banner, 
        isTesting: true,
        /*overlap: false, 
        offsetTopBar: true,*/ 
        position: AdMob.AD_POSITION.BOTTOM_CENTER,
        bgColor: 'black',
        autoShow: true
    } );

    AdMob.prepareInterstitial({
      adId:admobid.interstitial,
      isTesting: true,
      autoShow: false,
    });
    AdMob.showInterstitial();

}
```

obviously  i am using the real ad units ids in the above code but have no idea why the interstitials do not show up .

i appreciate any help with this issue 1

thank you
JOSEF

**Comment by psimondk** [comment]
I get this error:  Cannot find an ad network adapter with the name(s): com.mobfox.adapter.MobFoxAdapter

**Comment by floatinghotpot** [comment]
1. remember to have this line in your index.html:
```html
<script type="text/javascript" src="cordova.js"></script>
```

2. double check whether you are using the wrong ad unit id, for example, on ios, you can only use the ad unit id created for ios app.

3. change `isTesting: true` to `isTesting: false`.

4. call `AdMob.showInterstitial();` when your user click.

**Comment by hdmx-josef** [comment]
Thanks floatinghotpot , when i use the following code everything is working fine 
`AdMob.prepareInterstitial({
      adId:admobid.interstitial,
      autoShow: true,
    });`

the problem is when i use the autoShow: false , i need the  , AdMob.showInterstitial(); to show when the user clicks any link on the page to navigate to other page  ,how do i call AdMob.showInterstitial(); when a user click ? i would appreciate it if you give me the exact code !

thanks a lot for your help !
Josef

**Comment by floatinghotpot** [comment]
if you use `autoShow:false`, you need trigger the show with user action or event, for example, when game is over, when navigate to a page, or when user click a button. 

example code (if you use jQuery):
```javascript
$('button#viewad').click(function(){
    AdMob.showInterstitial();
});
```

**Comment by hdmx-josef** [comment]
THANKS floatinghotpot 
i successfully managed  to get the interstitial to show when the user navigates to the next page with this code
` AdMob.prepareInterstitial({
      adId:admobid.interstitial,
      autoShow: false
    });
    var elements = document.getElementsByTagName('a');
for(var i = 0, len = elements.length; i < len; i++) {
    elements[i].onclick = function () {
    AdMob.showInterstitial();
    setInterval(AdMob.showInterstitial, 10*60*1000);
    }
}`

i still have a problem with the setInterval(AdMob.showInterstitial, 10*60*1000); to show only every 10 minutes because it is now showing every click , something is wrong !

THANKS for your help
josef

**Comment by floatinghotpot** [comment]
It's not a good idea to show ad with timer. As it will interrupt user action, and may trigger unexpected click, which is forbidden by google.

Try trigger the show ad with event, navigation, or user action only.

**Comment by hdmx-josef** [comment]
you are right regarding google but the other pages don't not have any a links  , i tested the click function and it works good in the index.html file which is the jquery menu . 
that is why i need the timer so if a user comes back after 5 minutes to the index.html file and clicks another link so doesn't show the Interstitial , it should show only after 10 minutes or longer .

thanks for your help and i will see if i manage to do it !
