### ISSUE TITLE
interstitial issue/misundestunding

### ISSUE THREAD

**Issue by telekosmos** [floatinghotpot/cordova-admob-pro#437]
Hi there
I am facing the following scenario in an ionic/cordova app:
- start the app
- initialize the the ads unit ids
- creates the interstitial
- then, in the controller of the initial view I show the interstitial
- this is repeated every time the app is run

I know the interstitial is created (or, at least, the `prepareInterstitial` method is called and its success callback is run). 
Then, in the initial view's controller, I call a `showInterstitial` and I know its success callback is run. Also, the `onAdPresent` event is triggered.

The issue is, when I close the app and then rerun again, the startup flow is pretty much the same but the interstitial is not showing: its success callback is called but the `onAdPresent` is not triggered.

This scenario only is happening in android!!!, in iOS everything goes smooth

Environment:
- cordova 6.2
- platform android@5.1.1
- cordova-plugin-admobpro 2.19.1 👍 
- cordova-plugin-crosswalk-webview 1.5.0
- (...) more plugins (...)

Any hint is very welcome

Cheers in advance and very good plugin

**Comment by floatinghotpot** [comment]
I just guess, in android, when you close the app, the process does not really exit.

Note: Before each showInterstitial, you need call prepareInterstitial() once again.

**Comment by telekosmos** [comment]
hey, thanks for the reply!!!
Actually, now I am seeing it is happening also in iOS :-/.
I can provide the code which is run. This is an angular factory exporting the functionality. The piece of code in the factory where I prepare the interstitial is:
```javascript
function initInterstitial(autoShow) {
      var deferred = $q.defer();
      var defaultOpts = {
        adId: admobid.interstitial,
        autoShow: typeof autoShow !== 'undefined' ? autoShow : true,
        isTesting: true,
        success: function() {
          console.log('Interstitial created!!!');
          deferred.resolve();
        },
        error: function() {
          console.log('Failed to created interstitial');
          deferred.reject();
        }
      };

      $window.AdMob.prepareInterstitial(defaultOpts);

      return deferred.promise;
    }
```
I know this is run (and, apparently, successfully) as I can se the _'Interstitial created!!!'_ message in the console.
Then, the part where the interstitial is shown is easier:
```javascript
function showInterstitial() {
      $window.AdMob.showInterstitial(function() {
        console.log('Interstitital showed ok');
      }, function() {
        console.log('Failed to show the interstitial');
      });
    };
```
Also, I can see the in the console _'Interstitial showed ok'_ message.

Before preparing the interstitial, I register to the `onAdPresent` event, as:
```javascript
$document.bind('onAdPresent', function(data) {
        console.log('$document.bind(onAdPresent): ' + JSON.stringify(data));
        if (data.adType == 'rewardvideo') {
          console.log(data.rewardType);
          console.log(data.rewardAmount);
        }
});
```
Despite I always can see the _'Interstitial showed ok'_ message, I can't see the event triggered along with it, which is confusing me more. I dunno whether or not there is some scenario where the ads are not shown despite following all these steps, but I don't get any other clue/error.

I am trying to modify my codebase in the case I can miss some events which can provide more information or just the flow is wrong, but the fact the interstitial seems to be prepared and then not shown is driving me quite confused.

Cheers!!!!
