### ISSUE TITLE
black & blank ads and errors

### ISSUE THREAD

**Issue by svmszcck** [floatinghotpot/cordova-admob-pro#444]
Helloi am getting black blank banner and in android logcat i am getting this error: JS: Uncaught ReferenceError: AFMA_ReceiveMessage is not defined I googled and stackowerflowed it but couldn't find a solution. What can i do? I am using the plugin as it is explained in git repo. I think the problem is about sdk.

After a couple of app starts now i am getting this error in logcat and still black & blank banner ad.

"Receiver error Http response code: 403 " 
"There was a problem getting an ad response. ErrorCode: 0 " 
"Failed to load ad: 0"

http://i.stack.imgur.com/g8wQA.png 
http://i.stack.imgur.com/2E4Q1.png 

Thanks...

**Comment by floatinghotpot** [comment]
Did you use the wrong ad unit id? For example, if you create an ad unit for ios, but use it on android, it may cause such error. If use create an ad unit for banner, but use it for interstitial, it may also cause such error.

**Comment by svmszcck** [comment]
No i did not. I am using exactly the same and right ad id. Admob team replied to my question in their forum. I will send my ad id them.  They will check it.
