### ISSUE TITLE
Interstitial ad not working when a button is clicked

### ISSUE THREAD

**Issue by Touficbatache** [floatinghotpot/cordova-admob-pro#445]
Hey,

I am using this plugin to show interstitial and banner ads in my app. I made a function called donate() and in js, in the function I added : 
`if(AdMob) AdMob.showInterstitial();`

I want to make a donate button so people can click the button and a interstitial ad show up!

The whole code is :

``` javascript
var admobid = {};
if( /(android)/i.test(navigator.userAgent) ) { 
  admobid = {
    banner: 'banner-id',
    interstitial: 'interstitial-id'
  };
}

function initApp() {
  if (AdMob) AdMob.createBanner( {
    adId: admobid.banner,
    position: AdMob.AD_POSITION.BOTTOM_CENTER,
    overlap: false,
    offsetTopBar: false,
    bgColor: 'white',
    orientationRenew: true
  } );

  if (AdMob) AdMob.prepareInterstitial({
    adId: admobid.interstitial,
    autoShow: true
  });
}

if(( /(android)/i.test(navigator.userAgent) )) {
    document.addEventListener('deviceready', initApp, false);
} else {
    initApp();
}

function donate() {
    if(AdMob) AdMob.showInterstitial();
}
```

**Comment by floatinghotpot** [comment]
Please check:
* Did you refer to `cordova.js` in your index.html?
* Did you use a valid ad unit id, created for the exact platform and exact type?
* Did you test it on a real device instead of simulator?

If you are testing on android, please get some logs with LogCat, if testing on iOS, get some logs with Xcode. With more details, it will be easier to troubleshoot.

**Comment by Touficbatache** [comment]
All of these are true... I refered to cordova.js, used a valid unit id
(because I used autoshow on prepareInterstitial and it worked and banners
are showing) and I am testing on my own android device!

**Comment by sysads** [comment]
Was this ever fixed?

**Comment by Touficbatache** [comment]
No, just make a function in which you prepare the interstitial and add an
auto show then call the function and tadaaa!
