### ISSUE TITLE
How to stop admob in some pages?

### ISSUE THREAD

**Issue by maxlinux2000** [floatinghotpot/cordova-admob-pro#446]
Hi
I have an app width admob working just fine, but I want to stop the ads in some pages (simple html pages)

How to do it?

**Comment by floatinghotpot** [comment]
just call AdMob.hideBanner() when switch to the page.

**Comment by maxlinux2000** [comment]
yea.. I tried to add in the head of html page a simple

```
<script>
 AdMob.hideBanner();
</script>

```
but the ads are also loaded...

**Comment by floatinghotpot** [comment]
First all, not a good idea to use multiple pages, as when page html file loads, it need re-run all the referenced javascript files, including cordova.js, which will re-init the plugin.

In Cordova apps, you'd better write only 1 page of index.html, then dynamically change the content in div, then you only init the plugin once.
