### ISSUE TITLE
Example Usage Code

### ISSUE THREAD

**Issue by GiovanniL19** [floatinghotpot/cordova-admob-pro#447]
Hi,

Sorry if this is a silly question, I am still new to cordova. Where do I write the javascript usage code please?

Thank you in advance

**Comment by floatinghotpot** [comment]
There is no silly question, only silly answers. :-)

See some example code here:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/test/index.html

Of course, you need learn how to use cordova first.

**Comment by GiovanniL19** [comment]
Ha I like that :D 
Thank you very much @floatinghotpot !!
