### ISSUE TITLE
Which one is interstitial id and ads id

### ISSUE THREAD

**Issue by freddy-daniel** [floatinghotpot/cordova-admob-pro#449]
**Can you little help which one is interstitial id and ads id.I got this from AdMob**

> Hello,

Follow the instructions below to finish implementing AdMob in your app.

Download the Google Mobile Ads SDK.
Follow the SDK integration guide. Specify ad type, size, and placement when you integrate the code.
App: Pic-Mob (Android)
App ID: ca-app-pub-6862823256626444~2168573608

Ad unit(s):

Name: ads
Format: Interstitial
ID: ca-app-pub-6862823256626444/3645776800

For SDK integration questions, check out the Google Mobile Ads SDK Technical forum. For AdMob product questions, visit the AdMob help center.

Sincerely,
The AdMob Team

**Comment by floatinghotpot** [comment]
Format: Interstitial
ID: ca-app-pub-6862823256626444/3645776800

This one is ad unit id, use this one.

**Comment by freddy-daniel** [comment]
If that is interstitial which one is banner .Is that my AdMob publisher id or something else where i can find it please help?

  {
      **banner**: 'ca-app-pub-xxx/zzz',  //ca-app-pub-6862823256626444/3645776800
      **interstitial**: 'ca-app-pub-xxx/kkk'
    };

**Comment by floatinghotpot** [comment]
You need login into AdMob portal, select your app, then create ad unit, select type "banner".

**Comment by freddy-daniel** [comment]
Thanks for i got it.
