### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by choppermio** [floatinghotpot/cordova-admob-pro#451]
this is my code

http://pastebin.com/CWDGKp22

```html
<html>
  <head>
    <title>Device Ready Example</title>

    <script type="text/javascript" charset="utf-8" src="cordova.js"></script>
    <script type="text/javascript" charset="utf-8">

    // Wait for device API libraries to load
    //
    function onLoad() {
        document.addEventListener("deviceready", onDeviceReady, false);
    }

    // device APIs are available
    //
    function onDeviceReady() {
        // Now safe to use device APIs
        var admobid = {};

// TODO: replace the following ad units with your own
if( /(android)/i.test(navigator.userAgent) ) { 
     admobid = { // for Android
                banner: 'i put my key here',
                interstitial: 'i put my key here'
            };
        } else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
            admobid = { // for iOS
                banner: 'i put my key here',
                interstitial: 'i put my key here'
            };
        } else {
            admobid = { // for Windows Phone
                banner: 'i put my key here',
                interstitial: 'i put my key here'
            };
        }
 

function initApp() {
  if (! AdMob ) { alert( 'admob plugin not ready' ); return; }

  // this will create a banner on startup
  AdMob.createBanner( {
    adId: admobid.banner,
    position: AdMob.AD_POSITION.BOTTOM_CENTER,
 //   isTesting: true, // TODO: remove this line when release
    overlap: false,
    offsetTopBar: false,
    bgColor: 'black'
  } );
setInterval(function(){
  // this will load a full screen ad on startup
  AdMob.prepareInterstitial({
    adId: admobid.interstitial,
   // isTesting: true, // TODO: remove this line when release
    autoShow: true
  });
  alert('fsf')
  },5000);
}

if(( /(ipad|iphone|ipod|android|windows phone)/i.test(navigator.userAgent) )) {
    document.addEventListener('deviceready', initApp, false);
} else {
    initApp();
}
    }

    </script>
  </head>
  <body onload="onLoad()">
  </body>
</html>
```
i put my key here(that i replaced the sense with my real admob key)

i get this error (Uncaught SyntaxError: Invalid or unexpected token) in GapDebug and not interstitial  ads showed

**Comment by floatinghotpot** [comment]
`Uncaught SyntaxError: Invalid or unexpected token`, something is wrong with your javascript code. Try running your html file in a web browser to locate the syntax error.

**Comment by choppermio** [comment]
this error even in your example 
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/test/admob_simple.js
when isTesting:true it works when i remove that line no interstitial ads showed
and this is in log cat 

`9-05 20:15:27.823 2777-2888/io.cordova.hellocordova D/GraphicBuffer: register, handle(0xaf949400) (w:812 h:490 s:816 f:0x1 u:0x000f02)
09-05 20:15:28.410 2777-2803/io.cordova.hellocordova I/Ads: No fill from ad server.
09-05 20:15:28.413 2777-2777/io.cordova.hellocordova W/Ads: Failed to load ad: 3
09-05 20:15:28.670 2777-2777/io.cordova.hellocordova D/SettingsInterface:  from settings cache , name = show_password , value = null
09-05 20:15:28.677 2777-2777/io.cordova.hellocordova W/cr_AwContents: onDetachedFromWindow called when already detached. Ignoring
09-05 20:15:28.723 2777-2777/io.cordova.hellocordova I/cr_Ime: ImeThread is not enabled.
09-05 20:15:29.127 2777-2888/io.cordova.hellocordova D/GraphicBuffer: register, handle(0xaf949470) (w:812 h:490 s:816 f:0x1 u:0x000f02)
`
i don't know the problem from admob or the plugin cause the fill rate drop very hard for me

**Comment by floatinghotpot** [comment]
No fill is a different issue, but the code has no syntax error.  Just change the ad unit to your own, it should work.
