### ISSUE TITLE
IOS Build Failed

### ISSUE THREAD

**Issue by hsmith825** [floatinghotpot/cordova-admob-pro#452]
I upgraded admobpro 2.13.0 to admobpro 2.19.1.  I am using Xcode version 7.3.1.

I am getting the following build errors in CDVAdMobPlugin.m:
    1. I am getting  Implicit conversion of int to NSString disallowed in ARC .
    2. Use of undeclared identifier 'ADTYPE_REWARDVIDEO'

Any help is appreciated.
Thanks!
Howard

**Comment by floatinghotpot** [comment]
```bash
cordova plugin rm cordova-plugin-extension
cordova plugin add cordova-plugin-extension
```

**Comment by hsmith825** [comment]
Hi floatinghotpot, Thanks for your suggestion!

I changed from cordova-plugin-extension 1.2.1  to cordova-plugin-extension 1.5.0.  That did not help.  I still get the same two errors.  One thing I should mention is that I had an error  with a suggest fix to change interstitialREADY to interstitialId.  I made that change as well and that did eliminate that referenced problem.

Any other suggestions?
Thanks!
Howard

**Comment by floatinghotpot** [comment]
```bash
cordova plugin rm cordova-plugin-pro
cordova plugin rm cordova-plugin-extension

rm -rf ~/.npm/cordova-plugin-extension
rm -rf ~/.npm/cordova-plugin-pro

cordova plugin add cordova-plugin-pro
```

**Comment by hsmith825** [comment]
Hi, 
Thanks for your help.  I solved the problem with you help.  The problem is if you use --save when you add the plugin, the extension is not saved.  I added <plugin name="cordova-plugin-extension" spec="~1.5.1" /> to config.xml and it works.
Thanks!
