### ISSUE TITLE
Do we need to add facebook admob too 

### ISSUE THREAD

**Issue by ezazwar1** [floatinghotpot/cordova-admob-pro#453]
hey i was wondering as i saw the setting in the admob dashboard to add facebook  audience network 
do we need to add facebook ad plugin too

**Comment by floatinghotpot** [comment]
No need to add facebook ad plugin, instead, you need add the mediation adapter plugin. Please check the README.

**Comment by ezazwar1** [comment]
do we need to also write code for mediation adapter or will it work automatically

**Comment by floatinghotpot** [comment]
No need to write code for mediation, but you need configure in AdMob Portal, to link the mediation network to your ad unit id.
