### ISSUE TITLE
Google stops support for android SDK 6.4.1 and lower

### ISSUE THREAD

**Issue by apollonin** [floatinghotpot/cordova-admob-pro#454]
Hi! I've got an email that google stops support android SDK v 6.4.1 and lower. Does it affect this plugin? I just can not find info about used SDK here.
Thanks

**Comment by floatinghotpot** [comment]
This plugin depends on the latest extra SDK you installed when you build APK. I think most developers should have installed quite new version. 

See Google's release note here:
https://firebase.google.com/docs/admob/release-notes#android

**Comment by apollonin** [comment]
Oh, i got it! Thanks a lot for the answer
