### ISSUE TITLE
No close buttons on DFP banners ?

### ISSUE THREAD

**Issue by zabojad** [floatinghotpot/cordova-admob-pro#457]
I display in my app a 320 x 50 banner from DFP.

It displays correctly but does not have a close button (like on interstitials) so that the user can close it...

[The screenshots here](https://github.com/floatinghotpot/cordova-admob-pro#screenshots) suggest that there should be such a button...

**Comment by zabojad** [comment]
@floatinghotpot is this a bug ?

**Comment by floatinghotpot** [comment]
The close button is provided in Ad resource or DFP SDK, not this plugin. We can do nothing about it.
