### ISSUE TITLE
I got below [email] from ad mob... what version of plugin is compatible with this regulation...?

### ISSUE THREAD

**Issue by lse123** [floatinghotpot/cordova-admob-pro#458]
I got below [email] from ad mob... what version of plugin is compatible with this regulation...?

Hi AdMob Publisher,
In early July, we sent out a notice to AdMob Publishers who have apps running on SDK version 6.4.1 and lower, to inform them about deprecating SDK versions and the need to upgrade by September 15, 2016.
We apologize for any inconvenience or unclarity that the email may have caused to some developers. To ensure that you have sufficient time to make the changes, we have extended the deprecation date to October 17, 2016. We also reevaluated the SDK versions being deprecated, so here is the updated information.
What will happen starting on October 17, 2016:
•
All support for non-Google Play Services supported SDKs and Google Mobile Ads SDK version listed here will be deprecated.
•
This means that all traffic from these SDKs will be disabled.
What you will need to do:
In order to ensure that your AdMob ads continue to serve after October 17, 2016, please upgrade your apps to run on the minimum SDK versions listed here. If you are using a Google Mobile Ads SDK version from Play Services that is listed on this link, you are not required to take any action.
If you have any questions, please contact us on the developer forum.
Thank you, and stay tuned for more updates and tips.
Cheers, 
The AdMob Team

**Comment by floatinghotpot** [comment]
Take it easy. See answer in same question, #454

**Comment by lse123** [comment]
I get lost,... the developer in my Intel XDK says Liming Xie... is this the plugin for this developer?

https://github.com/floatinghotpot/cordova-admob-pro

**Comment by floatinghotpot** [comment]
floatinghotpot is nickname of Liming Xie ...

Simply ignore this warning, as 6.x is very old, most SDK is 7/8/9.x, it won't impact this plugin.

**Comment by lse123** [comment]
Take it easy. See answer in same question, #454 https://github.com/floatinghotpot/cordova-admob-pro/issues/454

YOU SAY THIS - BUT I AM USING INTEL XDK latest version - build online and I download apk... am i covered [no problem]??
