### ISSUE TITLE
A little demo showing how to delay interstital

### ISSUE THREAD

**Issue by benoit1980** [floatinghotpot/cordova-admob-pro#463]
Hello,

Would you have a demo that shows how to delay the interstitial ad please? or Simply have it showing up when a specific button is clicked? Thanks!

Hi,

I would like to delay the interstitial of lets say 10 seconds, how to do this please? This seems to be missing from your doc.

``` javascript
function initApp() {
  if (! AdMob ) { alert( 'admob plugin not ready' ); return; }

  // this will create a banner on startup
    AdMob.createBanner( {
    adId: admobid.banner,
    position: AdMob.AD_POSITION.BOTTOM_CENTER,
    isTesting: true, // TODO: remove this line when release
    overlap: false,
    offsetTopBar: false,
    bgColor: 'black'
  } );

  // this will load a full screen ad on startup
  /*AdMob.prepareInterstitial({
    adId: admobid.interstitial,
    isTesting: true, // TODO: remove this line when release
    autoShow: true
  });*/
}

if(( /(ipad|iphone|ipod|android|windows phone)/i.test(navigator.userAgent) )) {
    document.addEventListener('deviceready', initApp, false);
} else {
    initApp();
}

```

At the moment it is loading on app init but this is not good and causes the app to get banned.

Thanks in advance for your help.

**Comment by floatinghotpot** [comment]
Assuming you are using jQuery:

```javascript
$('button#yourbuttonid').click(function(){
  if(AdMob) {
    AdMob.isInterstitialReady(function(){
      AdMob. showInterstitial();
    });
  }
});
```

**Comment by benoit1980** [comment]
Thanks!
I am trying to do it in pure javascript with intel SDK,  would this work please?
function show_interstitial_app(){
    AdMob.createBanner( {
    adId: admobid.banner,
    position: AdMob.AD_POSITION.BOTTOM_CENTER,
    isTesting: true, 
    overlap: false,
    offsetTopBar: false,
    bgColor: 'black'
  } );
    
}



    $(document).on("click", ".uib_w_17", function(evt)
    {
          uib_sb.toggle_sidebar($(".uib_w_1")); 
         setTimeout(show_interstitial_app, 3000); <------------------
         return false;
    });

**Comment by floatinghotpot** [comment]
Not good, createBanner() is creating a permanent banner, not a one-time interstitial. So it should be called only once, not every time of click.

**Comment by benoit1980** [comment]
My apology, I pasted the wrong code! :-(

Here it is:

function show_interstitial_app(){
    AdMob.createBanner( {
    adId: admobid.banner,
    position: AdMob.AD_POSITION.BOTTOM_CENTER,
    isTesting: true, // TODO: remove this line when release
    overlap: false,
    offsetTopBar: false,
    bgColor: 'black'
  } );
}

    $(document).on("click", ".uib_w_17", function(evt)
    {
          uib_sb.toggle_sidebar($(".uib_w_1")); 
         setTimeout(show_interstitial_app, 3000); <------------------
         return false;
    });


I think this should work, awaiting for my app to get generated, taking ages with intel sdk....

**Comment by benoit1980** [comment]
just tried...it is failing too....what a pain!!

**Comment by ejfrias** [comment]
Try this: 

```
AdMob.prepareInterstitial({
	adId: admobid.interstitial,
	autoShow: false
});

$(document).on("click", ".uib_w_17", function(evt)
{
	uib_sb.toggle_sidebar($(".uib_w_1")); 
	setTimeout(function(){
		AdMob.showInterstitial();
	}, 3000);
	return false;
});
```
