### ISSUE TITLE
Banner Ads show below the tab bar

### ISSUE THREAD

**Issue by dwinnbrown** [floatinghotpot/cordova-admob-pro#464]
I have followed the tutorial/installation guide set out on the ReadMe.md file and am trying to find a way to position the banner at the bottom of the view but on top of the tab bar which I currently have.

Currently the banner ads show below the tab bar (see [image](http://imgur.com/a/RR1vM)) but they should site on top of it and at the same time not overlap the content. Is there a setting I am missing here?

Code:

```
  AdMob.createBanner( {
    adId: admobid.banner,
    position: AdMob.AD_POSITION.BOTTOM_CENTER,
    isTesting: true, // TODO: remove this line when release
    overlap: false,
    offsetBottomBar: true,
    offsetTopBar: false
  } );
```

**Comment by floatinghotpot** [comment]
The banner cannot be displayed above your tab bar.

Please be aware that, all your content is displayed in a native webview, while ad banner is another native view. They cannot be displayed inside one another.

**Comment by dwinnbrown** [comment]
Ok thanks for explaining. 

Doesn't this go against the human interface guidelines if tabs are above an ad banner?

Thanks

**Comment by floatinghotpot** [comment]
You can put the banner at top of the screen, or use interstitial instead.
