### ISSUE TITLE
How do we get the License key

### ISSUE THREAD

**Issue by francois-n-dream** [floatinghotpot/cordova-admob-pro#466]
We bought some hours ago the license, but we did not get any license key.

How do we get the license key?

Thank you!

**Comment by floatinghotpot** [comment]
Sorry for a few delay, as we are in holiday. The license has been just sent to you, please check the email and follow the instruction. Enjoy monetisation.

**Comment by francois-n-dream** [comment]
Perfect - enjoy your vacation!
