### ISSUE TITLE
ADMOB undefined in ionic app

### ISSUE THREAD

**Issue by sashacarvajal94** [floatinghotpot/cordova-admob-pro#468]
Hi, I’m having a lot of trouble getting admob to work on my app, i’ve been 2 weeks researching for a solution to my problem but no luck yet, my problem is that admit variable is undefined:

Here is the factory:

``` javascript
.factory('AdMob', function ($window){
 var admob = $window.AdMob;

 if(admob)
 {
   // Register AdMob events
   // new events, with variable to differentiate: adNetwork, adType, adEvent
   document.addEventListener('onAdFailLoad', function(data){
     console.log('error: ' + data.error +
     ', reason: ' + data.reason +
     ', adNetwork:' + data.adNetwork +
     ', adType:' + data.adType +
     ', adEvent:' + data.adEvent); // adType: 'banner' or 'interstitial'
   });
   document.addEventListener('onAdLoaded', function(data){
     console.log('onAdLoaded: ' + data);
   });
   document.addEventListener('onAdPresent', function(data){
     console.log('onAdPresent: ' + data);
   });
   document.addEventListener('onAdLeaveApp', function(data){
     console.log('onAdLeaveApp: ' + data);
   });
   document.addEventListener('onAdDismiss', function(data){
     console.log('onAdDismiss: ' + data);
   });

   var defaultOptions = {
     // bannerId: admobid.banner,
     // interstitialId: admobid.interstitial,
     // adSize: 'SMART_BANNER',
     // width: integer, // valid when set adSize 'CUSTOM'
     // height: integer, // valid when set adSize 'CUSTOM'
     position: admob.AD_POSITION.BOTTOM_CENTER,
     // offsetTopBar: false, // avoid overlapped by status bar, for iOS7+
     bgColor: 'black', // color name, or '#RRGGBB'
     // x: integer,     // valid when set position to 0 / POS_XY
     // y: integer,     // valid when set position to 0 / POS_XY
     isTesting: true, // set to true, to receiving test ad for testing purpose
     // autoShow: true // auto show interstitial ad when loaded, set to false if prepare/show
   };
   var admobid = {};

   if(ionic.Platform.isAndroid())
   {
     admobid = { // for Android
       banner: 'ca-app-pub-6869992474017983/9375997553',
       interstitial: 'ca-app-pub-6869992474017983/1657046752'
     };
   }

   if(ionic.Platform.isIOS())
   {
     admobid = { // for iOS
       banner: 'ca-app-pub-8411076950619415/4316130686',
       interstitial: 'ca-app-pub-6869992474017983/7563979554'
     };
   }

   admob.setOptions(defaultOptions);

   // Prepare the ad before showing it
   //       - (for example at the beginning of a game level)
   admob.prepareInterstitial({
     adId: admobid.interstitial,
     autoShow: false,
     success: function(){
       console.log('interstitial prepared');
     },
     error: function(){
       console.log('failed to prepare interstitial');
     }
   });
 }
 else
 {
   console.log("No AdMob?");
 }

 return {
   showBanner: function() {
     if(admob)
     {
       admob.createBanner({
         adId:admobid.banner,
         position:admob.AD_POSITION.BOTTOM_CENTER,
         autoShow:true,
         success: function(){
           console.log('banner created');
         },
         error: function(){
           console.log('failed to create banner');
         }
       });
     }
   },
   showInterstitial: function() {
     if(admob)
     {
       // If you didn't prepare it before, you can show it like this
       // admob.prepareInterstitial({adId:admobid.interstitial, autoShow:autoshow});

       // If you did prepare it before, then show it like this
       //       - (for example: check and show it at end of a game level)
       admob.showInterstitial();
     }
   },
   removeAds: function() {
     if(admob)
     {
       admob.removeBanner();
     }
   }
 };
})

```

And the controller:

``` javascript
.controller('AdsCtrl', function($scope, $ionicActionSheet, AdMob, iAd) {

    $scope.manageAdMob = function() {

        // Show the action sheet
        var hideSheet = $ionicActionSheet.show({
            //Here you can add some more buttons
            buttons: [
                { text: 'Show Banner' },
                { text: 'Show Interstitial' }
            ],
            destructiveText: 'Remove Ads',
            titleText: 'Choose the ad to show',
            cancelText: 'Cancel',
            cancel: function() {
                // add cancel code..
            },
            destructiveButtonClicked: function() {
                console.log("removing ads");
                AdMob.removeAds();
                return true;
            },
            buttonClicked: function(index, button) {
                if(button.text == 'Show Banner')
                {
                    console.log("show banner");
                    AdMob.showBanner();
                }

                if(button.text == 'Show Interstitial')
                {
                    console.log("show interstitial");
                    AdMob.showInterstitial();
                }

                return true;
            }
        });
    };
```

I have the plugin admob pro installed and Cordova CLI 5.0.0

I really really appreciate if you could help with this!

**Comment by floatinghotpot** [comment]
The AdMob object is not undefined, means either you did not create it properly.

Please double check you have this line in your index.html:
```html
<!-- must-have, which will be created by cordova prepare/build -->
<script type="text/javascript" src="cordova.js"></script>
```

Here is a simple demo to use it in Ionic, but not with controllers, you may have a try to make sure it works, then do some porting work.
https://github.com/floatinghotpot/admob-demo-app-ionic/tree/master/demo

Good luck!

**Comment by sashacarvajal94** [comment]
I followed your steps in the Quick Start of admobpro plugin:

    # create a demo project
    cordova create test1 com.rjfun.test1 Test1
    cd test1
    cordova platform add android
    cordova platform add ios

    # now add the plugin, cordova CLI will handle dependency automatically
    cordova plugin add cordova-plugin-admobpro

    # now remove the default www content, copy the demo html file to www
    rm -r www/*;
    cp plugins/cordova-plugin-admobpro/test/* www/;

    # now build and run the demo in your device or emulator
    cordova prepare; 
    cordova run android; 
    cordova run ios;
    # or import into Xcode / eclipse


but it is still giving me undefined! :( I've tried to emulate it in my phone, and in the simulator of my computer and when i check my plugins it gives me this 

MBP-de-Sasha:test1 sashacarvajal$ ls -l plugins
total 24
drwxr-xr-x  11 sashacarvajal  staff   374 Oct 11 12:20 cordova-plugin-admobpro
drwxr-xr-x   8 sashacarvajal  staff   272 Oct 11 12:20 cordova-plugin-extension
drwxr-xr-x  11 sashacarvajal  staff   374 Oct 11 12:18 cordova-plugin-whitelist
-rw-r--r--   1 sashacarvajal  staff   612 Oct 11 12:20 fetch.json
-rw-r--r--   1 sashacarvajal  staff  5774 Oct 11 12:37 ios.json


what can it be? how can i be sure the plugin is installed correctly? I tried emulating in ios

**Comment by sashacarvajal94** [comment]
and this is my ionic info


Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by floatinghotpot** [comment]
Yes, very weird issue if you exactly follow the instructions.

Then try the most simple verification steps (it will auto run the steps):

```bash
sudo npm install -g plugin-verify
plugin-verify cordova-plugin-admobpro ios
plugin-verify cordova-plugin-admobpro android
```

**Comment by sashacarvajal94** [comment]
its still not workin, when i run 

plugin-verify cordova-plugin-admobpro ios

it displays the emulator on my computer, but stills does not shows the ad banner

Any other ideas on what it might be happening??? :(

**Comment by floatinghotpot** [comment]
I just re-run the command `plugin-verify cordova-plugin-admobpro ios`, and it load the test app correctly, see attached picture.

The only question I can imagine is, which country are you located, are you blocked to access Google service?

![test1](https://cloud.githubusercontent.com/assets/2339512/19632093/b0e30320-99d5-11e6-82fa-bac49a74346c.jpg)
![test2](https://cloud.githubusercontent.com/assets/2339512/19632095/b6e8e4ce-99d5-11e6-9d9f-1206b1f2d20f.jpg)

**Comment by sashacarvajal94** [comment]
Does it works for IOS? to emulate in IOS is the same than Android?

**Comment by floatinghotpot** [comment]
I've just upgraded the admob sdk for ios to v7.15.0, and re-verified the plugin working well. please update the plugin and try again.

**Comment by kelvinblade** [comment]
Your system information:

Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.1 Build version 8B62

cordova-plugin-admobpro 2.25.0 "AdMob Plugin Pro"

I am getting Uncaught ReferenceError: AdMob is not defined

I tried both AdMob and window.AdMob

Here's the code I used:


 ```
.run(function($ionicPlatform) {
 $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if (window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
      cordova.plugins.Keyboard.disableScroll(true);

    }
    if (window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }
  });
  if (ionic.Platform.isAndroid()) {
    var admobid = {};
    if (/(android)/i.test(navigator.userAgent)) {
      admobid = { // for Android
        banner: 'ca-app-pub-1332258519895616/6710698886',
        interstitial: 'ca-app-pub-1332258519895616/6291896488'
      };
    } else if (/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
      admobid = { // for iOS
        banner: 'ca-app-pub-6869992474017983/4806197152',
        interstitial: 'ca-app-pub-6869992474017983/7563979554'
      };
    } else {
      admobid = { // for Windows Phone
        banner: 'ca-app-pub-6869992474017983/8878394753',
        interstitial: 'ca-app-pub-6869992474017983/1355127956'
      };
    }

    if (!AdMob) {
      alert('admob plugin not ready');
      return;
    }

    AdMob.createBanner({
      adId: admobid.banner,
      isTesting: true,
      overlap: false,
      offsetTopBar: false,
      position: AdMob.AD_POSITION.BOTTOM_CENTER,
      bgColor: 'black'
    });

    AdMob.prepareInterstitial({
      adId: admobid.interstitial,
      autoShow: true
    });
  }
})
```

**Comment by floatinghotpot** [comment]
In ionic, you need access window as $window, so AdMob should be accessed as $window.AdMob.

Here is a complete working demo for Inoic, written by my friend @jaivehall:
https://github.com/jaivehall/admob-ionic-demo

See: https://github.com/jaivehall/admob-ionic-demo/blob/master/demo/js/services.js#L14
