### ISSUE TITLE
cordova-admob-pro support Windows Phone 8 ?

### ISSUE THREAD

**Issue by qngnht** [floatinghotpot/cordova-admob-pro#47]
Im using cordova-admob-pro, but I wonder if it supports WIndows Phone 8 ? and how to use it for wp 8 ?

**Comment by ricardobarrospereira** [comment]
I've tested here aswell in many ways and it doesn't show on wp8.1 device... no banner or interstitial. I've downloaded your jumprope xap file and installed it but it keeps loading forever without any banner, and also your test index file doesn't work.

**Comment by andreszs** [comment]
I tested it with Cordova 4.2.0 under WP8.1 and nothing is shown, while it works on Android only.

Should I buy a support license? I need to make it work under WP8 urgently, thanks.

**Comment by mobilino** [comment]
I have exactly the same problem too. iOS and Android are working perfectly, nothing shows using WP 8.1.
I use Phonegap Build with 3.6.3.

**Comment by floatinghotpot** [comment]
I've merged the code from dbaseman and did some bugfix. it's build pass with a demo project with phonegap build service, but not tested on device yet. 

could you please help to verify the plugin wp8 code?

**Comment by ricardobarrospereira** [comment]
Almost there! I've tried with your index file on phonegap build, and it worked fine, showed the initial banner at the bottom and it shows the interstitial. But there are still some bugs:

1. When I tried to change the banner size, for example, selecting "medium_rectangle" and clicked on "create", the app auto closed;

2. When I clicked on "remove banner", the app auto closed. (hide banner is working fine.);

3. Interstitial not showing automatically when selecting the option "auto show when ready" and click on prepare, I had to click on "show" anyway.

4. The first time I tried to show interstitial,  it loads and shows properly, BUT, if I try to show interstitial 2 or more times, it displays an error (the error is on the last image attached).

Btw, i've also configured on my personal project with CLI and it is also working fine, but when I call the interstitial for the second time, the app auto close.

Here are some images:

![wp_ss_20150225_0001](https://cloud.githubusercontent.com/assets/7256843/6374781/dee8396a-bcf1-11e4-92aa-48a00f3a1cdf.png)
![wp_ss_20150225_0002](https://cloud.githubusercontent.com/assets/7256843/6374782/deedfcb0-bcf1-11e4-872d-efef29244425.png)
![wp_ss_20150225_0003](https://cloud.githubusercontent.com/assets/7256843/6374783/def4cc66-bcf1-11e4-8118-f4ea98be9bd4.png)

**Comment by Udinra** [comment]
As suggested by you sharing the issue details on this thread.

I am using this plugin to display Admob ads in my app.It is working for Android but not for Windows Phone 8.I am outlining the code and details for your reference.

        //********************
        // Start of Admob code
        //********************
                    var admobid = {};
                    if( /(android)/i.test(navigator.userAgent) ) { 
                        admobid = { // Android Admob ad code
                            banner: 'my android admob code pasted here'
                        };
                        } else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
                         //   admobid = { // for iOS I do not want iOS app
                            //    banner: 'ca-app-pub-6869992474017983/4806197152'
                       // };
                        } else {
                            admobid = { // my windows phone admob code
                            banner: 'my windows phone admob code pasted here'
                        };
                    }

                    function initApp() {
                        if (AdMob) {
                            AdMob.createBanner({
                            adId : admobid.banner,
                            position : AdMob.AD_POSITION.BOTTOM_CENTER,
                            autoShow : true
                            });
                        }
                    } 

I am calling initApp function from ondeviceready.The App code remain same for Android as well as Windows Phone. But on WIndows Phone the ads are not getting displayed. If I comment the initApp call from ondeviceready my app is working fine for Windows.So there is something which halts the flow of app.

Note I am using Intel XDK for my development and have used 2.7.4 version of your plugin with Cordova CLI 4.1.2.And I am doing Legacy Windows Phone 8 build

Do let me know in case more information is required from my side

**Comment by softexe** [comment]
Hello,

I have found the issue with calc webview's height in dependence of device orientation. Current code calcs only height, width isn't calculated and doesn't check the device orientation with application starts.
I have changed method to this

```
		/// Set cordova view height based on banner height and frame orientation
		private void setCordovaViewHeight(PhoneApplicationFrame frame, CordovaView view) {
			bool deduct = bannerVisible && (! overlap);

			if (frame.Orientation == PageOrientation.Portrait ||
			    frame.Orientation == PageOrientation.PortraitDown ||
			    frame.Orientation == PageOrientation.PortraitUp) {
				if(initialViewHeight > initialViewWidth){ //was portrait
					view.Height = initialViewHeight - (deduct ? BANNER_HEIGHT_PORTRAIT : 0);
					view.Width = initialViewWidth;
					}else{
					view.Height = initialViewWidth - (deduct ? BANNER_HEIGHT_PORTRAIT : 0);
					view.Width = initialViewHeight;
					}
				
			} else {
				if(initialViewHeight > initialViewWidth){ //was landscape
					view.Height = initialViewWidth - (deduct ? BANNER_HEIGHT_LANDSCAPE : 0);
					view.Width = initialViewHeight;
				}else{
					view.Height = initialViewHeight - (deduct ? BANNER_HEIGHT_LANDSCAPE : 0);
					view.Width = initialViewWidth;
				}				
			}

			fireEvent ("window", "resize", null);
		}
```

**Comment by floatinghotpot** [comment]
I've verified this plugin on a Lumia windows phone and prove it works. I will close this issue.
