### ISSUE TITLE
Danger!!! THIS PLUGIN TAKE UP TO 30% of your money!!!

### ISSUE THREAD

**Issue by sashastg** [floatinghotpot/cordova-admob-pro#470]
Hello guys,
**If my calculation is right, author stole only from me  around 20 000 usd!!!**

i had used this plugin in my projects time a while, and thought that  only 2% of ad traffic they takes.
but few days ago i found this thread:
https://github.com/floatinghotpot/cordova-admob-pro/issues/450
i made small research myself and i had noticed that  %  different per every project.
so, they manually change % which they takes!

As i noticed, new projects (and not popular)  has 0%, but if your project has good traffic, its can be 30%.  and you will never know about it!!!
every time when your app starts, it calls authors server and sends "app id" and get back as response what % author will take. 

Test yourself what % they takes on your apps. Its will take just 2 mins and save you a lot of money.
1) download and open charlesproxy.com   - they have 30 days free trial.
2) in your device -  change network settings to use proxy address from charleys.
in my case it  was  (192.168.0.104  and port:8888)
thats it!  now you can see all network data which your device sends/receive.

open your app and you will see something like me:
![screenshot at oct 12 09-15-33](https://cloud.githubusercontent.com/assets/5595929/19300801/ea521882-9064-11e6-8cd0-299b026dca40.png)
![screenshot at oct 12 09-40-41](https://cloud.githubusercontent.com/assets/5595929/19300802/ea58e64e-9064-11e6-99e7-3e2f5a23d492.png)

r - means what % they take.

https://github.com/userweb/expose-liar-plugin/blob/master/GenericAdPlugin.java#L380
this.adlicRate = e.optInt("r");
this.testTraffic = (new Random()).nextInt(100) < this.adlicRate;

If my calculation is right, he stole only from me   ~ around 20k usd!!!
WTF?

I want detailed explanation from author.

**Comment by ezazwar1** [comment]
omg that thing is wrong @floatinghotpot  you should be honest if u want 30% you can write it in your readme 

i will check my self and reply the results i get back

**Comment by floatinghotpot** [comment]
As in the discussion #450, I asked for the package id to double check, I just guessed a fake license key is used and trigger some punishment logic. But the anonymous issue reporter @userweb never reply, and just fade away in the following discussions. 

@sashastg, please let me know your package id to double check what's wrong. BTW, why @@sashastg is also an anonymous user with nothing posted in github, again?

**Comment by sashastg** [comment]
i am not active user on github. as you can see i had created account on 2013.
its commercial project.

i had never used fake license key!
i just copy code and used it, as everyone other developers. 
we need focus on our apps and not on cheating license key which cost $20.
you lie when you trying to explain your 30%  as some mistake and you do it for cheaters.
you are not fair.

no one can be sure that you change settings for app on your server any time when you want and set any %.

two of my applications had 30% (my best apps with high traffic).
one 10%
one 2%
few applications had 0%  (because there was no traffic).

every one check your apps!
i think this guy will change settings of his server so maybe its will works as must to be for some time. but who knows when he will back settings back?

**Comment by sashastg** [comment]
good question:

> If 30% is 20 000USD, then 2% is 1333 USD. Why not choose the commercial option, pay only $20 to get a valid license? Quite confused...
i just forget about this 2%.
just insert your plugin and forget about it. and continue used it on another projects.

2) i am not anymyos:
here is my facebook: https://www.facebook.com/sashastg

**Comment by sashastg** [comment]
my position is simple:

everyone check your apps. and if response right now 0-2%.  check it again in some time. maybe in week, or in month.  

some time same as me you will detect that percentage comes 10-30% - write it here.
so if i will be not alone, its will be hard for author  go away from the answers on questions.

**Comment by floatinghotpot** [comment]
@sashastg, let me know your app id for a double check. And, a valid license is now required for your case, please read the license agreement for details, thanks.

**Comment by ezazwar1** [comment]
i had a look on aerserv plugin @sashastg  i am currently working on it to make it work and if successful then i will migrate towards aerserv cause i feel too that there is something wrong with this plugin cause as i use the plugin onesignal and i can see there are lots of users using the app but the impression count is too low

**Comment by MBuchalik** [comment]
@ezazwar1 You could also try the open source admob plugin (cordova-admob... without "pro"). Integrating it into my app was just a tiny bit more work than with cordova-admob-pro but now I know for sure how the whole source code looks like. It might look like a "DIY" plugin but it is actually pretty easy to use. The only problem is that the iOS Admob SDK hasn't been updated to version >= 7.11.0. But I am pretty confident that we can fix this as well.

**Comment by ezazwar1** [comment]
i tried the admob but its not working and no ads are shown

**Comment by ezazwar1** [comment]
i personally feel aerserv is better cause u can integrate 44 ad mediations and only one plugin needs to be installed and you have full control . I tried it and it worked fine for the test ad but i am having problem when i add the production key . That shows an error no ads to show.

**Comment by MBuchalik** [comment]
The admob plugin does work. I am using it and ads are getting displayed correctly. You could open an issue on the cordova-admob page to find the problem (in case you don't manage to get the other plugin to work properly). But that's not related to the issue here anyway :-)

**Comment by floatinghotpot** [comment]
@sashastg, please drop me an email, and list your app ids for a double check. it's more cost effective to get a commercial license key to disable the ad sharing in your case.

**Comment by floatinghotpot** [comment]
@sashastg, we see your valid license key now, and double checked to confirm ad sharing is disabled.

**Comment by sashastg** [comment]
why you changed title of issue and closed my topic?
you said you get license key, but i never emailed to you. how you get it?

**Comment by floatinghotpot** [comment]
* I checked your facebook homepage, and know your name.
* I received your paypal payment, and send you the license key.
* in our authentication server, we see about 20 app id with your license key, and double confirm the ad sharing for all of them is disabled.

**Comment by palmtreeint** [comment]
Floating hot pot, thanks for the plug in.  We appreciate the code.  How do we pay for the commercial license and can you Please make a demo showing how to get the reward ads to work? We are struggling to get them 100%

**Comment by floatinghotpot** [comment]
Please read the license agreement at bottom of README file, it will link to more details in Wiki docs, and a link to a purchase page.

After you pay via PayPal, we will send you the license key via email. Then you can send us private email and ask for further support.

**Comment by palmtreeint** [comment]
Great.  Thank you

**Comment by userweb** [comment]
@floatinghotpot  you is a liar !!!!!!!!!!!!!!!!!!
your code stolen our dollars


thanks @sashastg   i know your angry

**Comment by floatinghotpot** [comment]
@sashastg already spent $20 to get a commercial license to disable the ad traffic sharing for all this apps.

@userweb  please buy a license and show me your package id, I will double check it for you.

**Comment by Venkat-TTapp** [comment]
@floatinghotpot thanks for this wonderful plugin and various support model. I was not aware of ad sharing until this point of time.. (just somehow stumbled upon this page now).

Although my admob impression is in few hundreds, I would like to buy commercial license as 2% ad may bypass the admob block setting.

Please let me know if this license for one single app or can be used of multiple app? At present I use this plugin for 4 apps.
