### ISSUE TITLE
Error: more than one library with package name 'com.google.android.gms'

### ISSUE THREAD

**Issue by cyclonmaster** [floatinghotpot/cordova-admob-pro#471]
> D:\cordova>cordova plugin add cordova-plugin-admobpro --save
> D:\cordova>cordova platform add android
> Adding android project...
> Creating Cordova project for the Android platform:
>         Path: platforms\android
>         Package: com.cygnosis729.KursusFlyers
>         Name: KursusFlyers
>         Activity: MainActivity
>         Android target: android-23
> Android project created with cordova-android@5.2.2
> Installing "cordova-google-play-services" for android
> Installing "cordova-plugin-admobpro" for android
> Installing "cordova-plugin-extension" for android
> Dependent plugin "cordova-plugin-extension" already installed on android.
> Installing "cordova-plugin-inappbrowser" for android
> Installing "cordova-plugin-whitelist" for android
> 
> ```
>            This plugin is only applicable for versions of cordova-android gr
> ```
> 
> eater than 4.0. If you have a previous platform version, you do _not_ need this
> plugin since the whitelist will be built in.
> 
> D:\cordova>cordova build android
> ANDROID_HOME=C:\Users\mkhairunns\AppData\Local\Android\sdk
> JAVA_HOME=C:\Program Files\Java\jdk1.8.0_20
> Starting a new Gradle Daemon for this build (subsequent builds will be faster).
> Incremental java compilation is an incubating feature.
> :preBuild UP-TO-DATE
> :preDebugBuild UP-TO-DATE
> :checkDebugManifest
> :CordovaLib:preBuild UP-TO-DATE
> :CordovaLib:preDebugBuild UP-TO-DATE
> :CordovaLib:compileDebugNdk UP-TO-DATE
> :CordovaLib:compileLint
> :CordovaLib:copyDebugLint UP-TO-DATE
> :CordovaLib:mergeDebugProguardFiles
> :CordovaLib:packageDebugRenderscript UP-TO-DATE
> :CordovaLib:checkDebugManifest
> :CordovaLib:prepareDebugDependencies
> :CordovaLib:compileDebugRenderscript
> :CordovaLib:generateDebugResValues
> :CordovaLib:generateDebugResources
> :CordovaLib:packageDebugResources
> :CordovaLib:compileDebugAidl
> :CordovaLib:generateDebugBuildConfig
> :CordovaLib:mergeDebugShaders
> :CordovaLib:compileDebugShaders
> :CordovaLib:generateDebugAssets
> :CordovaLib:mergeDebugAssets
> :CordovaLib:processDebugManifest
> :CordovaLib:processDebugResources
> :CordovaLib:generateDebugSources
> :CordovaLib:incrementalDebugJavaCompilationSafeguard
> :CordovaLib:compileDebugJavaWithJavac
> :CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have ch
> anged, no previous execution, etc.).
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> :CordovaLib:processDebugJavaRes UP-TO-DATE
> :CordovaLib:transformResourcesWithMergeJavaResForDebug
> :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
> :CordovaLib:mergeDebugJniLibFolders
> :CordovaLib:transformNative_libsWithMergeJniLibsForDebug
> :CordovaLib:transformNative_libsWithSyncJniLibsForDebug
> :CordovaLib:bundleDebug
> :cordova-google-play-services:google-play-services_lib:preBuild UP-TO-DATE
> :cordova-google-play-services:google-play-services_lib:preDebugBuild UP-TO-DATE
> :cordova-google-play-services:google-play-services_lib:compileDebugNdk UP-TO-DAT
> E
> :cordova-google-play-services:google-play-services_lib:compileLint
> :cordova-google-play-services:google-play-services_lib:copyDebugLint UP-TO-DATE
> :cordova-google-play-services:google-play-services_lib:mergeDebugProguardFiles
> :cordova-google-play-services:google-play-services_lib:packageDebugRenderscript
> UP-TO-DATE
> :cordova-google-play-services:google-play-services_lib:checkDebugManifest
> :cordova-google-play-services:google-play-services_lib:preDebugAndroidTestBuild
> UP-TO-DATE
> :cordova-google-play-services:google-play-services_lib:preDebugUnitTestBuild UP-
> TO-DATE
> :cordova-google-play-services:google-play-services_lib:prepareAndroidCordovaLibU
> nspecifiedDebugLibrary
> :cordova-google-play-services:google-play-services_lib:prepareDebugDependencies
> :cordova-google-play-services:google-play-services_lib:compileDebugRenderscript
> :cordova-google-play-services:google-play-services_lib:generateDebugResValues
> :cordova-google-play-services:google-play-services_lib:generateDebugResources
> :cordova-google-play-services:google-play-services_lib:packageDebugResources
> :cordova-google-play-services:google-play-services_lib:compileDebugAidl
> :cordova-google-play-services:google-play-services_lib:generateDebugBuildConfig
> :cordova-google-play-services:google-play-services_lib:mergeDebugShaders
> :cordova-google-play-services:google-play-services_lib:compileDebugShaders
> :cordova-google-play-services:google-play-services_lib:generateDebugAssets
> :cordova-google-play-services:google-play-services_lib:mergeDebugAssets
> :cordova-google-play-services:google-play-services_lib:mergeDebugResources
> :cordova-google-play-services:google-play-services_lib:processDebugManifest
> :cordova-google-play-services:google-play-services_lib:processDebugResources
> :cordova-google-play-services:google-play-services_lib:generateDebugSources
> :cordova-google-play-services:google-play-services_lib:incrementalDebugJavaCompi
> lationSafeguard
> :cordova-google-play-services:google-play-services_lib:compileDebugJavaWithJavac
> 
> :cordova-google-play-services:google-play-services_lib:compileDebugJavaWithJavac
> - is not incremental (e.g. outputs have changed, no previous execution, etc.).
>   :cordova-google-play-services:google-play-services_lib:processDebugJavaRes UP-TO
>   -DATE
>   :cordova-google-play-services:google-play-services_lib:transformResourcesWithMer
>   geJavaResForDebug
>   :cordova-google-play-services:google-play-services_lib:transformClassesAndResour
>   cesWithSyncLibJarsForDebug
>   :cordova-google-play-services:google-play-services_lib:mergeDebugJniLibFolders
>   :cordova-google-play-services:google-play-services_lib:transformNative_libsWithM
>   ergeJniLibsForDebug
>   :cordova-google-play-services:google-play-services_lib:transformNative_libsWithS
>   yncJniLibsForDebug
>   :cordova-google-play-services:google-play-services_lib:bundleDebug
>   :prepareAndroidCordovaGooglePlayServicesGooglePlayServices_libUnspecifiedDebugLi
>   brary
>   :prepareAndroidCordovaLibUnspecifiedDebugLibrary
>   :preReleaseBuild UP-TO-DATE
>   :CordovaLib:preReleaseBuild UP-TO-DATE
>   :CordovaLib:compileReleaseNdk UP-TO-DATE
>   :CordovaLib:copyReleaseLint UP-TO-DATE
>   :CordovaLib:mergeReleaseProguardFiles
>   :CordovaLib:packageReleaseRenderscript UP-TO-DATE
>   :CordovaLib:checkReleaseManifest
>   :CordovaLib:prepareReleaseDependencies
>   :CordovaLib:compileReleaseRenderscript
>   :CordovaLib:generateReleaseResValues
>   :CordovaLib:generateReleaseResources
>   :CordovaLib:packageReleaseResources
>   :CordovaLib:compileReleaseAidl
>   :CordovaLib:generateReleaseBuildConfig
>   :CordovaLib:mergeReleaseShaders
>   :CordovaLib:compileReleaseShaders
>   :CordovaLib:generateReleaseAssets
>   :CordovaLib:mergeReleaseAssets
>   :CordovaLib:processReleaseManifest
>   :CordovaLib:processReleaseResources
>   :CordovaLib:generateReleaseSources
>   :CordovaLib:incrementalReleaseJavaCompilationSafeguard
>   :CordovaLib:compileReleaseJavaWithJavac
>   :CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have
>   changed, no previous execution, etc.).
>   Note: Some input files use or override a deprecated API.
>   Note: Recompile with -Xlint:deprecation for details.
>   :CordovaLib:processReleaseJavaRes UP-TO-DATE
>   :CordovaLib:transformResourcesWithMergeJavaResForRelease
>   :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
>   :CordovaLib:mergeReleaseJniLibFolders
>   :CordovaLib:transformNative_libsWithMergeJniLibsForRelease
>   :CordovaLib:transformNative_libsWithSyncJniLibsForRelease
>   :CordovaLib:bundleRelease
>   :cordova-google-play-services:google-play-services_lib:preReleaseBuild UP-TO-DAT
>   E
>   :cordova-google-play-services:google-play-services_lib:compileReleaseNdk UP-TO-D
>   ATE
>   :cordova-google-play-services:google-play-services_lib:copyReleaseLint UP-TO-DAT
>   E
>   :cordova-google-play-services:google-play-services_lib:mergeReleaseProguardFiles
> 
> :cordova-google-play-services:google-play-services_lib:packageReleaseRenderscrip
> t UP-TO-DATE
> :cordova-google-play-services:google-play-services_lib:checkReleaseManifest
> :cordova-google-play-services:google-play-services_lib:preReleaseUnitTestBuild U
> P-TO-DATE
> :cordova-google-play-services:google-play-services_lib:prepareAndroidCordovaLibU
> nspecifiedReleaseLibrary
> :cordova-google-play-services:google-play-services_lib:prepareReleaseDependencie
> s
> :cordova-google-play-services:google-play-services_lib:compileReleaseRenderscrip
> t
> :cordova-google-play-services:google-play-services_lib:generateReleaseResValues
> :cordova-google-play-services:google-play-services_lib:generateReleaseResources
> :cordova-google-play-services:google-play-services_lib:packageReleaseResources
> :cordova-google-play-services:google-play-services_lib:compileReleaseAidl
> :cordova-google-play-services:google-play-services_lib:generateReleaseBuildConfi
> g
> :cordova-google-play-services:google-play-services_lib:mergeReleaseShaders
> :cordova-google-play-services:google-play-services_lib:compileReleaseShaders
> :cordova-google-play-services:google-play-services_lib:generateReleaseAssets
> :cordova-google-play-services:google-play-services_lib:mergeReleaseAssets
> :cordova-google-play-services:google-play-services_lib:mergeReleaseResources
> :cordova-google-play-services:google-play-services_lib:processReleaseManifest
> :cordova-google-play-services:google-play-services_lib:processReleaseResources
> :cordova-google-play-services:google-play-services_lib:generateReleaseSources
> :cordova-google-play-services:google-play-services_lib:incrementalReleaseJavaCom
> pilationSafeguard
> :cordova-google-play-services:google-play-services_lib:compileReleaseJavaWithJav
> ac
> :cordova-google-play-services:google-play-services_lib:compileReleaseJavaWithJav
> ac - is not incremental (e.g. outputs have changed, no previous execution, etc.)
> .
> :cordova-google-play-services:google-play-services_lib:processReleaseJavaRes UP-
> TO-DATE
> :cordova-google-play-services:google-play-services_lib:transformResourcesWithMer
> geJavaResForRelease
> :cordova-google-play-services:google-play-services_lib:transformClassesAndResour
> cesWithSyncLibJarsForRelease
> :cordova-google-play-services:google-play-services_lib:mergeReleaseJniLibFolders
> 
> :cordova-google-play-services:google-play-services_lib:transformNative_libsWithM
> ergeJniLibsForRelease
> :cordova-google-play-services:google-play-services_lib:transformNative_libsWithS
> yncJniLibsForRelease
> :cordova-google-play-services:google-play-services_lib:bundleRelease
> :prepareComAndroidSupportSupportV42400Library
> :prepareComGoogleAndroidGmsPlayServicesAds961Library
> :prepareComGoogleAndroidGmsPlayServicesAdsLite961Library
> :prepareComGoogleAndroidGmsPlayServicesBase961Library
> :prepareComGoogleAndroidGmsPlayServicesBasement961Library
> :prepareComGoogleAndroidGmsPlayServicesClearcut961Library
> :prepareComGoogleAndroidGmsPlayServicesGass961Library
> :prepareComGoogleAndroidGmsPlayServicesTasks961Library
> :prepareDebugDependencies
> :compileDebugAidl
> :compileDebugRenderscript
> :generateDebugBuildConfig
> :mergeDebugShaders
> :compileDebugShaders
> :generateDebugAssets
> :mergeDebugAssets
> :generateDebugResValues
> :generateDebugResources
> :mergeDebugResources
> :processDebugManifest
> :processDebugResources FAILED
> 
> FAILURE: Build failed with an exception.
> - What went wrong:
>   Execution failed for task ':processDebugResources'.
>   >
>   BUILD FAILED
> 
> Total time: 7 mins 54.696 secs
> Error: more than one library with package name 'com.google.android.gms'
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug
>   option to get more log output.
>   Error: cmd: Command failed with exit code 1 Error output:
>   Note: Some input files use or override a deprecated API.
>   Note: Recompile with -Xlint:deprecation for details.
>   Note: Some input files use or override a deprecated API.
>   Note: Recompile with -Xlint:deprecation for details.
> 
> FAILURE: Build failed with an exception.
> - What went wrong:
>   Execution failed for task ':processDebugResources'.
>   
>   > Error: more than one library with package name 'com.google.android.gms'
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug
>   option to get more log output.

I get error as above. How to fix this?

**Comment by floatinghotpot** [comment]
The error is caused by "Installing "cordova-google-play-services" for android", please remove it.

The admob pro plugin has its dependency in plugin.xml, will automatically load when install.

**Comment by cyclonmaster** [comment]
I use latest cordova 6.3.1

Installing "cordova-google-play-services" for android

is run by default by cordova. How to remove it?
Is this correct?

cordova plugin rm cordova-google-play-services --save

**Comment by floatinghotpot** [comment]
```bash
cordova plugin rm cordova-google-play-services
```
