### ISSUE TITLE
Error: cordova-google-play-services, File path too long

### ISSUE THREAD

**Issue by cyclonmaster** [floatinghotpot/cordova-admob-pro#472]
> BUILD FAILED
> 
> Total time: 4 mins 47.915 secs
> Error: cmd: Command failed with exit code 1 Error output:
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 
> FAILURE: Build failed with an exception.
> - What went wrong:
>   Execution failed for task ':cordova-google-play-services:google-play-services_li
>   b:mergeDebugResources'.
>   > D:\xampp\htdocs\projects\KursusFlyers\KursusFlyers\cordova\platforms\android\c
>   ordova-google-play-services\KursusFlyers-google-play-services_lib\res\drawable-m
>   dpi\common_signin_btn_text_disabled_focus_light.9.png: Error: File path too long
>   on Windows, keep below 240 characters : D:\xampp\htdocs\projects\KursusFlyers\K
>   ursusFlyers\cordova\platforms\android\cordova-google-play-services\KursusFlyers-
>   google-play-services_lib\build\intermediates\res\merged\debug\drawable-mdpi-v4\c
>   ommon_signin_btn_text_disabled_focus_light.9.png

Without cordova-admob-pro plugin, I can compile fine.
But after install plugin, I get this file path too long error.
I can move out the cordova file out to root path to reduce the file path and compile fine.

It's messy to move file out every time I want to compile the mobile app when I usually do the development and debugging using xampp server.

Any suggestion?

**Comment by floatinghotpot** [comment]
It's windows issue, try put your project to a simple folder at root.
