### ISSUE TITLE
Banner ad overlaps webview when screen is rotated

### ISSUE THREAD

**Issue by willadamskeane** [floatinghotpot/cordova-admob-pro#473]
I have an ad positioned at the bottom of the screen. On start, it correctly pushes the Webview above it. However, if I rotate the device 90 degrees, into landscape mode, the ad updates but is now overlapping the navbar which is positioned at the bottom of the screen as well. If I rotate back to portrait mode, the ad is still overlapping the content.

**Comment by floatinghotpot** [comment]
Thanks for the bug report. Could you please provide more details?
1. ios, or android? which version?
2. cordova and plugin version?
3. even better if some screenshot.

**Comment by lurkas34** [comment]
Something new on that issue?
The issue is occuring on iOS 10.1.1 with cordova 6.4.0 (ionic)
cordova-plugin-admobpro ver 2.24.0

Its really easy to reproduce. The banner works well unless you change the screen orientation. Then it behaves as with overlap: true.

**Comment by BenjaminKobjolke** [comment]
Seems that the Workaround from lurkas34 is not always working.

**Comment by willadamskeane** [comment]
Yeah still having this issue. Haven't found a decent workaround that works consistently.

**Comment by floatinghotpot** [comment]
As the banners for portrait and landscape have different size, you may need to re-create the banner after screen rotated. 

Try set the option: `orientationRenew:true`

**Comment by gonzoradio** [comment]
Was there ever a solution to this that doesn't involve updating the SDK? I can't further upgrade my mac os or xcode.  For me the container that holds the banner drops away on change orientation, but the banner stays and is stuck as overlapping the webview. I'd be happy to just make the entire ad unit disappear on rotation, which i can do, but turning back to portrait view makes the overlapping banner come back. Thanks for an advice!

**Comment by floatinghotpot** [comment]
As mentioned, As the banners for portrait and landscape have different size, you may need to re-create the banner after screen rotated. Try set the option: `orientationRenew:true`

Another simple solution is, build your app in fixed orientation and do not allow it rotate. In most occasions, it's enough.

**Comment by gonzoradio** [comment]
Thank you so much for you reply. I decided to try your suggestion a second time and managed to make it happen. You have saved my week!! Thank you!!!!  I can sleep now.
