### ISSUE TITLE
Ads not showing in latest cordova (6.4.0)

### ISSUE THREAD

**Issue by rraju007** [floatinghotpot/cordova-admob-pro#476]
Hi , before I was working on it , it's a fantastic ads solution I think , but yesterday I updated my Cordova version its now - 6.4.0 , after that my ads not showing :( 
What's wrong , Please clear me , Thanks

**Comment by mjurczyk** [comment]
See https://github.com/floatinghotpot/cordova-admob-pro/issues/478#issuecomment-258679091 for temporary solution for iOS.

**Comment by floatinghotpot** [comment]
I've just upgraded the admob sdk for ios to v7.15.0, and re-verified the plugin working well. please update the plugin and try again.
