### ISSUE TITLE
still showing Test ads, removed isTesting too!!!

### ISSUE THREAD

**Issue by megaappcaesarapps** [floatinghotpot/cordova-admob-pro#480]
I already removed isTesting, line even in release and signed App it is showing only test ads

Please check the code..

`/**** AdmobPro Code ****/
		  
			// select the right Ad Id according to platform
			if( /(android)/i.test(navigator.userAgent) ) {
				admobid = { // for Android
					banner: 'ca-app-pub-xxxxxxxxxx/xxxxxxxx',
					interstitial: 'ca-app-pub-xxxxxxxxx/xxxxxxxx'
				};
			}
	  if(window.AdMob) AdMob.createBanner( {publisherId:admobid.banner, position:AdMob.AD_POSITION.BOTTOM_CENTER,autoShow:true} );
	/**** AdmobPro Code End.****/
	
  });
  //Display interstitial Ad
  $ionicPlatform.on('pause', function() {
		//Do something here on entering background
		 if(window.AdMob) AdMob.prepareInterstitial({publisherId: admobid.interstitial,autoShow: true});
	});`

Please help me on this, I am loosing revenue...

**Comment by floatinghotpot** [comment]
Please check and make sure:
1. you are running the apps on device, not simulator. On simulator, it will always show test ad.
2. you are using a valid ad unit id, not a test id.

**Comment by megaappcaesarapps** [comment]
Hi dear, thank you so much for the quick reply, I really appreciate that, before I give answer I need to admit that your issue support is one of the best among Cordva Plugins :)

1. I am testing in device only, not in simulator,

2. I have made ad unit id as regular, how do I check it is for test or regular in Admob?

Thanks again

**Comment by floatinghotpot** [comment]
Then really weird that you see test ad only. Could you please paste some screenshot?

**Comment by megaappcaesarapps** [comment]
Hi dear,

please check the links:
1. [http://appsmonk.tk/cdn/admob (1).png](url)
2. [http://appsmonk.tk/cdn/admob (2).png](url)
3. [http://appsmonk.tk/cdn/admob (3).png](url)

I am having this problem since beginning, I have used this tutorial:
[pointdeveloper.com/how-to-add-banner-ads-to-ionic-apps-using-admob-pro-plugin/](url)

Please help us on this,

Thanks and Regards

**Comment by floatinghotpot** [comment]
Yes, they are test Ads indeed.

Could you please let me see your source code, if you don't mind? 

(Send only html/js files to rjfun.mobile@gmail.com)

**Comment by megaappcaesarapps** [comment]
Please guide me on the test ads, I am loosing revenues...

Let me know if I need to check anything more...

**Comment by imthat** [comment]
I'm having the same issue with interstitial ads, were you able to fix it?

**Comment by Venkat-TTapp** [comment]
Hi,

I have used this plugin successfully for many Phonegap Build iOS & Android apps, but today I when i was testing release of a new app, I encountered this wired issue. 

My 1st two test build were showing live ads, but 3rd test build app showed only test ads only (Both Banner & Interstitial ads). After rebuilding app again this issue was resolved.

Regards,
Venkat
