### ISSUE TITLE
For Windows 10 Phone/Desktop Ad-Mob AD plugin 

### ISSUE THREAD

**Issue by lse123** [floatinghotpot/cordova-admob-pro#481]
For Windows 10 Phone/Desktop Ad-Mob AD plugin 

Since ad-mob deprecated WINDOWS ADs, means will Not show in a Windows Phone/Desktop App... even exist key that exist or Not exist?

BTW if key Not exist either Android, iOS in this Plugin ... app still function but Not appear ADs...?

**Comment by floatinghotpot** [comment]
Since AdMob dropped support to Windows phone, the wp8 implementation may not work anymore.
