### ISSUE TITLE
Feature Request: LARGE_BANNER

### ISSUE THREAD

**Issue by oangelo** [floatinghotpot/cordova-admob-pro#482]
Please, implement LARGE_BANNER: https://firebase.google.com/docs/admob/android/banner

**Comment by floatinghotpot** [comment]
Done in cordova-plugin-admobpro@2.25.1

https://github.com/floatinghotpot/cordova-admob-pro/commit/5119c0bf6878a61ce6afa5f69c928d0092ec32a4
