### ISSUE TITLE
Google play services compatibility.

### ISSUE THREAD

**Issue by cesarlvielma** [floatinghotpot/cordova-admob-pro#484]
Hi Guys. I was tring to build a cordova app with this two plugins:

https://github.com/floatinghotpot/cordova-admob-pro/
https://github.com/fechanique/cordova-plugin-fcm

but something is wrong with google services version and i did get this error:

`Error: /home/cesar/Freelancer/gamerchampions/fleek/fleek-main/angular/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.2.0.
`

A possible fix that i found was replace in platforms/android/project.properties :

`cordova.system.library.1=com.google.android.gms:play-services-ads:+` 
by
`cordova.system.library.1=com.google.android.gms:play-services-ads:9.2.0`

i am not a plugin developer or something like that, What you think about a better solution for this?

Regards !

**Comment by floatinghotpot** [comment]
Please check:
https://github.com/fechanique/cordova-plugin-fcm/blob/master/src/android/FCMPlugin.gradle#L16

The another plugin your are using, is specifying an exact version number 9.2.0, which will conflict with any other version (even most recent version).

Suggestion:
Ask the author to change it to:
```
dependencies {
	compile 'com.google.firebase:firebase-core:+'
	compile 'com.google.firebase:firebase-messaging:+'
}
```

Which will auto use the most recent version, and won't cause conflict with other plugins.

**Comment by punksta** [comment]
The problem is: ```android.gms:play-services-ads``` is a part of firebase. You can't have both in project.
Solution is changing `android.gms:play-services-ads` to `com.google.firebase:firebase-ads` if you use firebase.
checkout my fork: https://github.com/punksta/cordova-admob-pro/commit/aa64fa36895aabcc3c67282497c37adf9e5aed86

**Comment by amokrunner** [comment]
@punksta : after doing this, does your AdMob data appear in the Firebase Analytics console?

**Comment by punksta** [comment]
@amokrunner original library has `cordova-admob-pro-firebase` branch and npm package https://www.npmjs.com/package/cordova-plugin-admobpro-firebase. You better use that.
