### ISSUE TITLE
Is there any possibility of using “Child-directed setting” using this plugin?

### ISSUE THREAD

**Issue by Venkat-TTapp** [floatinghotpot/cordova-admob-pro#486]
Can we use “Child-directed-setting” For purposes of the Children's Online Privacy Protection Act (COPPA), there is a setting called tagForChildDirectedTreatment in admob which needs to be flagged to receive COPPA complaint ads.

More information on this link:
https://firebase.google.com/docs/admob/ios/targeting#child-directed_setting

Please let me know if we can tag for child directed treatment using this plugin.

Regards,
Venkat

**Comment by floatinghotpot** [comment]
Yes, you can. 

Please see details in docs:
https://github.com/floatinghotpot/cordova-admob-pro/tree/master/docs#targetting-options

**Comment by Venkat-TTapp** [comment]
Thanks for your information.

I presume this setting works for both i-OS and Android.

1) I would like to purchase license, as I am not sure the ad sharing would overrule Child-directed-setting, It would be helpful, if you can confirm on this.

2) Is license applicable per app or an account which has multiple apps.

**Comment by floatinghotpot** [comment]
Yes, get a license to disable ad sharing will be safer, if you are going to use Child-directed-setting.

You can use the same license key for your own apps, under the same domain, like com.yourcompany.xxx

**Comment by Venkat-TTapp** [comment]
Thanks for your information. Appreciate your time and effort to reply my question. Please mark this as closed. I will contact you via the email mentioned in license purchase webpage.
