### ISSUE TITLE
Admob Pro doesn't show ads on ios

### ISSUE THREAD

**Issue by trueicecold** [floatinghotpot/cordova-admob-pro#487]
My code is:

`        var admobid = {};
        if( /(android)/i.test(navigator.userAgent) ) { // for android & amazon-fireos
            admobid = {
                banner: 'ca-app-pub-3239881464377321/5106410391'
            };
        } else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) { // for ios
            admobid = {
                banner: ' ca-app-pub-3239881464377321/5106410391'
            };
        }

        if(window.AdMob) {
            window.AdMob.createBanner({
                adId: admobid.banner,
                position: window.AdMob.AD_POSITION.BOTTOM_CENTER,
                autoShow: true,
                isTesting: true,
                overlap: true,
                success: function(){
                },
                error: function(){
                    alert('failed to create banner');
                }
            });
        }
    }`

My code is inside a deviceready event, and I'm not even getting the error event.
plugin-verify also didn't show any ads, for that matter...

on Android everythi g works just fine.

**Comment by floatinghotpot** [comment]
I've just upgraded the admob sdk for ios to v7.15.0, and verified the plugin.

It's now published to npm as cordova-plugin-admobpro@2.25.0.

**Comment by megaappcaesarapps** [comment]
Glad to here that, I am testing it now...

**Comment by urbanmania** [comment]
I've been fighting a similar issue (at least I think it is similar).  Everything works fine on the Android front but on iOS the logs always show:
{'adNetwork':'AdMob','adType':'banner','adEvent':'onAdFailLoad','error':1,'reason':'Request Error: No ad to show.'}

No matter whether I put isTesting: true or not.  Any idea?  (house ads don't even show)

**Comment by trueicecold** [comment]
Scratch that, Silly me.. I had a space in the bannerid... :/
Everything seems to be working now (test mode)

**Comment by urbanmania** [comment]
Hummm, I guess my issue wasn't related at all.  I created the banner with autoShow:false and then called showBanner but then tried changing autoShow to true and skippe the showBanner call, and then it seems to work. Haven't done full testing but at least it is progress :)

**Comment by floatinghotpot** [comment]
@urbanmania "Request Error: No ad to show." means no suitable Ad resources is not found for your Ad request. 

Calling showBanner() immediately after createBanner() won't work, as it will cost a little time for the plugin to download Ad resource. You can use autoShow:false, and listen to event 'onAdLoaded', then showBanner() in the event handler.

**Comment by JohnBain** [comment]
Alternatively, you can do window.setTimeout(AdMob.showInterstitial, 10) anywhere in the app :)
