### ISSUE TITLE
banner/interstitial/reward adid no more? gone?

### ISSUE THREAD

**Issue by frozenxis** [floatinghotpot/cordova-admob-pro#488]
Hi. First of all, great work!

I seem to struggle with latest version (25). i use ionic2 rc3.
when i try to add adid to createBanner or prepareRewardVideoAd or any other one which has adid in the readme i get:

> Argument of type '{ adId: string; isTesting: true; autoShow: true; }' is not assignable to parameter of type 'string | AdMobOptions'.
>   Object literal may only specify known properties, and 'adId' does not exist in type 'string | AdMobOptions'.

is there a workround for this?

**Comment by technotip** [comment]
Post your code ..

You can also check this video tutorial to fix your code [Adding AdMob In Ionic 2](http://technotip.com/5113/adding-admob-in-ionic-2/)
