### ISSUE TITLE
BUild error in linux sdk with command line. How to solve this?

### ISSUE THREAD

**Issue by zahiruldu** [floatinghotpot/cordova-admob-pro#490]
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
  [SDK Patch Applier v4, Google Repository].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

**Comment by floatinghotpot** [comment]
Read this: 
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.

```bash
$ android sdk
```

Then install the missing Android SDK components mentioned.

The error has nothing to do with this plugin. So I close the tracker now.
