### ISSUE TITLE
Interstitial ads show only one time when app starts

### ISSUE THREAD

**Issue by SharifulRonie** [floatinghotpot/cordova-admob-pro#491]
Hi,
Is there any option to show interstitial ads after an interval i.e. after every 3 mins, interstitial ads will appear. I know very little about coding and using default admobpro code. for my current code, interstitial ads showing only when app starts and one time only.

Here is my code:

        var admobid = {};

        // TODO: replace the following ad units with your own
        if (/(android)/i.test(navigator.userAgent)) {
            admobid = { // for Android
                banner: "ca-app-pub-xxxxxxxx/xxxxxxx",
                interstitial: "ca-app-pub-xxxxxxx/xxxxxx"
            };
        } else if (/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
            admobid = { // for iOS
                banner: "ca-app-pub-xxxxxxxx/xxxxxxx",
                interstitial: "ca-app-pub-xxxxxxx/xxxxxx"
            };
        } else {
            admobid = { // for Windows Phone
                banner: "ca-app-pub-xxxxxxxx/xxxxxxx",
                interstitial: "ca-app-pub-xxxxxxx/xxxxxx"
            };
        }

        function initApp() {
            if (!AdMob) { alert('admob plugin not ready'); return; }

            // this will create a banner on startup
            AdMob.createBanner({
                adId: admobid.banner,
                position: AdMob.AD_POSITION.BOTTOM_CENTER,
            //    isTesting: true, // TODO: remove this line when release
                overlap: false,
                offsetTopBar: false,
                bgColor: 'black'
            });

            // this will load a full screen ad on startup
            AdMob.prepareInterstitial({
                adId: admobid.interstitial,
           //     isTesting: true, // TODO: remove this line when release
                autoShow: true
            });
        }

        if ((/(ipad|iphone|ipod|android|windows phone)/i.test(navigator.userAgent))) {
            document.addEventListener('deviceready', initApp, false);
        } else {
            initApp();
        }
		
		// test case for #256, https://github.com/floatinghotpot/cordova-admob-pro/issues/256
    $(document).on('backbutton', function(){
      if(window.confirm('Are you sure to quit?')) navigator.app.exitApp();
    });

Please someone help me...

**Comment by floatinghotpot** [comment]
Each time you want to show the Ad, you need call:

```javascript
AdMob.prepareInterstitial({
            adId: admobid.interstitial,
       //     isTesting: true, // TODO: remove this line when release
            autoShow: true
        });
```

**Comment by SharifulRonie** [comment]
Thanks Raymond for the reply but I am confused how to call AdMob.prepareInterstitial and where to call? I want interstitial add to be appeared after 3 minutes interval. I know this is not the right way and create bad user experience and my app may get removed. I am got gaming app maker, I make only content based apps. I will be happy if you modify my code and send me the full code with changes, I need badly :(

**Comment by floatinghotpot** [comment]
```javascript
var admobid = {};

    // TODO: replace the following ad units with your own
    if (/(android)/i.test(navigator.userAgent)) {
        admobid = { // for Android
            banner: "ca-app-pub-xxxxxxxx/xxxxxxx",
            interstitial: "ca-app-pub-xxxxxxx/xxxxxx"
        };
    } else if (/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
        admobid = { // for iOS
            banner: "ca-app-pub-xxxxxxxx/xxxxxxx",
            interstitial: "ca-app-pub-xxxxxxx/xxxxxx"
        };
    } else {
        admobid = { // for Windows Phone
            banner: "ca-app-pub-xxxxxxxx/xxxxxxx",
            interstitial: "ca-app-pub-xxxxxxx/xxxxxx"
        };
    }

    function initApp() {
        if (!AdMob) { alert('admob plugin not ready'); return; }

        // this will create a banner on startup
        AdMob.createBanner({
            adId: admobid.banner,
            position: AdMob.AD_POSITION.BOTTOM_CENTER,
        //    isTesting: true, // TODO: remove this line when release
            overlap: false,
            offsetTopBar: false,
            bgColor: 'black'
        });

        // this will trigger interstitial Ad every 3 minutes
        window.setInterval(function(){
            AdMob.prepareInterstitial({
                adId: admobid.interstitial,
                autoShow: true
            });
        }, 3*60*1000);
    }

    if ((/(ipad|iphone|ipod|android|windows phone)/i.test(navigator.userAgent))) {
        document.addEventListener('deviceready', initApp, false);
    } else {
        initApp();
    }
	
	// test case for #256, https://github.com/floatinghotpot/cordova-admob-pro/issues/256
$(document).on('backbutton', function(){
  if(window.confirm('Are you sure to quit?')) navigator.app.exitApp();
});
```

But, trigger interstitiall Ad with a timer, is not a good practice, as it may cause the user happen to click the Ad unexpectedly.
