### ISSUE TITLE
Causes version for conflict com.google.android.gms in Phonegap Build

### ISSUE THREAD

**Issue by jamminjames** [floatinghotpot/cordova-admob-pro#492]
When using this plugin with a Phonegap Build project, I get the following error:

Found com.google.android.gms:play-services-ads:+, but version 9.2.0 is needed for the google-services plugin

How can I resolve this in Phonegap Build? Thanks for any help.

**Comment by jamminjames** [comment]
cesarlvielma's solution at this thread worked for me: https://github.com/fechanique/cordova-plugin-fcm/issues/179

It involves forking the plugin and changing this line in plugin.xml:
`<framework src="com.google.android.gms:play-services-ads:+" />`
to
`<framework src="com.google.android.gms:play-services-ads:9.2.0" />`

**Comment by floatinghotpot** [comment]
To be compatible with latest SDK, instead of fork admob and changing + to 9.2.0, try fork this plugin, then change here:
https://github.com/fechanique/cordova-plugin-fcm/blob/master/src/android/FCMPlugin.gradle#L17
```
dependencies {
	compile 'com.google.firebase:firebase-core:9.2.0'
	compile 'com.google.firebase:firebase-messaging:9.2.0'
}
```
Change to 
```
dependencies {
	compile 'com.google.firebase:firebase-core:+'
	compile 'com.google.firebase:firebase-messaging:+'
}
```

**Comment by jamminjames** [comment]
It doesn't like that. I get the following in build log. Line 22 is the end of the file, where it says "apply plugin: com.google.gms.googleservices.GoogleServicesPlugin":

FAILURE: Build failed with an exception.

* Where:
Script '/project/cordova-plugin-fcm/newscartoons-FCMPlugin.gradle' line: 22

* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

**Comment by floatinghotpot** [comment]
http://stackoverflow.com/questions/28538824/how-to-update-gradle-dependencies-to-their-latest-version

**Comment by floatinghotpot** [comment]
Sorry, what I suggested 4 days ago was not correct, as gradle file cannot handle "+" as latest version automatically as cordova plugin.xml does. So here is a new suggestion and I tested.

Fork and modify `plugin.xml`, just move the framework dependency from gradle file to plugin.xml:
Replace
```xml
	<framework src="src/android/FCMPlugin.gradle" custom="true" type="gradleReference"/>
```
with
```xml
        <framework src="com.google.gms:google-services:+" />
        <framework src="com.google.firebase:firebase-core:+" />
        <framework src="com.google.firebase:firebase-messaging:+" />
```

Here is my test build log:
```bash
iMac:testfcm liming$ cordova plugin ls
cordova-plugin-admobpro 2.25.0 "AdMob Plugin Pro"
cordova-plugin-extension 1.5.1 "Cordova Plugin Extension"
cordova-plugin-fcm 1.1.5 "FCMPlugin"
cordova-plugin-whitelist 1.3.1 "Whitelist"

iMac:testfcm liming$ cordova build
... ...
... ...
BUILD SUCCESSFUL

Total time: 25.808 secs
Built the following apk(s):
	/Users/liming/workspace/cordova-apps/testfcm/platforms/android/build/outputs/apk/android-debug.apk
```

**Comment by floatinghotpot** [comment]
BTW, I've send a pull request to @fechanique:
https://github.com/fechanique/cordova-plugin-fcm/pull/198

**Comment by jamminjames** [comment]
Thanks a lot! I'll give it a try.

**Comment by floatinghotpot** [comment]
As Google has provided two ways of using AdMob, one with Firebase, another standalone without Firebase.

If firebase is used in your project, such as `cordova-plugin-fcm` etc, please use this one:
* cordova-plugin-admobpro-firebase

If firebase is not used, then use the original:
* cordova-plugin-admobpro
