### ISSUE TITLE
Want interstitial to show on certain page, can't get it to work

### ISSUE THREAD

**Issue by jamminjames** [floatinghotpot/cordova-admob-pro#494]
I have banner ads set to show on the main page of my app, but would like that to go away and an interstitial ad to appear on certain pages.

On the index page, I have this for banner ads:
document.addEventListener("deviceready", function(){
	if(AdMob) AdMob.createBanner( admobid.banner );   
});

...and on the other page, I have this, but it's not working:
if(AdMob) AdMob.prepareInterstitial({
    removeBanner( admobid.banner ),
    adId: admobid.interstitial,
    autoShow: true
});

...also tried:
if(AdMob) AdMob.hideBanner({
    AdMob.showInterstitial(),
});

Any help would be appreciated. Thank you.

**Comment by floatinghotpot** [comment]
Every time before displaying an interstitial Ad, you need prepare it before show it, as it cost a little time (maybe some seconds) for the SDK to download Ad resource from Ad server.

When switching to a new page, you can first check whether the interstitial Ad is ready or not, if ready, then show it.

**Comment by jamminjames** [comment]
Thanks for the reply. You say check first whether it's ready, then show it. That's what this does, yes?
if(AdMob) AdMob.prepareInterstitial({
removeBanner( admobid.banner ),
adId: admobid.interstitial,
autoShow: true
});

I have the prepare statement on the index page of the app, so it should be ready, right? (See next paragraph.) But if it's NOT ready, what happens? It just won't show at all? Or will when it's ready? If not at all, how can I make it show when it is ready?

On the index page, I do have this, to try and prepare the interstitial, but only show the banner:
document.addEventListener("deviceready", function(){
	if(AdMob) AdMob.createBanner( admobid.banner );
       AdMob.prepareInterstitial( {adId:admobid.interstitial, autoShow:false} );	
});

I'm also trying to remove the banner ad before loading the Interstitial with that second line, but that's not working either. Even if the interstitial would automatically remove the banner, I don't want the banner returning on this particular page. How can I make that happen?

**Comment by jamminjames** [comment]
I was finally able to get this working satisfactorily. Thank you.
