### ISSUE TITLE
Reward video only show once, then just no error at all, just callback never fire. help!!

### ISSUE THREAD

**Issue by mrkaratechamp** [floatinghotpot/cordova-admob-pro#495]
well, my tittle say's all, I just put my test case:
using cordova-plugin-admobpro 2.25.2 with crosswalk cordova webview 2.2.0

I already got all my admob mediation config ok, because I use on unity too and everything it's ok there.

Here on cordova, I got the mediation work ok, well, still didn't see an adcolony ad, but no error , so maybe it's just not show it, because of my problem, I just see once time a video, and then nothing more, I can see charboost, vungle and unity ads ok, but only one time, restart app, then I can see other video (or something charboost again for example, it's not an order specific, but that's ok on mediation).

So I try to track the problem, but don't found nothing wrong, just can't track more without trying to get into the main jar file of the plugin,  but I think that's not be the way to go.

on summary:
```javascript
AdMob.prepareRewardVideoAd({
                        adId: this.adMobService.video,
                        autoShow: false
                     },function(e) {
                        alert('SUCCESS ' + e );
                        console.log(e);
                    }, function(e) {
                        alert('FAIL ' + e);
                        console.log(e);
                    });
 document.addEventListener('onAdLoaded',function(e){                   
                   if(e.adType == "rewardvideo")
                        AdMob.showRewardVideoAd();
                 });
  document.addEventListener('onAdDismiss',function(e){
                       if(e.adType == "rewardvideo")
                           alert("dissmiss OK!!!");
                          // some code to do stuff and then:
                             AdMob.prepareRewardVideoAd({
                        adId: this.adMobService.video,
                        autoShow: false
                     },function(e) {
                        alert('SUCCESS ' + e );
                        console.log(e);
                    }, function(e) {
                        alert('FAIL ' + e);
                        console.log(e);
                    });
                 });
```
and what happend:

I got a SUCCESS and e = OK
GOT the video and load it, see one of the video from my networks
got dissmiss OK!!!" and all my stuff post video got perfectly ok.

got SUCCESS  e = OK (so video ad will prepare again).

and that's all... never got the callback and never got other video until I restart the app.

please any clue will be appretiate.

thanks all and sorry my bad english

**Comment by pedrosobral** [comment]
Did you figure it out?

**Comment by rohorhweb** [comment]
i have the same issue, any update please?

**Comment by psimondk** [comment]
I have that issue too. 

If I change to interstitial no problem - you can fire up as many ads as you like even using the same add unit as for rewarded video, but when using rewarded video no such luck.

_Please, is there anything we the community, can do to help ?_ 

AdmobPro is a cool plugin and we all want it to be the best.

**Comment by floatinghotpot** [comment]
I will look into this issue. Which mediation do you use for reward video?

**Comment by rohorhweb** [comment]
nothing now, just admob

**Comment by pedrosobral** [comment]
I'm using Unity.

**Comment by psimondk** [comment]
Im am just using admob

- thanks for looking into it !

Best Regards

**Comment by floatinghotpot** [comment]
Only use AdMob is not enough to see the rewarded video Ad. 

Here is the message from Veer Arjun Busani (Mobile Ads SDK Team) at AdMob official forum:
https://groups.google.com/forum/#!topic/google-admob-ads-sdk/3Un64E2olMQ

> Currently, since Reward Video Ads are only supported via third party Mediation Ad networks and not by AdMob, you would have to create an Ad Unit ID by yourself to test it out. [Here is our guidelines](https://support.google.com/admob/answer/3052638?hl=en)  on how to create an Reward Video Ad Unit ID. You have to add third party ad networks to mediate ads from. You can get the list of supported Ad Networks [here](https://firebase.google.com/docs/admob/android/mediation-networks#supported-ad-formats).
>
> Once you have created one, and added your ad networks to mediate with, you need to add their [SDK and adaptor](https://firebase.google.com/docs/admob/android/mediation-networks#supported-ad-networks) into your project.

**Comment by psimondk** [comment]
Hi

Thanks for your support

We have created a reward video Ad Unit pr. guidelines and Admob Pro is duly
showing the reward vide with counter and all one time pr. session.

The problem is that it only fires once and that the app needs to be
reloaded if we need to see another reward video.

In the OnAdPresent we can see the data we have created on the AdUnit

Best Regards

**Comment by floatinghotpot** [comment]
@mrkaratechamp , I see some bug in your javascript code, which might be the root cause that the second preparing is not called.
```javascript
document.addEventListener('onAdDismiss',function(e){
                       if(e.adType == "rewardvideo")
                           alert("dissmiss OK!!!");
                          // some code to do stuff and then:
                             AdMob.prepareRewardVideoAd({
                        adId: this.adMobService.video,
                        autoShow: false
                     },function(e) {}, function(e) {});
                 });
```

This line is not correct, `adId: this.adMobService.video,`  

You put this line in the anonymous function, what's the value of `this` ?!

**Comment by floatinghotpot** [comment]
Every time before you call show, you need call prepare correctly to load the ad resources.

**Comment by psimondk** [comment]
We are doing that.

Show is called in the success callback on prepare.

Here is the raw code were we just pulled out interstitial:


admob.prepareRewardVideoAd({

          adId: admobid.interstitial,
          autoShow: false,

          success: function(){
            console.log('interstitial prepared');
admob.showRewardVideoAd();
            deferred.resolve(true);
          },
          error: function(){
            console.log('failed to prepare interstitial');
            deferred.reject(false);
          }
        });
        return deferred.promise;

**Comment by rohorhweb** [comment]
i fixed it like that if user watch reward video, user is forced to restart
app to if want to check another one...

**Comment by psimondk** [comment]
That is a workaround - yes. We would rather have the Admob code showing the Reward video without having to reload the app though.

**Comment by rohorhweb** [comment]
sure

Dňa 11. 3. 2017 11:29 AM používateľ "psimondk" <notifications@github.com>
napísal:

**Comment by floatinghotpot** [comment]
@psimondk  do not calll show...() in callback of prepare...(). instead, call it in callback of event `onAdLoaded`.

```javascript
var adunitid = 'your ad unit id here';
function prepare() {
    AdMob.prepareRewardVideoAd({
                        adId: adunitid,
                        autoShow: false
                    },function(e) {
                       // success only means no syntax error in params
                    }, function(e) {
                       // fail means the something wrong in params
                    });
}

document.addEventListener('onAdLoaded',function(e){                   
    if(e.adType == "rewardvideo")
        AdMob.showRewardVideoAd();
});

document.addEventListener('onAdDismiss',function(e){
    if(e.adType == "rewardvideo") {
        // prepare again for next ad, when previous ad dismissed
        prepare();
    }
});
```

**Comment by psimondk** [comment]
Thanks a lot Raymond.

It works perfectly on IoS, but on Android it still just fire once.

Best Regards

**Comment by psimondk** [comment]
Debugging I can see that on IoS the onAdLoaded is fired each time whereas
on Android it fires once

On Sun, Mar 12, 2017 at 11:52 AM, Palle Simonsen <p.simon.simonsen@gmail.com

**Comment by floatinghotpot** [comment]
Here is my plugin java code for the event.

```java
@Override
    public void onRewardedVideoAdClosed() {
      fireAdEvent(EVENT_AD_DISMISS, ADTYPE_REWARDVIDEO);

      // if focus on webview of banner, press back button will quit
      // force focus on main view, so that 'backbutton' override will work
      View mainView = getView();
      if (mainView != null) {
        mainView.requestFocus();
      }
    }
```

I cannot find any error here, when the rewarded video is closed, if the java callback is called, it should fire the right javascript event correctly.

As it's very weird, I just guess, is there any possibility that the mediation did not callback correctly? 

@psimondk, which mediation adapter are you using please? If I can find their source code, maybe I can look into it for a double check.

**Comment by rohorhweb** [comment]
i am not using mediationg and i am able to show rewarded video? i am geting
video from admob

**Comment by psimondk** [comment]
Hi Raymond,

Here is the plugin list for this app:

[image: Inline image 1]

Best Regards, Palle

**Comment by floatinghotpot** [comment]
@rohorhweb as mentioned, admob itself does not offer rewarded video ad, all are from 3rd party mediation.

@psimondk I see iAd, which is from Apple, but now not served anymore. Did you configure any 3rd party mediation in admob portal for the rewarded video?

**Comment by psimondk** [comment]
Hi,

Thanks for your support

AdMob actually now do offer reward video's pr. the latest annoncement from
Google.

As I wrote it works perfectly on IOS whereas the callback only fires once
for Android.On Android the RewardVideo shows once.

I removed the Mobfox plugin and I will remove IAD to see if it has the
desired effect.

Best Regards, Palle

**Comment by rohorhweb** [comment]
yes i am also not using mediation and showing video, but EVENT FIRES ONLY
ONCE, this si the only problem

**Comment by psimondk** [comment]
Removed IAD but to no avail - so is now running a pure admob installation.

Will PM the ca- for testing.

**Comment by floatinghotpot** [comment]
@psimondk thanks for the info about admob own rewarded video, i will test it myself. if any update, will let you know.

**Comment by rohorhweb** [comment]
i have one more issue with this plugin i just found that in IOS bannerad
overlay webview and i have to make space of 50pix down of app... is there
any posibility to not add special space to my app?

**Comment by floatinghotpot** [comment]
@rohorhweb please create another issue tracker if you are talking about a different issue. thanks.

**Comment by Finnb8r** [comment]
Some input regarding this issue :
I also encounter it on Android (iOS works fine), to reproduce :
1) prepare reward video 
2) `onAdFailed` / `onAdLoaded` is called
3) Show the video
4) Prepare a new video
5) `onAdFailed` / `onAdLoaded` are not called

I had a look at the source, main difference between  iOS and Android is that on Android you use a synchronized object containing a boolean `mIsRewardedVideoLoading` keeping track of if there is a video being loaded but on iOS it loads in any case.
If on Android `mIsRewardedVideoLoading` is `false` when we call the `__prepareRewardVideoAd` method, the admob request is not executed and by cascade, the callbacks (`onAdFailed` or `onAdLoaded`) neither.
My best guess is that that boolean is not updated properly (but can't find why not, maybe because the listener is set on a sharedInstance outside of the synchronized).
Hope this helps.

**Comment by floatinghotpot** [comment]
@Finnb8r yes, that's the root cause, thanks! I will publish a patch version soon.

**Comment by floatinghotpot** [comment]
published as cordova-plugin-admobpro@2.28.3

**Comment by Finnb8r** [comment]
Great !
As a side note though, you might want to add the line `rewardVideoAd = null;` in the `onRewardedVideoAdFailedToLoad` and maybe `onRewardedVideoAdLeftApplication` methods too though as if it fails to load an ad the issue persists as can't be prepared again.
Sorry for not mentioning this in my previous comment but thought you might change the GenericAdPlugin.

**Comment by psimondk** [comment]
Great work all that contributed !

Thanks !

**Comment by JCarlosR** [comment]
@Finnb8r This only applies to Cordova apps? I'm developing an Android native app using Java and Admob                                                           only loads one ad.
