### ISSUE TITLE
Banner ad sometimes showing AdSense ads instead of ads from specified adId

### ISSUE THREAD

**Issue by kingpin298** [floatinghotpot/cordova-admob-pro#497]
A very small percentage of the time when the app loads the banner displays incorrect ads from an AdSense account instead of the ads for the DFP path.  It seems to happen very very rarely on iOS and infrequently on android.  From the android log file it shows that createBanner from GenericAdPlugin is being called with the proper DFP path.  

Watching the web traffic on a bad request it goes strait to "https://googleads.g.doubleclick.net" to fetch the AdSense ad but on a good request it goes to "https://pubads.g.doubleclick.net" with the correct querry string to get the correct ad.

**Comment by chaffeqa** [comment]
I'm seeing this as well... is there possibly a timing issue here?

**Comment by Nuuf** [comment]
https://github.com/floatinghotpot/cordova-admob-pro/wiki/License-Agreement

**Comment by chaffeqa** [comment]
thanks @Nuuf !! that really wasnt prominent and our client was pissed at seeing ads they werent serving.

@floatinghotpot we just payed the admob amount, is there a timeline we can tell our client before the ads stop propogating?

**Comment by floatinghotpot** [comment]
@chaffeqa your license has just been sent, please check your email.

BTW, you can send me your app id privately via email (rjfun.mobile at gmail.com), we will double check to make sure the ad sharing has been disabled.
