### ISSUE TITLE
Intel XDK Cordova 6.2.0 Android Build Fail

### ISSUE THREAD

**Issue by Nuuf** [floatinghotpot/cordova-admob-pro#499]
When adding this plugin via Intel XDK and when using Cordova 6.2.0, the build fails.

Also fails with 5.4.1, is this an Intel issue?

**Comment by Nuuf** [comment]
Log: https://gyazo.com/aa95a6af4f49a2a015bcef9124515d44

**Comment by Nuuf** [comment]
https://software.intel.com/en-us/forums/intel-xdk/topic/600642

This is from 2015

**Comment by pearlwebsolution** [comment]
sir,
 intel xdk not supporting gradle build. So could you please give some suggestion for this.
