### ISSUE TITLE
Attempt to invoke virtual method 'int org.json.JSONObject.length()' on a null object reference

### ISSUE THREAD

**Issue by theunreal** [floatinghotpot/cordova-admob-pro#500]
I'm trying to use this plugin to show an admob interstitial ad using the following code:

```
ngOnInit() {
    this.platform.ready().then(() => {
    if (this.platform.is("cordova")) {
      if (AdMob) {
    AdMob.prepareInterstitial('ca-app-pub-MY-PUB/MY-AD-KEY')
    .then(() => {
      console.log("Ad init");
      AdMob.showInterstitial(); });
    }
  }
  });
}
}
```

and I get the following error:

`Uncaught (in promise): Attempt to invoke virtual method 'int org.json.JSONObject.length()' on a null object reference`

What's wrong?

**Comment by floatinghotpot** [comment]
Do not pass a string to the API, pass a JSON object instead, see:
```javascript
if(AdMob) AdMob.prepareInterstitial( 
  {
    adId: admobid.interstitial, 
    autoShow: false
  } 
);

```

**Comment by PrithiviRajG** [comment]
how did the `admobid` look like?
did you meant the below one?
```
admobid = {
      banner: 'ca-app-pub-xxx/xxx', // or DFP format "/6253334/dfp_example_ad"
      interstitial: 'ca-app-pub-xxx/yyy'
    };
```

admobid.interstitial will again return string I guess. Please corrrect me if I am wrong. I am also getting the same exception.
