### ISSUE TITLE
No response / reply for clarification for commercial customer/paid license customer!

### ISSUE THREAD

**Issue by Venkat-TTapp** [floatinghotpot/cordova-admob-pro#503]
Hi,

I purchase this awesome plugin few days back. Although you shared license credentials via private email within few hours of payment, there is no response for the clarification/query which I emailed you. Despite followup no response for the past 4 days.

README.md states  commercial customer, will be supported with high priority, via private email or even Skype chat but I did not get any such response.

Regards,
Venkat

**Comment by floatinghotpot** [comment]
Please follow the instruction sent to you in email. If any technical questions, please post here. 

We do not provide code review service, at least it's not covered in the license fee.
