### ISSUE TITLE
AdMob.createBanner  stop the app functions

### ISSUE THREAD

**Issue by sabirali007** [floatinghotpot/cordova-admob-pro#504]
Banner and interstitial working fine but when we use function AdMob.createBanner it stop the app. Once banner is loaded app functions running fine. Please help me about this issue.

**Comment by floatinghotpot** [comment]
What happened as you mentioned when "it stops the app"? And, which platform please, iOS or Android?

**Comment by sabirali007** [comment]
it stop the app function for example all buttons not work, i am using android platform

**Comment by floatinghotpot** [comment]
It may take some CPU time for network activity to load ad resource from Google AdMob server.

**Comment by sabirali007** [comment]
How we handle this issue?

**Comment by laziaf** [comment]
+1 for this issue, this issue give my client a teribble UX, do you have any workaround? using timeout has no effect

**Comment by floatinghotpot** [comment]
You may try using time of the splash screen to initialize the banner.

**Comment by rahmadid** [comment]
Hi,
I think the 'stop' problem is related to these issues: #370 (reported by me several months ago) and #403.
I myself still using the older version of the plugin (cordova-plugin-admobpro v2.12.0 and cordova-plugin-extension v1.2.9), the last known version without the stop/freeze problem.
@floatinghotpot Please kindly solve this issue. Thanks.
