### ISSUE TITLE
Native Ads

### ISSUE THREAD

**Issue by ayyfish** [floatinghotpot/cordova-admob-pro#506]
Are native ads still a planned feature? I'm just trying to figure out if I should wait for this feature or go another route. Thanks.

**Comment by NiltonFelicio** [comment]
I have the same doubt.
Although it appears in the list of Ad Types.
How do I include Native Ads?

**Comment by oangelo** [comment]
I was after such a feature some time ago... I do not understand very much of AdMob SDK, but, from what I have researched, it will never be possible.

**Comment by floatinghotpot** [comment]
Same topic as #461, close this one and tracking there.
