### ISSUE TITLE
Banner not showing for Plugin Verify for iOS 10.2

### ISSUE THREAD

**Issue by emerwang** [floatinghotpot/cordova-admob-pro#507]
Hi floatinghotpot:

This is in reference to #501 
Here are some updates from my side. I think what concerned me most is that even the plugin-verify demo will not display any banner or interstitial for ios. The buttons are simply not responding and no ad is being served.

Here are some details of my environment:
macOS Sierra 10.12.3
cordova 6.5.0
Simulator iphone SE 10.2
XCode 8.2.1 

I think it is highly likely this is a bug with iOS 10. I have tried doing the same thing with my old laptop that runs iOS 9.3 and the same demo app runs perfectly (with buttons responding and banner ads showing correctly). Is the plugin currently supporting ios 10.2?

I also did some debug with a project that included the admob_simple.js. It seems like the code after AdMob variable never executes in admob_simple. I think this could be due to AdMob var being undefined and the entire code crashes without getting to the line:
if (! AdMob ) { alert( 'admob plugin not ready' ); return; }

As for app unit ids, I have been coding and integrating many ios and android native apps in the past with Admob. And I verified that the ad unit ids used in my version of admob_simple.js are correct. Also 
I check that cordova.js and cordova_plugin.js are included and called before admob_simple.js.

Thanks for the help. Been stuck on this topic for days now. Any pointer will be good at this point. 👍

**Comment by floatinghotpot** [comment]
Thanks for the detailed info, we will look into this issue.

**Comment by psimondk** [comment]
Please do.
I experience a similar issue with IOS 10.x
App worked perfectly on IOS 9.x versions but is working eraddic on IOS 10.1

This has some urgency so please revert

**Comment by psimondk** [comment]
Have a build made w. Xcode 7 and one w. Xcode 8

The Xcode 7 build works flawless whereas the Xcode8 build sometimes displays an interstitial and sometines not.

It seems that displaying an Interstitial after a button click doesn't work, however after an external event such as an ajax message it does.

**Comment by psimondk** [comment]
I can verify thatt after having downloaded xcode7.3.1, rebooted, danced the rain dance **and** symlinked all the IOS 10.x images from 8 to 7 admob .pro just works again.

DO NOT USE THE LATEST XCODE VERSION UNTILTHE TEAM FIXES THIS ISSUE

**Comment by emerwang** [comment]
Thanks psimondk for the information. Also waiting for the update! :+1:

**Comment by floatinghotpot** [comment]
Great thanks to @psimondk for identifying the issue. iOS 10.x must have done something. We've just upgraded to xcode 8.x and iOS 10.x to troubleshoot. If any update, will post here.

**Comment by joseescaballero** [comment]
Any news?

**Comment by pulsedemon** [comment]
This is a problem for me too

**Comment by pablo-gonzalez** [comment]
When compiled with Xcode 8.2.1 the banner at the bottom overlaps the web view.
When compiled with Xcode 7 it works fine. 

```
ionic info

Your system information:

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002



ionic plugin

cordova-plugin-admobpro 2.26.0 "AdMob Plugin Pro"
```

**Comment by emerwang** [comment]
Hi, any updates?

**Comment by floatinghotpot** [comment]
I find the answer in StackOverflow:
http://stackoverflow.com/questions/38410159/cordova-app-hanging-during-startup-on-ios-10-beta

Root cause:
It seems that iOS 10 requires additional entries in the Content-Security-Policy meta tag, namely gap://ready and file:. 

Solution: add the following content to the index.html:
```html
<meta 
http-equiv="Content-Security-Policy" 
content="default-src * gap://ready file:; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src * 'unsafe-inline' 'unsafe-eval'"
>
```

Tested, it did work.

**Comment by floatinghotpot** [comment]
As the issue fixed, this tracker closed.
