### ISSUE TITLE
Test Mode Maybe Not Working

### ISSUE THREAD

**Issue by mfisher31** [floatinghotpot/cordova-admob-pro#509]
Hello, I'm developing a simple iOS app which is not published to iTunes yet.  I am using isTesting equals true everywhere.  However, when I look at my AdMob console, I see impressions and revenue increasing!!!!  I would expect to see no data here since the app isn't public yet and isTesting is in use. Pardon my ignorance on this.  It's my first experience with admob itself and this plugin.

I really would like it if my account doesn't get  suspended from testing with this plugin... is this something I should be concerned about?

Thank You

**Comment by mfisher31** [comment]
Side note, my AdMob implementation is based on your ionic/angular JS example.

**Comment by floatinghotpot** [comment]
If you can see test Ad, your isTesting is working.

**Comment by mfisher31** [comment]
That's my point, even with isTesting = true, I see real ads, not testing ads.  Only seeing this on iOS

**Comment by floatinghotpot** [comment]
Weird, we never see such case.

1. Could you please paste your javascript code here?

2. Can you try the demo project with command `plugin-verify cordova-plugin-admobpro ios`? (after install npm utility plugin-verify)

**Comment by floatinghotpot** [comment]
no more reply, I suppose problem resolved.
