### ISSUE TITLE
Changing Orientation Causes Banner to Cover Up Screen

### ISSUE THREAD

**Issue by ericmorgan1** [floatinghotpot/cordova-admob-pro#513]
I am using Ionic/Cordova and am adding a banner to the bottom center of my app according to the instructions here:
[https://github.com/floatinghotpot/cordova-admob-pro/wiki/01.-How-to-Use-with-Cordova-CLI](url)

I am compiling it to iOS.

When the app is first loaded, the banner appears correctly and pushes the rest of the app upwards to make room for it.

However, if I change my orientation (to landscape), the banner then overlaps the rest of the app. There is no way to get the banner to reappear below the app content without killing the app. This is especially problematic for apps with tabs on the bottom, as the banner will completely cover them.

--
As a workaround:
Does anyone know if removing/re-adding the banner when the orientation changes will work?
Or positioning it at x/y?

**Comment by floatinghotpot** [comment]
If you app is not fixed orientation, you need set option `orientationRenew: true` when creating the banner.

Explain: orientationRenew, boolean, re-create the banner on web view orientation change (not screen orientation), or else just move the banner.

See more options in the wiki:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/1.2-Method:-AdMob.setOptions()

**Comment by ericmorgan1** [comment]
Thank you! It worked. : )
