### ISSUE TITLE
How to show Interstitial during exit app

### ISSUE THREAD

**Issue by cyclonmaster** [floatinghotpot/cordova-admob-pro#514]
On Android, I created a function for exit the app when user click on back button as follows:

if(AdMob) AdMob.showInterstitial();
navigator.app.exitApp();

But the mobile just exit without showing the Interstitial ads.

It did work when I use this plugin before:
https://github.com/appfeel/admob-google-cordova

Any help?

**Comment by floatinghotpot** [comment]
Javascript is non-block language and driven with event. You need give user chance to interact with the Ad before edit, for example, really exit after dismissing the interstitial.

Try this:
```javascript
    var bExiting = false;
    document.addEventListener('onAdFailLoad', function() {
        if(bExiting) navigator.app.exitApp();
    });
    document.addEventListener('onAdDismiss', function(){
        if(bExiting) navigator.app.exitApp();
    });

    // now ready to exit
    bExiting = true;
    if(AdMob) AdMob.showInterstitial();
```

**Comment by cyclonmaster** [comment]
Thank you.

It work now. Only that if(AdMob) AdMob.showInterstitial(); will not work.

I change it into function in index so that I can call it anytime like this:

function admobinterstitial() {
        if (! AdMob ) {
            console.log("admob plugin not ready");
            return;
        }
        // this will load ads
        AdMob.prepareInterstitial({
            adId: admobid.interstitial,
            isTesting: true, // TODO: remove this line when release
            autoShow: true
        });
    }

//call the ads anywhere
admobinterstitial();

**Comment by floatinghotpot** [comment]
Yes, you need call prepareInterstitial() with `autoShow:false` before calling showInterstitial() at the best timing.

Calling prepareInterstitial() with `autoShow:true` will show the Ad once the Ad resource is ready, maybe not at the best timing.

**Comment by prantikv** [comment]
It is not recommended to show ads before exit, as it might cause accidental clicks.

Read the docs [here](https://support.google.com/admob/answer/6201362?hl=en)
