### ISSUE TITLE
Need help reward video does not work

### ISSUE THREAD

**Issue by cyclonmaster** [floatinghotpot/cordova-admob-pro#515]
This is my code based on sample. I want to test using admob test id.

```
//Prepare your AdMob Ad Unit Id for your banner and interstitial
    var admobid = {};
    admobid = { // this is sample test id
        banner: 'ca-app-pub-6869992474017983/9375997553',
        interstitial: 'ca-app-pub-6869992474017983/1657046752'
    };

// prepare reward video
    function admobRewardVideoAd(){
        if(AdMob) AdMob.prepareRewardVideoAd({
            adId: admobid.reward,
            isTesting: true,
            autoShow: true
        });
    }

//1. try call after device ready
document.addEventListener("deviceready", admobRewardVideoAd, false);

//2. try call the reward video
AdMob.showRewardVideoAd();

//3. try call the reward video
admobRewardVideoAd();
```

I try 3 ways, all of them still not show the reward video. Any hints?

Thank you

**Comment by floatinghotpot** [comment]
AdMob has no much video sources, you need add some mediation to some other Ad networks, like vungle, adcolony, etc.

I am working on a new plugin `cordova-plugin-vungle`, and will add a mediation adapter `cordova-plugin-admob-vungle` but not finished yet.

You can try downloading the mediation adapters from admob website then add it manually, or wait my vungle plugin done.

**Comment by floatinghotpot** [comment]
See #511, same issue, let's follow up in that tracker.
