### ISSUE TITLE
isTesting: true don't work on RewardVideoAd

### ISSUE THREAD

**Issue by avihaiandroid** [floatinghotpot/cordova-admob-pro#517]
I set isTesting: true but i get real ads
(in Interstitial isTesting: true work)

**Comment by floatinghotpot** [comment]
there seems no testing reward video ad.

**Comment by johnborges** [comment]
Google recommends using a test ad unit from them until they provide a real solution. 

Ad Unit ID: ca-app-pub-3940256099942544/5224354917
> Since we have enabled AdMob network to serve Reward Video ads as well, you can use our test Ad Unit ID: ca-app-pub-3940256099942544/5224354917 for now and change it your live one once your app is ready for prod. You would not be able to add test devices for now for Reward Video ads.

[source](https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/android/k-kVwVu2XBc)
