### ISSUE TITLE
Rewarded Videos and InMobi

### ISSUE THREAD

**Issue by oangelo** [floatinghotpot/cordova-admob-pro#519]
InMobi does offers rewarded videos, and the plugin does offers integration with InMobi by installing the cordova-inmobi-sdk. Does this means that I can use rewarded videos from InMobi? Any way, I am trying, but I am having an error: "Attempt to invoke virtual method 'int org.json.JSONObject.length()' on a null object reference".
I already configurated the mediation in AdMob.

**Comment by johnborges** [comment]
Have you installed both `cordova-inmobi-sdk` and `cordova-plugin-admob-inmobi`? You need to install the InMobi SDK as well as the mediation adapter.

**Comment by oangelo** [comment]
@johnborges, I have both those plugins installed. And my code is: 
```      
      videoReward = () ->
        alert("reward init")
        options =
          adId: "ca-app-pub-****************"
          autoShow: true
        success = ()->
          alert("loaded rewarded video")
          return
        fail = (data)->
          alert("fail rewarded video"+data)
          return
        if AdMob
          AdMob.prepareRewardVideoAd(options, success, fail)
```
But "AdMob.prepareRewardVideoAd(options, success, fail)" is failing with "'int org.json.JSONObject.length()' on a null object reference". I have no idea of what it means.

**Comment by oangelo** [comment]
Don't know why but now it is working. I just changed alert by console.log.
