### ISSUE TITLE
Banner Overlaps Screen After Cordova-Camera

### ISSUE THREAD

**Issue by ericmorgan1** [floatinghotpot/cordova-admob-pro#520]
After opening and clsoing the camera from the cordova-plugin-camera, the AdMobPro banner then covers up part of the screen.

I had a similar issue when changing orientation that was corrected by setting orientationRenew, but is there also a workaround for this camera issue?

I'm sorry, I couldn't find it in the API documentation.

I thought maybe calling 
`AdMob.removeBanner();`
`AdMob.createBanner();`
but it doesn't seem to work.

Or do you need to wait for the removal somehow before creating it again?

Thank you!

**Comment by floatinghotpot** [comment]
Maybe you don't have to remove then create, try just hiding the banner, then delay 1 second and show it.

```javascript
AdMob.hideBanner();
window.setTimeout(function(){
    AdMob.showBanner(AdMob.AD_POSITION.BOTTOM);
}, 1000);
```

I am not sure what's your situation and the root cause, so just have a try.

**Comment by ericmorgan1** [comment]
Thanks!
