### ISSUE TITLE
Admob Pro License

### ISSUE THREAD

**Issue by wahyuxo** [floatinghotpot/cordova-admob-pro#524]
Hi Sir,

I want to buy Admob Pro License
Can you help me to implement the interstitial ads on navigation menu

**Comment by floatinghotpot** [comment]
The license fee only cover the usage of this plugin for commercial.

Please read the documentation and example code to learn how to use it, if any question, you can ask here.

**Comment by wahyuxo** [comment]
I only have basic html skills
my apps are based on simple html only, only article as a content
If you can help me to implement the interstitial ads on navigation menu in index.html, I'll buy the license
I'll sent my index.html later

**Comment by floatinghotpot** [comment]
@wahyuxo to my understanding, an app needs some logic, even very basic. I guess you need learn some javascript to make it an app.

**Comment by wahyuxo** [comment]
I use cordova to make app and I have the complete and working html5 template (include jquery.mobile and other javascript), I've tested it with admob_simple.js and the banner and interstitial appeared in my app, but the interstitial appear a few second after the app opened, and it break the admob rules.

The interstitial should be appeared in the transtition page before the next page appeared.

I want to call the interstitial to appear in the transatition page between index.html and the next page
I hope you understand it and can help me 
thanks

**Comment by floatinghotpot** [comment]
Okay, now I understand. 

I can check if I can help if you can send me (rjfun.mobile at gmail dot com):
1, your index.html file;
2, your ad unit id (created in your admob portal)

**Comment by wahyuxo** [comment]
I've sent you my index and ad unit via email (grapmarbel at yahoo dot com)
Title : "Wahyuxo Interstitial Github + ( Index Template File )"

I hope you can help me
thanks

**Comment by floatinghotpot** [comment]
I did received your email and downloaded your files from dropbox, but unfortunately, when open it in browser, it does not work properly and always show error loading page. Sorry, I have no time to debug your app, you need resolve it.

**Comment by wahyuxo** [comment]
You should remove cordova.js in the folder before to try it in the browser, because cordova.js will be loaded first before the index.html opened
I forget to remove the cordova.js from the folder

I've sent you a new file without cordova.js, you should be able to open it properly
I hope you can help me 
thanks

**Comment by floatinghotpot** [comment]
Yes, when I remove the following things to get it loaded in broswer.
```html
		<script type="text/javascript" charset="utf-8" src="cordova.js"></script>
		<script type="text/javascript" src="admob_simple.js"></script>
```
I can see clickable items in the browser, but when I click the items, it always shows `Error Loading Page`.

**Comment by wahyuxo** [comment]
Oks I see the problem,
You should open the file in Mozilla browser
I've tried to open it in Opera and the button always shows Error Loading Page
But, I have some applications from this template and run smoothly in my android devices.
