### ISSUE TITLE
Question about Commercial License

### ISSUE THREAD

**Issue by epraveen92** [floatinghotpot/cordova-admob-pro#525]
Hi,

I just started using your admob-pro plugin for my cordova app.

There are some discussions/issues I read that, regarding the 2% ad sharing to 30% ad sharing.

Questions/Clarifications:
1. Whether it is 2% ad sharing and How?
2. If I paid and get a license key from you, is it 100% no ad sharing and explain me how ?
3. Why should I get a license?

Please explain me.

**Comment by floatinghotpot** [comment]
Here is the license agreement:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/License-Agreement

**Comment by prantikv** [comment]
I would like some clarification as well.
As you have mentioned in the agreement,

> If you are using this plugin in a commercial project, please get a license. If you have used this plugin for FREE but monetized more than $1000, you are also required to get a license, or share very little Ad traffic.

1) If I use the plugin but the app has not made $1000, then there will be no sharing id ad traffic. Correct? Or the traffic is shared for every commercial App?

2) The $1000 limit is that a yearly, monthly, or Lifetime limit?
