### ISSUE TITLE
Close interstitial also closes background popup (on Android but not iOS)

### ISSUE THREAD

**Issue by peterel** [floatinghotpot/cordova-admob-pro#527]
Hi,

This is working on iOS but not on Android. 

I show an ad and open a popup in the background. When closing the ad the user sees the popup. This works well in iOS. However, on Android (HTC one) the closing of the ad also closes the popup. Any ideas on how to prevent that?

Id also like to add that the ad is an interstitial.

Is there any difference between onAdDismiss for iOS and Android which causes this?

Thanks.

Peter

**Comment by peterel** [comment]
No one that has any clue about how to solve this issue? The code looks something like this:

`...
if (typeof AdMob !== 'undefined') {
    //show ad
    if(AdMob) AdMob.showInterstitial();
    }
popup(data, to, popup);
...`

**Comment by peterel** [comment]
Not sure if anyone is reading this...would be great with some tips. Anyway, Ive been able to narrow it down a bit. Seems that closing an ad, on Android device (not iOS), also triggers the Cordova onResume (document.addEventListener("resume", onResume, false)). By my design this closes the popup so I now know why the popup gets closed but why would closing of an ad cause onResume to trigger?

**Comment by floatinghotpot** [comment]
I just guess, when an interstitial ad is displayed, the cordova in background will lose focus and trigger a 'pause' event. when the interstitial ad close, the cordova view get focus again, then it trigger a 'resume' event.

So, maybe you should not depends on the 'resume' or 'pause' event.

**Comment by peterel** [comment]
Thanks @floatinghotpot It makes sense that this is the case. Tricky to catch as it seems that iOS does not do this. Ive "solved" it with a flag which is checked in the 'resume' event to avoid unwanted behavior. Closing this issues now.
