### ISSUE TITLE
createBanner vs showBanner

### ISSUE THREAD

**Issue by prantikv** [floatinghotpot/cordova-admob-pro#528]
I am creating an app that will only have banner ads. As I am using just banner ads I want to maximize my earnings.

To do that I want to show different banner ads on two pages.

So For example I have the following user flow:
HomePage -> Page1 (showbannerAd) -> Page2(ShowbannerAd2)

I am preparing the banner ads as follows

      if (AdMob) AdMob.createBanner({
        adId: admobid.banner,
        isTesting: true,//comment this out before publishing the app
        autoShow: true
      });

Then, I am showing the ads as follows

     AdMob.showBanner

Will hiding and showing banner ads call a new ad? Or It that out of developers controlled and automatically managed by google?

If I want to get new ad as I want to maximize earnings what can be done?

PS: I know that doing so will have heavy data usage.

**Comment by floatinghotpot** [comment]
The banner is in native view, not part of your HTML page (DOM) in the web view.

You can use the same banner, and you can configure ad refresh time in admob portal.

**Comment by prantikv** [comment]
Thanks.
As mentioned by the author, the refresh rate can be changed in the abmod dashboard. The lowest is 30 seconds.
