### ISSUE TITLE
prepareInterstitial always invokes successCallback?

### ISSUE THREAD

**Issue by st0n3vn** [floatinghotpot/cordova-admob-pro#529]
`Hello,` I am trying to integrate AdMob in a Phaser game. I am only using interstitial ads (both static and video ads). I have done everything as explained and am getting both static and video ads successfully. The problem comes when a video interstitial is not filled.

I want to execute different logic when a video interstitial is played and when it's not. Unless I have understood the methods wrong, prepareInterstitial() should invoke its success callback only if the video has a fill? For me, prepareInterstitial() always invokes its success callback, even if the device has no internet access or there is no fill, and isInterstitialReady() behaves the same way.

I am currently displaying ads by calling prepareInterstitial with autoShow set to true (before that i was pre-fetching and manually playing the ad with showInterstitial(), but there was another bug which I won't mention now, and the workaround was to use autoshow).

Here is my code:

`AdMob.prepareInterstitial(

                {
                    adId: idToPrepare,
                    isTesting: false,
                    autoShow: true
                }, 
                () => {
                    AdMob.isInterstitialReady(() => {
                            console.log("ad ready");
                        }, 
                        () => {
                            console.log("ad not ready");
                        });
                    if ((<any>navigator).connection.type !== 'none') {
                        successFunction();
                    }
                    else {
                        failedFunction();
                    }
                }, 
                () => {
                    failedFunction();
                }
            );`

Note that because I was getting the success callbacks even with internet connection turned off, I had to manually handle that case. So basically, I am always logging "ad ready" and I am always calling successFunction, even if there is no fill (both with and without internet connection). Please help.

Thanks in advance!

**Comment by floatinghotpot** [comment]
Yes, prepareInterstitial() already return success if you provide a valid param. You need listen to event 'onAdLoaded' or 'onAdFailLoad' to check whether the ad is ready or not.

**Comment by st0n3vn** [comment]
Thanks, I didn't see these events before in the readme. Will try them out tomorrow and report back if everything's ok :)

**Comment by st0n3vn** [comment]
Sorry for the late response, just wanted to say that everything works correctly. The aforementioned events work correctly!
