### ISSUE TITLE
On the operation of reward video on iOS device

### ISSUE THREAD

**Issue by t-kura8400** [floatinghotpot/cordova-admob-pro#532]
Hello, I downloaded the test program and tried it.
https://github.com/floatinghotpot/cordova-admob-pro/tree/master/test
On Android worked normally, but on iOS it looks like the following.

1) In the test unit ID, the reward video was not played.
rewardvideo: 'ca-app-pub-3940256099942544/1712485313'
I was able to play the video with my unit ID.

2) Even if autoShow is set to true, video playback does not start.
I was able to play with showRewardVideoAd ();

3) 'onAdPresent' event can not be detected
'OnAdPresent' does not occur even if I closed the video after playing back the reward video.

*On the android device, both "rewardType" and "rewardAmount" were acquired.

**Comment by fermedina** [comment]
On iOS the autoShow: true don't work fine. I had the same problem and I solved this problem by changing autoShow to false and call to showRewardVideoAd() in the 'onAdLoaded' event

document.addEventListener('onAdLoaded', data => {
      console.log('Ad Loaded', data);
      AdMob.showRewardVideoAd();
});

This work fine with the test unit ID.

About 'onAdPresent' in my iPhone-6 emulator this event can be detected and get the rewardAmount. You can open the system log and see if the event is detected or no.

**Comment by t-kura8400** [comment]
Thank you for telling me how to autoShow.

  'OnAdPresent' seems to have not worked because it was experimenting in the environment called the monaca debugger. I tried it through testflight and it worked normally.

Thank you very much.
