### ISSUE TITLE
isTesting set to false ads do not appear in production on Android

### ISSUE THREAD

**Issue by ghost** [floatinghotpot/cordova-admob-pro#533]
On production overlay ad do not appear does it takes 24 to 48 hours? Should I need to Link my app from adMob dashboard?

I am using below code 
// prepare at beginning of a game level
AdMob.prepareInterstitial({
	adId: admobid.interstitial,
	autoShow: true,
isTesting: false
});
// check and show it at end of a game level
AdMob.isInterstitialReady(function(isready){
	if(isready) AdMob.showInterstitial();
});

**Comment by appplumbr** [comment]
isTesting: false and autoShow: true my ads not appearing?

**Comment by abdullahhacettepe** [comment]
i guess there is a version problem at android 7.0 included devices. plugin works smooth at my htc m8 and m7, but ads doesnt seem at my friends samsung (after update to 7.0). Any solution would be appreciable.

**Comment by floatinghotpot** [comment]
If you can see the test ad when isTesting:true, it's not the plugin or SDK issue.

please double check you are using a valid ad unit id, which is created for the exact platform.

**Comment by appplumbr** [comment]
Sorry still no luck, test ads appear and isTesting: false and autoShow: true my ads not appearing yet am on lollipop

**Comment by salahrd** [comment]
I've got the same problem,
when i set isTesting: false the ads not showing, i've got this error.
(btw, My ad unite works fine)

![errroo](https://cloud.githubusercontent.com/assets/17403871/24779562/2dd009bc-1b29-11e7-92e6-ad89f25c9351.PNG)

**Comment by floatinghotpot** [comment]
@salahrd 'No fill' is not a plugin or SDK error. It just means that the ad server did not find suitable ad resource for you. 

Usually, admob has a very good fill rate >95% for banner/interstitial ad, but there is still chance that your ad request may not be filled sometimes. 

You can try using mediation to some other ad networks to increase the fill rate. But no one can guarantee 100% fill rate.

**Comment by salahrd** [comment]
@floatinghotpot When i set isTesting : True; the app shows the test ads perfectrly, but when i set the value to false, its giving me that error message.
Can you please provide me a correct exemple with (showing intertitial on button click)

**Comment by appplumbr** [comment]
Same for me - When i set isTesting : True; the app shows the test ads perfectly. My app is live on play store with no ads displayed when set to "false"

**Comment by David-Kurniawan** [comment]
Me too....
Not work if i try set
`isTesting : false;`

@floatinghotpot  Help please...

**Comment by quocpt** [comment]
I have sample problem. For more clearly info: 

My IOS app is working file in emulator and real phone
My ANDROID app is display Admob Interstitial as in testing mode (even i change isTesting: false). And does not display on real phone.

**Comment by David-Kurniawan** [comment]
Yeah....
After 2 hours... my ads work perfect!

this is just about time. wait until admob find ads with same content with your app.

Thank you for the great plugin! :+1:

**Comment by burton22ful** [comment]
Does the app have to be available on the app store for the real ads to show ie isTesting: false because im not getting any real ads?

**Comment by floatinghotpot** [comment]
No need be on app store. but it must be installed to a real device. And usually after some hours after create the ad unit id. We guess that it takes Google system some time to sync the data to Ad server.

**Comment by burton22ful** [comment]
The error im getting for both banner and interstitial onAdFailLoad is: isTrusted : false, error: 0 , reason: Internal error. Im testing on a real device.

**Comment by burton22ful** [comment]
The device is android

**Comment by zahiruldu** [comment]
My ads code is in production. It is showing live ads smoothly. But recently I am observing sometimes it is showing test ads. Don't know why.

**Comment by angryanatole** [comment]
i have the same issue on adnroid
