### ISSUE TITLE
Make sure interstitials are fully loaded

### ISSUE THREAD

**Issue by calebeaires** [floatinghotpot/cordova-admob-pro#534]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[x] demo with specific cordova-admob-pro feature
[ ] support request
```
I received a google letter that complains about how the interstitials are being presented. I recognize that this plugin has the function `isInterstitialReady(function(ready){ if(ready){ } });` ([on wiki it is seted as DEPRECATED](https://github.com/floatinghotpot/cordova-admob-pro/wiki/1.4-Methods-for-Interstitial)) and I have already implemented it, but Google still sent me this letter.

There is on [ionic demo here](https://github.com/floatinghotpot/admob-demo-app-ionic), but it does not have `isInterstitialReady(function(ready){ if(ready){ } });`.

**I would like to ask the author or the community around this plugin that could create a demo for ionic that make sure that interstitials only appears if it is are fully loaded.**

Maybe I am missing something!

**Comment by floatinghotpot** [comment]
@calebeaires the API has been added back, as we found it's useful indeed.

See the API definition here:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/www/AdMob.js#L126

Just use it like this, as you mentioned:
```javascript
isInterstitialReady(function(ready){ 
    if(ready){ 
    } 
});
```

**Comment by calebeaires** [comment]
Thanks!
