### ISSUE TITLE
AdMob banner pushed the app title up in iOS

### ISSUE THREAD

**Issue by angel1st** [floatinghotpot/cordova-admob-pro#536]
Hi there,
Please note, I have already reported this in [AdMob Issues thread](https://github.com/floatinghotpot/cordova-plugin-admob/issues/229), however it seems present when using AdMobPro as well.
I would appreciate your feedback on this, thanks,
Angel

**Comment by catakkio** [comment]
I've got the same problem... ou've found any solution ?

**Comment by floatinghotpot** [comment]
When creating the banner, try adding more option: `offsetTopBar:true`. 

See the docs for more options here:
https://github.com/floatinghotpot/cordova-admob-pro/tree/master/docs#admobsetoptionsoptions
