### ISSUE TITLE
Does AdMobPro Show Developers Ads?

### ISSUE THREAD

**Issue by technotip** [floatinghotpot/cordova-admob-pro#537]
As claimed here: [AdMobFree](https://github.com/ratson/cordova-plugin-admob-free)
Does AdMobPro share revenue with the developer of the plugin?
Means, showing developers ad for certain percentage of times?

Is this true? 

Developer please don't get offended - my intention is just to clarify things and not to criticize for anything.

Thank you ..

**Comment by floatinghotpot** [comment]
Please read the license agreement for details. 

It's fully up to you to choose my open source one to DIY, or commercial/partnership one with timely support.

BTW, either AdMobSimple, or AdMobFree, is just a copy of my open source project (https://github.com/floatinghotpot/cordova-plugin-admob), my open source project has no  ad sharing long time ago. But the guy does not mention it.
