### ISSUE TITLE
Conflict with phonegap-plugin-push

### ISSUE THREAD

**Issue by jpveldtman** [floatinghotpot/cordova-admob-pro#539]
Please update to Firebase (ios 7.13.1 and later and managed by gradle in android)
As it is causing conflicts when using phonegap-plugin-push and read that is because both uses the google services which is causing the issue - please see https://github.com/phonegap/phonegap-plugin-push/issues/283.
If i use this plugin with the push plugin, the app crashes

**Comment by degaray** [comment]
I have the same issue. Do you have an idea on how to solve it or give it a turnaround?

**Comment by floatinghotpot** [comment]
I've implemented another version to work with firebase, with same API.

Try this one: `cordova-plugin-admobpro-firebase`.
