### ISSUE TITLE
Rewarded video is not showing.

### ISSUE THREAD

**Issue by saikat-ganguly** [floatinghotpot/cordova-admob-pro#541]
Hi,

I am trying to implement this plugin with my telerik platform hybrid app. I am trying to show reward video. Below is the code that I am using which is provided in your doc.

```javascript
var admobid = {};

// TODO: replace the following ad units with your own
if( /(android)/i.test(navigator.userAgent) ) {
  admobid = { // for Android
    banner: 'ca-app-pub-3940256099942544/6300978111',
    interstitial: 'ca-app-pub-3940256099942544/1033173712',
    rewardvideo: 'ca-app-pub-3940256099942544/5224354917',
  };
} else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
  admobid = { // for iOS
    banner: 'ca-app-pub-3940256099942544/4480807092',
    interstitial: 'ca-app-pub-3940256099942544/4411468910',
    rewardvideo: 'ca-app-pub-3940256099942544/1712485313',
  };
} else {
  admobid = { // for Windows Phone
    banner: 'ca-app-pub-6869992474017983/8878394753',
    interstitial: 'ca-app-pub-6869992474017983/1355127956',
    rewardvideo: '',
  };
}

function initApp() {
  if (! AdMob ) { alert( 'admob plugin not ready' ); return; }

  // this will create a banner on startup
  /*AdMob.createBanner( {
    adId: admobid.banner,
    position: AdMob.AD_POSITION.BOTTOM_CENTER,
    isTesting: true, // TODO: remove this line when release
    overlap: false,
    offsetTopBar: false,
    bgColor: 'black'
  } );

  // this will load a full screen ad on startup
  AdMob.prepareInterstitial({
    adId: admobid.interstitial,
    isTesting: true, // TODO: remove this line when release
    autoShow: true
  });*/

  AdMob.prepareRewardVideoAd({
                  adId: admobid.reward,
                  autoShow: true, 
                  isTesting: true
            		},
                function(msg) {
                    alert("prepare video : "+JSON.stringify(msg));
                },
                function(msg) {alert("prepareReward failed: " + msg)});
  AdMob.showRewardVideoAd();
}
```

I am calling the initApp method in button click. I can see the alert box of successful prepare but no ads are showing.

Can anybody please help me out with this ?

Thanks!
Saikat

**Comment by floatinghotpot** [comment]
It will take a few seconds for the plugin to load ad resources from server, so do not call showRewardVideoAd() immediately. Instead, call it later.

```javascript
var videoReady = false;
function prepare() {
    videoReady = false;
    AdMob.prepareRewardVideoAd({
        adId: admobid.reward,
        autoShow: false,
        isTesting: true
    });
}
function show() {
    if(videoReady) {
         AdMob.showRewardVideoAd();
    }
}
document.addEventListener('onAdLoaded', function(data){
    if(data.adType == 'rewardvideo') videoReady = true;
});
document.addEventListener('onAdFailLoad', function(data){
    if(data.adType == 'rewardvideo') {
         videoReady = false;
         prepare(); // prepare again for next ad
    }
});
document.addEventListener('onAdDismiss', function(data){
    if(data.adType == 'rewardvideo') prepare(); // prepare again for next ad
});

// call prepare() when your app init
// call show() when game level end or other place
```

**Comment by saikat-ganguly** [comment]
Hello,

Thank you very much for your support. I have tried to do what you suggested. I actually calling prepare method from another button click. But it is always failing back to onAdFailLoad event. I have printed the response. It is as follows. 

`{ "isTrusted" : false}, "adNetwork" : "AdMob", "adType" : "rewardedvideo", "adEvent" : "onAdFailLoad", "error" : 3 , "reason" : "No fill"`

I am not sure why this is happening. Can you please help me out on this ?

**Comment by floatinghotpot** [comment]
No fill, means that admob did not find suitable ad resource for your ad request. 

Usually, banner/interstitial ad have very high fill rate (>95%), but I am not quite sure about the fill rate of video ad.

Maybe you can try using admob with mediation to Vungle or other video ad provider, to increase the fill rate.

**Comment by saikat-ganguly** [comment]
Thank you for your answer. I will try and let you know . One more thing , is there any adapter required in cordova for admob-Vungle ?

**Comment by PrithiviRajG** [comment]
why I am getting **Internal Error**. below is the response for reward video fail
adEvent:"onAdFailLoad"
adNetwork:"AdMob"
adType:"rewardvideo"
bubbles:false
cancelBubble:false
cancelable:false
composed:false
currentTarget:null
defaultPrevented:false
error:0
eventPhase:0
isTrusted:false
path:Array(2)
reason:"Internal error"
returnValue:true
srcElement:document
target:document
timeStamp
103994.015
type:"onAdFailLoad"

**Comment by floatinghotpot** [comment]
We guess the "internal error" might be caused by SDK version change. The plugin has just been upgraded to latest SDK, please update the plugin and re-try.

**Comment by harryt2** [comment]
I guess this a little late but the problem may be this.

```
admobid = { // for Android
    banner: 'ca-app-pub-3940256099942544/6300978111',
    interstitial: 'ca-app-pub-3940256099942544/1033173712',
    **rewardvideo:** 'ca-app-pub-3940256099942544/5224354917',
  };
```

```
AdMob.prepareRewardVideoAd({
                  adId: **admobid.reward,**
                  autoShow: true, 
                  isTesting: true
            		},
                function(msg) {
                    alert("prepare video : "+JSON.stringify(msg));
                },
                function(msg) {alert("prepareReward failed: " + msg)});
  AdMob.showRewardVideoAd();
}
```
