### ISSUE TITLE
Not show Rewarded video

### ISSUE THREAD

**Issue by iRomano** [floatinghotpot/cordova-admob-pro#543]
After click, load video, and i have event:

Event {isTrusted: false, adNetwork: "AdMob", adType: "rewardvideo", adEvent: "onAdLoaded", type: "onAdLoaded", …}

But... video not showing, maybe app over it.
iOS 10.3.1

options = {
            adId: this.admobid.banner,
            isTesting: true,
            offsetTopBar:true
        }

**Comment by floatinghotpot** [comment]
as you did not set option `autoShow:true`, you need call showRewardVideoAd() to show it.

**Comment by iRomano** [comment]
Yes, i did:
AdMob.prepareRewardVideoAd(options, function(e) {
         console.log("success")
         AdMob.showRewardVideoAd();
         }, function(e) {
         console.log("error")
         });

**Comment by iRomano** [comment]
autoShow:true - not work

**Comment by floatinghotpot** [comment]
the prepare success callback just means your param has nothing wrong, but it does not mean the ad resource is ready.

instead of call show in prepare callback, call it in 'onAdLoaded' callback handler, or a even better timing is, call it at a game level end.

see #541 for the example code.

**Comment by iRomano** [comment]
@floatinghotpot thank you!
