### ISSUE TITLE
Interfering with local storage on IOS after new install?

### ISSUE THREAD

**Issue by rulorulo** [floatinghotpot/cordova-admob-pro#546]
Hi, I have installed the plugin on an Apperyio based app. Overall plugin works great. So thanks for that. 

I have one particular technical issue on IOS. My app uses localstorage to save game progress between sessions. When my app runs the very first time after install, it does save to localstorage fine, but when app is reopened it cant find the saved values. This is only on the very first open after an install (and the second re-open).  Subsequent opens have no problem, and can find the previously saved values. I searched the net and similar problem was reported for ios apps a few years ago. (https://issues.apache.org/jira/browse/CB-1535)("The problem is the UIWebView is created earlier than the new Key WebKitStoreWebDataForBackup"). The impact is that any progress made in the first run session of the game is lost. Subsequent runs have no problem.

This only happens with the admobpro plugin. I tested on a minimal clean app, and managed to reproduce the problem. When I uninstall AdmobPro, the problem goes away. No other plugins seem to cause the same problem. Hence my suspicion that this plugin is perhaps causing this problem. 

Does your plugin use localstorage in any way, which may be interfering with the initialisation process? Have you heard any similar story from other apps? Really appreciate any help you can give on this.

**Comment by floatinghotpot** [comment]
@rulorulo the plugin itself is Obj-C or java native code and based on Google AdMob SDK, it won't access the local storage inside the webview. 

The admob ad view is a webview, it might read/write the local storage value (We are not very sure about that part.) But in our previous app, we use the local storage without any problem.

If this problem exist persistently, there is still other options to save/load game records:
https://github.com/litehelpers/Cordova-sqlite-storage

FYI.
