### ISSUE TITLE
VideoReward not working

### ISSUE THREAD

**Issue by tominou** [floatinghotpot/cordova-admob-pro#548]
Hi,

I can't get videoReward to work. Here is what i do:

Prepare ---> onAdFailLoad called ---> prepare ---> nothing happens ---> prepare ---> nothing happens again

onAdLoaded is never called, the same always happened, the first attempt fail, then nothing in return for further attempts.

**Comment by centrual** [comment]
Same here. Fail data:
``` bash
Error: 0,
reason: Internal error,
adNetwork: AdMob,
adType: rewardvideo,
adEvent: onAdFailLoad
```

**Comment by prantikv** [comment]
+1
