### ISSUE TITLE
android build fails if I add admob pro plugin

### ISSUE THREAD

**Issue by varunaaruru** [floatinghotpot/cordova-admob-pro#549]
I just created a blank ionic2 app and installed the plugin using,

```
 ionic plugin add cordova-plugin-admobpro
 npm install --save @ionic-native/admob
```

and then `ionic platform add android` works fine
but `ionic build android` gives this error...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeDebugResources'.
> Error: com.android.builder.internal.aapt.AaptException: Failed to crunch file
C:\Users\varun\Desktop\personal apps\app\appname\platforms\andro
id\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10
.2.1\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_backgroun
d.9.png into C:\Users\varun\Desktop\personal apps\app\appname\pl
atforms\android\build\intermediates\res\merged\debug\drawable-xxhdpi-v4\common_g
oogle_signin_btn_icon_light_normal_background.9.png

struck with this from yesterday..build is working fine if I remove admob pro plugin

ionic version  2.2.2
node version 7.8.0
npm version 4.4.4

**Comment by floatinghotpot** [comment]
it seems that your android support library is not installed properly. please run `android sdk` to open the android sdk manager, then add the support libraries.

**Comment by varunaaruru** [comment]
Hi thanks for the reply.. What support libraries I need to add inorder to use this plugin?

**Comment by varunaaruru** [comment]
working fine after updating android sdk tools. Thanks..
