### ISSUE TITLE
WP8 Complie error

### ISSUE THREAD

**Issue by dadde** [floatinghotpot/cordova-admob-pro#55]
Trying to compile for WP8 i get the following error

Missing namespace 'boolean' at line 103 column 13 in AdMobPlugin.cs

**Comment by dbaseman** [comment]
@devalexqt,
It's because the class is named "AdMobPlugin", but in the examples, the calls from Javascript use "AdMob.createBanner".  Renaming the class to "AdMob" fixes this.  See also my issue: https://github.com/floatinghotpot/cordova-admob-pro/issues/70

**Comment by floatinghotpot** [comment]
I've merged the code from dbaseman, and built pass on phonegap build service. please update.

if any further issue, please discuss in #47 or #84
