### ISSUE TITLE
'Request Error: No ad to show.' on iPAD

### ISSUE THREAD

**Issue by standinga** [floatinghotpot/cordova-admob-pro#550]
Hey, I'm using cordova-plugin-admobpro 2.28.3
It works fine in Android, on iOS it works on iphone, but on iPad ad doesn't show up and Xcode shows: 
AdMob, onAdFailLoad, {'adNetwork':'AdMob','adType':'banner','adEvent':'onAdFailLoad','error':1,'reason':'Request Error: No ad to show.'}

I use the following code (works except on iOSX except iPADs): 
if(AdMob) {
                AdMob.createBanner( {
                    adId:admobid.banner,
                    autoShow:false
                } );
                document.addEventListener('onAdLoaded', function(e){
                    AdMob.showBanner(AdMob.AD_POSITION.BOTTOM_CENTER);
                });
                }

**Comment by floatinghotpot** [comment]
No Ad to show, may not be a error. 

The ad server just cannot find suitable Ad resource for your iPad device. Just not lucky enough.

As we know, the Ad fill rate cannot be 100%.

**Comment by standinga** [comment]
Strange because I never had this situation when I implement AdMob natively both swift and obj-c. Also I tried many times and I never succeeded displaying ads on Ipad and it never failed (with the same code) on iphone so far.
