### ISSUE TITLE
Android: Add not shown for package id com.example.helloworld

### ISSUE THREAD

**Issue by dellagustin** [floatinghotpot/cordova-admob-pro#551]
After some tests, I was only able to show the testing banner.
I could not solve the issue until I thought of trying to change my package id from the standard hello world to something else. It started showing my ads then.

when listening to onAdFailLoad I got the reason "Internal error".

I'm not sure if this is a known issue/feature (from AdMob, not from this plugin), but maybe it is worth mentioning it in the documentation.

**Comment by floatinghotpot** [comment]
AdMob might check your package id to be a unique id. Just guess.

Another reason is, it may take a little time for Google system to sync your data, so that it take into effect.

Another guess, the error `internal error` might be related with SDK update.
