### ISSUE TITLE
Error as soon as adding this plugin

### ISSUE THREAD

**Issue by dhruvJaiswal** [floatinghotpot/cordova-admob-pro#552]
When i add this plugin, and go for release it shows me error.
![screenshot_1](https://cloud.githubusercontent.com/assets/22024865/25574975/baee6dde-2e70-11e7-83f5-5d8a92556441.png)

please help me out i am trying from long. I am working with cordova in visual studio

**Comment by floatinghotpot** [comment]
The error seems to have nothing to do with this plugin. It tells you to open the SDK manager, and accept the license agreement.
