### ISSUE TITLE
iAD Mediation Adapter Plugin do not work.

### ISSUE THREAD

**Issue by carlobs** [floatinghotpot/cordova-admob-pro#56]
Now i see that the Plugin is supported by phonegap build but no info
on the mediation plugin, like:

com.google.cordova.admob-flurry
com.google.cordova.admob-iad
com.google.cordova.admob-inmobi
com.google.cordova.admob-mmedia
com.google.cordova.admob-mobfox

this should be a BIG improvements for all my iOS apps... i'm waiting for this.

**Comment by carlobs** [comment]
Hi,
I tryed to use the iAD adapter in CLI mode on MacMini, but i have BUILD FAILED,
the build is ok with Admob alone.
I think the plugin com.google.cordova.admob-iad have an error inside.

Here a part of the build error message:
"
Undefined symbols for architecture i386:
  "_ADBannerContentSizeIdentifierLandscape", referenced from:
      -[GADMAdapterIAdBannerPreIOS7 getBannerWithSize:] in libAdapterIAd.a(GADMAdapterIAdBannerPreIOS7.o)
      -[GADMAdapterIAdBannerPreIOS7 adjustADBannerToAdSize] in libAdapterIAd.a(GADMAdapterIAdBannerPreIOS7.o)
  "_ADBannerContentSizeIdentifierPortrait", referenced from:
      -[GADMAdapterIAdBannerPreIOS7 getBannerWithSize:] in libAdapterIAd.a(GADMAdapterIAdBannerPreIOS7.o)
      -[GADMAdapterIAdBannerPreIOS7 adjustADBannerToAdSize] in libAdapterIAd.a(GADMAdapterIAdBannerPreIOS7.o)
  "_OBJC_CLASS_$_ADBannerView", referenced from:
      objc-class-ref in libAdapterIAd.a(GADMAdapterIAdBannerPreIOS7.o)
      objc-class-ref in libAdapterIAd.a(GADMAdapterIAdBannerIOS7.o)
  "_OBJC_CLASS_$_ADInterstitialAd", referenced from:
      objc-class-ref in libAdapterIAd.a(GADMAdapterIAdInterstitial.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
"

**Comment by carlobs** [comment]
GREAT NEWS:
if i add both iad and mobfox adapter, both work fine.

**Comment by floatinghotpot** [comment]
sorry too busy to look into this issue. 

it's caused by missing iAd.framework in iad adapter, which exists in mobfox adapter too.

I've added it in adapter v1.0.1
```xml
<framework src="iAd.framework"/>
```

**Comment by floatinghotpot** [comment]
published to cordova registry already:
http://plugins.cordova.io/#/package/com.google.cordova.admob-iad

**Comment by ridwanridiawan** [comment]
Hi.. bro bagaimana cara install mediation ad network di intel xdk?
...

**Comment by floatinghotpot** [comment]
Use the Id: com.google.cordova.admob-iad

[v] in cordova plugin registry

**Comment by ridwanridiawan** [comment]
Thank's..

Third party plugin yang terinstall jadi 2? 
- com.google.cordova.admob
- com.google.cordova.admob-iad

Atau
com.google.cordova.admob-iad saja?

**Comment by floatinghotpot** [comment]
yes... I just guess, if the above is not English. :P

**Comment by ridwanridiawan** [comment]
:D i can not speak english..

i want to install admob and admob ad network on intel xdk..

- only use
 the Id: com.google.cordova.admob-iad

-or
Use the Id: com.google.cordova.admob, and com.google.cordova.admob-iad

There are modify code on index.html or config.xml?
...

**Comment by floatinghotpot** [comment]
If use ```com.google.cordova.admob-iad```, another one ```com.google.cordova.admob``` will be installed automatically as it's dependant.

Just treat it like AdMob plugin, you may need double check whether the mediation to be configured or not in AdMob portal.

**Comment by ridwanridiawan** [comment]
I design from adobe muse 720x1280 potrait with more html and insert adobe edge animate (oam). ->export to html.. and i create app on intel xdk base import from html5 and export to android croswalk.. app is great..

My question is why after add admob plugin on intel xdk my app so slow..?

**Comment by floatinghotpot** [comment]
admob sdk will load some ad resources from ad server, which may impact a little on the performance. but it should not be a big problem.

You can try the solution here:
https://shatter-box.com/knowledgebase/troubleshooting/

Or, delay a little big to enter your game, let the admob sdk loading plugin in "loading" stage.
