### ISSUE TITLE
Calling reward video multiple times

### ISSUE THREAD

**Issue by berrygal** [floatinghotpot/cordova-admob-pro#560]
Hi 
 I use your AdMob pro plugin in my apps and it works really well. but when I use the rewarded video for AdMob, i notice that it can only be called once until the app is reopened. I'm currently using jquery mobile and PhoneGap built, please how can I adjust the code so i can make a reward video click request multiple times in a session? 

thanks in advance

**Comment by Takahico** [comment]
Hi berrygal :)

Did you call function "prepareRewardVideo" multiple too ?
I don't know original specification, but I can see  reward video for multiple times, if I called "prepareRewardVideo" multiple.

**Comment by floatinghotpot** [comment]
Yes, each time before you call `showRewardVideoAd()`, you must call `prepareRewardVideoAd()` to load ad resource from server.

**Comment by ahmetkarakaya** [comment]
Thanks it works.
