### ISSUE TITLE
All except video ads are not closing (interstitial ads), iPhone 6 (not 5)

### ISSUE THREAD

**Issue by peterel** [floatinghotpot/cordova-admob-pro#562]
Ive not seen this as much as today. Tested on 3 of my apps that are using admob-pro interstitial ads. All on iOS. When an ad is presented (see attached image) the "x" does not close the ad. No matter how much you press on it/around it or even in the other corners. In fact, its not possible to press anywhere in the ad which makes any effect. Any idea what can be causing this and/or what I can do about it? Note: If its a "video ad" where the "x" comes up a bit later all works as intended and tapping the "x" does indeed close the ad. Note2: I would also like to add that this happens for more than just this specific "Trading ad". Note3: It seems that all is well on iPhone 5 but not on my iPhone 6. Would very much apprechiate if someone can verify if this is a general issue or not? My apps are "Movie Tip - Film recommendations for Your Taste" and "Tv-Series Tip: Tv Show Recommendations". Many thanks in advance! 

![img_5955](https://cloud.githubusercontent.com/assets/24371993/26348832/51bda1d2-3fae-11e7-92ce-30b12f4126f1.PNG)

**Comment by peterel** [comment]
Has anyone been able to reproduce this? It seems all is fine on iPhone 6s as well as 5. Im completely stomped on this. Id really like to know if anyone else is able to reproduce this. Or, if you can show me some other app which uses this plugin I can try them out to see if I can close ads there...maybe its just my phone with my apps that are the issue.

**Comment by peterel** [comment]
UPDATE: Sometimes, I see another "x" show up in the top left corner but it disappears very quickly, before I get a chance to click it. Clicking where it showed up after it disappears does noting.

Has really no one experienced or seen this?

**Comment by peterel** [comment]
No one that has experienced this?

**Comment by Takahico** [comment]
Hi peterel !

I can't reproduce this things.
and I looked for the same case project without this plugin, but I could not find it ;(

I could see [x] button to wait for a while that some InterstisialAd. 
Can' t you see [x] button to wait for a while ? 

I'm sorry if it's out of the way...

**Comment by peterel** [comment]
@Takahico Many thanks for you reply and help!

I was just able to reproduce. This happens when not of WiFi and being displayed ads on 4g or 3g. Im on iPhone 6 and this only happens for non-video ads (see attached for the ads that now froze). When it happens the first time, I see 2 [x], one on each top-corner, but for maybe just a second, and then one disappears. The other [x] does nothing and one gets no response clicking anywhere in the ad. All subsequent similar ads (non-video) then only show 1 [x] which does nothing and the entire ad is frozen. 

Please:

1) Can anyone reproduce?
2) Can anyone give a link or app name to ANY OTHER iOS app that uses this plugin so I can check if this only happens on my phone or is a general error?

Thanks! 

![img_6029](https://user-images.githubusercontent.com/24371993/27124586-dc67190e-50f1-11e7-82f9-cb1aa975c567.PNG)
![img_6028](https://user-images.githubusercontent.com/24371993/27124587-dc6c65e4-50f1-11e7-998b-34c176ab753c.PNG)
