### ISSUE TITLE
Reward videos are firing on Android device and iPhone simulator but not on iPhone device.

### ISSUE THREAD

**Issue by adampru209** [floatinghotpot/cordova-admob-pro#565]
I am testing on an iPhone 5. I am getting the following error in my XCode console:

<Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.

I have set -ObjC in the 'Other Link Flags' setting as well. I'm guessing this is a whitelist issue? Any feedback is appreciated.

**Comment by floatinghotpot** [comment]
You can try some mediation adapter to some other ad services, for example, UnityAds, has some good video ad resources.

With adapter plugin `cordova-plugin-admob-unityads`, and configure the mediation in admob portal.
