### ISSUE TITLE
Found com.google.android.gms:play-services-ads:+, but version 9.0.0 is needed fo r the google-services plugin.

### ISSUE THREAD

**Issue by Simerjit-developer** [floatinghotpot/cordova-admob-pro#566]
Android Build Failed with following exception:
```
Found com.google.android.gms:play-services-ads:+, but version 9.0.0 is needed fo
r the google-services plugin.
```
![error](https://cloud.githubusercontent.com/assets/13643281/26638027/bc55a9e0-463e-11e7-8215-2f3bd2a2e965.png)

**Comment by floatinghotpot** [comment]
com.google.android.gms:play-services-ads:+ means the latest version.

what do you mena by `google-services plugin`? any URL to the project home?

**Comment by simerjit-fwrk** [comment]
How I can check version from android studio sdk? All the dependencies are already installed in the android studio sdk

**Comment by floatinghotpot** [comment]
Did you install any other plugins?

Type `cordova plugin ls` then paste what you see.

**Comment by simerjit-fwrk** [comment]
I have installed Cordova fcm plugin, keyboard, console

**Comment by floatinghotpot** [comment]
We've found the root cause, this plugin is not compatible with fcm plugin. 

We will look into this issue, and will release another version compatible with fcm later.

**Comment by floatinghotpot** [comment]
@simerjit-fwrk we just published a plugin named `cordova-plugin-admobpro-firebase` to npm, it should be compatible with the fcm plugin. 

please remove `cordova-plugin-admobpro` from your cordova project, and use this new one, `cordova-plugin-admobpro-firebase`.

**Comment by Simerjit-developer** [comment]
Thanks.. I'll try this plugin and let u know.

**Comment by Simerjit-developer** [comment]
Still build not Successful, if i remove either of plugin, either fcm or  admobpro build get successful. After adding cordova-plugin-admobpro-firebase error came is:

Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-s
ervices plugin (information about the latest version is available at https://bin
tray.com/android/android-tools/com.google.gms.google-services/) or updating the
version of com.google.android.gms to 9.0.0.

**Comment by floatinghotpot** [comment]
Now the framework dependency has been changed to 
```xml
<framework src="com.google.firebase:firebase-ads:+" />
```
I have verified the plugin `cordova-plugin-admobpro-firebase` with fcm together and it builds pass. 

Try creating a new cordova project and verify the plugins.
```bash
cordova create test com.rjfun.test Test
cd test
cordova platform add android
cordova plugin add cordova-plugin-admobpro-firebase
cordova plugin add cordova-plugin-fcm
cordova build android
```

If error still happens, it must be something else wrong. Maybe your local SDK or cache.

**Comment by FrnandMG** [comment]
I had the same problem, now solved with `cordova plugin add cordova-plugin-admobpro-firebase`

thanks
