### ISSUE TITLE
Can't display rewarded video on iOS with mediation to UnityAds

### ISSUE THREAD

**Issue by Takahico** [floatinghotpot/cordova-admob-pro#567]
Please help me guys ;(
I Can't display rewarded video on iOS....
But I can display banner and interstisial ad.

*My environment ----------------------
  . cordova 7.0.1
  . cordova-admob-pro 2.29.0

*Error Message ------------------------
 <Google> Cannot find an ad network adapter with the name(s): GADMAdapterUnity. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.

{'adNetwork':'AdMob','adType':'rewardvideo','adEvent':'onAdFailLoad','error':9,'reason':'No ad returned from any ad server.'}
-----------------------------------------

Do I need to put in other plugins or SDKs ?

**Comment by Takahico** [comment]
Hi guys :)

I was self resolved this things.
I think, the cause of this things was "cache of Xcode build".

I deleted these directories and files.
 ->    /Users/USER_NAME/Library/Developer/Xcode/DerivedData/APP_PROJECT_NAME/
 ->    /Users/USER_NAME/Library/Developer/Xcode/DerivedData/ModuleCache/

and cordova build

$ cordova build ios

then, Open the project file and run.

I can see the all AdMob ads.

I'm sorry that I doubt many informations, blogs about AdMob.
I should have to doubted my skills....;(

thanks for all guys.

**Comment by Takahico** [comment]
Hi guys ..

I'm very sad ;(  Because, I can't display reward video to blame same errors...

*Error Message ------------------------
<Google> Cannot find an ad network adapter with the name(s): GADMAdapterUnity. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
-----------------------------------------

Some say that Admob is the cause.
but, I want to delete this error.
Where is "GADMAdapterUnity" and how do I setting this file ?

**Comment by floatinghotpot** [comment]
You are attempt to use admob mediation to unity, but did not add the admob-unity adapter yet.

We will look into this issue, and create a admob-untiy adapter plugin, if possible.

**Comment by floatinghotpot** [comment]
We've just published an adapter plugin named `cordova-plugin-admob-unityads`. Please add this new plugin after adding `cordova-plugin-admobpro`.

```bash
cordova plugin add cordova-plugin-admobpro
cordova plugin add cordova-plugin-admob-unityads
```

BTW, you must configure mediation to unity ads in your admob web portal. 

If any further problem, please let us know.

**Comment by Takahico** [comment]
Hi 

Yhank you very much your great job !
but it can't ;(

this is error message.
------------------------
$ cordova plugin add cordova-plugin-admob-unityads

Error: Uh oh!
Path must be a string. Received undefined
------------------------

**Comment by Takahico** [comment]
And

I install "cordova-plugin-admob-unityads".
then display this message.

------
Installing "cordova-plugin-admob-unityads" for android
------

and error message

------
Error: Uh oh!
Path must be a string. Received undefined
------

it is only android ?

**Comment by Takahico** [comment]
unity ads by My mediation group is Pending optimization now.
Is it one of cause ?

<img width="966" alt="ad-source" src="https://user-images.githubusercontent.com/29187512/27009616-8e2587f6-4ecd-11e7-9551-14773c5285ad.png">

**Comment by Takahico** [comment]
Hi floatinghotpot :)

Thnak you very much ! and really appreciate !
It is all works :)
I could install after remove android platform.

This is incompatible for android ?

**Comment by floatinghotpot** [comment]
I found the problem. When I published the adapter plugin, the unity-ads.aar is missing. Now the unity-ads.aar is added, and re-published as `cordova-plugin-admob-unityads@0.6.0`.

Please update the plugin, by removing and adding it again.

**Comment by Takahico** [comment]
Hi floatinghotpot :)

Thank you very much for your reply :)

I try "@0.6.0" but I can't install with android platform.
errror message is same, 
---------------------------
 Uh oh! Path must be a string. Recieved undefined
---------------------------

Just like last time, I delete Android platform, then I could install.
Actually, my apps not ready for android. Therefore, I don't setting BILLING_KEY now.
Perhaps, Is it may be the cause ?
and, my project file directory's name included 2byte strings.
I think,  this tihngs are bad environment ;(

**Comment by floatinghotpot** [comment]
Try naming your directory name to pure English?

**Comment by Takahico** [comment]
Hi floatinghotpot :)

I try it. but I can't ;(
directory named pure english ...
This is capture that the time.

This is capture that I tried.　(I am glad if it becomes helpful.)

<img width="1066" alt="sample" src="https://user-images.githubusercontent.com/29187512/27127918-b205398e-5137-11e7-9dd3-30eeb986ccd5.png">

**Comment by floatinghotpot** [comment]
I've fixed the plugin.xml like following (I just guess it cause error):
```diff
-    <resource-file src="unity-ads.aar" target-dir="libs" />
+    <resource-file src="unity-ads.aar" target="libs/unity-ads.aar" />
```

And I tested to build pass with following commands.

```bash
#!/bin/sh

rm -rf test

cordova create test com.rjfun.test Test
cd test

cordova plugin add cordova-plugin-admobpro
cordova plugin add cordova-plugin-admob-unityads

cordova platform add android

rm -rf www/*
cp -r plugins/cordova-plugin-admobpro/test/* www/

cordova build android
```

BTW, I upgraded cordova CLI to v7.0.1.
```bash
npm install cordova -g
```
