### ISSUE TITLE
children under the age of 13 as defined by COPPA 

### ISSUE THREAD

**Issue by subhash8108** [floatinghotpot/cordova-admob-pro#574]
Hi,

When I have select "Primarily Child-Directed" Yes then not working admob apps from play store.. please help me? please check below screen shot.
 
![admob](https://user-images.githubusercontent.com/542535/27704685-056f9cac-5d29-11e7-97bd-c1cfb78c28e1.png)

Thanks

**Comment by floatinghotpot** [comment]
Please read the docs:
https://github.com/floatinghotpot/cordova-admob-pro/tree/master/docs#targetting-options
```
AdMob.setOptions({
  // ... other options ...
  // custom targeting options
  customTargeting: {
    forChild:"yes"
  },
});
```
