### ISSUE TITLE
How to show ads from Facebook Audience Network together with AdMob ads?

### ISSUE THREAD

**Issue by remisture** [floatinghotpot/cordova-admob-pro#576]
Hi,

What are the steps needed to get Facebook ads showing together with AdMob ads?

This is what I have done so far, but I only get `'adNetwork':'AdMob'` requests served:

1.  `cordova plugin add cordova-plugin-facebookads`
2. `cordova plugin add cordova-plugin-admob-facebook`
3. Add space and banner placement in Facebook Audience Network
4. Add sources for the specific banner in AdMob: AdMob Network, Facebook Audience Network
5. Use this plugin to request Ads:
```
AdMob.createBanner({
          adId: "ca-app-pub-xxx", // banner-id from Admob
          position: AdMob.AD_POSITION.BOTTOM_CENTER,
        });
```

What am I missing? Should this be enough to get ads from Facebook? 

I can only see this in the logs: `{'adNetwork':'AdMob','adType':'banner','adEvent':'onAdLoaded'}`

Is there a complete working example of this anywhere?

PS. I have the Facebook app installed on my device, and logged in as admin, as the Facebook docs states.

Thank you!

**Comment by floatinghotpot** [comment]
In AdMob portal, add Facebook AudienceNetwork in mediation.

**Comment by remisture** [comment]
Yes, that was in my step 4. Still only `'adNetwork':'AdMob'` showing.

**Comment by remisture** [comment]
It works if I use `FacebookAds` directly, but isn't the idea that this plugin can show both AdMob and Facebook mediations, as long as both are added to the AdMob portal, and the `cordova-plugin-admob-facebook` is installed in the project?:

```
FacebookAds.createBanner({
   adId: admobid.facebook.banner, // Placement id from Facebook
   position: AdMob.AD_POSITION.BOTTOM_CENTER,
});
```

**Comment by floatinghotpot** [comment]
No, when use Facebook as mediation of AdMob, just set the facebook placement id into AdMob Portal, as medation.

It's correct the event only shows 'adNetwork':'AdMob', as facebook is only the mediated.

**Comment by remisture** [comment]
I still don't get it. So you are saying that this should give me Facebook ads, as long as the adId (in admob.com) contains a facebook mediation placement_id? Well, that is not happening :(

```
AdMob.createBanner({
   adId: admobid.banner,
   position: AdMob.AD_POSITION.BOTTOM_CENTER,
});
```

**Comment by floatinghotpot** [comment]
Yes, only need specify AdMob ad unit id here. And in AdMob portal, mediation, link your admob ad unit id to one or more other Ad network ad unit id. You need also configure priority with eCPM for each mediation Ad Network, then when condition matches, AdMob will request Ad resource from other Ad Networks. That's how AdMob mediation works.

**Comment by remisture** [comment]
Thank you, hopefully it works :)
