### ISSUE TITLE
Ads show over wifi, but dont show over mobile data

### ISSUE THREAD

**Issue by gem1000** [floatinghotpot/cordova-admob-pro#577]
Hello, please I have an issue I don't know what the cause is, but on my ionic 2 app, the ad units from google show over Wi-Fi connection, but don't show when I am connected to the internet via my mobile network. Thanks

**Comment by floatinghotpot** [comment]
As you can see the Ad over WiFi, the SDK and plugin are both working fine. 

As to why Ad does not show on mobile network, we don't have any clue. Try asking in Google AdMob official forum. https://groups.google.com/forum/#!forum/google-admob-ads-sdk

**Comment by gem1000** [comment]
Okay, thanks, will do just that

**Comment by MattWenger** [comment]
@gem1000 did you get an answer to this issue?  I'm experiencing the exact same issue with an ionic 2 app.

**Comment by gem1000** [comment]
Yes, I just simply ignored it and it solved itself, I have reason to
believe that my data provider probably had a part to play in the issue

**Comment by MattWenger** [comment]
Interesting - thanks for the input.  I'll keep an eye on it and see what happens.
