### ISSUE TITLE
Ad does not shows up in ionic 1 app

### ISSUE THREAD

**Issue by hemant07rulz** [floatinghotpot/cordova-admob-pro#578]
I have followed all the steps, still nothing shows up in ionic 1 app. please help

**Comment by vbmistry** [comment]
I am also facing same issue. I tried with testing id and also with my newly created( more then 3 days) app unit id. But showing black black box if i forcefully call showBanner() method. 
If i set autoShow: true then no any ads are coming.

I tried to check android log and found that getting "Error code : 2, Network Error" but my network is enabled on that device. so i don't know why it happening. 

Also i tried on many devices and many time with test and without test but not showing.

plugin & version i using
cordova-plugin-admobpro 2.29.21 "AdMob Plugin Pro"
cordova version : 6.2.0

Can you please help us if anyone also faced same issue and resolved ?

**Comment by hemant07rulz** [comment]
It takes some time to get real ads from Google Server. Please check your AdMob Id also. I used the free AdmOb plugin which does not share your ad revenue. Try this https://github.com/ratson/cordova-plugin-admob-free

**Comment by vbmistry** [comment]
As you can see on my above comment my app unit is created before 3 days. I am getting "Error code : 2, Network Error" even after my connection is enabled on that device. 
I waited for 5 to 10 min but every time i am getting same error. 

We would like to use plugin for earn revenue so we can't use free AdmOb plugin. 

Can you please help us on cordova-admob-pro if you have any idea on this issue ?
