### ISSUE TITLE
Build Error for cordova-plugin-admob-facebook 

### ISSUE THREAD

**Issue by t-kura8400** [floatinghotpot/cordova-admob-pro#579]
When building on iOS, the following error occurs.
Is something missing?

Installed plugin:
  cordova-plugin-admob-facebook
  cordova-plugin-facebookads
  cordova-plugin-extension

> Undefined symbols for architecture arm64:
>   "_kFBAdSizeHeight50Banner", referenced from:
>       -[GADFBBannerAd getBannerWithSize:] in FacebookAdapter(GADFBBannerAd.o)
>   "_kFBAdSizeHeight90Banner", referenced from:
>       -[GADFBBannerAd getBannerWithSize:] in FacebookAdapter(GADFBBannerAd.o)
>   "_OBJC_CLASS_$_FBAdView", referenced from:
>       objc-class-ref in FacebookAdapter(GADFBBannerAd.o)
>   "_kFBAdSizeHeight250Rectangle", referenced from:
>       -[GADFBBannerAd getBannerWithSize:] in FacebookAdapter(GADFBBannerAd.o)
>   "_kFBAdSizeInterstitial", referenced from:
>       -[GADFBBannerAd getBannerWithSize:] in FacebookAdapter(GADFBBannerAd.o)
>   "_OBJC_CLASS_$_FBAdSettings", referenced from:
>       objc-class-ref in FacebookAdapter(GADMAdapterFacebook.o)
>   "_OBJC_CLASS_$_FBNativeAd", referenced from:
>       objc-class-ref in FacebookAdapter(GADFBNativeAd.o)
>   "_OBJC_CLASS_$_FBAdChoicesView", referenced from:
>       objc-class-ref in FacebookAdapter(GADFBNativeAd.o)
>   "_OBJC_CLASS_$_FBInterstitialAd", referenced from:
>       objc-class-ref in FacebookAdapter(GADFBInterstitialAd.o)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by floatinghotpot** [comment]
It seems the plugin for dependent SDK not installed.

After a proper installation, you should find following plugins:
```bash
LimingAir:test1 liming$ cordova plugin ls

cordova-facebook-audnet-sdk 4.23.0 "Facebook AudienceNetwork SDK for Cordova"
cordova-plugin-admob-facebook 4.23.0 "AdMob Mediation Adapter for Facebook Audience Network"
cordova-plugin-admobpro 2.29.21 "AdMob Plugin Pro"
cordova-plugin-extension 1.5.1 "Cordova Plugin Extension"
cordova-plugin-facebookads 4.23.1 "FacebookAds"
```

**Comment by floatinghotpot** [comment]
Basically, you need manually install the following plugins:
```bash
cordova plugin add cordova-plugin-admobpro
cordova plugin add cordova-plugin-admob-facebook
```

The others will be auto installed as dependency.

**Comment by t-kura8400** [comment]
"Cordova-facebook-audnet-sdk" has not installed, so I installed it.
But ,the same error occurs yet.
It may be my PC environmental problem.
I will check the cause of errors.
Thank you.
