### ISSUE TITLE
iOS and android demos not working initially, iOS not working from command line.

### ISSUE THREAD

**Issue by wwhyte** [floatinghotpot/cordova-admob-pro#580]
I tried the quick start demo:
```
    cordova create test1 com.rjfun.test1 Test1
    cd test1
    cordova platform add android
    cordova platform add ios
    cordova plugin add cordova-plugin-admobpro
    rm -r www/*;
    cp plugins/cordova-plugin-admobpro/test/* www/;
    cordova prepare; 
    cordova run android; 
    cordova run ios;
```

On Android I got the error

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'android'.
> > java.lang.NullPointerException (no error message)

On iOS the build output ended with the following:

> Signing Identity:     "-"
> 
>     /usr/bin/codesign --force --sign - --timestamp=none /Users/wwhyte/Dropbox/wwhyte-dev/cordova-sandbox/admob-sandbox/test1/platforms/ios/build/emulator/Test1.app
> 
> ** BUILD SUCCEEDED **
> 
> Error: Cannot read property 'replace' of undefined

When I open the platforms/android/build.gradle file in Android Studio, it prompts me to upgrade Gradle. When I do that, I can build inside Android Studio and the demo app shows the banner when I hit the "show banner" button.  Once I've done that once, I can then run the demo with "cordova run android".

When I open platforms/ios/Test1.xcodeproj in Xcode, it runs perfectly, but then when I go back and try to run from the command line it fails with the same error as before.

I can run from Xcode okay, but it would be handy to be able to use the CLI. Any thoughts?

**Comment by floatinghotpot** [comment]
You may need upgrade the cordova CLI to latest version, I just guess.

**Comment by floatinghotpot** [comment]
> Error: Cannot read property 'replace' of undefined

This error is caused by Cordova tool. The ios-sim is out of date.

Solution: after create each cordova project, run following commands to fix it:
```bash
cd platform/ios/cordova && npm install ios-sim@latest && cd ../../..
```
Now it will work.
```bash
cordova emulate ios
```
