### ISSUE TITLE
AdMob.prepareInterstitial() not showing interstitial on iOS only (Device & Simulator)

### ISSUE THREAD

**Issue by anhackin** [floatinghotpot/cordova-admob-pro#581]
Simply call prepareInterstitial like this:

`AdMob.prepareInterstitial({
    adId: "ca-app-pub-XXXX/YYYY",
    autoShow: true
});`

It seems to be the command that is not executed when sended by cordova.exec() at line 119 in AdMob.js.

> I think I found two errors in AdMob.js (Lines 119 & 143).

`cordova.exec( successCallback, failureCallback, 'AdMob', 'prepareInterstitial', [ args ] );`

> Maybe should be replaced by:

`cordova.exec( successCallback, failureCallback, 'AdMob', 'prepareInterstitial', [ options ] );`

> However I've tested with "args" and with "options", the interstitial still does not show itself.

The only way to display the interstitial is to open the notification center. 
By doing this the native side of the plugin receives the command "createInterstitial".

Tested on devices (iPhone 5C , iPhone 6 & iPhone 6+) on iOS 10.3.2 (14F89) and simulator on iOS 10.2 (14C89).

**Comment by carlosjavier84** [comment]
Same problem. Any solution?

**Comment by floatinghotpot** [comment]
Thanks to @anhackin, yes, it's a bug, though it does not impact most situation, if args is a string only (for adId), it will cause error. Fixed, thanks again.
