### ISSUE TITLE
Admob Pro auto shoe doesnt work for interstitial ads

### ISSUE THREAD

**Issue by Detercan** [floatinghotpot/cordova-admob-pro#584]
Hi,

i ve bulding an app by using vs7 cordova and i ve installed this plugin, it works well but for intersititial ads dont show auto. my codes are below;

```javascript
    function reklamYukle() {
        var admobid = {};
        // TODO: replace the following ad units with your own
        if (/(android)/i.test(navigator.userAgent)) {
            admobid = { // for Android
                banner: 'ca-app-pub-5534669392136777/9811456161',
                interstitial: 'ca-app-pub-5534669392136777/5454702358',
            };
        } else if (/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
            admobid = { // for iOS
                banner: 'ca-app-pub-5534669392136777/7944497261',
                interstitial: 'ca-app-pub-5534669392136777/4856501200',
            };
        } else {
            admobid = { // for Windows Phone
                banner: 'ca-app-pub-6869992474017983/8878394753',
            };
        }

        AdMob.createBanner({
            adId: admobid.banner,
            position: AdMob.AD_POSITION.BOTTOM_CENTER,
            overlap: false,
            offsetTopBar: false,
            bgColor: 'black',
            autoshow: true
        });

        AdMob.prepareInterstitial({
            adId: admobid.interstitial,
            autoShow: true
        });
    }

    function onDeviceReady() {
        reklamYukle();
    }

    document.addEventListener("deviceready", onDeviceReady, false);
```

**Comment by floatinghotpot** [comment]
Actually it's not a good idea to auto show interstitial, as usually it will take a little time to load ad resource from server, and may display unexpected.

It's a better practice to prepareInterstitial() with autoShow:false, then showInterstitial() at a better timing, like at a game level over, or let the use decide to watch it.

**Comment by Detercan** [comment]
I changed my code as u said. But i released that interstitial ads are not displayed twice. I just put click function for a button to checked it wheather its working or not when i click first time its working well, but on twice click its not working. What can be caused this ?

**Comment by floatinghotpot** [comment]
Before each call to showInterstitial(), you need call prepareInterstitial() to load ad resource from server,  and wait for 'onAdLoaded' event as notification of ad resource ready.
