### ISSUE TITLE
Hundreds of Android Vitals crash reports

### ISSUE THREAD

**Issue by tominou** [floatinghotpot/cordova-admob-pro#585]
Hi,

I got hundreds of crash reports linked to cordova-admob-pro from Android vitals.

I am using:
cordova 7.0.1
cordova-android 6.2.3
cordova-admob-pro 2.29.21

I am not using crosswalk webview.

Here are the reports (all are the same, but happen on different devices and android version 4.4 to 7+):

> java.lang.NullPointerException: 
>   at com.rjfun.cordova.admob.AdMobPlugin.getAdViewSize (AdMobPlugin.java:185)
>   at com.rjfun.cordova.admob.AdMobPlugin.__getAdViewWidth (AdMobPlugin.java:191)
>   at com.rjfun.cordova.ad.GenericAdPlugin$5.run (GenericAdPlugin.java:582)
>   at android.os.Handler.handleCallback (Handler.java:739)
>   at android.os.Handler.dispatchMessage (Handler.java:95)
>   at android.os.Looper.loop (Looper.java:158)
>   at android.app.ActivityThread.main (ActivityThread.java:7225)
>   at java.lang.reflect.Method.invoke (Native Method)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

Thank you in advance.

**Comment by floatinghotpot** [comment]
Here is the source code:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/src/android/AdMobPlugin.java#L185
```java
  protected AdSize getAdViewSize(View view) {
    if(view instanceof PublisherAdView) {
      PublisherAdView dfpView = (PublisherAdView) view;
      return dfpView.getAdSize();
    } else {
      AdView admobView = (AdView) view;
      return admobView.getAdSize();
    }
  }
```

NullPointerException means adview is NULL, it seems the adview is not created for some unknown reasons.

In normal cases, it won't happen. Unless, system error, like out of memory, etc.

**Comment by tominou** [comment]
Thank you for your answer.

Then isn't it possible to check if adview is NULL or not to avoid the crashes?

**Comment by floatinghotpot** [comment]
Nothing can be done if out of memory.

**Comment by tominou** [comment]
I am not sure that is the issue.
It occurs on many phones with 4gb ram or more. Users report that it happens a few seconds after launching the app.

What would happen if i call AdMob.removeBanner, AdMob.showBanner or AdMob.hideBanner before the banner is created? Could it be the source of the crashes?

**Comment by floatinghotpot** [comment]
calling removeBanner() too soon after createBanner() might cause the issue. As it will take some time to load the ad resource from ad server, need give the app a little time to process. hideBanner() won't cause the issue, as the ad view is not deleted, it's just make invisible.
