### ISSUE TITLE
Disabling Back Button During Ads

### ISSUE THREAD

**Issue by faytekin** [floatinghotpot/cordova-admob-pro#587]
In my app, you can skip an AdMob ad, both using the default closing button (X) on the ad or using the device's back button. I want device's back button to be useless. Nobody should close an ad with back button. How can I do that?

**Comment by floatinghotpot** [comment]
It seems not possible, as the behavior is handled by the Google AdMob SDK.

You can override the cordova backbutton event to prevent app from exiting, but it may not work for Ads.

```javascript
    $(document).on('backbutton', function(){
      if(window.confirm('Are you sure to quit?')) navigator.app.exitApp();
    });
```

**Comment by momikus** [comment]
But it seems that some developers do that. Is it not allowed or is it not possible? (Talking for preventing back button from ad screen)

**Comment by floatinghotpot** [comment]
As said, it seems not possible, as the behavior is handled by the Google AdMob SDK, I think it's designed by Google intentionally.
