### ISSUE TITLE
AdMob doesn't display adz on Android - Uncaught error type "require"  undefined function 

### ISSUE THREAD

**Issue by Samuelpinheiro** [floatinghotpot/cordova-admob-pro#588]
I have integrated the cordova-plugin-admob-pro into my Cordova Project without build errors, however, it doesn't display adz at all in the app. Using Cordova serve, the web browser throws an error in the console. Please help with this project, I have been looking around for solutions for weeks. Thanks 

Android - target 25
Cordova @7.0.0

**Comment by richardm75** [comment]
Same problem here, no ads are displaying in my own app. But the sample test app works perfectly. I copied code from the test app into mine.

There are no errors in the console. For my app the Chrome inspect page lists only my app window. The sample app (which works fine for me) contains 3 extra entries

- https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html
- about:blank
- about:blank

That's the only difference. My app is missing those 3 entries. Seems that AdMobPro is not setting up fully, not reaching out to fetch ads. Why might that happen?

Android target 25
Cordova 7.0.1
plugins: media, device. whitelist.

**Comment by floatinghotpot** [comment]
try:
```
npm install -g plugin-verify
plugin-verify cordova-plugin-admobpro
```
This will create a demo project and verify the plugin in your environment. If you see a test ad, it works well.

And, please double check and make sure:
1. you are running the app on a device, not on emulator.
2. If you are using ios device, you have to use a valid ad unit created for ios, AND create for interstitial.

**Comment by richardm75** [comment]
Thanks. I think I've got into a mess here. 

Originally your verify test app worked. Then I copied your code into my app. I mistakenly put an IOS key into my real app and ran it on Android. For about 30 mins I saw ads appearing. Great, all working. 

But then new ads stopped appearing. Every time I restarted my app I saw this error message:
`AdMobPro onAdFailLoad error: 2, reason: Network Error, adNetwork:AdMob, adType:banner, adEvent:onAdFailLoad`
I am using code
`        if(AdMob) { 
            AdMob.createBanner({
            adId: AdsJB.adBannerID,
            position: AdMob.AD_POSITION.BOTTOM_CENTER,
            autoShow: true
            });
            console.log("ad banner created")
        }`
Does "Network Error" mean the Ad Network? (rather than the wi-fi/phone network)

I updated my app with the correct key for Android. But the same error continues to appear. I seem to be stuck in permanent error mode. Is the ad network blocking me because of my mistake?

And, worse, when I run your test app (unchanged) I see an alert box with the same error message. This still uses the original keys that you included in your code. I changed nothing in your test, but it no longer works.

How do I get back to working ads? I have the correct Android key in place now. and I see from my console log that it is being used. Everything else about my Android phone and my app is functioning perfectly.

**Comment by floatinghotpot** [comment]
For test purpose, please run with test ad only. Using real ad for test is forbidden by Google, as it's regarded as cheat behavior. Your app id might have been banned.

Try creating a new app. 

For test purpose, using test ad is enough. Just remember to set isTesting:true before packaging for release.

Good luck.

**Comment by richardm75** [comment]
Thank you but this doesn’t quite make sense. Maybe my App ID has been banned. But . . . 

 

I rebuilt your test app. Didn’t change anything in it. The test app fails with the same alert message,

 

error: 2, reason: Network Error, 

adNetwork:AdMob, adType:banner, 

adEvent:onAdLoadFail

 

How can your test app fail now? It used to work. It uses your app ID, not mine. That’s what I don’t understand. 

 

Is it possible that they are blocking my device, or my IP address, rather than my App ID? If so, can you suggest how to get unblocked? 

 

Sorry about these questions, but I am baffled by the behavior.

 

Richard Mott

San Diego

**Comment by floatinghotpot** [comment]
I don't think they will block device or IP. Maybe it's really your network problem.

Could you please send your ad unit id to us (rjfun.mobile at gmail.com)? we can test it in a demo project to check whether the ad unit id is good.

**Comment by richardm75** [comment]
Thanks.

 

These are the Unit IDs for my project. 

 

    adBannerIdIOS:           "ca-app-pub-9541931695796816/3783557642", 

    adInterstitialIdIOS:     "ca-app-pub-9541931695796816/9007964163",

    adBannerIdAndroid:       "ca-app-pub-9541931695796816/4856966168",

    adInterstitialIdAndroid: "ca-app-pub-9541931695796816/9037428912",

 

I am using the Android keys in my app. 

 

But I’m still puzzled as to why your test app is now failing as well. It doesn’t use my project Unit IDs. It uses yours. 

Richard Mott

 

San Diego

**Comment by floatinghotpot** [comment]
hi @richardm75 I tested your ad unit in a demo project, it works fine.

Just use this html file
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/test/index.html

Replace the ad unit ids with yours, and change `isTesting:true` to `isTesting:false`, then `cordova build android`. 
When run `cordova run android` to install and run the app in a device, it works and display the real ad. 
The ad units are correct.

**Comment by richardm75** [comment]
Raymond, 

 

First, thank you so much for taking time on this problem, and for responding so quickly. I am up against a deadline and I love your support. 

 

I did exactly what you suggest and it didn’t work. Result is in attached jpg. I see this screen when the app loads, before I get the chance to tap any button. If I tap OK to clear the error then tap createBanner or prepareInterstitial the alert appears again. This is exactly the same symptom that I see in my app. 

 

My phone is fine in every other respect. My app streams internet audio perfectly, browses anywhere, etc. My wi-fi connection is totally fine, very strong, right next to the router. I don’t have any blockers on my phone, just simple apps. I see ads in several other apps. 

 

Any thoughts here? Why might my requests to AdMob be failing? Any ideas how can I start to debug this problem?

 

The frustrating thing is that I did see ads successfully using your AdMobPro plugin in my app for about 30 minutes. I was delighted. Then new ads stopped appearing and an every application restart showed this error via onAdFailLoad. 

 

My code changes to your test app are,  

 

  var admobid = {};

  if( /(android)/i.test(navigator.userAgent) ) {

    admobid = { // for Android

      banner: 'ca-app-pub-9541931695796816/4856966168',

      interstitial: 'ca-app-pub-9541931695796816/9037428912',

      rewardvideo: 'ca-app-pub-3940256099942544/5224354917',

    };

  } else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {

    admobid = { // for iOS

      banner: 'ca-app-pub-9541931695796816/3783557642',

      interstitial: 'ca-app-pub-9541931695796816/9007964163',

      rewardvideo: 'ca-app-pub-3940256099942544/1712485313',

    };

 

    AdMob.setOptions({

      // adSize: 'SMART_BANNER',

      position: AdMob.AD_POSITION.BOTTOM_CENTER,

      isTesting: false, // set to true, to receiving test ad for testing purpose

      bgColor: 'black', // color name, or '#RRGGBB'

      // autoShow: true // auto show interstitial ad when loaded, set to false if prepare/show

      // offsetTopBar: false, // avoid overlapped by status bar, for iOS7+

    });

 

Again, thank you,

 

Richard Mott

San Diego

**Comment by richardm75** [comment]
Hi Raymond, 

 

Problem solved. At least for now. Until it happens again . . . . 

 

The problem must have been in my phone. I still have no idea what it was. The old, old solution worked: clear cache, reboot. Then the ads came back. Very strange. These days I never think to reboot a phone. They are so reliable that I go months without rebooting. 

 

Still, can’t argue with success. I am running at the moment in test mode and seeing test ads. I briefly tried production mode and that worked fine too. 

 

Raymond your support response has been terrific. I never doubted your plugin, just couldn’t work out what was going on. 

 

Now, I will certainly recommend the owner to buy a license! Keep up the good work. 

 

Richard Mott

San Diego

**Comment by floatinghotpot** [comment]
hi @richardm75 Good to see you find the root cause and resolved the problem. Enjoy monetization with admob.

**Comment by Samuelpinheiro** [comment]
Hi Raymond,  
Thanks for your response. 
I used the plug-in  verify and it run on my device but the same error 

AdMobPro onAdFailLoad error: 2, reason: Network Error, adNetwork:AdMob, adType:banner, adEvent:onAdFailLoad

Restarted my device severally and the same error appears. 

So I used the  test  index.html in my device but not nothing was displayed. 

I have sent my Admob Ad Unit to your mail.  Please could you help verify mine too 
Thanks

**Comment by floatinghotpot** [comment]
No problem, send us your ad unit id, we can try verifying it, but we did not receive your email with ad unit id yet.

BTW, network error, usually means your device has problem loading ad resource from google server. You can check the network routing path.

**Comment by floatinghotpot** [comment]
@Samuelpinheiro 

When I use your ad unit id in the test app, it reports error:
> error:1, reason: invalid request.

Please double check your ad unit id, and make sure it’s created for ANDROID app and BANNER.

BTW, here are the often seen admob error code. The error code is usually:
ERROR_CODE_INTERNAL_ERROR, 
ERROR_CODE_INVALID_REQUEST, 
ERROR_CODE_NETWORK_ERROR, 
or ERROR_CODE_NO_FILL.
