### ISSUE TITLE
replace "com.google.android.gms:play-services-ads" to "com.google.firebase:firebase-ads:10.2.6"

### ISSUE THREAD

**Issue by katouyuta** [floatinghotpot/cordova-admob-pro#589]
my cordova app using this "cordova-admob-pro"  plugin.

this plugin is using "com.google.android.gms:play-services-ads".
affter add another  plugin "cordova-plugin-fcm".
 "cordova-plugin-fcm" is  include "framework com.google.firebase".

build error 

`* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.`

my situation is  replace "com.google.android.gms:play-services-ads" to "com.google.firebase:firebase-ads:10.2.6"  on the plugins.xml define.

Is there any good method for this situation?

**Comment by floatinghotpot** [comment]
instead of `cordova-plugin-admobpro`, use this one: `cordova-plugin-admobpro-firebase`

**Comment by katouyuta** [comment]
@floatinghotpot 
Thank you.
