### ISSUE TITLE
Interstitial ad is not displaying when isTesting = false

### ISSUE THREAD

**Issue by giorgioarmanix** [floatinghotpot/cordova-admob-pro#591]
Hello,

In first, thank you for your plugin.

I want to display an Interstitial ad on an ionic 1 app, it's working find on demo mode, but when the isTesting property is set to false, no ad appears...

I'have found a lot of issues with the same problem but no solution.

Here is my code:
```javascript
/**
 * @description
 * Public method used to show an interstitial ad.
 */
showInterstitialAd: function() {
    var admob  = $window.AdMob;
    if(admob) {
        admob.prepareInterstitial({
            adId: 'ca-app-pub-6869992474017983/1657046752',
            autoShow: true,
            isTesting: false,
            success: function() {
                admob.showInterstitial(
                    function(success) {
                        console.log('success: ', success);
                    },
                    function(error) {
                        console.log('error: ', error);
                    }
                );
            }
        });
    }
}
```
The success log is reached every time but no ad appends. I have tested it with my own Interstitial id created on admob 1 month ago, plus tested with yours and it's still not working (yours: 'ca-app-pub-6869992474017983/1657046752').

Here are my cordova plugins:

```
cordova-plugin-admobpro 2.29.21 "AdMob Plugin Pro"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-device-orientation 1.0.7 "Device Orientation"
cordova-plugin-extension 1.5.1 "Cordova Plugin Extension"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-sqlite-storage 1.5.3 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

+ all my android sdk, google services, etc... are up to date.

Thank you very much.

**Comment by floatinghotpot** [comment]
hi @giorgioarmanix, if the demo mode works, the plugin and sdk is fine.

please double check and make sure:
1. you are running the app on a device, not on emulator.
2. If you are using ios device, you have to use a valid ad unit created for ios, AND create for interstitial.

**Comment by giorgioarmanix** [comment]
hi @floatinghotpot, thank you for your answer.

Im running it on android devices, tested it on android 7 and 6, everytime it's the same issue.

I have tested a lot of things like adding AdMob mediation adapters, testing run from Linux, Windows or Mac, removing some cordova plugins, testing timeout about 1000 ms in the prepareInterstitial success method, changing the admob interstitial id,  no more ideas now :(

Does my code is correct ?

Thank you very much.

**Comment by floatinghotpot** [comment]
In most cases, I can guess, the only issue is your ad unit id, is it valid? (did you create an android app in admob portal, then create an interstitial id for it?)

**Comment by giorgioarmanix** [comment]
It seems to be valid, it's an Interstitial ad on android device with no restriction, tested it with yours from your demo code + tested it with a new one this morning, same result.

I have somes news today:

```javascript
document.addEventListener('onAdFailLoad', function(e){
    console.log('onAdFailLoad: ', e);
});
```

This event is catching an error:

```javascript
{  
   "isTrusted":false,
   "adNetwork":"AdMob",
   "adType":"interstitial",
   "adEvent":"onAdFailLoad",
   "error":0,
   "reason":"Internal error"
}

```
I'm searching for it (internal error) right now.

**Comment by floatinghotpot** [comment]
'internal error' is usually caused by version out of date. try updating your android sdk, google play services, etc.

**Comment by floatinghotpot** [comment]
As you mentioned, you are using this ad unit id for testing: (yours: 'ca-app-pub-6869992474017983/1657046752') Do not use this ad unit id for testing purpose. It's already out of date. Google will not push ad for it.

Use your own ad unit id, and make sure it's created properly, which means:
* If you are using ios device, you have to create an ios app in admob portal, AND create for interstitial ad unit id.
* If you are using android device, you have to create android app, AND create for interstitial ad unit id.

Again, please notice: 
* DO NOT use the real ad for testing purpose, it's forbidden by Google.
* If you are seeing test ad works well, it means your implementation is good and ready to work. 

(see more details here:
https://developers.google.com/admob/android/test-ads
It is important to enable test ads during development so that you can click on them without charging Google advertisers. If you click on too many ads without being in test mode, you risk your account being flagged for invalid activity.)

Finally, remember to change to `isTesting:false` before packaging your app for release.

**Comment by jules-jayet** [comment]
Hey, thank you very much for these information, i will test it tomorrow and let you know about the results.

Regards

**Comment by giorgioarmanix** [comment]
Hey, thank your very much for these information, i will test it tomorrow and tel you about the results.

Regards

**Comment by giorgioarmanix** [comment]
Hey floatinghotpot,

I've found the solution, after reinstallations & reinstallations finally found a small box test on my admob account, telling me to give my payment informations.

I have completed the information and ... it's work great.

Thank you for your great plugin & support !

**Comment by floatinghotpot** [comment]
Glad to hear that your problem is resolved. Enjoy.
