### ISSUE TITLE
No Ad to Show (reward video)

### ISSUE THREAD

**Issue by Lecramed** [floatinghotpot/cordova-admob-pro#592]
Hi, i get an error "No ad to show",
But it was working fine 2 weeks ago. "isTesting=true"

After this error i created a new account and a new advertisement block in admob. But again the same message in the **onAdFailLoad**

Anyone else having this problem?

**Comment by floatinghotpot** [comment]
Try changing `isTest:false`, and run app on device to have a look. (But be aware that do not use real ad for testing too many times)

"No Ad to show", just means, the ad server did not find proper for you to show at the time. It's very often situation. If at the time, no advertiser is investing on ad. 

As I know, AdMob has very good fill rate, like 95% or higher, but still sometimes no ad filling and maybe lower in some countries. Some other ad network has much lower fill rate, like 75% or even 50%.

**Comment by Lecramed** [comment]
I switched to a interstitial..brought it to production. it worked all day but now the same error. Is there a way to reduce the error.

**Comment by Lecramed** [comment]
Oh the error in the rewardvideo persists when istesting=false. Also left A remark at admob site. Because i agree the plugin should work.

**Comment by floatinghotpot** [comment]
No Ad to show, is not a real error. It's just the system happen to fail find proper ad resource for you. No ad network, even AdMob, cannot guarantee 100% fill rate. 

Again, use test ad to test. Do not test with real ad on your own device. Google smart system may detect as a cheat behavior. If your app & admob works fine with test ad, then the plugin, SDK and integration is okay and ready to work.
