### ISSUE TITLE
Inappropriate ads shown on Android and IOS

### ISSUE THREAD

**Issue by jmelvin** [floatinghotpot/cordova-admob-pro#595]
When doing some final testing for our app before updating, I noticed that an ad started showing up consistently on both IOS and Android for "male enhancement pills" and shows a CNN logo.  I have to believe this is out-of-policy for AdMob.  But somehow the ad is displayed on the test devices (iPhone 6+ / Samsung Galaxy S5) and is very rarely refreshed by other ads.

Has anyone else seen this ad?  I don't want to update my app and potentially expose my users to a possible virus/malware infection.  It's unlikely, but could this plugin be compromised to show inappropriate ads?  Here is a snapshot from iPhone 6+ with the ad that won't go away for 10+ minutes at a time...
![img_0024](https://user-images.githubusercontent.com/5302648/30301520-393d8e1a-9729-11e7-9583-6dc41bee1efd.jpg)

**Comment by jmelvin** [comment]
Note: It's the unusual display behavior that makes it definitely suspect.  The ad will not go away for extended periods of time.  The other ads in the rotation include "5+ best dating apps" and "make money traveling the world".  I suspect they are all rogue ads.  I'd love to be able to explain this, so I can update my app in the appstores.  I have the latest plugin code and IOS and Android versions installed.

**Comment by jmelvin** [comment]
As an extra insurance policy, in the AdMob portal I selected the following categories to avoid showing in the app...

Sexual and Reproductive Health
References to Sex and Sexuality

However, after an hour the ads continue to show unabated.  Not sure when the change will be effective.  I guess it's possible this fake CNN ad is listed in another more acceptable category to avoid the axe.

**Comment by floatinghotpot** [comment]
Hi @jmelvin The ad content is provided by Google AdMob service, retrieved by plugin with AdMob SDK API. It's out of our control. 

If you are satisfied with the ad content, try contacting Google team directly, or check their online docs:
https://support.google.com/admob/?hl=en#topic=3052991

**Comment by jmelvin** [comment]
Sounds good, @floatinghotpot.  Setting the categories to NOT show has worked.  I no longer see the clearly fraudulent ad.  I'll close this issue and confidently proceed with my app update.  Thanks!
