### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by ChristianGrieger** [floatinghotpot/cordova-admob-pro#598]
Hey,

yesterday all was working well and after updating ionic and cordova to latest version and try to build for android i get this error. How can i fix that? :/ 

✖ Running command - failed!
[ERROR] An error occurred while running cordova build android (exit code 1):

        (truncated) ...              ^
           symbol:   variable adWidth
           location: class AdMobPlugin
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:112:
        error: cannot find symbol
               adSize = new AdSize(adWidth, adHeight);
                                            ^
           symbol:   variable adHeight
           location: class AdMobPlugin
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:146:
        error: method does not override or implement a method from a supertype
           @Override
           ^
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:154:
        error: cannot find symbol
               PublisherAdView ad = new PublisherAdView(getActivity());
                                                        ^
           symbol:   method getActivity()
           location: class AdMobPlugin
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:160:
        error: cannot find symbol
               AdView ad = new AdView(getActivity());
                                      ^
           symbol:   method getActivity()
           location: class AdMobPlugin
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:168:
        error: method does not override or implement a method from a supertype
           @Override
           ^
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:191:
        error: method does not override or implement a method from a supertype
           @Override
           ^
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:194:
        error: cannot find symbol
             return sz.getWidthInPixels(getActivity());
                                        ^
           symbol:   method getActivity()
           location: class AdMobPlugin
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:197:
        error: method does not override or implement a method from a supertype
           @Override
           ^
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:200:
        error: cannot find symbol
             return sz.getHeightInPixels(getActivity());
                                         ^
           symbol:   method getActivity()
           location: class AdMobPlugin
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:203:
        error: method does not override or implement a method from a supertype
           @Override
           ^
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:216:
        error: method does not override or implement a method from a supertype
           @Override
           ^
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:229:
        error: method does not override or implement a method from a supertype
           @Override
           ^
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:244:
        error: method does not override or implement a method from a supertype
           @Override
           ^
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:246:
        error: cannot find symbol
             interstitialReady = false;
             ^
           symbol:   variable interstitialReady
           location: class AdMobPlugin
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:251:
        error: cannot find symbol
               PublisherInterstitialAd ad = new PublisherInterstitialAd(getActivity());
                                                                        ^
           symbol:   method getActivity()
           location: class AdMobPlugin
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:256:
        error: cannot find symbol
               InterstitialAd ad = new InterstitialAd(getActivity());
                                                      ^
           symbol:   method getActivity()
           location: class AdMobPlugin
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:263:
        error: method does not override or implement a method from a supertype
           @Override
           ^
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:276:
        error: method does not override or implement a method from a supertype
           @Override
           ^
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:295:
        error: method does not override or implement a method from a supertype
           @Override
           ^
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:305:
        error: method does not override or implement a method from a supertype
           @Override
           ^
        /Users/christiangrieger/SimpleCoinPriceSidebar/platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:310:
        error: cannot find symbol

**Comment by floatinghotpot** [comment]
It seems the dependency not installed correctly.

Please remove the plugin and add back again.

**Comment by ChristianGrieger** [comment]
I needed to remove whole plugin folder and platform folder and prepare cordova again and it looks to work again. thanks for the fast reply
