### ISSUE TITLE
Admob Video Reward Revenue $0

### ISSUE THREAD

**Issue by ranjhanisaddam** [floatinghotpot/cordova-admob-pro#599]
I have implemented admob video reward few days ago. released my app update and then i tested it myself on another device I was being served with video reward ad and was successfully getting reward.
Problem is its been couple of days now that my admob account is showing $0.00 revenue for my reward video ad unit.
I am sure I have removed isTesting attribute.
Should I add isTesting = false on reward video? because on banner and interstitial removing isTesting works fine and generating revenue.

I am worried It would have been the top performer but showing $0.00 revenue.

**Comment by floatinghotpot** [comment]
Removing the option `isTesting` is same as `isTesting:false`.

How many users updated to your latest version? (You can see the data in Google Play developer console.)

Here are some key data related with revenue:
.................  (ad frequency) ......... (fill rate) ............. (click rate) ...... (ad price)  ........
(daily active users) -> (ad request) -----> (impression) ---> (clicks)  -----> (revenue)

In AdMob portal, you check the following key data for each ad unit id:
* ad request count (user traffic)
* impression (ad correctly displayed)
* clicks (most ad are CPC - cost per click ad)

FYI.

**Comment by ranjhanisaddam** [comment]
Following is the reposone of my video ad

AdMob Network requests | Matched requests | Match rate | Impressions | Clicks | Impressions CTR | Impression RPM | Estimated earnings

220,278 | 897 | 0.41% | 89 | 0 | 0.00% | $0.00 | $0.00

Can you please help, math request is too low

**Comment by ranjhanisaddam** [comment]
Actually
Request = 220,278
Match Rate = 897
Impression = 89
Revenue = $0.00

Can you please help how to improve?

**Comment by floatinghotpot** [comment]
request is not bad, but the impression is very little, which means, in the area of most users, not enough video ad is available for display.

my advice:
1. Either use normal interstitial ad (text, picture, etc) more than reward video ad. The normal intersititial ad fill rate is much higher, which may fully make use of your user traffic.
2. Or, add mediation to other video ad networks, like vungle, or unityads, etc.

**Comment by ranjhanisaddam** [comment]
Thank you so much, I will give a try to mediation otherwise back to pavilion interstitial ads :)

**Comment by sanamsta** [comment]
i have same problem implemented reward ad in my app but even after watching video revenue is 0. Should User have to click the ad or after watching video we will be paid...I have implemented it on non game app..User have to watch video to unlock content like book pages...or video ad only works for game only?

**Comment by floatinghotpot** [comment]
as I know, most ads are CPC (cost per click) type. only the ad is clicked, it's counted.
