### ISSUE TITLE
How to know when no video available

### ISSUE THREAD

**Issue by nomadeon** [floatinghotpot/cordova-admob-pro#600]
I've been able to show video ads when mediating with Unity and I can see image ads with admob interstitial (no mediation). However, I do not see a video when I do either of these:
(1) Admob interstitial with only Video ad type selected, no mediation
(2) Admob reward type, no mediation

I understand that a video unit is not always available, that's fine. But I would like to know that after I call the prepare method so I can react accordingly. Right now, the success callback is firing but when I show the ad nothing appears. The showX() methods are also calling the success callback when there was no ad to see.

This happens with isTesting set both ways.

Is there another event I should look for? If no video ad is available I would like to not give my user the option of seeing an ad for a reward.

**Comment by floatinghotpot** [comment]
The prepareX() callback only indicates the params has no error. Please check the event 'onAdLoaded' or 'onAdLoadFail'. See:
https://github.com/floatinghotpot/cordova-admob-pro/tree/master/docs#events-1

**Comment by nomadeon** [comment]
onAdLoaded/onAdLoadFail are working for my use case, many thanks!
