### ISSUE TITLE
Can not show live ad on android

### ISSUE THREAD

**Issue by kalok1989** [floatinghotpot/cordova-admob-pro#602]
​I find an app cannot show ad banner on apk release version, but it works fine on testing version in Android emulator. When I tried to build an apk, and test it on a real devices, it does not show anything.
details as follow:
cli packages: (/usr/local/lib/node_modules)

@ionic/cli-utils  : 1.12.0

ionic (Ionic CLI) : 3.12.0
global packages:

cordova (Cordova CLI) : 7.1.0 
local packages:

@ionic/app-scripts : 3.0.0

Cordova Platforms  : android 6.3.0

Ionic Framework    : ionic-angular 3.7.1
System:

ios-deploy : 1.9.1 

Node       : v6.9.5

npm        : 4.3.0 

OS         : macOS Sierra

Xcode      : Xcode 9.0 Build version 9A235 
Misc:

backend : pro
$ ionic cordova plugin add cordova-plugin-admobpro
$ npm install --save @ionic-native/admob-pro
already run.

home.ts
```typescript
import { Component } from ‘@angular/core’;
import { NavController } from ‘ionic-angular’;
import { AdMobPro } from ‘@ionic-native/admob-pro’;
@Component({
selector: ‘page-home’,
templateUrl: ‘home.html’
})
export class HomePage {

constructor(public navCtrl: NavController,private admob: AdMobPro) {
this.banner();
}

onClick() {
let adId = ‘ca-app-pub-xxxxx’;

this.admob.prepareInterstitial({adId: adId})
.then(() => { this.admob.showInterstitial(); });
}

banner(){
let adId = ‘ca-app-pub-xxxxxx’;

if(this.admob) this.admob.createBanner({
adId: ‘ca-app-pub-xxxxx’,
position: this.admob.AD_POSITION.BOTTOM_CENTER,
autoShow: true });
```
Please help, many thanks.

**Comment by floatinghotpot** [comment]
If working fine with test ad on emulator, then the plugin and sdk should be no problem.

Please double check your ad unit id. Is it created for the right type and right platform?

All similar issues from other guys are caused by incorrect ad unit id, or invalid status of admob account.

**Comment by kalok1989** [comment]
OK, Problem solved, thank you.

**Comment by floatinghotpot** [comment]
Good to see your problem resolved. Enjoy.
