### ISSUE TITLE
AdMob.showInterstitial() is not working.

### ISSUE THREAD

**Issue by hypesol** [floatinghotpot/cordova-admob-pro#603]
Hello

I am using this plugin everything is working fine but I want ot display somewhere Intersitial on click. I am using "if(AdMob) AdMob.showInterstitial();" this command on click but Intersitial is not displaying. Please guide me how can I use this command?

Thanks.

**Comment by floatinghotpot** [comment]
Yes you can, but before calling showInterstitial(), you have to call prepareInterstitial() to load ad resource from server, and wait for 'onAdLoaded' event, or check whether the ad resource is ready with isInterstitialReady().

For more details, read the wiki:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/1.4-Methods-for-Interstitial

**Comment by floatinghotpot** [comment]
Please see the demo index.html:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/test/index.html

It demonstrates use the 'onAdLoaded' event to wait ad resource ready, then use click or other logic to show the interstitial ad.
