### ISSUE TITLE
iOS 11 support requires SDK 7.24

### ISSUE THREAD

**Issue by unstableair** [floatinghotpot/cordova-admob-pro#604]
Do you have a time frame for update to SDK 7.24 which provides iOS11  support.
Currently I'm having issues with banner placement and view port redraws which may have been fixed in the 7.24 SDK release.

**Comment by floatinghotpot** [comment]
Thanks for reminder. 

The plugin has been upgraded with latest AdMob iOS SDK v7.24.1.
Please update the plugin to:
+ cordova-plugin-admobpro@2.29.24

**Comment by unstableair** [comment]
Thanks, latest SDK now in use.
