### ISSUE TITLE
Found com.google.android.gms:play-services-ads:+, but version 9.0.0 is needed for the google-services plugin

### ISSUE THREAD

**Issue by siphiwe** [floatinghotpot/cordova-admob-pro#606]
Good day,
Please help, I've been sitting with this error message for 2 days now and am at my wit's end. How do I resolve it? I'm running Ionic 2.

`Found com.google.android.gms:play-services-ads:+, but version 9.0.0 is needed for the google-services plugin.
processDebugGoogleServices FAILED
BUILD FAILED
Total time: 1 mins 34.311 secs
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task :processDebugGoogleServices.
Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.
`

Thanks

**Comment by floatinghotpot** [comment]
My plugin use `com.google.android.gms:play-services-ads:+`, means the latest version will be used.

Please list the cordova plugins you are using, and find which plugin requires version 9.0.0, and turn to the author of that plugin.

**Comment by siphiwe** [comment]
Thanks for your response @floatinghotpot. That's what I thought but when I uninstall admob pro, my build works without error. I also did a search through my code base and nothing uses google play services. I'm quite stumped :-/

**Comment by floatinghotpot** [comment]
How do you build the cordova app? Using cordova or ionic CLI, or some online build service?

**Comment by siphiwe** [comment]
Using ionic CLI

**Comment by siphiwe** [comment]
The exact command is `ionic cordova run android --device`

**Comment by floatinghotpot** [comment]
Try opening the android SDK manager, then find and update the google play service and support repository.

**Comment by siphiwe** [comment]
I did a few hours ago and it didn't help

**Comment by siphiwe** [comment]
Hi @floatinghotpot. If you do have any other thoughts please share as I'm still battling.

Thank you

**Comment by floatinghotpot** [comment]
Please show us more details so that we may find out what's wrong.

Type `cordova plugin ls` to list all the plugins.

And, open android SDK manager, screen shot the info about google play service repositories.

**Comment by siphiwe** [comment]
Thanks. Please see below.

```
siphiwe@siphiwe-desktop:~/dev/afroswag$ cordova plugin ls
com-sarriaroman-photoviewer 1.1.10 "PhotoViewer"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```
![screenshot from 2017-10-26 08-59-56](https://user-images.githubusercontent.com/2149932/32039069-ed6eed68-ba2c-11e7-8f62-6a6e15c4e3ec.png)

Thanks again for your assistance.

**Comment by CookieCookson** [comment]
It might be conflicting google libraries with the cordova-plugin-fcm plugin. Try adding this plugin and removing that plugin to see if the build works. It will most likely mean you will need to modify the plugin to use a different version of the google services.

**Comment by floatinghotpot** [comment]
`cordova-plugin-fcm` is based on firebase, it may cause conflict on library.

Try switching `cordova-plugin-admobpro` to `cordova-plugin-admobpro-firebase`, which is compatible on firebase library and `cordova-plugin-fcm`.

**Comment by siphiwe** [comment]
Thanks for your assistance guys :+1: . Switching to cordova-plugin-admobpro-firebase did the trick.

**Comment by floatinghotpot** [comment]
thanks, i will update the docs and readme.
