### ISSUE TITLE
Keywords for interstitial ads

### ISSUE THREAD

**Issue by bahadircolak** [floatinghotpot/cordova-admob-pro#608]
Is it possible to give keywords for interstitial ads? (to show more targeted ads)

**Comment by floatinghotpot** [comment]
yes, see the docs here:
https://github.com/floatinghotpot/cordova-admob-pro/tree/master/docs#targetting-options

**Comment by bahadircolak** [comment]
Thank you for the quick response! 

But does content URL support local urls in cordova? Because gender, child etc. is not my issue. Content is (I want to specify a keyword like "make up"). Or should I create an online url than point to it in my app?

Thank you again!

**Comment by floatinghotpot** [comment]
Try this:
```javascript
AdMob.setOptions({
  customTargeting: {
    interest: ["make up"],
  },
});
```
