### ISSUE TITLE
my app is blocked when add plugin 

### ISSUE THREAD

**Issue by younesyzd** [floatinghotpot/cordova-admob-pro#609]
when i'm add the cordova-admob-pro  in my project and start my game is blocked for loading so i need to restart the game and it's work .. and when i'm remove the plugin and start the game is working good ? so why ?
Thanks

**Comment by floatinghotpot** [comment]
Really? We will look into this issue. What's your platform, android or ios please?

**Comment by floatinghotpot** [comment]
I guess it happened on new iOS. Some network access granting is required by AdMob SDK, but it's missing. It's now fixed in new version of plugin. 

Removing the plugin and adding it back, will fix this blocking.
