### ISSUE TITLE
Build error with admob pro on adobe phonegap build site

### ISSUE THREAD

**Issue by havenht** [floatinghotpot/cordova-admob-pro#614]
I have been using abmob pro with no problem, yesterday when I tried to build it in adobe phonegap build site, it give me a build error. I built my app using that site many times with no problem. its just yesterday when it give me the error. this is what I use in my config.xml
plugin name="cordova-plugin-admobpro" source="npm" 

**UPDATE: i put in the older version of admob pro and it work again.
plugin name="cordova-plugin-admobpro"  spec="2.28.3"
so the problem is the latest version of admob pro 2.29.25**

Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-plugin-admobpro" via npm Error during untar for /home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.25/package.tgz: Error: EACCES: permission denied, open '/home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.25/package/src/ios/GoogleMobileAds.framework/Headers/DFPBannerView.h' Failed to fetch plugin cordova-plugin-admobpro via registry. Probably this is either a connection problem, or plugin spec is incorrect. Check your connection and plugin name/version/URL. Error: EACCES: permission denied, open '/home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.25/package/src/ios/GoogleMobileAds.framework/Headers/DFPBannerView.h'

**Comment by jamminjames** [comment]
Same here.

**Comment by havenht** [comment]
cool!

**Comment by niivanpee** [comment]
i hope this gets fixed soon but thanks for the suggestion and it worked!

**Comment by floatinghotpot** [comment]
Weird, as it's tested okay with cordova CLI. 

It seems the error is caused by a corrupted file, see: `Error during untar for /home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.25/package.tgz`

You can download the tgz file here: 
https://registry.npmjs.org/cordova-plugin-admobpro/-/cordova-plugin-admobpro-2.29.25.tgz

Just download and untar this file, will find the correct file:
`src/ios/GoogleMobileAds.framework/Headers/DFPBannerView.h`

I just wonder, is it caused by network issue of phonegap build server, or a corrupted file?

**Comment by sebinator** [comment]
same here...

Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-plugin-admobpro@~2.29.25" via npm Error during untar for /home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.25/package.tgz: Error: EACCES: permission denied, open '/home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.25/package/src/ios/GoogleMobileAds.framework/Headers/DFPBannerView.h' Failed to fetch plugin cordova-plugin-admobpro@~2.29.25 via registry. Probably this is either a connection problem, or plugin spec is incorrect. Check your connection and plugin name/version/URL. Error: EACCES: permission denied, open '/home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.25/package/src/ios/GoogleMobileAds.framework/Headers/DFPBannerView.h'

**Comment by sebinator** [comment]
i confirm, 2.28.3 works good, so it is indeed the new version

**Comment by floatinghotpot** [comment]
Here are the screenshots, using the `cordova-plugin-admobpro@2.29.25`.

![2017-11-04 12 08 06](https://user-images.githubusercontent.com/2339512/32383927-5c9ae3a8-c087-11e7-85de-f1c641c2cb2a.png)
![2017-11-04 12 08 19](https://user-images.githubusercontent.com/2339512/32383935-6198647a-c087-11e7-8233-6f3116ae3874.png)

**Comment by floatinghotpot** [comment]
Attempt to republish as `cordova-plugin-admobpro@2.29.26`, to see if the error keep consistent.

**Comment by jamminjames** [comment]
I tried 2.29.26, still brings up error:

> Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-plugin-admobpro@2.29.26" via npm Error during untar for /home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.26/package.tgz: Error: EACCES: permission denied, mkdir '/home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.26/package/src/ios/GoogleMobileAds.framework/Headers' Failed to fetch plugin cordova-plugin-admobpro@2.29.26 via registry. Probably this is either a connection problem, or plugin spec is incorrect. Check your connection and plugin name/version/URL. Error: EACCES: permission denied, mkdir '/home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.26/package/src/ios/GoogleMobileAds.framework/Headers'

**Comment by floatinghotpot** [comment]
It's a different error message.

* First one:
Error during untar for /home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.25/package.tgz: 
Error: EACCES: permission denied, open '/home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.25/package/src/ios/GoogleMobileAds.framework/Headers/DFPBannerView.h'

* Second one:
Error during untar for /home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.26/package.tgz: 
Error: EACCES: permission denied, mkdir '/home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.26/package/src/ios/GoogleMobileAds.framework/Headers'

Same:
EACCES: permission denied, when create file or create directory. 

Is the disk full?

**Comment by jamminjames** [comment]
No, no problem with the disk being full. Besides, if it was, the earlier versions wouldn't work either, correct?

**Comment by floatinghotpot** [comment]
As the plugin has been tested pass with cordova CLI. 

There is no problem if you use cordova CLI locally. This error happens to PhoneGap Build service, so I just attempt to identify what the root cause is. 

The earlier versions have been cached already, it won't be re-downloaded from npm repository, so won't cause `EACCES: permission denied` error.

But to new version, the cordova CLI will download and untar to disk, this will write the disk. See the 2 errors are similar but still some different:
* first time: Error: EACCES: permission denied, open '/home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.25/package/src/ios/GoogleMobileAds.framework/Headers/DFPBannerView.h'
* second time: Error: EACCES: permission denied, mkdir '/home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.26/package/src/ios/GoogleMobileAds.framework/Headers'

The error `EACCES: permission denied` indicates something is wrong when writing to disk. 

May I ask, how do you confirm "no problem with the disk being full"?

**Comment by jamminjames** [comment]
Well, all the build happens on the Phonegap Build server, that's where the error happens, not on the device. I doubt their server has that disk problem. I tried it again, and this time the error reads:

> Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-plugin-admobpro" via npm Error during untar for /home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.26/package.tgz: Error: EACCES: permission denied, open '/home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.26/package/src/ios/GoogleMobileAds.framework/GoogleMobileAds' Failed to fetch plugin cordova-plugin-admobpro via registry. Probably this is either a connection problem, or plugin spec is incorrect. Check your connection and plugin name/version/URL. Error: EACCES: permission denied, open '/home/ec2-user/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.26/package/src/ios/GoogleMobileAds.framework/GoogleMobileAds'
Different again, but I don't know what to make of it.

**Comment by floatinghotpot** [comment]
Can you contact phonegap build service support team to check if something wrong?

**Comment by jamminjames** [comment]
Okay, I posted in their support forum, with a link to this thread.

**Comment by floatinghotpot** [comment]
Another developer using cocoon.io also report the same issue, so it's not the phonegap build only problem. 

I guess might be something wrong with npm. So I dig in.

* Compare v2.29.23 with v2.29.24:
```diff
$ diff 2.29.23/package.json 2.29.24/package.json
3c3
<   "version": "2.29.23",
---
>   "version": "2.29.24",
72c72
<   "gitHead": "32ffbe20238667a1cae2b40e80bc4c685270bfc6",
---
>   "gitHead": "3c7b3f51fbcc95bbbae0363c4bc78628250e2e3e",
74c74
<   "_id": "cordova-plugin-admobpro@2.29.23",
---
>   "_id": "cordova-plugin-admobpro@2.29.24",
76,77c76,77
<   "_shasum": "6e9b0744dce569853e820cbfa26468160128f8f7",
<   "_from": "cordova-plugin-admobpro@2.29.23"
---
>   "_shasum": "f4b46adac9756aa5de9add10d952817005b6210e",
>   "_from": "cordova-plugin-admobpro@2.29.24"
```

* Compare v2.29.24 with v2.29.26:
```diff
$ diff 2.29.24/package.json 2.29.26/package.json
3c3
<   "version": "2.29.24",
---
>   "version": "2.29.26",
71,72c71
<   "readmeFilename": "README.md",
<   "gitHead": "3c7b3f51fbcc95bbbae0363c4bc78628250e2e3e",
---
>   "gitHead": "7a6c439e60023c26515a836d3ebbc96de822d31e",
74,77c73,99
<   "_id": "cordova-plugin-admobpro@2.29.24",
<   "scripts": {},
<   "_shasum": "f4b46adac9756aa5de9add10d952817005b6210e",
<   "_from": "cordova-plugin-admobpro@2.29.24"
---
>   "_id": "cordova-plugin-admobpro@2.29.26",
>   "_npmVersion": "5.5.1",
>   "_nodeVersion": "6.11.4",
>   "_npmUser": {
>     "name": "floatinghotpot",
>     "email": "rjfun.mobile@gmail.com"
>   },
>   "maintainers": [
>     {
>       "name": "floatinghotpot",
>       "email": "rjfun.mobile@gmail.com"
>     }
>   ],
>   "dist": {
>     "integrity": "sha512-tmNCr/PXMEvsKo5wIlkDaaL9SwRvrkDVjt7cUzxJurwN85HeCvAeUGLghVfJ76HPTOtBinpMmf/zhIpnVlIIMg==",
>     "shasum": "b5482f0a8dbd2e0f987ea7b72caed6fc6b7be2ae",
>     "tarball": "https://registry.npmjs.org/cordova-plugin-admobpro/-/cordova-plugin-admobpro-2.29.26.tgz"
>   },
>   "_npmOperationalInternal": {
>     "host": "s3://npm-registry-packages",
>     "tmp": "tmp/cordova-plugin-admobpro-2.29.26.tgz_1509726520643_0.5399553501047194"
>   },
>   "directories": {},
>   "_shasum": "b5482f0a8dbd2e0f987ea7b72caed6fc6b7be2ae",
>   "_resolved": "https://registry.npmjs.org/cordova-plugin-admobpro/-/cordova-plugin-admobpro-2.29.26.tgz",
>   "_from": "cordova-plugin-admobpro@2.29.26",
>   "readme": "ERROR: No README data found!"
```

Though the original package.json I published is almost same except version info, npm has automatically added lots of items to it. 

I am not sure whether the new changes is causing the problem. If the build service is using some old version of npm CLI and cannot recognize the spec.

**Comment by jamminjames** [comment]
I just recompiled again on PB, and it did not have the error. Thanks!

**Comment by jamminjames** [comment]
By the way, I had just recently made my app live on Google Play with version 2.29.24. Is there a compelling reason I should change it to include the new version, or do you think it's okay for now? The [app is here](https://play.google.com/store/apps/details?id=com.humortimes.newscartoons&hl=en), btw, if you're interested.

**Comment by floatinghotpot** [comment]
Okay for now, if release app for Android only.

If you release app for iOS, using v2.29.25 or higher is required for iOS 11 compatibility.

**Comment by jamminjames** [comment]
Okay, thanks!
