### ISSUE TITLE
Coocon.io plugin build error

### ISSUE THREAD

**Issue by gametrick** [floatinghotpot/cordova-admob-pro#616]
I have trouble in last build from Cocoon.io. It was working fine last week. This is the error log. 

COMPILER ERROR: 

Failed to fetch plugin cordova-plugin-admobpro@* via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: EACCES: permission denied, open '/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.26/package/src/ios/GoogleMobileAds.framework/GoogleMobileAds'

CORDOVA LOG: 

[36m[2017-11-05 03:46:37.604] [DEBUG] AndroidBuilder - [39m[prepare] cordova restore platforms
[36m[2017-11-05 03:46:37.618] [DEBUG] AndroidBuilder - [39m[prepare] adding engine android@6.2.3
Subproject Path: CordovaLib
Subproject Path: CordovaLib
Subproject Path: CordovaLib
Subproject Path: CordovaLib
Subproject Path: CordovaLib
[36m[2017-11-05 03:46:50.471] [DEBUG] AndroidBuilder - [39m[prepare] cordova restore plugins
[36m[2017-11-05 03:46:50.473] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin cocoon-plugin-inapps-android-googleplay@*
[36m[2017-11-05 03:46:50.505] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin cocoon-plugin-share@*
[36m[2017-11-05 03:46:50.550] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.cmackay.plugins.googleanalytics@*
[36m[2017-11-05 03:46:50.584] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.ludei.defaultres.android@1.0.1
[36m[2017-11-05 03:46:50.636] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.ludei.usericon.android@1.0.1
[36m[2017-11-05 03:46:50.672] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.ludei.usersplash.android@1.0.2
[36m[2017-11-05 03:46:50.703] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.ludei.webviewplus.android@2.2.1
[36m[2017-11-05 03:46:50.751] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.ludei.webviewplus.ios@1.1.0
[36m[2017-11-05 03:46:50.783] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin cordova-plugin-admobpro@*
[36m[2017-11-05 03:46:50.863] [DEBUG] AndroidBuilder - [39mFailed to fetch plugin cordova-plugin-admobpro@* via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: EACCES: permission denied, open '/.cordova/lib/npm_cache/cordova-plugin-admobpro/2.29.26/package/src/ios/GoogleMobileAds.framework/GoogleMobileAds

**Comment by floatinghotpot** [comment]
Though new version of plugin has been tested with cordova CLI, it seems some compatibility issue with build service.

Please use `cordova-plugin-admobpro@2.29.24` to avoid the issue.

We will find and fix the new version.

**Comment by floatinghotpot** [comment]
Same issue as #614 , let's follow up there.
