### ISSUE TITLE
Live Ads not Showing  Up 

### ISSUE THREAD

**Issue by X0t0** [floatinghotpot/cordova-admob-pro#617]
Hey first i tried the test ads and it's showing up , after that i tried the live ads but not showing at all i waited for 15 min but nothing showing up.
MY Code : 

![screenshot 2](https://user-images.githubusercontent.com/19890345/32420135-fd579a98-c285-11e7-9105-419696a37cba.png)

**Comment by floatinghotpot** [comment]
You are using the wrong plugin. 

To use AdMobPro, see the demo here:
https://github.com/jaivehall/admob-ionic2-demo/blob/master/demo/providers/admobpro.ts

**Comment by X0t0** [comment]
now i'm using this plugin , but still nothing showing up
![screenshot 5](https://user-images.githubusercontent.com/19890345/32439555-a426427a-c2ef-11e7-816c-03243795872b.png)

**Comment by X0t0** [comment]
the test ads work but the live doesn't work at all nothing showing up , i tried the ids in other app but they work fine

**Comment by floatinghotpot** [comment]
Did you test the app on emulator or device?

**Comment by X0t0** [comment]
Real Device

**Comment by X0t0** [comment]
i tried test ads and it's work fine , and for live ads not showing , i removed isTesting

**Comment by floatinghotpot** [comment]
if test ads work fine, the code and plugin is correct. please double check the admob account and ad unit id. 

please make sure: 
* your account is in valid status, (some guy did not validate the pin in time, and google stop pushing ad resource);
* the ad unit id are created for the correct platform (android in your case), (some guy use ad unit id created for ios in android platform)
* the ad unit id are create for the right type (banner / interstitial). (some guy misuse banner ad unit id for interstitial)

**Comment by floatinghotpot** [comment]
BTW, using logcat to see the android device log, is a good practice to troubleshoot what's wrong inside.

Import the android project into Android Studio, connect USB cable to your device, then start the project.

**Comment by X0t0** [comment]
My accounts is work Fine , other apps is working fine 
for ad units i created them a day a go mean they're active by now .
and for ids they're correct and checked them more than 5 times . 
now i will check my Package NAme sometimes admob block some packages

**Comment by X0t0** [comment]
i'm using this commend 
`ionic cordova run adnroid -l -c `
and no error showing app

**Comment by floatinghotpot** [comment]
yes, your might be right. as I know some guy using package id like *.hello or *.test, failed to see the live ad, after change to some others, it becomes okay. worth a try.

**Comment by X0t0** [comment]
i change the package name but still not working , now i'm trying to use one of my old unit ads that world very well in other apps and it's showing in other app

**Comment by X0t0** [comment]
still not working bro

**Comment by floatinghotpot** [comment]
okay, i will try your ad unit in demo for a testing.

**Comment by X0t0** [comment]
okay , thanks i hope if you can do that now , because i need to publish this app today

**Comment by X0t0** [comment]
i tried those ad unit in other app unity and it's work fine

**Comment by floatinghotpot** [comment]
your ad unit id please?

banner id:
interstitial id:

**Comment by X0t0** [comment]
banner id: ca-app-pub-5788116230257500/5538723877
interstitial id: ca-app-pub-5788116230257500/7578084927

**Comment by floatinghotpot** [comment]
I use it in the demo app, and can see the live ad.

**Comment by X0t0** [comment]
Oh , where’s the problem in my app did i need to build a new one , please send me your code

**Comment by floatinghotpot** [comment]
[index.html.zip](https://github.com/floatinghotpot/cordova-admob-pro/files/1446228/index.html.zip)

**Comment by floatinghotpot** [comment]
This is the default demo file in plugin/www folder, just replace the ad unit id to your own, and comment out `isTesting:true`.

**Comment by X0t0** [comment]
Okay thanks i will try it , because i’m usin Ionic 3

**Comment by X0t0** [comment]
Isn’t a version problem of your plugin

**Comment by floatinghotpot** [comment]
Maybe your variable is not in the right scope.

Try not assign the ad unit id to a variable, use it directly in the API.

**Comment by X0t0** [comment]
I will try it what you sent me and contact you back

**Comment by X0t0** [comment]
hey man how i can add this code to home.ts
