### ISSUE TITLE
iOS build failing (2.29.25)

### ISSUE THREAD

**Issue by fobaz** [floatinghotpot/cordova-admob-pro#621]
Hi, trying to build the app on OS X fails with this error:
> Undefined symbols for architecture x86_64:
>   "_OBJC_CLASS_$_GADRewardBasedVideoAd", referenced from:
>       objc-class-ref in CDVAdMobPlugin.o
>   "_OBJC_CLASS_$_DFPInterstitial", referenced from:
>       objc-class-ref in CDVAdMobPlugin.o
>   "_OBJC_CLASS_$_GADBannerView", referenced from:
>       objc-class-ref in CDVAdMobPlugin.o
>   "_OBJC_CLASS_$_GADInterstitial", referenced from:
>       objc-class-ref in CDVAdMobPlugin.o
>   "_OBJC_CLASS_$_DFPRequest", referenced from:
>       objc-class-ref in CDVAdMobPlugin.o
>   "_OBJC_CLASS_$_DFPBannerView", referenced from:
>       objc-class-ref in CDVAdMobPlugin.o
>   "_OBJC_CLASS_$_GADExtras", referenced from:
>       objc-class-ref in CDVAdMobPlugin.o
>   "_kGADAdSizeBanner", referenced from:
>       -[CDVAdMobPlugin __AdSizeFromString:] in CDVAdMobPlugin.o
>   "_OBJC_CLASS_$_GADRequest", referenced from:
>       objc-class-ref in CDVAdMobPlugin.o
>   "_kGADAdSizeFullBanner", referenced from:
>       -[CDVAdMobPlugin __AdSizeFromString:] in CDVAdMobPlugin.o
>   "_kGADAdSizeSmartBannerPortrait", referenced from:
>       -[CDVAdMobPlugin __createAdView:] in CDVAdMobPlugin.o
>       -[CDVAdMobPlugin __AdSizeFromString:] in CDVAdMobPlugin.o
>       -[CDVAdMobPlugin __showBanner:atX:atY:] in CDVAdMobPlugin.o
>   "_kGADSimulatorID", referenced from:
>       -[CDVAdMobPlugin __buildAdRequest:forDFP:] in CDVAdMobPlugin.o
>   "_kGADAdSizeLargeBanner", referenced from:
>       -[CDVAdMobPlugin __AdSizeFromString:] in CDVAdMobPlugin.o
>   "_GADAdSizeEqualToSize", referenced from:
>       -[CDVAdMobPlugin __createAdView:] in CDVAdMobPlugin.o
>       -[CDVAdMobPlugin __showBanner:atX:atY:] in CDVAdMobPlugin.o
>   "_kGADAdSizeSkyscraper", referenced from:
>       -[CDVAdMobPlugin __AdSizeFromString:] in CDVAdMobPlugin.o
>   "_kGADAdSizeInvalid", referenced from:
>       -[CDVAdMobPlugin __createAdView:] in CDVAdMobPlugin.o
>       -[CDVAdMobPlugin __AdSizeFromString:] in CDVAdMobPlugin.o
>   "_kGADAdSizeLeaderboard", referenced from:
>       -[CDVAdMobPlugin __AdSizeFromString:] in CDVAdMobPlugin.o
>   "_GADAdSizeFromCGSize", referenced from:
>       -[CDVAdMobPlugin __createAdView:] in CDVAdMobPlugin.o
>   "_kGADAdSizeSmartBannerLandscape", referenced from:
>       -[CDVAdMobPlugin __createAdView:] in CDVAdMobPlugin.o
>       -[CDVAdMobPlugin __AdSizeFromString:] in CDVAdMobPlugin.o
>       -[CDVAdMobPlugin __showBanner:atX:atY:] in CDVAdMobPlugin.o
>   "_kGADAdSizeMediumRectangle", referenced from:
>       -[CDVAdMobPlugin __AdSizeFromString:] in CDVAdMobPlugin.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> ** BUILD FAILED **

Android build works. Dependencies:
 ```
 "dependencies": {
    "@angular/common": "^5.0.1",
    "@angular/compiler": "^5.0.1",
    "@angular/compiler-cli": "^5.0.1",
    "@angular/core": "^5.0.1",
    "@angular/forms": "^5.0.1",
    "@angular/http": "^5.0.1",
    "@angular/platform-browser": "^5.0.1",
    "@angular/platform-browser-dynamic": "^5.0.1",
    "@ionic-native/admob-pro": "^4.3.3",
    "@ionic-native/app-rate": "^4.3.3",
    "@ionic-native/base64": "^4.3.3",
    "@ionic-native/camera": "^4.3.3",
    "@ionic-native/core": "^4.3.3",
    "@ionic-native/deeplinks": "^4.3.3",
    "@ionic-native/facebook": "^4.3.3",
    "@ionic-native/file": "^4.3.3",
    "@ionic-native/file-path": "^4.3.3",
    "@ionic-native/firebase": "^4.3.3",
    "@ionic-native/in-app-browser": "^4.3.3",
    "@ionic-native/in-app-purchase": "^4.3.3",
    "@ionic-native/social-sharing": "^4.3.3",
    "@ionic-native/splash-screen": "^4.3.3",
    "@ionic-native/status-bar": "^4.3.3",
    "@ionic/storage": "2.1.3",
    "com-badrit-base64": "^0.2.0",
    "cordova-android": "^6.2.3",
    "cordova-plugin-admobpro-firebase": "^2.29.25",
    "cordova-plugin-apprate": "^1.3.0",
    "cordova-plugin-camera": "^2.4.1",
    "cordova-plugin-compat": "~1.1.0",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-dialogs": "^1.3.3",
    "cordova-plugin-extension": "^1.5.2",
    "cordova-plugin-facebook4": "^1.9.1",
    "cordova-plugin-file": "^4.3.3",
    "cordova-plugin-file-transfer": "~1.6.3",
    "cordova-plugin-filepath": "^1.1.0",
    "cordova-plugin-firebase": "^0.1.24",
    "cordova-plugin-globalization": "^1.0.7",
    "cordova-plugin-inappbrowser": "^1.7.1",
    "cordova-plugin-inapppurchase": "^1.1.0",
    "cordova-plugin-ios-in-app-ratings-and-reviews": "0.0.4",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.2",
    "cordova-plugin-whitelist": "^1.3.1",
    "cordova-plugin-x-socialsharing": "^5.2.1",
    "es6-promise-plugin": "^4.1.1",
    "ionic-angular": "^3.9.2",
    "ionic-plugin-deeplinks": "^1.0.15",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionic2-rating": "^1.2.2",
    "ionicons": "3.0.0",
    "rxjs": "^5.5.2",
    "sw-toolbox": "3.6.0",
    "web": "0.0.2",
    "zone.js": "0.8.18",
    "cordova-ios": "~4.5.3"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.1.0",
    "typescript": "^2.4.1"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-file": {},
      "cordova-plugin-filepath": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-x-socialsharing": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-ios-in-app-ratings-and-reviews": {},
      "cordova-plugin-apprate": {},
      "cordova-plugin-inapppurchase": {},
      "cordova-plugin-facebook4": {... },
      "cordova-plugin-firebase": {},
      "cordova-plugin-camera": {.. },
      "ionic-plugin-deeplinks": {  ...},
      "cordova-plugin-admobpro-firebase": {},
      "cordova-plugin-compat": {},
      "com-badrit-base64": {}
    },
    "platforms": [
      "android",
      "ios"
    ]
```

Any ideas?

**Comment by floatinghotpot** [comment]
`cordova-plugin-admobpro-firebase` is dependent on `cordova-plugin-extension`, but it's missing in your plugin list. 

Re-installing the plugin will fix it, usually. Or, install them manually.
