### ISSUE TITLE
Android designed for families

### ISSUE THREAD

**Issue by davedidisco** [floatinghotpot/cordova-admob-pro#622]
Hi,

Was wondering if you are looking at adding an option to set android 'designed for families' to true?

many thanks

**Comment by floatinghotpot** [comment]
```javascript
AdMob.setOptions({
  forFamily:'yes'
});
```

Please read the docs:
https://github.com/floatinghotpot/cordova-admob-pro/tree/master/docs#targetting-options

BTW, I just identified a related bug in plugin code, will fix it now.
