### ISSUE TITLE
Use Google-Mobile-Ads-SDK pod for iOS

### ISSUE THREAD

**Issue by ruudruud** [floatinghotpot/cordova-admob-pro#625]
The Google Mobile Ads SDK for iOS can be installed with only one line of code, just like this plugin is doing for Android with gradle. Simply add the Google-Mobile-Ads-SDK pod (that is maintained by Google) to plugin.xml.

```
<platform name="ios">
        <framework src="Google-Mobile-Ads-SDK" type="podspec" spec="" />
</platform>
```

**Comment by floatinghotpot** [comment]
Yes, you are correct.

But,
1. The cocoapods repository is not always up to date.
2. This will require everyone install cocoapods and download the cocoapods index files which is more than 500MB.

**Comment by ruudruud** [comment]
Thanks for your quick reply. Those are good points! I did not think about what would happen for users that have not installed cocoapods yet. It is quite large indeed.

I have a second AdMob cordova plugin that installs mediation networks. This plugin also downloads the latest AdMob SDK with this pod. It would reduce the size of our apps because the SDK is getting installed twice now. That's the reason that I would prefer this plugin to install the AdMob SDK pod as well.

Nevertheless, I am glad that you already investigated this approach. I'm not sure if it is wise for all users of this plugin to transition to using pods. Thanks.

**Comment by floatinghotpot** [comment]
Thanks for accepting my answer. Enjoy monetization with AdMob.
