### ISSUE TITLE
prepareInterstitial with autoShow:false still shows the ad

### ISSUE THREAD

**Issue by billqian99** [floatinghotpot/cordova-admob-pro#626]
Hi,

When calling prepareInterstitial with {adId: xxxxx, autoShow:false}, the ad still show up due to the function call.  

However subsequent calling of showInterstitial() doesn't bring up the ad.  

Observed this with actual AD Unit ID on actual Android device.

Please help.

Thanks,

Bill

**Comment by floatinghotpot** [comment]
Should not be. Will look into this issue to confirm.

**Comment by floatinghotpot** [comment]
We re-tested, your are not correct. Using `autoShow: false` won't pop up the interstitial ad automatically.

Please use this index.html for testing:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/test/index.html

**Comment by billqian99** [comment]
I agree with you after more testing on my side and it works as expected now.  Thanks for confirming.

A couple of more questions,

1. Is it recommended to call prepareInterstitial once at beginning and repeatedly call showInterstitial afterwards?

2. If my AD unit has a cap on the interstitial, does showInterstitial respect the cap?  What's the best way to test the cap?

Thank you!

Bill

**Comment by floatinghotpot** [comment]
@billqian99 the interstitial ad is one-time ad, which means, before every show, you have to call prepare.

So, a good practice is, 
* call the first prepare() when app starts, 
* then in handler of event 'onAdFailLoad' and 'onAdDismiss', check if it's a interstitial, then call prepare() again, for next ad.
* this will always keep one ad in buffer ready for show.

**Comment by billqian99** [comment]
@floatinghotpot, 

Thank you very much for the guide.  

Bill

**Comment by floatinghotpot** [comment]
You can use isInterstitialReady() to check whether the ad resource is ready.

What I suggested, " in handler of event 'onAdFailLoad' and 'onAdDismiss', check if it's a interstitial, then call prepare() again, for next ad.", is to keep it as a loop: 
prepare -> show -> dismiss -> prepare -> show -> ...

**Comment by billqian99** [comment]
got it.  Thanks!
