### ISSUE TITLE
How can you get if someone clicked on an AD?

### ISSUE THREAD

**Issue by Ziv-Barber** [floatinghotpot/cordova-admob-pro#635]
How can you get if someone clicked on an AD?
Is there an event for that? or an option to put invisible layer on the top of the AD to detect a click?

**Comment by floatinghotpot** [comment]
event 'onAdLeaveApp'
Triggered when user click the Ad, and will jump out of your App.

See:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/1.5-Events

**Comment by Ziv-Barber** [comment]
Thanks! I forgot about this event :)
