### ISSUE TITLE
more than banner ads in the same view 

### ISSUE THREAD

**Issue by Abdeza** [floatinghotpot/cordova-admob-pro#637]
Hi there i hope u're doing good , thanks for this plugin , 
i have the overlap banner ads in bottom of my app , i want to show other banner ads as meduim rectangle inside details.html view and keep that bottom ads . is it possible ? because i tried many times and it didn't work

**Comment by BigFoppa** [comment]
Have you read #461

**Comment by Abdeza** [comment]
Yes mr @BigFoppa  , i know that native ads dosen't work , im talking about banner ads , i want to show 2 banner ads on same view . is it possible sir ?

**Comment by floatinghotpot** [comment]
No, it's not allowed by Google to show two or more banners on same screen.

**Comment by Abdeza** [comment]
@floatinghotpot  thanks bro .
