### ISSUE TITLE
Admob pro not working after app release

### ISSUE THREAD

**Issue by alamgira** [floatinghotpot/cordova-admob-pro#64]
Hi,
Admob stopped working right after release on android (App name: Hungry Haven) . Ios is still functional on test flight but unfortunately android stopped.
I am using dfp and also success and error function for create banner is not logging anything.

NOTE: This is in ionic framework
     if (navigator.userAgent !== undefined){
                        var admobid = ( /(android)/i.test(navigator.userAgent) ) ? adMobHelper.getAndroid() : adMobHelper.getIos();
                    }else{
                        var admobid = adMobHelper.getAndroid();
                    }
                    console.log(admobid.banner);
                    AdMob = window.AdMob;

                    AdMob.createBanner({
                            adId: admobid.banner,
                            adSize:AdMob.SMART_BANNER,
                            position:AdMob.AD_POSITION.BOTTOM_CENTER,
                            overlap: true,
                            autoShow:true,
                            success:function(){console.log("Success Ad");},
                            error:function(error){console.log("Error ad: "+error);}

                        }
                    );

Please help

**Comment by hamletdeljesus** [comment]
Im using Intel XDK, It does work in testing mode but not admob ads, however, when I build the app and then run it on my phone the admob ads work fine, but then when I use the  app crashes. If I don't have wifi, the app works nice, it's when on wifi the admobs starts and then charshes the app when you hit a button on the app o select the menu.

**Comment by floatinghotpot** [comment]
I cannot reproduce your issue... Do you use any other plugin? Any log or evidence to tell it's caused by admob plugin or clue for troubleshooting?
