### ISSUE TITLE
Phonegap build works on android not on iphone

### ISSUE THREAD

**Issue by baubeis** [floatinghotpot/cordova-admob-pro#65]
Using this plugin on an app build.  Seems to work fine on android but nothing happens on iphone.  Not sure if I maybe have to upload it to the store and download versus taking build off of phonegap to get it to work?

Here is my code:
```html
<script>
var admobid = {};
if( /(android)/i.test(navigator.userAgent) ) { 
    admobid = { // for Android
        banner: 'ca-app-pub-4032873873455264/2426559631',
        interstitial: 'a-app-pub-4032873873455264/2756133633'
    };
} else if(/(iphone)/i.test(navigator.userAgent)) {
    admobid = { // for iOS
        banner: 'ca-app-pub-4032873873455264/2426559631',
        interstitial: 'a-app-pub-4032873873455264/2756133633'
    };
}

function initApp() {
    if (AdMob) {
        AdMob.createBanner({
            adId : admobid.banner,
            position : AdMob.AD_POSITION.BOTTOM_CENTER,
            autoShow : true
        });
    }
}
document.addEventListener('deviceready', initApp, false);
</script>
```

----------------------------------------------------------------------------------------------------------------
at least thats the admob section of the code.  Here is my entire page code:
----------------------------------------------------------------------------------------------------------------
```html
<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta charset="UTF-8">
<title>Shop Military Discounts</title>
<link rel="stylesheet" type="text/css" href="bootstrap/3/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="Styles/dmxGoogleMaps.css" />
<link rel="stylesheet" type="text/css" href="Styles/dmxNotify.css" />
<link rel="stylesheet" type="text/css" href="fontawesome/css/font-awesome.min.css" />
<style type="text/css">
#mapWrapper {
	height: 100%;
	width: 100%;
	padding-top: 59px;
	position: absolute;
}
</style>
<script type="text/javascript" src="ScriptLibrary/jquery-latest.pack.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="bootstrap/3/js/bootstrap.min.js"></script>
<script type="text/javascript" src="ScriptLibrary/dmxBootstrap3Navigation.js"></script>
<script type="text/javascript" src="ScriptLibrary/dmxGoogleMaps.js"></script>
<script type="text/javascript" src="ScriptLibrary/dmxDataBindings.js"></script>
<script type="text/javascript" src="ScriptLibrary/dmxDataSet.js"></script>
<script type="text/javascript" src="ScriptLibrary/dmxDataBrowser.js"></script>
<script type="text/javascript" src="ScriptLibrary/dmxNotify.js"></script>
<script type="text/javascript" src="ScriptLibrary/dmxGeoLocation.js"></script>
<script type="text/javascript" src="cordova.js"></script>
<script type="text/javascript">
  /* dmxDataSet name "MobileAppData" */
       jQuery.dmxDataSet(
         {"id": "MobileAppData", "url": "http://admin.shopmilitarydiscounts.com/dmxDatabaseSources/MapDiscounts.asp", "data": {"discount_category": "{{$URL.discount_category}}", "limit": "2000"}, "siteName": "Shop Military Discounts - Admin", "dataSourceType": "database", "dataType": "jsonp"}
       );
  /* END dmxDataSet name "MobileAppData" */
   /* dmxDataSet name "mapDiscountsALL" */
       jQuery.dmxDataSet(
         {"id": "mapDiscountsALL", "url": "http://admin.shopmilitarydiscounts.com/dmxDatabaseSources/divMapTEST.asp", "data": {"limit": "2000"}, "siteName": "Shop Military Discounts - Admin", "dataSourceType": "database", "dataType": "jsonp"}
       );
  /* END dmxDataSet name "mapDiscountsALL" */
  /* dmxGeoLocation name "dmxGeoLocation" */
       jQuery.dmxGeoLocation(
         {"enableHighAccuracy": true, "timeout": 6000, "onTimeout": "dmxGoogleMapsAction('map1','setCenter',{\"address\": \"Fort Leonard Wood, MO 65473\"});", "onUnavailable": "dmxNotifyAction({\"type\": \"error\", \"positionClass\": \"toast-bottom-full-width\", \"title\": \"Geolocation is Unavailable\", \"msg\": \" ##message##\", \"extendedTimeOut\": 2000, \"tapToDismiss\": false});"}
       );
  /* END dmxGeoLocation name "dmxGeoLocation" */

function dmxGoogleMapsAction(playerName, actionName, extraInfo) { // v2.0
  var theMap = jQuery('#'+playerName);
  if (theMap && theMap.gMap) {
   	var gm = theMap.data("gmap");
    switch (actionName) {
      case 'addMarker' :
        theMap.gMap('addMarker', extraInfo);
		    break;
      case 'gotoMarker' :
      case 'panToMarker' :
        if (extraInfo && extraInfo.key) {
	    	  var theMarker = theMap.gMap('getMarker', extraInfo.key);
	    	  if (theMarker) {
	          var center = theMarker.getPosition();
	          if (actionName == 'panToMarker') gm.gmap.panTo(center)
	          else gm.gmap.setCenter(center);
	        }
	      }
		    break;
			case 'showInfoWindow' :
			  if (extraInfo && extraInfo.key) {
				  var theMarker = theMap.gMap('getMarker', extraInfo.key);
				  if (theMarker) {
				    google.maps.event.trigger(theMarker, 'click');
				  }
			  }
			  break;
		  case 'resizeMapSmooth' :
		    theMap.gMap('fixAfterResize');
			  break;
		  case 'resizeMapDirectly' :
		    theMap.gMap('fixAfterResize', true);
		    break;
		  case 'setCenter':
		  case 'panTo':
			  var $googlemaps = google.maps, $geocoder = new $googlemaps.Geocoder();
        if (extraInfo.latitude && extraInfo.longitude) {
          // lat & lng available, return
          var center = new $googlemaps.LatLng(extraInfo.latitude, extraInfo.longitude);
          if (actionName == 'panTo') gm.gmap.panTo(center)
          else gm.gmap.setCenter(center);
          return;
        } else {
	        // Check for address to center on
	        if (extraInfo.address) {
	          // Get coordinates for given address and center the map
	          $geocoder.geocode(
		          {address: extraInfo.address},
		          function(result, status) {
	              if (status === google.maps.GeocoderStatus.OK) {
	              	if (actionName == 'panTo') gm.gmap.panTo(result[0].geometry.location);
	              	else gm.gmap.setCenter(result[0].geometry.location);
	              }
		      	});
	        }
        }
				break;
      case 'removeAllMarkers' : theMap.gMap('removeAllMarkers'); break;
      case 'panBy' : gm.gmap.panBy(extraInfo.X,extraInfo.Y); break;
      case 'setZoom' : gm.gmap.setZoom(parseInt(extraInfo.zoom)); break;
      case 'setMapType' : gm.gmap.setMapTypeId(extraInfo.mapType); break;
    }
  }
}
function dmxNotifyAction() {   //ver 1.00
  if (arguments && arguments.length > 0) {
    if(typeof arguments[0] == 'object'){
      jQuery.dmxNotify(arguments[0]);
    }else if(arguments[0] === 'closeAll'){
       jQuery.dmxNotify.closeAll();
    }
  }
}
</script>
<script type="text/javascript" charset="utf-8">
// Wait for device API libraries to load
    //
    function onLoad() {
        document.addEventListener("deviceready", onDeviceReady, false);
    }

    // device APIs are available
    //
    function onDeviceReady() {
        // Now safe to use device APIs
		navigator.splashscreen.hide();		
    }
	
</script>

<script type="text/javascript" src="ScriptLibrary/dmxDataFilters.js"></script>
</head>

<body data-spy="scroll" data-target=".nav-container" onload="onLoad()">
<div class="container">
  <div class="row">
  <div class="col-lg-12">
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="nav-container container-fluid"> 
          
          <a href="list-view.html" rel="external"><button type="button" class="btn btn-default navbar-btn btn-sm"><i class="fa fa-list-ul fa-lg"></i> List View</button></a>
<button type="button" class="btn btn-default navbar-btn btn-sm" onClick="dmxGoogleMapsAction('map1','setCenter',{&quot;latitude&quot;: &quot;{{$GEO.coords.latitude}}&quot;, &quot;longitude&quot;: &quot;{{$GEO.coords.longitude}}&quot;, &quot;icon&quot;: {&quot;image&quot;: &quot;http://www.google.com/mapfiles/markerQ.png&quot;}});dmxGoogleMapsAction('map1','addMarker',{&quot;latitude&quot;: &quot;{{$GEO.coords.latitude}}&quot;, &quot;longitude&quot;: &quot;{{$GEO.coords.longitude}}&quot;, &quot;icon&quot;: {&quot;image&quot;: &quot;http://www.shopmilitarydiscounts.com/images/gps_not_fixed_48px-48.png&quot;, &quot;iconsize&quot;: [48, 48], &quot;iconanchor&quot;: [24, 24]}})"><i class="fa fa-crosshairs fa-lg"></i> Find Me</button>
<a href="options.html"><button type="button" class="btn btn-default navbar-btn btn-sm"><i class="fa fa-cogs fa-lg"></i> Options</button></a>        </div>
      </nav>
    </div></div>
</div>
  <div id="mapWrapper">
  <div class="dmxGoogleMaps" id="map1" style="width:100%;height:100%;"></div>
  </div>
<script type="text/javascript">
  // <![CDATA[
 jQuery(document).ready(
   function()
     {
       jQuery("#map1").dmxGoogleMaps(
         {"width": "100%", "height": "100%", "dataSource": "dmxDataSet", "dataSourceType": "dynamic", "repeatElement": "{{mapDiscountsALL.data}}", "latitude": "{{$GEO.coords.latitude}}", "longitude": "{{$GEO.coords.longitude}}", "zoom": 9, "markers": [{"address": "{{discount_address1}},{{discount_city}},{{discount_state}},{{discount_zip}}", "html": "<strong>{{discount_biz_name}} - <em>{{discount_amount}}% Off</em></strong><br>{{discount_description}}\r<br><strong>[ <a href='discount-detail.html?discount_id={{discount_id}}' rel='external'> DETAILS</a> ]</strong>", "icon": {"image": "icons/default.png", "iconsize": [48, 48], "iconanchor": [24, 48]}}], "scaleControl": false, "streetViewControl": false}
       );
     }
 );
  // ]]>
</script>
</div>
</body>
<script>
var admobid = {};
if( /(android)/i.test(navigator.userAgent) ) { 
    admobid = { // for Android
        banner: 'ca-app-pub-4032873873455264/2426559631',
        interstitial: 'a-app-pub-4032873873455264/2756133633'
    };
} else if(/(iphone)/i.test(navigator.userAgent)) {
    admobid = { // for iOS
        banner: 'ca-app-pub-4032873873455264/2426559631',
        interstitial: 'a-app-pub-4032873873455264/2756133633'
    };
}

function initApp() {
    if (AdMob) {
        AdMob.createBanner({
            adId : admobid.banner,
            position : AdMob.AD_POSITION.BOTTOM_CENTER,
            autoShow : true
        });
    }
}
document.addEventListener('deviceready', initApp, false);
</script>
</html>
```
--------------------------------
Thanks for any insight!
Baub

**Comment by floatinghotpot** [comment]
I see that your ad units for android and ios are exactly same.

ad unit for android cannot be used for ios. you need create app for ios and create ad unit. 

btw, the ad unit for interstitial is wrong when copy/paste, please double check.

**Comment by baubeis** [comment]
Creating the second set of ads fixed the problem.  Thanks for your quick response!

**Comment by baubeis** [comment]
I guess I was a little quick on the problem being fixed.  I don't know if this can be addressed here or if I need to search other forums, but thought I would give it a go.

When I said it worked it did, ads were appearing on the iphone no problem.  The FIRST time I open it, but then after I close the app and reopen they  don't appear again.  If I uninstall and reinstall the app then they will appear again for the one time.  Any ideas on what could be causing that?

Still works every time on android.

thanks for any insight?

**Comment by floatinghotpot** [comment]
I cannot reproduce your issue. How do you close the app, or just switch to background?

**Comment by baubeis** [comment]
I close app by just the normal apple way.  Double click home button and then
swipe up to close.

From:  Raymond Xie <notifications@github.com>
Reply-To:  floatinghotpot/cordova-admob-pro
<reply+009f8b9f05ea532969e7342e1a03ba85ecdea71435e7ac0a92cf0000000110e5383a9
2a169ce03350c06@reply.github.com>
Date:  Saturday, January 31, 2015 at 6:41 PM
To:  floatinghotpot/cordova-admob-pro <cordova-admob-pro@noreply.github.com>
Cc:  Baub <baub@baub.com>
Subject:  Re: [cordova-admob-pro] Phonegap build works on android not on
iphone (#65)


I cannot reproduce your issue. How do you close the app, or just switch to
background?

‹
Reply to this email directly or view it on GitHub
<https://github.com/floatinghotpot/cordova-admob-pro/issues/65#issuecomment-
72345029> .

**Comment by baubeis** [comment]
Here is code:  Don't that will help?

<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta charset="UTF-8">
<title>Shop Military Discounts</title>
<link rel="stylesheet" type="text/css" href="bootstrap/3/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="Styles/dmxGoogleMaps.css" />
<link rel="stylesheet" type="text/css" href="Styles/dmxNotify.css" />
<link rel="stylesheet" type="text/css" href="fontawesome/css/font-awesome.min.css" />
<style type="text/css">
#mapWrapper {
	height: 100%;
	width: 100%;
	padding-top: 59px;
	position: absolute;
}
</style>
<script type="text/javascript" src="ScriptLibrary/jquery-latest.pack.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="bootstrap/3/js/bootstrap.min.js"></script>
<script type="text/javascript" src="ScriptLibrary/dmxBootstrap3Navigation.js"></script>
<script type="text/javascript" src="ScriptLibrary/dmxGoogleMaps.js"></script>
<script type="text/javascript" src="ScriptLibrary/dmxDataBindings.js"></script>
<script type="text/javascript" src="ScriptLibrary/dmxDataSet.js"></script>
<script type="text/javascript" src="ScriptLibrary/dmxDataBrowser.js"></script>
<script type="text/javascript" src="ScriptLibrary/dmxNotify.js"></script>
<script type="text/javascript" src="ScriptLibrary/dmxGeoLocation.js"></script>
<script type="text/javascript" src="cordova.js"></script>
<script type="text/javascript">
  /* dmxDataSet name "MobileAppData" */
       jQuery.dmxDataSet(
         {"id": "MobileAppData", "url": "http://admin.shopmilitarydiscounts.com/dmxDatabaseSources/MapDiscounts.asp", "data": {"discount_category": "{{$URL.discount_category}}", "limit": "2000"}, "siteName": "Shop Military Discounts - Admin", "dataSourceType": "database", "dataType": "jsonp"}
       );
  /* END dmxDataSet name "MobileAppData" */
   /* dmxDataSet name "mapDiscountsALL" */
       jQuery.dmxDataSet(
         {"id": "mapDiscountsALL", "url": "http://admin.shopmilitarydiscounts.com/dmxDatabaseSources/divMapTEST.asp", "data": {"limit": "2000"}, "siteName": "Shop Military Discounts - Admin", "dataSourceType": "database", "dataType": "jsonp"}
       );
  /* END dmxDataSet name "mapDiscountsALL" */
  /* dmxGeoLocation name "dmxGeoLocation" */
       jQuery.dmxGeoLocation(
         {"enableHighAccuracy": true, "timeout": 6000, "onTimeout": "dmxGoogleMapsAction('map1','setCenter',{\"address\": \"Fort Leonard Wood, MO 65473\"});", "onUnavailable": "dmxNotifyAction({\"type\": \"error\", \"positionClass\": \"toast-bottom-full-width\", \"title\": \"Geolocation is Unavailable\", \"msg\": \" ##message##\", \"extendedTimeOut\": 2000, \"tapToDismiss\": false});"}
       );
  /* END dmxGeoLocation name "dmxGeoLocation" */

function dmxGoogleMapsAction(playerName, actionName, extraInfo) { // v2.0
  var theMap = jQuery('#'+playerName);
  if (theMap && theMap.gMap) {
   	var gm = theMap.data("gmap");
    switch (actionName) {
      case 'addMarker' :
        theMap.gMap('addMarker', extraInfo);
		    break;
      case 'gotoMarker' :
      case 'panToMarker' :
        if (extraInfo && extraInfo.key) {
	    	  var theMarker = theMap.gMap('getMarker', extraInfo.key);
	    	  if (theMarker) {
	          var center = theMarker.getPosition();
	          if (actionName == 'panToMarker') gm.gmap.panTo(center)
	          else gm.gmap.setCenter(center);
	        }
	      }
		    break;
			case 'showInfoWindow' :
			  if (extraInfo && extraInfo.key) {
				  var theMarker = theMap.gMap('getMarker', extraInfo.key);
				  if (theMarker) {
				    google.maps.event.trigger(theMarker, 'click');
				  }
			  }
			  break;
		  case 'resizeMapSmooth' :
		    theMap.gMap('fixAfterResize');
			  break;
		  case 'resizeMapDirectly' :
		    theMap.gMap('fixAfterResize', true);
		    break;
		  case 'setCenter':
		  case 'panTo':
			  var $googlemaps = google.maps, $geocoder = new $googlemaps.Geocoder();
        if (extraInfo.latitude && extraInfo.longitude) {
          // lat & lng available, return
          var center = new $googlemaps.LatLng(extraInfo.latitude, extraInfo.longitude);
          if (actionName == 'panTo') gm.gmap.panTo(center)
          else gm.gmap.setCenter(center);
          return;
        } else {
	        // Check for address to center on
	        if (extraInfo.address) {
	          // Get coordinates for given address and center the map
	          $geocoder.geocode(
		          {address: extraInfo.address},
		          function(result, status) {
	              if (status === google.maps.GeocoderStatus.OK) {
	              	if (actionName == 'panTo') gm.gmap.panTo(result[0].geometry.location);
	              	else gm.gmap.setCenter(result[0].geometry.location);
	              }
		      	});
	        }
        }
				break;
      case 'removeAllMarkers' : theMap.gMap('removeAllMarkers'); break;
      case 'panBy' : gm.gmap.panBy(extraInfo.X,extraInfo.Y); break;
      case 'setZoom' : gm.gmap.setZoom(parseInt(extraInfo.zoom)); break;
      case 'setMapType' : gm.gmap.setMapTypeId(extraInfo.mapType); break;
    }
  }
}
function dmxNotifyAction() {   //ver 1.00
  if (arguments && arguments.length > 0) {
    if(typeof arguments[0] == 'object'){
      jQuery.dmxNotify(arguments[0]);
    }else if(arguments[0] === 'closeAll'){
       jQuery.dmxNotify.closeAll();
    }
  }
}
</script>
<script type="text/javascript" charset="utf-8">
// Wait for device API libraries to load
    //
    function onLoad() {
        document.addEventListener("deviceready", onDeviceReady, false);
    }

    // device APIs are available
    //
    function onDeviceReady() {
        // Now safe to use device APIs
		navigator.splashscreen.hide();
		analytics.startTrackerWithId('UA-58388405-1');
		analytics.trackView('Main Map');
    }
	
</script>

<script type="text/javascript" src="ScriptLibrary/dmxDataFilters.js"></script>
</head>

<body data-spy="scroll" data-target=".nav-container" onload="onLoad()">
<div class="container">
  <div class="row">
  <div class="col-lg-12">
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="nav-container container-fluid"> 
          
          <a href="list-view.html" rel="external"><button type="button" class="btn btn-default navbar-btn btn-sm"><i class="fa fa-list-ul fa-lg"></i> List View</button></a>
<button type="button" class="btn btn-default navbar-btn btn-sm" onClick="dmxGoogleMapsAction('map1','setCenter',{&quot;latitude&quot;: &quot;{{$GEO.coords.latitude}}&quot;, &quot;longitude&quot;: &quot;{{$GEO.coords.longitude}}&quot;, &quot;icon&quot;: {&quot;image&quot;: &quot;http://www.google.com/mapfiles/markerQ.png&quot;}});dmxGoogleMapsAction('map1','addMarker',{&quot;latitude&quot;: &quot;{{$GEO.coords.latitude}}&quot;, &quot;longitude&quot;: &quot;{{$GEO.coords.longitude}}&quot;, &quot;icon&quot;: {&quot;image&quot;: &quot;http://www.shopmilitarydiscounts.com/images/gps_not_fixed_48px-48.png&quot;, &quot;iconsize&quot;: [48, 48], &quot;iconanchor&quot;: [24, 24]}})"><i class="fa fa-crosshairs fa-lg"></i> Find Me</button>
<a href="options.html"><button type="button" class="btn btn-default navbar-btn btn-sm"><i class="fa fa-cogs fa-lg"></i> Options</button></a>        </div>
      </nav>
    </div></div>
</div>
  <div id="mapWrapper">
  <div class="dmxGoogleMaps" id="map1" style="width:100%;height:100%;"></div>
  </div>
<script type="text/javascript">
  // <![CDATA[
 jQuery(document).ready(
   function()
     {
       jQuery("#map1").dmxGoogleMaps(
         {"width": "100%", "height": "100%", "dataSource": "dmxDataSet", "dataSourceType": "dynamic", "repeatElement": "{{mapDiscountsALL.data}}", "latitude": "{{$GEO.coords.latitude}}", "longitude": "{{$GEO.coords.longitude}}", "zoom": 9, "markers": [{"address": "{{discount_address1}},{{discount_city}},{{discount_state}},{{discount_zip}}", "html": "<strong>{{discount_biz_name}} - <em>{{discount_amount}}% Off</em></strong><br>{{discount_description}}\r<br><strong>[ <a href='discount-detail.html?discount_id={{discount_id}}' rel='external'> DETAILS</a> ]</strong>", "icon": {"image": "icons/default.png", "iconsize": [48, 48], "iconanchor": [24, 48]}}], "scaleControl": false, "streetViewControl": false}
       );
     }
 );
  // ]]>
</script>
</div>
</body>
<script>
var admobid = {};
if( /(android)/i.test(navigator.userAgent) ) { 
    admobid = { // for Android
        banner: 'ca-app-pub-4032873873455264/2426559631',
        interstitial: 'ca-app-pub-4032873873455264/2756133633'
    };
} else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
    admobid = { // for iOS
        banner: 'ca-app-pub-4032873873455264/5092321237',
        interstitial: 'ca-app-pub-4032873873455264/6569054437'
    };
}

function initApp() {
    if (AdMob) {
        AdMob.createBanner({
            adId : admobid.banner,
            position : AdMob.AD_POSITION.BOTTOM_CENTER,
            autoShow : true
        });
    }
}
document.addEventListener('deviceready', initApp, false);
</script>
</html>

**Comment by floatinghotpot** [comment]
I think you need refactoring on your code to simplify the logic, for example:

```javascript
document.addEventListener("deviceready", onDeviceReady, false);
...
document.addEventListener('deviceready', initApp, false);
...
```

**Comment by baubeis** [comment]
You mean something like this?

<script type="text/javascript" charset="utf-8">
// Wait for device API libraries to load
    //
    function onLoad() {
        document.addEventListener("deviceready", onDeviceReady, false);
    }

    // device APIs are available
    //
    function onDeviceReady() {
        // Now safe to use device APIs
		navigator.splashscreen.hide();
		analytics.startTrackerWithId('UA-58388405-1');
		analytics.trackView('Main Map');
    }
	
document.addEventListener('deviceready', initApp, false);	

var admobid = {};
if( /(android)/i.test(navigator.userAgent) ) { 
    admobid = { // for Android
        banner: 'ca-app-pub-4032873873455264/2426559631',
        interstitial: 'ca-app-pub-4032873873455264/2756133633'
    };
} else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
    admobid = { // for iOS
        banner: 'ca-app-pub-4032873873455264/5092321237',
        interstitial: 'ca-app-pub-4032873873455264/6569054437'
    };
}

function initApp() {
    if (AdMob) {
        AdMob.createBanner({
            adId : admobid.banner,
            position : AdMob.AD_POSITION.BOTTOM_CENTER,
            autoShow : true
        });
    }
}

</script>

That doesn't work, not sure what step I am missing?

**Comment by floatinghotpot** [comment]
hi, I find your problem: you are using same ad unit id for both iOS and android. In fact, you have to create separately for each platform.

```javascript
if( /(android)/i.test(navigator.userAgent) ) { 
    admobid = { // for Android
        banner: 'ca-app-pub-4032873873455264/2426559631',
        interstitial: 'a-app-pub-4032873873455264/2756133633'
    };
} else if(/(iphone)/i.test(navigator.userAgent)) {
    admobid = { // for iOS
        banner: 'ca-app-pub-4032873873455264/2426559631',
        interstitial: 'a-app-pub-4032873873455264/2756133633'
    };
}
```
