### ISSUE TITLE
Unable to get Ads on iOS7 Simulator

### ISSUE THREAD

**Issue by Tof07** [floatinghotpot/cordova-admob-pro#66]
Hi,
I am trying since several days to make my app displaying ads on iOS7 simulator. It works fine on Android.
So I directly tried the given example index.html. It does not work either...
Symptoms are that I first select overlap for iOS7,
Then click on first create button.
Next, click on Show. At this point of time, a black rectangle shows at the bottom using whole width. But nothing in it even when waiting more than 2 minutes.

![screenshot](https://cloud.githubusercontent.com/assets/9393004/5714158/13caa4e6-9ac5-11e4-813b-46aa2caebf30.png)

Please note I have a Mac in a virtual machine on a Windows-based PC, but this should not block the ads. I can connect to the internet correctly.
Could it be that the iMac firewall block the ads? Or maybe there is something like this in the iPhone simulator directly?
I use to use safari for debugging. So I attach to the simulator. Strangely safari show three possible apps/frames in the "develop/iphone simulator" menu: it starts showing:
 - blank
 - googleads.g.doubleclick.net - sdk-core-v40.html
 - Index.html
Then it turns into 
 - blank
 - blank
 - Index.html

Each time I try again, another blank page appear...

![screenshot2](https://cloud.githubusercontent.com/assets/9393004/5714207/c3431174-9ac5-11e4-9635-c3245e330489.png)

I looked at all these and could not find any console entry..
What tehnical information would you need for further investigation? I am not an expert in iOS environment.

Finally, I also tried interstitial, but it does nothing at all.

Thanks a lot for your help.
Best regards
Christophe

**Comment by floatinghotpot** [comment]
you are running emulator on a virtual machine? seems a little complex..  can you connect ios device to test?

**Comment by Tof07** [comment]
Hi,
I don't have a physical device to test on. I can ask a friend of mine. 
In the menatime, do you want me to provide you with version information or logs?
Thanks a lot for your reply.

**Comment by Tof07** [comment]
Hi,

Finally, I made it work!
Basically, I did this to make it work:
1. I used the setOptions method
2. I removed the autoShow property from the first parameter of createBanner
3. I added the success and errr callbacks of createBanner
4. I added the two callbacks of showBanner
5.. I changed the console.log statement in the onAdLoaded event to an alert statement

Now that it worked, I tried to remove those changes one by one until I get an error again.
Finally, after I removed everything, it was still working. In the end I completely copied original file and got a new error (which is quite severe). So I don't exactly from where the problem comes from, but I suspect the alert to console.log change... It creates multiple locks on web thread which is not supported. Here are some screen copies:
![screenshot3](https://cloud.githubusercontent.com/assets/9393004/5729984/e07dfd1a-9b76-11e4-934d-56b3c8dfa046.png)

![screenshot4](https://cloud.githubusercontent.com/assets/9393004/5729989/e677309c-9b76-11e4-98af-8532927488e1.png)

Here is the code I have (I did not clean it to make sure you see the exact same thing (except publisher ids)):
 * Failing code:

function AdvertisementManager() {
console.log("AdvertisementManager.class creation");
	this.admobid = {};
	this.adLoaded = false;
	
	this.initialize = function() {
console.log("ad.init1");
		if( ! AdMob) {
			console.log("Error: AdMob library is not ready.");
			return;
		}
console.log("ad.init2");
		// select the right Ad Id according to platform
		if( /(android)/i.test(navigator.userAgent) ) { 
			console.log("AdMob init: detected android device.");
			this.admobid = { // for Android
					banner: 'ca-app-pub-84846728845XXX',
					interstitial: 'ca-app-pub-84846728845XXX'
			};
		} else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
			console.log("AdMob init: detected iOS device.");
			this.admobid = { // for iOS
					banner: 'ca-app-pub-84846728845515XXX',
					interstitial: 'ca-app-pub-84846728845515XXX'
			};
		} 
		else
		{
			console.log("AdMob init: device type not detected");
		}
//		else {
//				this.admobid = { // for Windows Phone
//						banner: 'ca-app-pub-686999247401XXX',
//						interstitial: 'ca-app-pub-6869992474017XXX'
//				};
//		}

		document.addEventListener('onAdLoaded',function(data){
			console.log("Ad loaded");
			advertisementManager.adLoaded = true;
			if (pageManager.getCurrentPage() == pageManager.MENU_PAGE)
			{
				advertisementManager.showAd();
			}
		});
		
		AdMob.createBanner({
				adId: this.admobid.banner,
				autoShow: false
		});
	}
	
	this.showAd = function() {
		console.log("showAd called.");
		// Show a banner at bottom
		if(AdMob && this.adLoaded)
		{
			console.log("showAd : showing ad.");
			AdMob.showBanner( AdMob.AD_POSITION.BOTTOM_CENTER );
		}
	}
	
	this.hideAd = function() {
		if(AdMob && this.adLoaded)
		{
			AdMob.hideBanner();
		}
	}
}


 * The one that is working:

function AdvertisementManager() {
console.log("AdvertisementManager.class creation");
	this.admobid = {};
	this.adLoaded = false;
	
	this.initialize = function() {
console.log("ad.init1");
		if( ! AdMob) {
			console.log("Error: AdMob library is not ready.");
			return;
		}
console.log("ad.init2");
		// select the right Ad Id according to platform
		if( /(android)/i.test(navigator.userAgent) ) { 
			console.log("AdMob init: detected android device.");
			this.admobid = { // for Android
					banner: 'ca-app-pub-848467288455153XXX',
					interstitial: 'ca-app-pub-84846728845515XXX'
			};
		} else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
			console.log("AdMob init: detected iOS device.");
			this.admobid = { // for iOS
					banner: 'ca-app-pub-84846728845515XXX',
					interstitial: 'ca-app-pub-84846728845515XXX'
			};
		} 
		else
		{
			console.log("AdMob init: device type not detected");
		}
//		else {
//				this.admobid = { // for Windows Phone
//						banner: 'ca-app-pub-68699924740179XXX',
//						interstitial: 'ca-app-pub-686999247401798XXX'
//				};
//		}

        AdMob.setOptions( { bgColor: 'black', position: AdMob.AD_POSITION.BOTTOM_CENTER, isTesting: true } );
        
		document.addEventListener('onAdLoaded',function(data){
			alert("Ad loaded");
			advertisementManager.adLoaded = true;
			if (pageManager.getCurrentPage() == pageManager.MENU_PAGE)
			{
				advertisementManager.showAd();
			}
		});
		
        document.addEventListener('onAdFailLoad', function(data){
                                  alert('error: ' + data.error +
                                        ', reason: ' + data.reason +
                                        ', adNetwork:' + data.adNetwork +
                                        ', adType:' + data.adType +
                                        ', adEvent:' + data.adEvent); // adType: 'banner' or 'interstitial'
                                  });
        
		AdMob.createBanner({
                           adId: this.admobid.banner,
                           success: function() { console.log("CreateBanner OK");},
                           error: function() { console.error("CreateBanner failed");}
                           });
/*		AdMob.createBanner({
                           adId: this.admobid.banner,
                           success: function() { console.log("CreateBanner OK");},
                           error: function() { console.error("CreateBanner failed");}
                           });
*/	}
	
	this.showAd = function() {
		console.log("showAd called.");
		// Show a banner at bottom
		if(AdMob && this.adLoaded)
		{
			console.log("showAd : showing ad.");
			AdMob.showBanner( AdMob.AD_POSITION.BOTTOM_CENTER,
                             function() {alert("showBanner OK");},
                             function() {alert("showBanner Failed");});
		}
	}
	
	this.hideAd = function() {
		if(AdMob && this.adLoaded)
		{
			AdMob.hideBanner();
		}
	}
}

Hope this can help you finding the issue.
Thanks and regards
Christophe

**Comment by floatinghotpot** [comment]
i agree that the error may be caused by using console.log, avoid using it when debugging phonegap app, use alert() instead.
