### ISSUE TITLE
Parse error - there was a problem parsing the package (Genymotion)

### ISSUE THREAD

**Issue by stefek99** [floatinghotpot/cordova-admob-pro#67]
I'm using Genymotion as Android emulator.

On 4.1.1 (emulator) I'm getting this:

![screen shot 2015-01-13 at 13 51 08](https://cloud.githubusercontent.com/assets/249703/5722575/29e33ce6-9b35-11e4-8106-07651c79ca6a.png)
(forked the [sample repo](https://github.com/floatinghotpot/phonegap-admob-demo))

On 4.1.1 (actual device) it is working fine.

I wonder if anyone has encounter similar issues?

**Comment by floatinghotpot** [comment]
the issue is not for this repo, please post it to that project.
