### ISSUE TITLE
AdMob Pro Resize is Pushing Webview Down W/O Resize on IOS

### ISSUE THREAD

**Issue by tony-o** [floatinghotpot/cordova-admob-pro#68]
AdMob Pro is pushing the webview down without the resize.  Using XCode 6.1 and Cordova 3.6.3-0.2.13.  See screenshot below.  Notice the buttons along the bottom are gone below the bottom edge of the screen..

![screen shot of issue](http://i.imgur.com/QUbDzWR.png)

Relevant admob JS:

```javascript
       if(AdMob && globaloptions.showAds){
         var replug = function(){
           AdMob.createBanner({
             adId: id,
             //position: AdMob.AD_POSITION.BOTTOM_CENTER,
             autoShow: true,
             overlap: false
           }, function(){
             console.log("success");
           }, function(){
             console.log('retrying ad..');
             setTimeout(replug, 30000);
           });
         };
         replug();
       }
```

**Comment by floatinghotpot** [comment]
Which version do you use? It was a bug long time ago, but it’s fixed months ago.

Try listening to document resize event to update the layout.

Or, use overlap:true, and reserve banner space in your web view.

**Comment by tony-o** [comment]
I saw the old bugs.  Is the fix to resize the layout manually?  I'm using latest AFAICT, I uninstalled and reinstalled the module yesterday prior to opening the bug

**Comment by kvdv** [comment]
I had the same problem but the overlap solution fixed it for me.
The alternative is to listen to window / document resize and fix stuff manually indeed.
