### ISSUE TITLE
Minor wiki typos

### ISSUE THREAD

**Issue by jmelvin** [floatinghotpot/cordova-admob-pro#69]
(I'm not sure how best to propose changes to the wiki pages.  Perhaps filing this issue can serve as an alternative.)

There are a couple of typos in the wiki page for setOptions()...

1.2 Method: AdMob.setOptions():

< set the defualt Ad unit Id for interstitial
> set the default Ad unit Id for interstitial

< AdMob.AD_POSITION.BOTTOM_RIGHT  = 8,
> AdMob.AD_POSITION.BOTTOM_CENTER  = 8,

**Comment by floatinghotpot** [comment]
it's fixed, thank you.
