### ISSUE TITLE
Errors with WP8 plugin

### ISSUE THREAD

**Issue by dbaseman** [floatinghotpot/cordova-admob-pro#70]
1) Class should be named "AdMob" instead of "AdMobPlugin" (otherwise Cordova runtime throws the error: "Unable to locate command :: AdMob").

2) Can't use Dictionary<string, string> with JsonHelper.Deserialize.  Need to create a class like "AdMobOptions":

        public class AdMobOptions
        {
            public string adId { get; set; }
            // etc
        }

Then use:

        var options = JsonHelper.Deserialize<AdMobOptions>(inputs[0]);

**Comment by vpease** [comment]
tried this. Not working anyway

**Comment by floatinghotpot** [comment]
I've merged the code from dbaseman and did some bugfix. it's build pass with a demo project with phonegap build service, but not tested on device yet. 

could you please help to verify the plugin wp8 code?

**Comment by floatinghotpot** [comment]
close this tracker, please refer to #84
