### ISSUE TITLE
Admob Refresh

### ISSUE THREAD

**Issue by okwei2000** [floatinghotpot/cordova-admob-pro#71]
I have a single paged phonegap app, I dont see the banner get refreshed unless I reload my app. Is this normal, or I have to refresh the ads programmatically?

**Comment by floatinghotpot** [comment]
You can set the refresh rate in you admob portal when creating ad units

**Comment by okwei2000** [comment]
Forgot to mention that I already did set the refresh rate in you admob portal - tried both 30 or 60 secs, but  this doesn't seem to work. Tried both iOS and Android, seems to behave the same way. Can I manually refresh it?

**Comment by floatinghotpot** [comment]
Sometimes the refreshed ad may be same ad. You can listen to onAdLoaded event to check whether ad is refreshed or not.

**Comment by Narasim1234** [comment]
Hi floatighotpot i have done one game in flash professional cc, i got the output file of html and java script. Everything goes fine but when i am going to add AdMob in that game its not working ,
Could you plz help me

I am using the following File

1.Flash CC Html Canvas

**Comment by floatinghotpot** [comment]
need more input to tell what's wrong
