### ISSUE TITLE
Inline banners: how-to?

### ISSUE THREAD

**Issue by bheijns** [floatinghotpot/cordova-admob-pro#73]
Hi,

As seen here: http://googleadsdeveloper.blogspot.co.uk/2012/03/embedding-admob-ads-within-listview-on.html It is possible to show inline / listed ads with AdMob.

Is this also working with AdMob pro? And if so, can somebody tell me how to do it?

We prefer putting AdMob ads in a div of our Phonegap Build application.

<b>Thank you in advance.<b>

**Comment by floatinghotpot** [comment]
As admob banner is a native view not a HTML DOM element, you cannot put it into a div, and it's not recommended by Google to mix ad content with your app content.

**Comment by Prav92** [comment]
@floatinghotpot  any alternative way to do using this plug-in? we have to add ads into a div and or listview please give your comment, Thank you

**Comment by floatinghotpot** [comment]
AdMob has a new type of native Ad, which you get the ad resource and display in your DOM, but it's beta in some invited developers only. (You cannot see it in your admob portal)

Or, you can try Flurry Ad plugin, which support native Ad.
https://github.com/floatinghotpot/cordova-plugin-flurry

**Comment by valnub** [comment]
What's the status on this? Can you embed ads within DOM elements now?

**Comment by robobobo** [comment]
This is something I really need to do as well now. Pretty important for us to be able to display an advert in a scrollable list

**Comment by floatinghotpot** [comment]
It's not possible yet with AdMob SDK, as the native ad is pure native view, which cannot be insert into HTML DOM element. 

You can only try this feature with Facebook AudienceNetwork or Yahoo Flurry Ad plugins.
https://github.com/floatinghotpot/cordova-plugin-flurry
https://github.com/floatinghotpot/cordova-plugin-facebookads

**Comment by robobobo** [comment]
Thanks @floatinghotpot unfortunately we use DFP. Since the native ad is a pure native view it doesn't sound like injecting it into the HTML DOM is going to be possible any time soon is it?

**Comment by floatinghotpot** [comment]
Implementing native Ad API as DOM elements is usually quite hard. 

It's possible with Flurry & FacebookAds with some research and dirty hacks, as they both use a simple native view to capture user's click event.

But when I looked into AdMob SDK native Ad API, it seems even harder, as Google use quite different approaches. It requires developers to design a set of real native view and layout, and then pass to its native view class. So far, I did not think out a good method to achieve this yet.

**Comment by robobobo** [comment]
Capturing the click events seems to be the most difficult. Currently we use DFP standard web tags in our Phonegap app and listen for clicks with JS to open the links in the native browser

Issue with HTML5 creatives given to us is that we can't tell when or where the click is going to come from as some are video creatives, interactive or open a link with JS instead of using A HREF's so we can't handle them.

Thanks for your time and effort on this anyway, I'll keep trying to find a solution for ourselves!

**Comment by robobobo** [comment]
Just wondering if anyone ever managed to come up with a solution for this? Unfortunately I have not as yet!

**Comment by InternetMaster1** [comment]
Even I am interested in showing Admob ads inside the content of the app. Any progress on the AdMob native via this plugin?

**Comment by utsav-gupta** [comment]
Its 1 year now any resolution to this, I see tinder showing ads in cardview cant we do something like that?

**Comment by floatinghotpot** [comment]
The ad view is implemented by SDK and it's a native webview itself. Our cordova main view is a webview too. So it not possible to insert the ad view into the main webview as a DIV.

You can try the [facebookads](https://github.com/floatinghotpot/cordova-plugin-facebookads) plugin and use the native ad feature as a workaround. Get the ad resource and insert to your DIV yourself. It's a little harder.

As a piece of advice, using interstitial is a good choice, better presence effect and higher click rate, which means better revenue.

FYI.
