### ISSUE TITLE
iPad black screen

### ISSUE THREAD

**Issue by Createstandard** [floatinghotpot/cordova-admob-pro#74]
i just noticed this today but on both my IOS apps only a black screen is showing for the ad For iPad, iPhone is working just fine same code base. Is anyone else experiencing this? I'm not getting any errors, just a black screen with a close button.

**Comment by Createstandard** [comment]
I think this was a bad ad because ads are appearing now.

**Comment by floatinghotpot** [comment]
I agree, as the close button is visible and no error, should not be code problems.
