### ISSUE TITLE
Video insterstitial with no way to close

### ISSUE THREAD

**Issue by Createstandard** [floatinghotpot/cordova-admob-pro#75]
Yesterday I had this video ad come up on iPad with no way to close out of it. I tried everything I could think of. Tapping Learn more just brought up inappbrowser. The video was super long, probably a minute or so and I waited until the entire thing was over to no avail. My Admob limit is 5 seconds. Could it be an issue with the close button, which is usually on the top left, being cut off by that square image? 

![penske](https://cloud.githubusercontent.com/assets/1576641/6003501/dc892040-aac1-11e4-936f-6cb154b45292.png)

**Comment by floatinghotpot** [comment]
I think it's an admob sdk issue, need seek support from google. 

I've pasted your problem in admob official forum, see:
https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/ios/jM9DUvKQLPo

**Comment by floatinghotpot** [comment]
hi, AdMob SDK team has replied in the above link, can you follow up to answer their questions?

**Comment by Createstandard** [comment]
Replied. It's still happening. It appears just one ad network because I had a video one yesterday that had the countdown button that looked just like a youtube one. These appear to come from somewhere else.

**Comment by RedBrogdon** [comment]
AdMob SDK DevRel here.  From the screenshot provided by @Createstandard on our forum (see http://goo.gl/GM2nkd), it looks like the ad might be formatted for a portrait display even though it's being shown on a landscape-oriented screen.  Is it possible that the plugin and Mobile Ads SDK aren't in agreement over what the screen orientation is?

I'd love to see a Charles Proxy log of one of these requests, so I could tell whether a portrait or landscape request was made, and what the reported screen dimensions were.

**Comment by Createstandard** [comment]
I'm not sure about that, I think that might just be the video and a graphic I snapped at just the right time. I just got the real estate one, attached screenshot
![img_0132](https://cloud.githubusercontent.com/assets/1576641/6273910/da34c284-b838-11e4-9316-9b22f47e6976.png)

**Comment by Createstandard** [comment]
You are absolutely right, it's zoomed in. Here's a shot of it in portrait mode. The fact I didn't try this before is pretty ludicrous /facepalm. @floatinghotpot is this something I'm doing wrong?
![img_0133](https://cloud.githubusercontent.com/assets/1576641/6274000/97f244cc-b839-11e4-9fd4-1835a14f9efe.png)

**Comment by floatinghotpot** [comment]
Now I understand the problem, but I don't remember there is any interface to handle this.

Is there any API or parameter offered by AdMob SDK to request a portrait or landscape interstitial Ad? Or, should that be handled by SDK internally?

**Comment by Warface** [comment]
Having the same problem, I have to rotate the photo or tablet to fix it. Any update on Google Team on why it's doing this?

**Comment by floatinghotpot** [comment]
No further info and nothing to do, close issue.
