### ISSUE TITLE
Android Battery Consumption

### ISSUE THREAD

**Issue by okwei2000** [floatinghotpot/cordova-admob-pro#76]
I noticed a high battery usage after adding this plugin on Android - doesnt happen every time, but I could definitely see the CPU usage is high while the app is in background.

**Comment by floatinghotpot** [comment]
it should not be caused by the admob plugin, as the banner has been paused when switching to background, see code:
```java
    @Override
    public void onPause(boolean multitasking) {
        if (adView != null) {
        	__pauseAdView(adView);
        }
        super.onPause(multitasking);
    }
```

do you use any other plugins, or did you handle it in your code when switching to background?

**Comment by okwei2000** [comment]
On, this are no other plugins except the device and camera plugin (core plugins). let me look at this more carefully and get back to you.
