### ISSUE TITLE
Play Store violation rules for MobFox plugin adapter for AdMob

### ISSUE THREAD

**Issue by carlobs** [floatinghotpot/cordova-admob-pro#77]
today i found this warning on all my apps in the Play Store:

"We have determined that your app uses a library or an SDK (com.mobfox, com.mobfox.adapter) that violates rules of the program for developers. Keep in mind that, as of August 1, 2014, the Program Policies for developers require that all updates and new apps uploaded to respect the provision of the ID advertising ("advertising ID") of the Rules of the program for developers. The apps that do not comply are subject to permanent removal from the Store."

**Comment by floatinghotpot** [comment]
Today I received notification from mobfox that a new SDK has been released, I will upgrade the plugin in following days, stay tuned.

**Comment by carlobs** [comment]
I need to update all my ap for Android, can you upgrade the plugin?
thanks

**Comment by floatinghotpot** [comment]
the mobfox plugin as been upgraded with the latest sdk.

please remove the following 2 plugins and ADD AGAIN:
com.google.cordova.admob-mobfox
com.rjfun.cordova.mobfox

good luck.

**Comment by carlobs** [comment]
After upgrade with CLI i still see:
"com.mobfox.sdk 6.0.0" installed not the 6.0.7 or the last 6.0.8

i think something is missing.

**Comment by floatinghotpot** [comment]
please remove plugin com.mobfox.sdk too, and no need to add it back, as it's included in com.rjfun.cordova.mobfox now.

and, remove ~/.plugman/cache before add the plugins.

**Comment by carlobs** [comment]
i don't install the
com.mobfox.sdk
it is intalled from the com.google.cordova.admob-mobfox

what can i do?

**Comment by floatinghotpot** [comment]
I tried to create a project from scratch, when add com.google.cordova.admob-mobfox, it will add the plugin and its dependencies as following:
```
com.google.cordova.admob 2.7.0 "AdMob Plugin Pro"
com.google.cordova.admob-mobfox 6.0.0 "AdMob Mediation Adapter for MobFox"
com.google.playservices 19.0.0 "Google Play Services for Android"
com.rjfun.cordova.extension 1.0.6 "Cordova Plugin Extension"
com.rjfun.cordova.mobfox 2.1.1 "MobFox Ad"
```

com.mobfox.sdk will not be installed.

please remove the plugman cache folder ```~/.plugman/cache```, then try remove your plugins and add back.

**Comment by floatinghotpot** [comment]
follow up: did this resolve your problem?

**Comment by hunterfai** [comment]
Can i know how to update the Mobfox v6.07 to v6.08.jar and also add another jar simple-xml-2.7.1.jar.

**Comment by floatinghotpot** [comment]
mobfox sdk has been updated to latest one, see:
https://github.com/floatinghotpot/cordova-mobfox-pro/tree/master/src/android
