### ISSUE TITLE
DFP-ads are not centered

### ISSUE THREAD

**Issue by christoph-schindler** [floatinghotpot/cordova-admob-pro#78]
i use `position: AdMob.AD_POSITION.BOTTOM_CENTER` to display the ads in the center at bottom. While ads via AdMob follow my order, ads via DFP stay at left. Is there any trick to center them or did i found a bug? If so, can you please fix this issue? I looks broken that all ads are left-aligned at the moment.

**Comment by floatinghotpot** [comment]
What is the size of your dfp banner and your device screen?

**Comment by christoph-schindler** [comment]
Nothing special: the dfp banner is standard 320x50 and the device 1080x1920 (viewport 360x640).

**Comment by floatinghotpot** [comment]
as you are using standard banner not smart banner, try setting the ad size in options:

```javascript
AdMob.createBanner({
adId: 'your_ad_unit_id',
adSize: 'BANNER'
});
```

**Comment by floatinghotpot** [comment]
dupplicated with #72, please discuss in that thread.
