### ISSUE TITLE
error: package com.google.android.gms.ads does not exist

### ISSUE THREAD

**Issue by Ziv-Barber** [floatinghotpot/cordova-admob-pro#80]
[javac] E:\develop\tests\phonegap\gameOnApp\platforms\android\src\com\rjfun\
cordova\admob\AdMobMediation.java:5: error: package com.google.android.gms.ads does not exist

Tried to move to Cordova 3.7.1

**Comment by floatinghotpot** [comment]
the package is in a dependent plugin: com.google.playservices, it should be added automatically.

or, you can try add it manually:
```bash
cordova plugin add com.google.playservices@19.0.0
```

**Comment by Ziv-Barber** [comment]
Thanks!
Doing:

cordova plugin add com.google.playservices@19.0.0

before installing com.google.cordova.admob fix it for me.

**Comment by skhouseholder** [comment]
For anyone else who has this problem, using com.google.playservices is deprecated according to its github page: https://github.com/MobileChromeApps/google-play-services (YMMV, but installing it caused me duplicate-library problems with most other plugins that use Google Play Services.)

I was getting this error when running `ant release`, which I now know I wasn't supposed to be running at all. [This issue](https://github.com/floatinghotpot/cordova-admob-pro/issues/179) helped me straighten everything out. Hope this helps someone!
