### ISSUE TITLE
No way to programatically close the interstitial ad

### ISSUE THREAD

**Issue by avivais** [floatinghotpot/cordova-admob-pro#82]
I'd like to be able to (programatically) close the interstitial ad after a given timeout, or when returning to the app after tapping the ad.

Can it be done?

**Comment by floatinghotpot** [comment]
The behavior is defined by the admob SDK. User have to click close button to dismiss the interstitial ad, or jump to ad page after click ad.

**Comment by avivais** [comment]
I see a lot of interstitials that are removed by timeout, or perhaps I'm confusing it with something else?

**Comment by floatinghotpot** [comment]
I think admob's behavior is same as most of the other ad service, it's some kind of best practice which requires user's attention and interaction, and also bring you revenue. If you just need a splash screen, maybe you can write a html dom div to present something.
