### ISSUE TITLE
only Test Banners showing in both iOS and Android

### ISSUE THREAD

**Issue by SaganSpirit8** [floatinghotpot/cordova-admob-pro#83]
I replaced the admobid from the working example code (https://github.com/floatinghotpot/cordova-admob-pro/blob/master/test/index.html) with my own admobid, but I get only Test Banners. My app is already on the Android Play Store, but there is still just Test Banners on every device I install it on. What is going wrong? Thanks!

**Comment by floatinghotpot** [comment]
Please remove the option isTesting:true when call createBanner()

**Comment by SaganSpirit8** [comment]
nice! that did the trick.
