### ISSUE TITLE
not working with arm64 iphone 5s up

### ISSUE THREAD

**Issue by vanleab** [floatinghotpot/cordova-admob-pro#85]
i use with appgyver, and there is no build option to change arm64 to arm7

**Comment by floatinghotpot** [comment]
is there any error message?

**Comment by vanleab** [comment]
hi, below is error msg from appgyver build

We detected atleast the following error in the build:

One of your plugins does not seem to compile for 64bit architecture. You will need to contact the plugin author. (error was: 'ld: symbol(s) not found for architecture arm64)'

**Comment by floatinghotpot** [comment]
Is it caused by other plugins?

I double check the admob plugin and its dependency, and found that arm64 is supported.

iMac:ios liming$ lipo -info libCordovaGenericAd.a
Architectures in the fat file: libCordovaGenericAd.a are: armv7 armv7s i386 x86_64 arm64

iMac:GoogleMobileAds.framework liming$ lipo -info GoogleMobileAds
Architectures in the fat file: GoogleMobileAds are: armv7 armv7s i386 x86_64 arm64

**Comment by vanleab** [comment]
but i use only 1 plugin in my app. there is sth wrong with id symbol, which m not sure about.

**Comment by vanleab** [comment]
here is more detail from error log

The following build commands failed:
	CompileC build/Release-iphoneos/Build/Intermediates/AppGyver.build/Release-iphoneos/Scanner\ RC.build/Objects-normal/armv7/CDVAdMob.o Plugins/com.rjfun.cordova.plugin.admob/CDVAdMob.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by floatinghotpot** [comment]
CDVAdMob is provided in source code, should not be its problem

**Comment by vanleab** [comment]
hi, but i don't know those code :(
btw, i just rested another plugin of yours which is facebook ad, and it can b built without any error. could you check again to make this work? i believe it also help other developers who use appgyver. thank you.

**Comment by floatinghotpot** [comment]
I think you need upgrade your xcode to latest version.

**Comment by floatinghotpot** [comment]
just now, when i build the project with an old version of xcode, i see the same error log. 

after I upgrade to latest xcode, it's built successfully.
