### ISSUE TITLE
Problem installing the plugin : google-play-services

### ISSUE THREAD

**Issue by jounayd** [floatinghotpot/cordova-admob-pro#90]
When i try to install the plugin I have a google play services error:

<code>D:\WS\phonegap\IMCWS\imc>phonegap plugin add com.google.cordova.admob

Fetching plugin "com.google.cordova.admob" via plugin registry

Installing "com.google.cordova.admob" for android

Fetching plugin "https://github.com/floatinghotpot/google-play-services" via git
 clone

Failed to install 'com.google.cordova.admob':Error: Command failed: C:\Windows\s
ystem32\cmd.exe /s /c "git clone "https://github.com/floatinghotpot/google-play-
services" "C:\Users\DELL\AppData\Local\Temp\plugman\git\1424519374939""
fatal: could not create work tree dir 'C:\Users\DELL\AppData\Local\Temp\plugman\
git\1424519374939'.: No such file or directory

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)

Error: Command failed: C:\Windows\system32\cmd.exe /s /c "git clone "https://git
hub.com/floatinghotpot/google-play-services" "C:\Users\DELL\AppData\Local\Temp\p
lugman\git\1424519374939""
fatal: could not create work tree dir 'C:\Users\DELL\AppData\Local\Temp\plugman\
git\1424519374939'.: No such file or directory

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)</code>

**Comment by floatinghotpot** [comment]
Do you have git installed?

**Comment by floatinghotpot** [comment]
as you are using cordova on windows, you can try installing git for windows, and tortoiseGit (the GUI of git, integration with explorer), see: https://code.google.com/p/tortoisegit/wiki/SetupHowTo

**Comment by floatinghotpot** [comment]
see my log, the plugin is installed successfully after install git for windows:

```
E:\cordova-apps\test1>cordova plugin add com.google.cordova.admob
Fetching plugin "com.google.cordova.admob" via plugin registry
Installing "com.google.cordova.admob" for android
Fetching plugin "https://github.com/floatinghotpot/google-play-services" via git clone
Repository "https://github.com/floatinghotpot/google-play-services" checked out to git ref "r19".
Installing "com.google.playservices" for android
Installing "com.google.cordova.admob" for windows
Installing "com.rjfun.cordova.extension" for windows
Installing "com.google.cordova.admob" for wp8
Installing "com.rjfun.cordova.extension" for wp8
```

**Comment by dmotion** [comment]
You can also use Visual Studio with Cordova Tools, when running Windows.

It has an in-build GIT / NuGet system which works perfect when getting GIT files or updating them.

**Comment by floatinghotpot** [comment]
thanks for the recommendation.
