### ISSUE TITLE
"AdMob not is not defined". Baffled. 

### ISSUE THREAD

**Issue by SubjectiveEffect** [floatinghotpot/cordova-admob-pro#91]
I don't understand why I'm getting this problem. This is my code:

    var admobid = {};
      if( /(android)/i.test(navigator.userAgent) ) { // for android
          admobid = {
              banner: 'ca-app-pub-xxxx,
              interstitial: 'ca-app-pub-yyyy'
          };
      } else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) { // for ios
          admobid = {
              banner: 'ca-app-pub-xxxx',
              interstitial: 'ca-app-pub-yyyy'
          };
      } 

      if(typeof AdMob !== "undefined") AdMob.createBanner( {
       adId: admobid.banner, 
       position: AdMob.AD_POSITION.TOP_CENTER, 
       autoShow: true } );
      else alert("Admob is not defined");

I just don't see why I'm getting the not defined error. I'm using my own AdMob references obviously. And I am testing it on an Android phone. 

Any ideas?

**Comment by floatinghotpot** [comment]
Did you add admob plugin and include javascript file cordova.js in your html?

**Comment by SubjectiveEffect** [comment]
Yes I did. 

I have other plugins working - Google Analytics and one of the Email plugins - in the same app.

**Comment by SubjectiveEffect** [comment]
It's fixed now. I don't know why or how exactly but it's working. It may have been to do with another bit of code in .run but whatever, I've got banners now! Thanks.
