### ISSUE TITLE
WP8 not showing

### ISSUE THREAD

**Issue by andrequintino** [floatinghotpot/cordova-admob-pro#92]
Looking at the source code of AdMob, I found this line:
cordova.exec( successCallback, failureCallback, 'AdMob', 'createBanner', [ options ] );

But the name of C# class is AdMobPlugin.

In Cordova documentation, there is the following information:
"This class name must exactly match what you call specify as the service in the cordova.exec() call on the JavaScript side".

Please, am I correct? There are someone that can change this code?

**Comment by floatinghotpot** [comment]
I've merged the code from dbaseman and did some bugfix. it's build pass with a demo project with phonegap build service, but not tested on device yet. 

could you please help to verify the plugin wp8 code?

close this tracker, please refer to issue #84
