### ISSUE TITLE
Black screen on Android with Cordova

### ISSUE THREAD

**Issue by tazbambu** [floatinghotpot/cordova-admob-pro#93]
I am new on developing for android and struggling with the admob functionality.
Built cordova projects submitted on google play - cordova version 4.2.0 building on eclipse.
I have tried both the native admod and your plugin but the only I get is a black screen in the selected position. 
I ' ve read various posts on the web about low fill rate, not having ads to show, wrong admob id,not enough space to display the ad..still haven't managed to find a solution.

I am sure the id's are the correct ones, using the one's for the specific app and package name, in my Ad unit I only have the AdMob Network (Dynamically positioned) as source and on this source I don't have any access on Country specific settings.

Could you please provide me some insight?

**Comment by tazbambu** [comment]
Update - I get the response: 
There was a problem getting an ad reponse. Error code:0
Unable to resolve virtual method 3104 (tag:dalvikvm)
Unable to resolve virtual method 3114 (tag:dalvikvm)

**Comment by floatinghotpot** [comment]
Before using the plugin in your project, can you try the demo index.html under test folder first, to verify the plugin in your environment?

**Comment by tazbambu** [comment]
Yes I tried it , I get error:0, reason:Internal error, adNetwork:AdMOB,adType:banner,adEvent:onAdFailLoad

**Comment by tazbambu** [comment]
in the test1 project created according to your guide libs folder  there is the google-play-services.jar
but i get the console response: The google play services resources were not found

**Comment by floatinghotpot** [comment]
The resources warning message is always there and you can ignore it.

Usually a black ad is caused by invalid ad unit Id. 

Did you use the demo index.html as it is, without any change and no VPN?

**Comment by tazbambu** [comment]
I didnt change anything I used your own ad unit ids , shouldn't it display test ads as in the example? I am launching from an sony xperia j  -- 4.1.2 android version

**Comment by floatinghotpot** [comment]
yes, it should display test ad. Can you test it with android simulator first?

**Comment by tazbambu** [comment]
yeap the test ads display correctly on the emulator!

**Comment by floatinghotpot** [comment]
Do you have Internet connection on your android phone?

**Comment by tazbambu** [comment]
ofcourse im testing via wifi,
 according to your test project while installing only ACCESS_NETWORK_STATE permission is added (doesn't this require network information plugin though to work?) , i had previously tried with permissions added, INTERNET and WIFI STATE but same result

**Comment by floatinghotpot** [comment]
as you can see the ad on emulator, the plugin works well. maybe you can try changing another device to run the test to see what's happening.

**Comment by Dineshrajaa** [comment]
Hi Tazbambu,
 This is a simple test app which is using cordova-admob-pro plugin kindly install this and test it 
https://build.phonegap.com/apps/1349970/share
