### ISSUE TITLE
iOS doesn't have proper footer

### ISSUE THREAD

**Issue by vanleab** [floatinghotpot/cordova-admob-pro#94]
hi, i hav footer issue on ios device, but android works fine. i've attached the screenshot from iphone.
![20150227_023945000_ios](https://cloud.githubusercontent.com/assets/237713/6406585/4cda4ac0-be65-11e4-95a5-cc4a0ca26645.png)

**Comment by floatinghotpot** [comment]
I guess the web layout did not handle when web view resize. 

Please listen to resize event and update the layout according to actual width and height.
