### ISSUE TITLE
Callbacks from prepareInterstitial()

### ISSUE THREAD

**Issue by sandymacpherson** [floatinghotpot/cordova-admob-pro#95]
Hi,

I'm using the prepareInterstitial function

AdMob.prepareInterstitial(adId/options, success, fail)

and would like to use the success/fail callbacks. However, no combination of parameters works for me and I cannot find an example in the documentation or online of how to do this. Could you provide a snippet showing how to do this? Just example parameters to the function would be fine.

Also a note about the interstitials - the documentation mentions a function isInterstitialReady() but that appears to be old as the code no longer supports this.

Thanks
Sandy

**Comment by floatinghotpot** [comment]
Usually call to prepareInterstitial will not fail. If you want to check the ad loading status, please use the event listener, onAdLoaded or onAdLoadFail.

**Comment by sandymacpherson** [comment]
Right - I am using those events and they are working just fine. Perhaps it's just the documentation that needs an update then? The mention of 'success' and 'fail' as parameters is misleading when the events should be used instead. Another thing I noticed is that if I first call setOptions() and then make a call to AdMob.prepareInterstitial() with no parameters, the onAdLoaded event doesn't fire at all and the prepare seems to fail. If I instead do AdMob.prepareInterstitial({}), then it all works fine. I'd suggest making the function accept no parameters at all since you can preset them all with setOptions.

Also note the comment above about isInterstitialReady() not being available despite being in the docs.

Thanks
Sandy
