### ISSUE TITLE
Multiple Banners at different positions at the same time..??

### ISSUE THREAD

**Issue by gotu** [floatinghotpot/cordova-admob-pro#96]
To describe, if one wants to create 2 banners intuitively calling createBanner with 2 different adIds and different positions like this:

```javascript
AdMob.createBanner({ 
  adId:'[admob-adunit-id-1]', 
  position:AdMob.AD_POSITION.TOP_CENTER, 
  autoShow:true 
});

AdMob.createBanner({ 
  adId:'[admob-adunit-id-2]', 
  position:AdMob.AD_POSITION.BOTTOM_CENTER, 
  autoShow:true 
});
```

Then there is only one banner shown, the one at the BOTTOM_CENTER, so the last call to createBanner Method.

Is it possible to have more than one banner at different positions at the same time?
If it is not possible, is it an limitation of this plugin at current version or is it an limitation of the Google Mobile Ads SDK?

**Comment by floatinghotpot** [comment]
It's not allowed by Google to display 2 banners on the mobile screen, as the screen is small and will impact user experience.

**Comment by gotu** [comment]
Ok, thanks. I was actually aware of the Google policies (see below). But I wondered of the limitations in this cordova plugin or the limitations in Google Mobile Ads SDK.

https://support.google.com/admob/answer/2753860?hl=en
Ad placement
Number of ads per page
The number of ads on a single screen should not exceed one if the ad is fixed to the screen top or screen bottom.
