### ISSUE TITLE
Closing button on splash screen and banner

### ISSUE THREAD

**Issue by snoopas** [floatinghotpot/cordova-admob-pro#97]
Hello,

When calling AdMob.prepareInterstitial, splash screen comes with a button to close it.

However, when calling AdMob.createBanner, the banner can't be closed... is there an option or something to add this "x" and close the banner too?

Thanks,

**Comment by floatinghotpot** [comment]
the feature is provided by admob sdk, plugin cannot change it.

howevever, i notice that a "i" appears at bottom left of the banner ad, if click, it will change to "x" for closing. you may double check.

**Comment by Dineshrajaa** [comment]
Although if we click on that "X" its opening a browser so is there any way to hide it??

**Comment by floatinghotpot** [comment]
A banner cannot be closed by user. However, you can hide it by calling AdMob.hideBanner() or AdMob.removeBanner(), and it can be triggered when user click somewhere on your app page.

**Comment by Dineshrajaa** [comment]
can we control that "X" so that i could program it to hide that banner by clicking that "X"?

**Comment by floatinghotpot** [comment]
No, admob did not offer any API to access it, you may need implement some other logic.

**Comment by Dineshrajaa** [comment]
ok thank you for making such a great plugin :) and providing support for me :)

**Comment by snoopas** [comment]
Thanks for the feedback
