### ISSUE TITLE
AdMob is making the header semivisible in IOS

### ISSUE THREAD

**Issue by Dineshrajaa** [floatinghotpot/cordova-admob-pro#98]
Hi everyone,
 I am using cordova-admob-pro for an app in which whenever the ad is being shown the header is becoming semi-visible in IOS but working perfectly in Android , someone kindly help me to fix this issue.

**Comment by floatinghotpot** [comment]
Do you mean it's covered by the status bar? 

If yes, you can try setting option offsetTopBar:true when creating the banner. Read doc for more details.

**Comment by Dineshrajaa** [comment]
Thank you so much changing that setting has made the app to work normally :)
